### ISSUE TITLE
Controller Issues in Flathub

### ISSUE THREAD

**Issue by candrapersada** [libretro/RetroArch#10052]
how to use retroarch controller or Joypad for flatpak?

**Comment by i30817** [comment]
I personally gave up on using flatpak/the other thing.

They're always outdated in relation to the system libraries and cause problems. I 'simply' keep a git repo and build from master with a command line alias in .bashrc to pretent RA is installed systemwide.

**Comment by hizzlekizzle** [comment]
As a flatpak-only issue, I believe this should be reported here instead:
https://github.com/flathub/org.libretro.RetroArch

**Comment by RobLoach** [comment]
> how to use retroarch controller or Joypad for flatpak?

Upsteam udev has no interest in stable ABIs, so flatpak support for it isn't there. Because of that, we're using the SDL driver instead. If you have a controller that doesn't have the SDL definition, I invite you to submit the config over at:
https://github.com/libretro/retroarch-joypad-autoconfig

> They're always outdated in relation to the system libraries and cause problems.

Keeps to RA stable. If a compiled `master` works for you, then please do that.
