### ISSUE TITLE
[Request] (Cheevos) Toggle hardcore mode automatically

### ISSUE THREAD

**Issue by johanbcn** [libretro/RetroArch#10423]
## Description

Savestates (both manual and automatic), cheats, the rewind option, the pause option, and the slow-down option, are disabled when Hardcore mode is enabled on the achievements section.

In order to restore the disabled options, you must either disable the hardcore mode before starting the game, or to pause it temporarily from the quick menu when in-game. Restoring the hardcore mode forces the reset of the game.

### Proposal

If you really want hardcore achievements, it's kind of a hassle to have to keep fidling with the options in order to get back the disabled features. Or the other way around, to keep enabling hardcore mode before starting the game.

In my opinion, it would feel more natural to have hardcore achievements paused automatically whenever using any of these options, and to resume them again upon reseting the game (assuming there are no cheats enabled). Moreover, autosavestates could be loaded with hardcore mode paused by default.

If you are okay with this, I would like to give it a go and send a pull request.

### Version/Commit

- RetroArch: 1.8.5 / b01aabf

**Comment by Jamiras** [comment]
It's my understanding that very few players regularly switch back and forth between hardcore and non-hardcore. Typically, they choose one and stick with it.

Automatically _re-enabling_ hardcore after disabling it would be annoying to players who prefer to play in non-hardcore. I believe it does automatically re-enable hardcode mode when loading a new game after is has been paused.

The problem with automatically _disabling_ hardcore is a player may "bump" a hotkey and accidentally disable hardcore mode. The standalone emulators provide a popup to confirm the player intended to use a restricted feature before proceeding with disabling hardcore mode. As you've mentioned, to re-enable the functionality the player has to reset the game. Automatically disabling the feature without confirmation could cause a player to lose a significant amount of progress.

I wouldn't feel comfortable approving this feature without adding some sort of confirmation in front of the automatic disable.

**Comment by LordArchantos** [comment]
To chime in on this as a user, one of the reasons why I, along with others advocated getting saving state to be enabled in hardcore, was to be able to make a save state while playing in hardcore mode, for easier return later e.g. to practice a boss for a no damage cheevo in softcore. So turning hardcore off automatically when saving state would effectively remove that feature again. And I can confirm that even simply resetting the current game with hardcore paused unpauses it.

**Comment by johanbcn** [comment]
I see your point.

I don't know about accidentally bumping hotkeys, but about the default achievement mode, how about this:

We change the caption of the "Hardcore mode" option to "Use hardcore mode by default", and when true, we allow to enable the automatic toggle in a second option.

**Comment by johanbcn** [comment]
My bad, you are right @LordArchantos, resetting the content resumes the hardcore mode when paused previously.

Still, if you have enabled auto load states, wouldn't it make sense to resume automatically in pause mode when available? Then, to go back to hardcore, you would simply reset the content.

**Comment by LordArchantos** [comment]
I see the point there, but then in my use case on the other hand I might stop using auto load states, if it weren't possible to use overrides for savestate_auto_load. I like to have it enabled as I practice e.g. bullet hell shmups on platforms / content without cheevo support. And I wouldn't want to always then have a supported game / core start automatically with hardcore mode paused when I switch to something else.
Note that I haven't tested if this particular function works from overrides though I suspect it does, but it's also an additional barrier of entry as I've noticed that a lot of "casual" users don't really know how to work with overrides, or indeed know of them in general.

Maybe a toggle within the cheevo options for automatic hardcore pause (off by default) if auto load state is enabled, with the option hidden if auto load is disabled? And to make sure the notification pops up at content start about hardcore mode having been paused.
Of course this is all just from an advanced user's point of view, since sadly I can't contribute in other ways atm as I don't really know C / C++ (yet).

And yeah I agree with Jamiras about automatically pausing when pressing a hotkey for a softcore-only feature, I've accidentally bumped my load state hotkey in the past occasionally when I've been meaning to save state while playing in hardcore.

**Comment by johanbcn** [comment]
After reading your comments, I think I have a better understanding of the reason behind the restrictions and why the pause mode behaves as it does. I'm closing this because I have clearly gotten myself into an [XY problem](http://xyproblem.info).

What I'm really looking for is for a way to stick to hardcore mode and still have an easier way to load savestates without having to go through two or more additional steps (pause hardcore mode, choose the desired state slot, and then to load it).

I'm thinking that a better way to tackle this problem might be to have a "Run & Load savestate" option that would load the save state with the achievements in "softcore" mode directly; but I guess it would be better to discuss it on the discord channel first.
