### ISSUE TITLE
Linux: 1.8.5 Retroarch freezing every 3~4s

### ISSUE THREAD

**Issue by tewald** [libretro/RetroArch#10447]
## Description

Using version 1.8.5, Retroarch freezes every 3 or 4 seconds, and then resumes nomally. 
Not only menu, but also input, cores, display and sound hangs.
Tested with clean settings ( ~/.var/app/org.libretro.RetroArch deleted )

### Expected behavior

On version 1.8.4 (9e25601), retroarch navigation is smooth

### Actual behavior

Using version 1.8.5 available on flathub, retroarch hangs every 3~4 seconds.

### Steps to reproduce the bug

1. Install latest version from flathub
2. Run
3. Change to xmb and watch the background animation. Control hangs too.

### Version/Commit

- RetroArch: 1.8.5 (8bcd74b)

### Environment information

- OS: Kubuntu 19.10
- Kernel: 5.3.0-46-generic
- oibaf drivers PPA
- AMD R9 280X

1.8.4: https://youtu.be/NjqvRAXGPA8
1.8.5: https://youtu.be/OIIt4TdR1vk

**Comment by prurigro** [comment]
This was also happening with the flatpak for me, both with my 1.8.4 settings as well as starting with a fresh config.

I should add that 1.8.5 from the Archlinux repos doesn't have the issue.

**Comment by gouchi** [comment]
There is also a [RA flatpak repository](https://github.com/flathub/org.libretro.RetroArch) for the issue.

**Comment by tristianc** [comment]
I have 3 machines, all running Fedora 32, with kernel 5.6.2 and the following processors/graphics combinations:

  1. Desktop i7-2600S CPU @ 2.80GHz with an rx480
  2. Laptop i7-7600U CPU @ 2.80GHz with integrated graphics
  3. Laptop i7-7200U CPU @ @ 2.50GHz with integrated graphics
  
Flatpaked RetroArch <= 1.8.2 doesn't exhibit this issue on any machine.

On machines (1) and (2), flatpaked RetroArch >= 1.8.4 exhibits this issue. I can cause RetroArch to stop exhibiting this issue if I change `input_joypad_driver` to anything other than `sdl2`. Control pads don't work then, though, since none of the other `input_joypad_driver` choices function in flatpaked RetroArch.

On machine (3),  flatpaked RetroArch >= 1.8.4 doesn't exhibit this issue at all.

When I use non-flatpaked RetroArch on any of the machines, I don't get this issue at all.

**Comment by tewald** [comment]
@tristianc nailed it. Changing joypad to other than sdl2 stops freezing.
