### ISSUE TITLE
Linux (Flatpak): error saving shader preset

### ISSUE THREAD

**Issue by ivanershov51** [libretro/RetroArch#10457]
## Description

Saving shader preset is impossible (global/core/game - it does not matter) for Flatpak version of Retroarch. There is no such problem if I install it from official Ubuntu PPA (I prefer Flatpak version because PPA version has more bugs in my opinion).

### Expected behavior

Succesful shader saving.

### Actual behavior

Error message appears: "Error saving shader preset". Logs: [ERROR] Failed writing shader preset to /app/share/libretro/shaders/presets/global.glslp.

### Steps to reproduce the bug

1. Launch any game on any core.
2. Navigate to Quick menu > Shaders. Enable Video Shaders.
3. Load any shader preset.
4. Choose Save > Save Global Preset or (Game/Core Preset).

### Bisect Results

This happens on fresh retroarch installation.

### Version/Commit

- RetroArch: 1.8.5/8bcd74b

### Environment information

- OS: GNU/Linux (Ubuntu 19.10 on Wayland)

**Comment by 1h8me2** [comment]
I also get this issue. Ubuntu 20.04 using Flatpak. The path should be 
.var/app/org.libretro.RetroArch/config/retroarch/shaders/
Not sure how to change the path it is trying to save it in.

**Comment by hizzlekizzle** [comment]
You should be able to change the video shader directory path in settings > directory

**Comment by 1h8me2** [comment]
You are correct. This was just a symptom of a more widespread issue. The Retroarch flatpak tries to save certain directories in a location /app/share/libretro/ but nothing is installed there so it fails. The actual install directory is /.var/app/org.libretro.RetroArch/config/retroarch. You can fix this by manually creating the folders and pointing the directories to the correct locations. I saw this behavior in the following directories:
audio
autoconfig
cursors
info
rdp
runtime
shaders
video
After manually pointing each directory to the correct location, shaders save properly and settings carry over after a restart among other issues I was experiencing.

**Comment by RobLoach** [comment]
Since shaders are shipped with the Flatpak, they're "installed" to /app/share/libretro . The same approach is taken with the databases, assets, autoconfig, etc. If you'd like to save some new presets, I'd suggest changing the shader directory as hizzlekizzle suggests.

**Comment by ivanershov51** [comment]
I just want shaders to apply automatically when I launch a game. Otherwise I have to load shaders every time manually. It's sad that this won't be fixed, I'll just use Retroarch for Windows.

**Comment by i30817** [comment]
This shouldn't have been closed imo; there are ways of both having a system-wide dir and a user fallback dir.

**Comment by RobLoach** [comment]
Would be awesome to get multiple directories for the configs, cores, everything! https://github.com/libretro/RetroArch/issues/3237

**Comment by 1h8me2** [comment]
So I just did a fresh install of everything to look over the differences between how the flatpak handles default directories versus the standard repository version. There are three directories we are working with in the flatpak:

/home/user/.var/app/org.libretro.RetroArch/config/retroarch
/app/share/libretro/
/app/lib/retroarch/filters

1. First issue I see that is not standard is the format of /home/user/. For some reason the flatpak stores all of the files in /config/retroarch rather than just putting them all in the /home/user/.var/app/org.libretro.RetroArch/ like normal.
2. The second issue is that /app/share/ does not exist on my machine, however, I do have an /.app/share/libretro directory that has been created but nothing is populated in it. I think there is a typo in the default directories.
3. By default it tries to save the video and audio filters in /app/lib/ but there is nothing populated here either. When I run retroarch I tend to move the /filters/audio and video directories to the normal retroarch directory anyway so I can easily backup all of my retroarch configs.

Hope this helps. I have no idea where these directories are baked in so I am not able to investigate further.

**Comment by 1h8me2** [comment]
Also, when exploring the retroarch directories it sees an /app/ directory in the root directory that includes all of the subdirectories it references but I cannot find it in root. When using my file explorer the /app/ directory does not exist. Does this directory only exist in the flatpak container? If so, why can't retroarch save changes to it? Very strange.

Hopefully this information helps you out and maybe you can explain some of these peculiarities to us so we can help you out more in the future with bugs and issues.
