### ISSUE TITLE
[feature request] wrap-around save states

### ISSUE THREAD

**Issue by nr1995** [libretro/RetroArch#10471]
Hi,
I was wondering if you could implement an option
whereby after the (e.g.) 10th state is full,
it wraps around back to the 1st state again.

I ask because without such a feature I have no good way of automating saving.
As it stands, I can easily make a macro to press hotkeys for [next slot], then [save state].
But that's filling up my HDD fast,
and it's quite immersion breaking to be thinking of my remaining HDD space
every minute of a playthrough of **_Silent Hill_**.
I need a quantity of slots more than one!  But less than infinity!
Thanks for your work :)

**Comment by hizzlekizzle** [comment]
This has been requested before:
https://github.com/libretro/RetroArch/issues/6195

As bparker said, having it loop around and start overwriting states is potentially problematic, but you can already overwrite states by picking an occupied slot, so I don't know if that's a great argument against it.

**Comment by nr1995** [comment]
I agree.  There are plenty of options which are potentially problematic.
But they exist and RetroArch is the better for it.
If it's problematic, just make it an option, and turn it off by default.
It seems that many people are looking for this functionality.
There should always be a way to do something without reaching for a mouse,
or diving into menus for multiple clicks.  Especially something like saving.
I really hope this is considered.

**Comment by jdgleaver** [comment]
I agree that the current save state implementation is not ideal. I honestly cannot think of any valid use case for 'infinite' save states - I don't know of any other piece of software that does this. It means the current `Save State Auto Index` feature is literally unusable. It's bad enough on Linux/Windows, but for the console ports (and Android to a certain extent) there is no grantee that the user will have access to a file manager - so those states just build up and up, and there's no way to remove them or manage them in any sane fashion. Filling a user's drive with unlimited files is not good design.

I'm already planning some improvements to the save state interface (displaying a save timestamp is first on the list), and I'd like to clean up the way slots are handled. I'd propose the following:

- Add an option to set the number of save slots. This could be `10` by default (most stand-alone emulators are limited to a comparable value), with an upper limit of 999 (the sublabel text would warn that setting a high value might impact performance or lead to disk space issues)

- When `auto increment` is enabled, have the slot index wrap around as requested here (with a clear warning in the sublabel text). In fact, we can do better than this - it should always overwrite the *oldest* state first, irrespective of index.

- When pressing 'ok' on the save slot menu entry, the drop-down list should show the status of each slot: either the timestamp of the current save, or 'empty' if the slot is unused (and this should also be reflected in the save slot entry sublabel)

- In the future, we could also add an interface for deleting individual save states

@hizzlekizzle Do you think this sounds like a reasonable approach? I read bparker's comment, and I don't think save state wrap around is any more problematic than allowing manual selection of the current save slot...

**Comment by hizzlekizzle** [comment]
@jdgleaver I think it's a little more risky than that, since it happens with no user intervention (which was bparker's concern, I think), but the real question is: is it more problematic than the problems you've listed with our current, unlimited situation? and I think that answer pretty clearly "no, it would be a big improvement".

So yeah, I didn't want to rope you in on this because I know you have a big backlog and you always manage to find important things to fix that I often haven't noticed were bad until you've fixed them lol, but I'm glad to see you're interested :)

**Comment by jdgleaver** [comment]
@hizzlekizzle Heh - okay, glad you agree :)

I was in a save state frame of mind (the compression stuff got me interested), so despite the backlog it was something I wanted to have a go at anyway. Got a couple of other small things to work on first, but I'll probably make a start on this clean up operation sometime next week (have to begin by adding the VFS extension for getting file modification times - that's probably the only part that's a bit tricky).

**Comment by TruncusEncephali** [comment]
I was considering tinkering with this.  My design would separate automated save states from their manual counterparts. Automatic states could then have a configurable period and history.  Eg. Every 5 minutes for an hour.  After such we overwrite the oldest data.   Manual save states, and the auto-incrmented slot would remain unchanged. Thoughts?

**Comment by hizzlekizzle** [comment]
That sounds like a separate problem/solution to me, but I like the idea.

Would you care to make a separate issue/proposal and explain how you would approach it in the menu?

**Comment by jdgleaver** [comment]
Yes, some kind of automatic periodic state saving would be neat, but there are non-trivial technical issues involved (due to the way RetroArch's task system works). It would also make state management (and the menu) a little bit complicated. Expanding the functionality of the existing 'Auto' (-1) slot such that it could save on close content and/or with a set frequency would make the organisation much easier, but there would still be the task/multithreading issue to deal with (this is not a blocker, but needs careful thought).

I have to do a bunch of groundwork to enable any of this, anyway. I'll press on with what I have planned, and once everything is cleaned up we can maybe look at configurable auto saving as an extension.

**Comment by yesokcool** [comment]
I'd just like to chime in to say that automatic save states on a set interval (ideally separated from manual save states) would still be very much appreciated since the last post made on this issue, two years ago. I think this is a valuable feature because it allows the user to not have to "break" out of the game constantly to make sure their data is backed up like @nr1995 originally said, and it also serves as a valuable backup in cases of user error, power outages or other potential data loss situations.

I have a small suggestion that could possibly move Retroarch incrementally closer to this feature: an option that saves state automatically whenever a common action is performed in Retroarch. For example, a save state automatically being saved whenever the Retroarch menu is opened in-game, or a save state automatically saved when taking a screenshot. This could either be set to an auto-save slot, or just the normal incrementing slots.

This would help with passively backing up user data, and possibly be more trivial to implement. 

This also may feel a little redundant since saving state can already be set on a hotkey, and it's just a click away in the menu as well, but I personally think any redundancy in the realm of frankly precious time and data is never not valuable. This would be a potential savior in especially unexpected events that may result in data loss, where the user hasn't thought of saving or believed they didn't need to.

There may be other actions that you could attach automatic save states to as well. Opening the menu and screenshots are just the two that I use the most. Perhaps saving a state automatically before loading another state could prove useful as well.

These automatic saves would ideally be separated from manual saves, since they'd likely happen more frequently and would be economic to have "wrap around" more. However, if that would take longer to implement, I see two possibilities to implement it more quickly and easily:

- Create another auto-save slot like -2. There would be only one automatic save slot that gets overwritten. If possible, more slots like -2, -3, -4, -5 etc. would be more ideal for extra layers of safety.

Or:

- Create an option that allows these save states to save as normal save states, where their index is automatically incremented. This would include a warning that these save states are saved much more frequently, and may take up more space / wrap around more often.

The second choice would be more ideal for me, personally. I don't mind sacrificing some space to make sure a playthrough of my game is as safe as possible, with the ability to go back as far as I want, and I'm fine with manually clearing it out or just syncing to the cloud until I'm done with the game. 

Hopefully this suggestion isn't too far out there, and possible to consider.
