### ISSUE TITLE
[BUG?] kronos flickering when gl video driver is used

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#10486]
Other cores requesting a glcore context seem to be fine when ran with gl (actually i only tested flycast since i don't know any other core requesting glcore), except kronos for some reason : it's flickering (it doesn't with glcore video driver).

Could be a RA issue (something shader related) or not. Ultimately, since glcore is requested, RA should probably auto-switch to glcore video driver if available, the same way it does when vulkan is the current video driver.

**Comment by i30817** [comment]
> Other cores requesting a glcore context seem to be fine when ran with gl

I'll direct you to try ppsspp on a wayland-only self-built retroarch to see a crash with this (wayland only forces a glcore context, then then retroarch forces a null renderer for some reason then it crashes). 

If you run ppsspp on a retroarch with only x11 support it runs (in XWayland). Note, not with both x11 and wayland support, just x11.

**Comment by barbudreadmon** [comment]
@i30817 Meaning there would be at least 2 cases of issues when running glcore cores with the gl video driver ? Did you open an issue about this one ?

**Comment by i30817** [comment]
I opened issues both here and in ppsspp but the ppsspp authors simply aren't the maintainers of the libretro code in spite of it being upstreamed. If people want to fix this, they need to open a PR upstream, not wait for them to fix something that admittedly doesn't actually affect their default program configuration.

**Comment by barbudreadmon** [comment]
@i30817 could you confirm if things improved or not on ppsspp and/or openlara ?

**Comment by i30817** [comment]
I just did, openlara i didn't try but ppsspp still crashes. Note, as a reminder: I'm testing this on a wayland environment with a RA build of:

`./configure --disable-discord --disable-qt  --enable-zlib --disable-7zip --disable-sdl --disable-vulkan --disable-cdrom --disable-sdl2 --disable-xvideo --enable-opengl_core --disable-opengl1 --disable-xinerama --enable-wayland --disable-x11 && make`

And i tried both kinds of video driver, 'glcore' and 'gl'. I've read that wayland forces a glcore context for getting rid of X11 dependencies on the opengl drivers and general modernization of the driver.

If i boot either retroarch with X11 support (so it goes to XWayland) or maybe (didn't try it) that compile above in Xorg, ppsspp runs.

**Comment by i30817** [comment]
If you have any code you want me to try i can do it. Sort of.

**Comment by i30817** [comment]
Openlara with the ps1 tomb raider 1 levels has a funny flashing corruption in gl and in the glcore driver just has a blackscreen. TBF it also has a horrid frame rate on that blackscreen because my GPU is a awful thing from 2008 so maybe it's just a core bug.

I can hear Lara's footsteps if i press forward so it's a renderer problem, not a crash.

**Comment by i30817** [comment]
Ok, openlara started working when i setup 'gl' driver and 'core->hardware shared context: on', so there is some multivariable config issue here.

**Comment by barbudreadmon** [comment]
Ok, so from what i gather : 
- openlara requires "gl" video driver to work on your setup, which i guess void the theory of wayland only supporting "glcore" ?
- ppsspp doesn't work under wayland, whatever the settings

It might be totally unrelated to the issue i fixed then, my issue was about RA not listening the core's request, causing glitches in the process (seems legit when a core expects a type of context and you give it something else).

**Comment by i30817** [comment]
Mmm, i think it's more like openlara uses X11 and it's getting redirected to XWayland as soon as i turned 'hardware shared context', which has a misleading name:

This is the description of the option, and remember it started working with when it was turned on:

'Give hardware-rendered cores their own private context. Avoids having to assume hardware state changes inbetween frames'

The other missing part of the puzzle (IMO) is that the gl driver works\*. I think that might be explained when you examined the platform specific parts of openlara:
https://github.com/XProger/OpenLara/blob/39137fc3c4c07fdc0745badcb007fac8c136dcf4/src/platform/nix/main.cpp

It's full of calls like 'XSetWMProtocols' and 'GLXContext ctx = glXCreateContext'. That says to me it requires Xorg on linux, and thus gets shuffled to XWayland even if the compile of RA doesn't support Xorg, specifically because of the 'hardware shared context'.

\* (in these conditions, though without that purple defect happens, which might be a defective transition from the frontend glcore to 'gl'; while the other has a black screen)

**Comment by blikblum** [comment]
I still have flickering issues when using Kronos with gl driver (Games like sega rally, daytona usa flickers). If i manually switch the driver to glcore, it works fine

Using Retroarch 1.8.9 on windows 10. NVIDIA Geforce 230M

**Comment by barbudreadmon** [comment]
Yes, the fix was reverted...
