### ISSUE TITLE
[Feature Request] PIN protection to hide "mature" games

### ISSUE THREAD

**Issue by Zephyr-Battiassi** [libretro/RetroArch#10566]
A bit self-explaining, I would like to be able to hide some nasty unsuitable games like "Mortal Kombat", "Zero Zone", "Gals Panic", etc... so my children can't get a peek of them when we play together and search for a new game to play.

It would be enough by having an option within the game details to mark it as "mature", which will hide the box, title screen & screenshots from the game list, and leave only the same to allow unblocking it if you know the PIN and wanna play it.

Currently, I just removed manually the screenshots of the nastier games to avoid this.
But I think it would be nice to keep some games private.

What do you think?.
Thanks in advance.

**Comment by i30817** [comment]
My guess is you'd probably want to tie this in to the manual support for creating playlists and make a playlist 'password locked or something'.

Trouble is it's quite impossible/inconvenient with current code, since 

1. the playlist main technical use is to associate a emulator/console to it. A playlist that would be about a tag would have games of many different consoles on it and would always need a core chosen for every new game played.
2. You'd have to make the playlist data yourself. The only dumping project you'd be able to (with a lot of technical effort) to make a tag metadata playlist is MAME dat files after crossreferencing another database, and i'm not sure that what the consider 'mature' includes violence. Other dumping projects just don't bother.

**Comment by Zephyr-Battiassi** [comment]
Thanks @i30817.

I understand your point of view, 

I somehow felt easier to do as per my way, having an additional setting so I (the user) can mark the games manually as mature on my own (regardless what the dumping group says). After all, there are less mature than non-mature games on Mame and others.

I think your way would be rather complicated for the less savvy, but I don't want to hammer retroarch development staff with this, I just though that it would be a nifty feature.

I will leave it here written, but will not bump it anymore so in case this could be done some day.
Devs can feel free to close this if they find it silly, but it's not silly to me.

**Comment by i30817** [comment]
Indeed that would be easier ... for users, for this specific usecase. But i doubt that such a feature would get accepted because it's too specific in the larger context of 'tag/query filtering' which is the end incarnation of these kinds of systems - and that is not happening any time soon without a major effort (redesign the GUIs, adopt a query interface) and a available database (doesn't exist/not crossreferenciable to dat names).

I think you may have 'a pidgeon in hand' instead of 'two in flight' if you settle for requesting 'missing roms in playlist get hidden but not deleted'.

**Comment by Zephyr-Battiassi** [comment]
> Indeed that would be easier ... for users, for this specific usecase. 
> I think you may have 'a pidgeon in hand' instead of 'two in flight' if you settle for requesting 'missing roms in playlist get hidden but not deleted'.

Thanks @i30817 , something is better than nothing. I guess that sometimes, less is more
I appreciate your comment.

**Comment by i30817** [comment]
Actually now that I think about this again, you can make a retroarch start shortcut that makes it load a different cfg main file, that then loads different playlists to have the effect.
So it's something you can already do manually without Retroarch features.

**Comment by Zephyr-Battiassi** [comment]
> Actually now that I think about this again, you can make a retroarch start shortcut that makes it load a different cfg main file, that then loads different playlists without the 'mature games'.
> So it's something you can already do (hide games) manually without Retroarch features....

Hi @i30817 . Thanks, I couldn't imagine that retroarch could be launched with different config from a shortcut.

I already found my way to get the same by making a second retroarch installation (a plain copy) for them and linked the same roms directories. In our children's version, I deleted all naughty games from the playlist. Their retroarch is also disabled to scan directories or add new games, so they can't pick, choose naugthy or add unsafe content even if they want.

Thanks a lot, I think we can consider it closed, as your suggestion makes this even easier, just a plain copy of retroarch.cfg pointing to a different playlist folder and good to go. I disabled the content scanner for them (i hid it from the UI, and only later found out <<content_show_add = "false">> in retroarch.cfg).

I can't say thanks enough times.
