### ISSUE TITLE
RGUI scales improperly when Lock Menu Aspect Ratio is set to OFF

### ISSUE THREAD

**Issue by kevinfishburne** [libretro/RetroArch#10573]
RGUI's menu fails to scale with a non 1:1 aspect ratio when "Lock Menu Aspect Ratio" is set to OFF. It only scales non 1:1 when the vertical resolution is less than 240.

When "Lock Menu Aspect Ratio" is set to OFF the RGUI menu should completely fill the available screen geometry, regardless of what that is. Correcting this issue would not only result in what most people would consider expected behavior, but also result in superwide resolutions on CRTs displaying the menu correctly, such as with 3840x240 and under. Currently this requires that a custom viewport be set, which causes Integer Scaling to fail unless per-core overrides are created. Two birds, one commit.

This behavior occurs on the latest stable Retroarch (1.8.5), which I compiled from source in Raspbian Buster Lite (2020-02-13-raspbian-buster-lite.img), as well as Retroarch 1.8.5 from the stable PPA in Linux Mint 19.3 amd64. It is easiest to reproduce by resizing the Retroarch window on a desktop installation. You will see that as soon as the height of the window goes below 240 pixels the menu begins to fill the window rather than scale 1:1.

If modifying the behavior of the setting being set to OFF will cause issues, an alternative solution would be to add a "Fill Screen" option.

**Comment by hizzlekizzle** [comment]
So what you're wanting is the sub-240px behavior all the time? Or at least an option to do so? What do you think about that, @jdgleaver ?

**Comment by kevinfishburne** [comment]
Correct. Essentially the issue is that there's no way to have the RGUI menu display legibly and have integer scaling function properly at the same time when using a superwide resolution. You can either (1) enable a custom viewport to get the RGUI menu to display correctly, which then breaks integer scaling (probably a separate bug outside the scope of RGUI) and set per-core custom viewport settings to save as overrides, or (2) not use custom viewport settings so that integer scaling behaves properly but then be unable to see the RGUI menu legibly. Modifying the behavior of Lock Menu Aspect Ratio when set to OFF to ignore aspect ratio by using all available screen geometry would seem more intuitive with respect to the option's description/name, and at least solve RGUI's half of the problem. If there still appears to be an issue regarding integer scaling and custom viewports I'll file that separately, of course. :)

**Comment by jdgleaver** [comment]
Okay, let me start by saying that RGUI scaling is fraught with danger, and the aspect ratio lock is already a huge hack because to do it 'correctly' would require every gfx driver to be changed (quite significantly) which is impractical. Also, I can't do any more with the dynamic framebuffer resolution reduction below 240p - I've pushed that as far as it will go.

Anyway, when `Lock Menu Aspect Ratio` is `OFF`, RGUI uses the aspect ratio specified by `Settings > Video > Scaling > Aspect Ratio`. If this is giving you the wrong result, then it would seem that using superwide aspect ratios breaks the `Aspect Ratio` setting itself  :)

I don't have a crt, and so can't test... But if this is the case, then a separate issue should certainly be opened.

However! As I understand it, your immediate problem would be fixed by a new `Lock Menu Aspect Ratio` `Fill Screen` setting that just stretches RGUI's framebuffer across all available pixels? This can be implemented using the same kind of trick as that current `Fit Screen` and `Integer Scale` settings. I can certainly do this.

I'm in the middle of something else at the moment, but I'll get around to this soon - probably early next week.

**Comment by kevinfishburne** [comment]
That is fantastic; thank you. I did find a workaround for the issue in case anyone else is having the problem. While setting the aspect ratio to Custom and setting the Custom Viewport resolution does cause integer scaling to fail (it scales the game to fill the custom viewport resolution), setting Aspect Ratio to Config and setting Config Aspect Ratio to 16.000000 (3840 / 240 = 16) scales RGUI appropriately and does not break integer scaling, so no overrides are required. And now relief washes over me in an awesome wave. Thanks for all your hard work on this...love it. I'll give 1.8.6 a spin and report any weirdness if it arises.

**Comment by jdgleaver** [comment]
@kevinfishburne Okay, this should do the trick: #10613

As I said, I don't have a CRT - so please let me know if it does what you wanted :)

(BTW - that Config Aspect Ratio workaround was a good find - thanks for sharing!)
