### ISSUE TITLE
Rgui custom theme doesnt show image

### ISSUE THREAD

**Issue by apison** [libretro/RetroArch#10623]
&
## Description

In 1.8.6 versione rgui custon theme on arcade monitor doesnt work anymore, images are not showed at all , only colors change. All worked fine until version 1.8.5 .

### Expected behavior

[What you expected to happen]

Image in custom theme must be showed

**Comment by jdgleaver** [comment]
This issue is due to the PR I made here: #10386

Basically, it looks like you're using switchres (or a resolution override) which sets your display resolution below 240p. With the above PR, RGUI now automatically reduces its framebuffer resolution to fit this - but when the menu is less than 240p, any custom wallpaper is disabled.

I can't resize the wallpaper dynamically (the results would look terrible...), but I can crop it and show as much as I can in the available space. I'll make a PR shortly.

(If you want the full wallpaper, though, you'll still have to run at a resolution of at least 240p)

**Comment by jdgleaver** [comment]
Okay. this is about the best we can do here: #10629
