### ISSUE TITLE
 [Feature Request] Translations of retroarch for "Wii" and "3DS"

### ISSUE THREAD

**Issue by wuniversales** [libretro/RetroArch#10739]
It seems that the translations of retroarch for Wii and 3DS are not available.
At least I don't see the option to change the language.

### Expected behavior

It should allow to change the language of the application.

### Actual behavior

Only allows English. The default language.

### Steps to reproduce the bug

1. Open the app...

**Comment by LibretroAdmin** [comment]
We don't really want to gamble with enabling the additional languages since it would eat up more RAM, and already some ROMs on a Wii barely fit into RAM as is. If the system had 512MB RAM or more then we would feel reasonably assured we have the required memory footprint to throw features at it, as it is we have to be a bit more conservative.
