### ISSUE TITLE
Super Grafx x "Madou King Granzort" Game x graphic errors

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#10782]
I went to test this game and noticed that just below the screen part of the background is showing. Something that shouldn't happen. When I use the Mednaffen emulator the problem does not appear. But when I use retroarch with these cores below yes:
mednafen_supergrafx_libretro.dll
mednafen_pce_libretro.dll

I circled in red the part that is giving problems in the graphics.

![20200603_153508](https://user-images.githubusercontent.com/16063712/83676224-b6ec7b80-a5b0-11ea-9905-4b8a35f7d151.jpg)

**Comment by bslenul** [comment]
`Quick Menu > Options`, reduce the `Last Scanline` number by a few pixels and resume.

But please, to not clutter this issues board, if you need help use the forum, Reddit or Discord, or in the worse case the core issues board instead of the RetroArch one! For the latter, go to https://github.com/libretro and search for the core name:

![image](https://user-images.githubusercontent.com/33353403/83744889-11dbac80-a65d-11ea-9864-d08b055d5556.png)

**Comment by AlanRibas** [comment]
Thanks a lot for the help.
With your tip I managed to solve other problems too !!
I understood...
Now I know where to post my doubts or bug reports correctly.
