### ISSUE TITLE
Auto Save State freezes RetroArch while Cheevos is enabled

### ISSUE THREAD

**Issue by prataczak** [libretro/RetroArch#10943]
## Description

Confirmed to be an issue for Beetle Lynx, Mesen, FCEUmm, and BSNES Mercury Balanced cores.

All three worked fine before (version 1.8.8) Now they freeze on exit.

[What you expected to happen]

I expect to have 'Auto Save State' enabled, and have Cheevos enabled/my username and password filled out, and exit a game with the exit hotkey, and cleanly exit RetroArch with a save state.

### Actual behavior

When you try to exit while running a game with the both the Mesen and FCEUmm cores, RetroArch freezes.

### Steps to reproduce the bug

1. On a fresh install of RetroArch, open RetroArch, and go to settings/saving/Auto Save, and turn it on.
2. Go to settings/Achievements, turn on Achievements, and fill out your Username and Password.
2. Save your configuration.
3. Run a game with the Mesen  or FCEUmm cores.
4. Try to exit, with the exit hotkey - RetroArch freezes.

### Version/Commit
RetroArch 1.8.9, the latest stable version - but I also just tested with the latest nightly (6-29-20), and the issue is still present.

### Environment information

- OS: Windows 10

**Comment by prataczak** [comment]
I edited my first post with more details, as I figured out more of the issue.

**Comment by shantigilbert** [comment]
It seems this commit is the one that causes the issue: 6083450d4e2c49da74d0c4a4a1a4833a2a6a66fa

**Comment by Jamiras** [comment]
I am able to reproduce this with hardcore paused.

The problem seems to be the call to `task_queue_wait(NULL, NULL);` is waiting indefinitely for the task queue to be empty, but it's being called before notifying the achievements code to shutdown. As a result, the load task (and later the rich_presence scheduled task) keep the queue from being empty.

The second issue seems easy enough to fix. Change
https://github.com/libretro/RetroArch/blob/5ebce6a2382b4a14f29b992aff194d17b8607939/libretro-common/queues/task_queue.c#L423-L424
To:
```
      wait = (tasks_running.front && tasks_running.front->when) &&
             (!cond || cond(data));
```
So the scheduled task won't indefinitely keep the queue non-empty.

The first issue is a little harder. The indefinite wait is in `retroarch_main_quit`, which is called before `command_event(CMD_EVENT_CORE_DEINIT)`, where the achievements code is notified to shutdown via `rcheevos_unload`. I believe the correct solution is to change the
```
      if (content_save_state_in_progress())
         task_queue_wait(NULL, NULL);
```
to something equivalent to
```
    content_wait_for_save_state();
```
that only waits for the save state task to complete.
