### ISSUE TITLE
[Feature Request] Lock "Fullscreen thumbnails" view

### ISSUE THREAD

**Issue by nikolafeve** [libretro/RetroArch#10958]
currently we have to press the start button each time we want to see the thumbnails of a game in fullscreen. I suggest when you press start button it locks the "Fullscreen thumbnails" mode until you press start again, as we can continue to browse games with the arrows up and down and see the big thumbnails. Could be a great feature specially since ozone is the default UI (the thumbnails in this UI are very small and they can't be resize in the option)

**Comment by porg** [comment]
I personally would love this alternative fullscreen visual browsing mode too!
And as a UX designer I can give some objective reasons for this mode too:

Since ca 2005 [image galleries with a lightbox](https://fancyapps.com/docs/ui/fancybox/#quick-demo) are commonplace on websites and users are accommodated to this experience:
- If I go into the lightbox, I am in an immersive mode.
- I navigate images in this mode as long as I want.
- Then when I am done with my immersive browsing needs I exit back to the main content flow.

The current forced pogostick navigation is unnessecarily inflexible. If we change it then:
- Users who want to navigate out of immersive mode can still do so by pressing start again.
- Users who want to stay longer in immersive mode can too.

With this new paradigm we do not loose any functionality but instead humbly and elegantly add functionality.

**Comment by vanfanel** [comment]
I am also waiting for this, please :)
