### ISSUE TITLE
Snatcher, Popful Mail, and others will not import to playlist properly.

### ISSUE THREAD

**Issue by Khronikos** [libretro/RetroArch#10976]
I can't get this to pop on any SegaCD playlist, and believe me I have tried. I am curious as to who is actually getting these to show on playlists and what their source is. I have tried Snatcher and the rest mentioned from Internet Archives, guaranteed to be accurate and clean, and they still will not pull when scanned. These are full multi-bin roms that play perfectly when selected in Load Content, but I can't get them into a playlist.

This is my last bastion of hope here. I have no idea what RA considers a good burn of Snatcher, but it simply can't be realistic. When Internet Archive sets of the highest quality are not working, then something is wrong.

On PS2 this is definitely a major issue as well. I even got my own Maximo working, but it says beta for some reason even though it's from a legit copy. Maybe I am doing something wrong, but so far few games have worked for many PS2 games and definitely the Sega CD games outlined here. A couple others don't work, but these are the ones that really grind my gears. Any help or direction is appreciated. I don't make this thread lightly. I've tried 6 different versions of Snatcher.

Win 7 x64/RA latest stable version.

**Comment by Khronikos** [comment]
Alright, I have managed to get this working through a Manual Scan. I feel like RA needs to tune its scanning code possibly. Why would a manual scan work with cue and then a single file or directory scan does not pick up any of them? Again, it's only a few of them that don't pull, but they don't at all. Same with PSP stuff, and I have mostly been getting No-Intro stuff or verified dumps.

Anyway, you can close this I guess if there are no plans to improve how Retroarch sees a rom dump and imports to playlist. I guess Manual scan will just have to do.

**Comment by Sanaki** [comment]
Manual scan works with anything. You could scan cat photos into a playlist if you wanted. Improving the auto-scanner is a constant task, and one doomed to never be perfect. But there are plenty of people working on different aspects of it despite that.

**Comment by i30817** [comment]
Lots of people have either outdated segacd dumps. Redump always works but redump is rare for segacd (and saturn and dreamcast).

**Comment by Khronikos** [comment]
> 
> 
> Lots of people have outdated segacd dumps. Redump always works but redump is rare or incomplete for segacd (and saturn and dreamcast).

I've never gotten one copy of Snatcher to work literally anywhere. My dump is from here: https://archive.org/details/redump.mcd

Confirmed to not work, which is why I made the thread.

**Comment by twinaphex** [comment]
Please don't post links like that again.

**Comment by Khronikos** [comment]
> 
> 
> Please don't post links like that again.

Sorry, was that a link to no-intro? I can't remember, I was just trying to help people understand. I forgot it links to things. But yeah, that was the issue and dumps seem fine. I'll refrain from that.

**Comment by twinaphex** [comment]
Yeah, it was a link to it. Anyway, as long as you understood the reasoning for its removal, we can move on and it's no problem.

**Comment by i30817** [comment]
> Confirmed to not work, which is why I made the thread. Sol-Feace and Popful Mail also do not work. I just manually scanned them, and luckily the art and everything is there just needed some tweaking. I understand it is a long process of getting things right.

Try a manual scan. It will work if and only if the playlist name and game name is on the thumbnail server: http://thumbnails.libretro.com/

**Comment by Sanaki** [comment]
> They also could use symlinks to save space with the right kind of download tool, which would work for both games with more than 1 cd and 'alternative names'.

I did open #10665 regarding that. If that gets fixed, I'll personally go through and clean up a pretty big chunk of the thumbnail db. First using fslint, then by hand.

**Comment by i30817** [comment]
git knows how to download clone symlinks instead of following them, so making the thumbnail server 'get them' seems straightforward, the trouble is whatever download tool that RA uses (that isn't git), deal with symlinks, preferably without 2 https requests.

I think the best strategy in platforms with symlink capability might be something custom like 'check the existence of the file in the thumbnail server, download the file if a regular file but download the symlink target if not, then create a symlink to the target locally if the name requested is different from the file got'.

**Comment by Sanaki** [comment]
Regardless, we're going out of scope for this issue.

**Comment by Khronikos** [comment]
> 
> 
> > Confirmed to not work, which is why I made the thread. Sol-Feace and Popful Mail also do not work. I just manually scanned them, and luckily the art and everything is there just needed some tweaking. I understand it is a long process of getting things right.
> 
> Try a manual scan or a rename. It will work if and only if the playlist name and game name is on the thumbnail server: http://thumbnails.libretro.com/
> 
> The thumbnail server has 'problems' because the libretro-database repository doesn't create enough copies for all possible names (which they could and should do with a script instead of depending on contributors imo, since the redump/tosec/m3u names are predictable).
> 
> Especially if retroarch wants everyone to use m3us, the least they can do is make the m3u name (name without the disc part of the name) available for cd dumps, which is actually rare.
> 
> They also could use symlinks to save space with the right kind of download tool, which would work for both games with more than 1 cd and 'alternative names'.

Well they have all scanned. I guess it's not a huge deal. I definitely went through LOADS of work doing my playlists though. Countless new box arts for missing ones across many different emus. I'd like to submit some for the PSP, but I am not even sure how to do that efficiently with Git. I know I can make a fork or whatever and then propose changes, but not sure how much work it is to submit a bunch of stuff.

I see some progress now and then though, and it seems like the database gets updated, just not at times for the particular rom, so that means renaming it and/or the thumbnails. It's been a wild ride. For instance, though, there isn't even a correct version of Sonic 1 on Genesis. It's the horrible white art that bears no relation to the main art most of us saw on that system. Those are some of the things I would like to update, but I am not sure how to contribute efficiently, because I can't be on here a lot.

**Comment by i30817** [comment]
You can do it from the GUI interface, but it's not quite 'smooth' and you can gotcha yourself because you won't be able to update the PR without the command line git so if the project maintainer says he wants some adjustments, you'll have to close down the PR, create a new commit with another branch and reopen the PR, which is annoying.

You go to [libretro-thumbnails project](https://github.com/libretro-thumbnails), read the readme at the bottom of the page, create your images as the readme requests; of the right size without borders if possible (retroarch screenshots have the bad habit of including borders, so be careful if you're screenshooting the menu or ingame), find the console on the filelisting, [for instance ps1](https://github.com/libretro-thumbnails/Sony_-_PlayStation), click on it to go to the subproject, fork it with the button in the upper right side, then on the fork click the button 'add file -> upload files' and *drag and drop files'.

Drag and drop because that way you can drop three directories with the 3 game thumbnails inside, which would take multiple commits otherwise. Then instead of 'creating directly in the master branch', choose 'create a new branch'. If done correctly your new thumbnails will be on the right directories among the others. Then you'll see github showing a notification near the commit message to open a PR in the parent project. And you do that.

As mentioned, if you screw up, you'll have to make another branch with another drag and drop on 'master', so change to master in your fork in the web gui and redo the commit to a new branch and PR that.

**Comment by Khronikos** [comment]
Alright, thank you very much. So I can just submit the box and screen folders themselves in one go for one system correct? As in say 20 pngs in each of these for one system?

I will get to that at some point. I did open a fork, but hadn't done anything yet. I have to gather all the ones I have changed or added to and compare them to the directory. Does RA accept box and screen art for common translations, e.g., SNES RPGs? I had to do about ten of those. I don't use a hack playlist, and they come up in my normal playlists when scanned mostly. Mostly, they are just dupes of the ones already there under the name of the translation, but it would save anybody with that translation time.

________________________________

**Comment by i30817** [comment]
I don't know about the translations. The problem about them is that they have no standard name (or rather it's easy to do a standard name, by following the name on the hack database - [I even made a tool to help with updating the database](https://github.com/i30817/rhdndat) - but since libretro-database is not accepting SNES and a few systems hacks checksums (they complained about 'too many') and because retroarch has no way to use checksums for scanner anymore i just don't bother.

Which means that since i was the only using the tool, the names on the database are getting more and more distant from the predictable name the tool produces. Crap like FFVII_whatever_by_zeromus.fig or something. I'd be very mad if i had to name my hacks that way to get the image.

But sure, you can try asking.

**Comment by i30817** [comment]
> Alright, thank you very much. So I can just submit the box and screen folders themselves in one go for one system correct? As in say 20 pngs in each of these for one system? 

BTW, just to be clear since you might have misunderstood; the fork before you upload and choose the directories must be a clone of the subproject (they are directories with the playlist console name). If you try to commit directly to libretro-thumbnails, it won't work because you're going to end up trying to commit to a subproject, that's just a handy way to get to the subprojects.

**Comment by Khronikos** [comment]
Yes, directly to the sub project console or whatever. So I submit an entire clone as a fork of say PS1. And then I upload my part into that, and they can see all the changes correct?

AFAIK the translation roms are usually pretty samey from good sources, as in (T-En...) and then their project, but yeah those might not get included for whatever reason. It's still a huge hassle having to rename all of these and clone screens just to get it in there but whatever. I assume this all takes a long time lol to sort our rationally. But I think I will just start a little PSP and PS1 to try and fill out the gaps a little for major games and provide better boxart when necessary with a few sprinkled in from other systems like Sonic 1 Genesis, which needs to be changed.

What I am seeing is that they have a lot of (Disc 1 of 2) but no matching (Disc 1) for a lot of them, which I see a lot of roms name themselves, and I prefer as well this (Disc 1) type notation. I think those should be okay since their database already has met the paradigm of including both, just not consistently anywhere.

Anyway, thanks for your help man. I'll try and submit sometime here in the next few weeks.

________________________________

**Comment by i30817** [comment]
Honestly a script that could rename a standard name to dump variant names would be better utility.

**Comment by Khronikos** [comment]
Oh for sure, a script would purely be awesome for some of this stuff. And it should be done at some point for the easier things at least.

________________________________

**Comment by Rstation4** [comment]
I use Lakka OS and i noticed that Popful Mail does not add properly as well. I did do a manual scan of it but its not the only title and core that has a database issue. I end up having to add thumbnails manually for it but gets really out of hand when needing to do it when you have a larger amount of games.

**Comment by Khronikos** [comment]
> 
> 
> I use Lakka OS and i noticed that Popful Mail does not add properly as well. I did do a manual scan of it but its not the only title and core that has a database issue. I end up having to add thumbnails manually for it but gets really out of hand when needing to do it when you have a larger amount of games.

Yeah, I just manually scan most folders now. It just doesn't do it right even on some games straight from No-Intro. Whatever I guess.

**Comment by LibretroAdmin** [comment]
Retest against latest version.
