### ISSUE TITLE
[Feature Request] Proposed save-state improvements

### ISSUE THREAD

**Issue by keithbowes** [libretro/RetroArch#11008]
I've got a couple of improvements I'd like to see in save states. I might try to implement them, if the feedback doesn't show reasonable opposition or technical limitations:
1. Confirmation of overwriting an existing state.  Either I push the wrong key or I forget to change the slot, and poof!
2. Named states.  It would be awesome if you could provide a description of the save state instead having to remember what's saved in what slot.

**Comment by Sanaki** [comment]
The first should essentially be covered by the "Undo Save State" option. The second sounds good though.

**Comment by i30817** [comment]
2 things (opinions really): 

1. loadstates are imo more dangerous than saves overwrites, since RA already has a autoincrement option (and unfortunately it has no way to set a sane limit which is another problem).
2. I like the dolphin solution of making the loadstate harder to trigger accidentally. IIRC it uses shift+Fkey to loadstate and Fkey to save. However i don't expect RA to make it possible to have a flat array of saveslots assigned to Fkeys; but away to specify keyboard modifier for 'system' shortcuts among them savestate and loadstate wouldn't be too bad.

**Comment by awsms** [comment]
> 2\. Named states.  It would be awesome if you could provide a description of the save state instead having to remember what's saved in what slot.

What about also a screenshot?

**Comment by hizzlekizzle** [comment]
> What about also a screenshot?

This is already implemented, they're just not displayed in Ozone menu: https://github.com/libretro/RetroArch/issues/5368

**Comment by mandlar** [comment]
In regards to "naming a save state/giving it a description": would it be possible to at least include a datetime stamp for each save state that exists?

I'm using the Android version which doesn't have the option to include screenshots. Instead I end up taking a phone screenshot of which save state I used last so I remember which one to continue on the next time I play (I'm using a lot of save states because I'm playing a long strategy turn based game, Dark Wizard. I reset back to 0 when I finish a map/level). I wouldn't have to do this if the save states simply included the datetime stamp of when they were saved as I would be able to quickly scan the list of save states and see the last one I used.
