### ISSUE TITLE
[Feature Request] - Add a hotkey to "close content"

### ISSUE THREAD

**Issue by zanzabarjones** [libretro/RetroArch#11113]
most users would like to exit games easily back into retroarch,since ozone is a great frontend,you guys have made it so that it's more convenient to use an external frontend...it defeats the point of having a great interface or allowing users to download boxart if retroarch is such a hassle to exit games from,exiting back into ozone

**Comment by hizzlekizzle** [comment]
Hope you don't mind: I added some tags and clarified the title a bit.

This has been requested in a roundabout way a few times in the past, with people requesting that the "quit retroarch" hotkey close content instead, which would be a bad idea since launchers depend on being able to drop out entirely. I'm not against adding a new hotkey for it, though.

**Comment by bslenul** [comment]
A hotkey would be nice for sure, not a life changer or anything of course, but it's a bit annoying when you're deep into the menus and have to go all the way back to the quick menu just to be able to close content.

**Comment by ImJezze** [comment]
I also would like to have a "close content" hotkey, and it would be consistent with other quick menu entries that already have a hotkey, like "restart/reset game". (by the way the naming of the quick menu entry and hotkey is inconsistent)

Another thing, which might be a bit off-topic, but still related is: If I start a game via the desktop menu UI, a separate window opens for the game. When I close this window, the desktop menu window closes too. I think this is confusing.
