### ISSUE TITLE
[Feature Request] Metadata and thumbnails in content folder

### ISSUE THREAD

**Issue by QuaiGoner** [libretro/RetroArch#11218]
KODI-like metadata structure would be much more convenient and also would make way for a server based bulds (ROMS and their metadata are in one place, saves too and several clients)

**Comment by i30817** [comment]
Enabling ROM downloaders is a bad idea and i doubt the project will. Fork it if you want it so bad.

**Comment by QuaiGoner** [comment]
What ROM downloads? I want my collection of games be portable, just like movies with metadata and pictures in one place. What are you talking about?

**Comment by rbreaves** [comment]
> I think completely different dir for different OSes is a more elegant solution for the person who switches host OSes often though. Less chance of messy things happening, most of the same work (creating a new retroarch file with different paths).

If you use relative paths then I am not sure why we can't interpret UNIX forward slashes as backs slashes still for Windows. I've seen other projects do that just fine.

Also why was this proposal closed? @QuaiGoner Am I missing something because afaik we still don't have the ability to store metadata in a separate file for rom files and would be a huge help. I am needing and wanting to jump btwn different OS's and platforms and the lack of this feature is depressing.

I have done some work to gauge the work and effort needed to add metadata to the DAT or rdb and while I can personally go through and add quite a bit of data after I write a bit more code, in a somewhat automated fashion.. that is not a particularly easy process and hence why the metadata for certain data is so lacking still. The process to contribute metadata is too cumbersome atm - and for a lot of people it'd be far easier for them to create these individual files and pack them with romsets or a separate file that people can optionally add.

I think people wanting to keep their rom files themselves pristine makes sense, no one wants CRC checks to fail because of added metadata to a physical file ,- but the entire directory less so because it is easy enough to quickly sort and round up the actual files vs other files on literally any platform.
