### ISSUE TITLE
MAME 2015 core not working 

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#11291]
MAME 2015 core not working it goes back to the RetroArch screen. games tester in Romcenter it shows there good copies. Also the MAME UI32 0.159 Emulator will run them. Is this the right Emulator to use with MAME 2015?

**Comment by hizzlekizzle** [comment]
This issue should probably be opened at the core repo, since it's (probably) out of the frontend's control:
https://github.com/libretro/mame2015-libretro

The description there says v0.160-ish, which means most v0.159 ROMs *should* work, but if they don't, what's the error it's giving in the logs? You can include that information when you open the new issue at the core tracker.

**Comment by Cibomatto2002** [comment]
I got it working I had to disable rewind.

**Comment by i30817** [comment]
Cores which don't support rewind should really advertise it to prevent problems like this.

**Comment by hizzlekizzle** [comment]
Rewind (and other RetroArch-specific goodies, like shaders, remaps, runahead, etc.) isn't part of the API, so the cores can't and shouldn't directly know anything about it (and therefore shouldn't announce compatibility with it). However, I completely agree with your sentiment, and to this end I've started (slowly) adding frontend-agnostic descriptors for some of these things in the core info files, which could theoretically be used to automatically disable incompatible features: https://github.com/libretro/libretro-super/blob/master/dist/info/bsnes_libretro.info#L77
