### ISSUE TITLE
Desmume core is missing from linux builds

### ISSUE THREAD

**Issue by gal20** [libretro/RetroArch#11353]
As the title suggests, the desmume core is missing from the linux builds in the [buildbot](https://buildbot.libretro.com/nightly/linux/x86_64/latest/).

**Comment by i30817** [comment]
Melonds also hasn't been built for almost 20 days but not sure if that's normal.

**Comment by hizzlekizzle** [comment]
Yes, it's to be expected, unfortunately. We're just limping along until the new buildbot infrastructure is in place. I've been doing dolphin and melonDS builds for windows and linux 64-bit on my own, though, and I can add desmume to them, as well. https://github.com/hunterk/libretro_builds/releases

**Comment by i30817** [comment]
I'm ok, if i wanted i could add it to my navi build script along with the 2 version of retroarch, 2 versions (pgo) of beetle, 1 version of ppsspp, one (upstream) version of dolphin etc.

I'm just getting antsy because MelonDs had the big merge that fixed savestates upstream the day after that build doh.
