### ISSUE TITLE
glcore broken with hw cores w/ 96e6f99f1472a9d55b1fd6caf699d0a39ffde81a

### ISSUE THREAD

**Issue by valadaa48** [libretro/RetroArch#11487]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

commit 96e6f99f1472a9d55b1fd6caf699d0a39ffde81a (HEAD, refs/bisect/bad)
Author: barbudreadmon <barbudreadmon@gmail.com>
Date:   Wed Sep 23 11:29:44 2020 +0200

    allow context switching from gl to glcore

breaks odroidgo2 hw cores (flycast, ppsspp)

### Expected behavior

It's supposed to work

### Actual behavior

```
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[ERROR] [CONTENT LOAD]: Failed to load content
```

### Steps to reproduce the bug

1. Set video_driver to glcore and  Allow cores to switch the video driver = false.
2. Run retroarch with hw core

### Bisect Results

96e6f99f1472a9d55b1fd6caf699d0a39ffde81a is the offending commit

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0/96e6f99f1472a9d55b1fd6caf699d0a39ffde81a

### Environment information

- OS: Void Linux (RRVL)
- Compiler: gcc 9.3.0 arm64

**Comment by valadaa48** [comment]
https://github.com/valadaa48/retroroller/issues/188 some more context

**Comment by barbudreadmon** [comment]
i don't understand, that's on odroid go ? meaning a gles machine ? what's glcore video driver doing on such machine ?

**Comment by barbudreadmon** [comment]
So it turns out that, even before https://github.com/libretro/RetroArch/commit/96e6f99f1472a9d55b1fd6caf699d0a39ffde81a, gles devices are always using the "gl2_driver", whether you set "gl" or "glcore" as video driver. 
So the real question here is why the `--disable-opengl_core` isn't forced when building for gles targets ?

**Comment by barbudreadmon** [comment]
My PR should allow gles devices to use glcore again (it's non-sensical tbh, glcore is modern desktop gl, so i don't understand why this video driver can be used with gles).

> Allow cores to switch the video driver = false.

Yes, fucking up your cores when doing that is expected behavior, you should read https://www.libretro.com/index.php/changing-behavior-of-gl-and-glcore-video-drivers/
