### ISSUE TITLE
libretro api request - netplay enabled

### ISSUE THREAD

**Issue by SimpleTease** [libretro/RetroArch#11503]
Asking for way for core to check frontend if netplay is enabled. Then core options that break determinism (memory randomization, rtc clocks) could be disabled or value defaulted.

**Comment by hizzlekizzle** [comment]
This is a tough one, since rollback netplay (i.e., the thing that requires determinism) isn't a part of the libretro API, but rather just a thing that RetroArch can do. That is, we try not to have RetroArch dictate the API, since other frontends may not have rollback netplay, or perhaps they have non-rollback netplay and those options are actually desirable during that alternative netplay.

**Comment by SimpleTease** [comment]
Oh. Thanks for explaining this! I guess adding some warning to the core that special option could break rollback netplay would be better.
