### ISSUE TITLE
[Vita][Feature request] Bring the OpenGL ES 2.0 video driver over, now that it's possible to do so

### ISSUE THREAD

**Issue by swosho** [libretro/RetroArch#11534]
https://github.com/SonicMastr/Pigs-In-A-Blanket
The benefits of the gles2 driver are, of course, shaders and hardware acceleration.

This solution should supersede this unrealised GXM driver implementation:
https://github.com/libretro/RetroArch/issues/9015
and solve the point of this issue:
https://github.com/libretro/RetroArch/issues/9603

**Comment by OsirizX** [comment]
Here's a W.I.P version.
[https://github.com/OsirizX/RetroArch/tree/vita_gles](url)

It currently works only with DolceSDK as it seems to crash after compiling with VitaSDK.
Also it uses the forked version of PIB from fgsfds for easier lib compilation. [https://github.com/fgsfdsfgs/Pigs-In-A-Blanket](url)

**Comment by OsirizX** [comment]
With the TLS key [fix](https://github.com/vitasdk/newlib/commit/34ca70545302f63dcb15ffd3ea63894a8d224028) from TheFloW, it now runs fine using vitasdk.

**Comment by swosho** [comment]
Fantastic, it works! Looks like now it only needs to have the CG shaders support enabled and possibly GLSL disabled.
Hope it'll become a default driver eventually.

**Comment by frangarcj** [comment]
IMHO it should not become the default driver. The bundled distribution of piglet / pigs in a blanket within retroarch is illegal. So the only option for it to be included in retroarch is that the user installs the modules of piglet in a directory of their vitas.

On the one hand, I appreciate the work and I'd like to collaborate with @OsirizX in order to get a legal inclusion of piglet both on Vita and Ps4 ports.

On the other hand, let's clarify things about gxm and gl1 context. We already have hw acceleration on both drivers and it is possible to use them as contexts for hw accelerated cores. For instance, @Rinnegatamante is working on flycast. There's no magic solution that would make any 3D core to automatically work on Vita. Even with piglet you need to adapt the shaders to cg. Furthermore , that work would benefit the three drivers.

As a side note, gxm would always give you the best performance in 2d cores because it does the minimum steps to do so. Closer is vitaGL that could be optimized to give you similar performance.

**Comment by swosho** [comment]
While I understand the fair reasoning behind why it shouldn't be a default driver, since not everyone by default have piglet and shacccg modules dumped and ready to use, I don't see how including the mentioned Pigs-In-A-Blanket itself is illegal.

And it looks like you only have to compile the PIB-enabled RetroArch with "Cg runtime support" for the RA-bundled CG shaders to just work, so no adapting is required with this driver at least. The audio pops/cracks occurring during the frame drops are also much less pronounced with this driver for some reason, there's really no downside in using it driver over the other currently available solutions.

**Comment by frangarcj** [comment]
My bad, previous versions of pib did include the modules as binaries in c code. I'm not against having another driver.

CG bundled shaders are working because @OsirizX ported them. This shaders will be available to the three drivers. I saw his code and it needs some changes in order to have the three drivers available to users. 

Can you tell me what core are you testing? I want to see the audio crack problem.

**Comment by swosho** [comment]
Ah, sorry, I meant that this RetroArch build can't discover/see the CG shaders at all but it does acknowledges the GLSL shaders, despite the Cg runtime supposedly being there all right. "Might not be available if RetroArch is built without Cg runtime support" is essentially the only thing that came up while looking up the issue.

Regarding the audio crackle, this might be a bit too narrow for a valid example but here goes: Gungage (J) on PCSX ReARMed drops frames severely when there's an explosion happening close to the camera, the accompanying explosion sound is harsh when played with vita2d video driver, though not nearly as much with gl.

Thank you guys for working on this!

**Comment by SonicMastr** [comment]
To clarify, PIB has never, and will never include modules in the library. I made it with that in mind. The user installs the modules with a separate tool. PIB is nothing other than an enabler and patching library to bridge the gap between Piglet and ShaccCg while also fully implementing SCE extensions just like Orbis Piglet. Pigs in a Blanket is perfectly legal, and just like VitaShark, the part that could be a gray area is in the hands of the user instead. This makes it easier on developer in legality with basically no repercussions to the user instead of a prerequisite setup.

That setup, though, is all the more of a good reason to not have a GL driver of any kind as a default renderer. Vita2d is completely open source and doesn't need external modules, meaning no extra setup for the user. The GL drivers in this current state would either need to stay optional or the modules would need to be included in Retroarch, which is a big nono.

**Comment by frangarcj** [comment]
Right @SonicMastr, it was my mistake about PIB. The one having problems of distribution is PIB-Configuration-Tool. I'm sorry about that.

And about legality... I am not saying that the software is illegal. This is a matter of illegal distribution.

I will try to adapt @OsirizX branch in order to the 3 drivers to coexist.

**Comment by jop3-vita** [comment]
Is Retroarch still using Piglet or is it using solutions like https://github.com/GrapheneCt/PVR_PSP2 or https://github.com/Rinnegatamante/vitaGL ?

**Comment by Rinnegatamante** [comment]
Still Piglet.

**Comment by jop3-vita** [comment]
Sad... I can see its not a money issue, the bounty @Rinnegatamante started https://app.bountysource.com/issues/82107167-bring-hw-context-support-to-gl1-driver has a good value in it. The tools are already here for a better retroarch on the ps vita, again https://github.com/GrapheneCt/PVR_PSP2, https://github.com/Rinnegatamante/vitaGL, and https://github.com/GrapheneCt/vitaAL. And also the community is wishfull for the same https://github.com/libretro/RetroArch/issues/14760. What can more be done from the community/users/developers?
