### ISSUE TITLE
Retroarch for switch and 7z archives

### ISSUE THREAD

**Issue by alucryd** [libretro/RetroArch#11687]
## Description

Can't browse 7z archives or load any 7zipped roms in retroarch for the nintendo switch, works fine on linux.

### Expected behavior

7z archives should work just like on linux.

### Actual behavior

7z archives appear empty and loading them directly doesn't work. First time trying retroarch on switch so I'm not sure if that's expected or not, and I couldn't find any issue about it in here. Not sure if this is a switch limitation, I don't remember having troubles with them on the 3DS, PSP and Vita, but I could be wrong.

### Version/Commit

- RetroArch: 1.9.0

### Environment information

- OS: Nintendo Switch running Atmosphere 0.16.1

**Comment by mpalomas** [comment]
This is because, apparently, the Switch build is not compiled with HAVE_7ZIP=1. 

That's rather strange indeed, maybe there is/was a good reason. Other systems including WiiU, Vita seems to have this flag.

It's literally a 10 seconds fix (in Makefile.switch)... Maybe we can try it and see if the CI passes.

**Comment by alucryd** [comment]
Great! Should I submit a PR? Does libretro-super need modification as well?

**Comment by mpalomas** [comment]
You should yes, then we'll see if one of the main contributors has some recollection about why it's missing. You should test your custom build on your Switch if you can.
