### ISSUE TITLE
RG350M Screen Resolution is reported incorrectly by log [INFO]: 320x240 when it should be 640x480

### ISSUE THREAD

**Issue by john-parton** [libretro/RetroArch#11880]
## Description

When you start a core on the RG350**M**, the logs report the screen resolution is `320x240` when it is in fact supposed to be `640x480`. Here's the log: [retroarch__2020_12_13__17_06_35.log](https://github.com/libretro/RetroArch/files/5816305/retroarch__2020_12_13__17_06_35.log)

### Expected behavior

[INFO] Should report the correct resolution of 640x480 and core should run at 640x480

### Actual behavior

[INFO] is reporting wrong resolution. I think (although I'm not 100% sure) that the core is running at the wrong resolution

### Steps to reproduce the bug

1. Enable Logging
2. Start any core
3. Inspect the logs and look for `[INFO] [Video]: Video @`

### Bisect Results

It looks like there are lots of places where it's assumed the resolution of an OpenDingux device is 320x240. Examples:

https://github.com/libretro/RetroArch/blob/cb087656ddc012f321078eb0c7bdb16e30a7dd95/menu/drivers/rgui.c#L4898-L4901
https://github.com/libretro/RetroArch/blob/cb087656ddc012f321078eb0c7bdb16e30a7dd95/menu/drivers/rgui.c#L4933-L4936

I think this one is just for the menu, and not for the cores: https://github.com/libretro/RetroArch/blob/184d15bdd2bbcb17d4ee5f670a80d5bc06675066/gfx/drivers/sdl_dingux_gfx.c#L49-L50

### Version/Commit

- RetroArch: Nightly, build date Jan. 13, 2021

### Environment information

- OS: OpenDingux on RG350M
- Compiler: Automated build from Jan. 13

**Comment by jdgleaver** [comment]
No, that's not how it works. RetroArch on OpenDingux always outputs at the content resolution. RGUI is 320x240, so that's what you get when running the menu. If you run a GBA game, it will output at 240x160. If you run a GBA game with the Grid2x video filter, it will output at 480x320. And so on.

This is absolutely the correct behaviour. It is the job of the IPU hardware scaler to upscale RetroArch's output to the full 640x480 of the display. Performing this upscale in software (i.e. on the RetroArch side) would do nothing but reduce both performance and image quality.

**Comment by john-parton** [comment]
@jdgleaver It looks to my weak eyes like all of the cores are scaled correctly.

If you look at the logs, it definitely reports the following:

```
[INFO] [Video]: Video @ 320x240
```

What's this logger actually saying?

I've used RetroArch for years, but I'm just starting to actually contribute.

**Comment by jdgleaver** [comment]
> It looks to my weak eyes like all of the cores are scaled correctly.

Yes, all content is indeed scaled correctly :)

> What's this logger actually saying?

I can certainly understand why that log message might be deceptive!

What it's showing you there is the current fullscreen resolution at the point when the video driver is initialised. On most platforms (e.g. Windows, Linux) this corresponds to the actual screen resolution, which for the most part can be considered a fixed parameter - i.e. no matter what content is being displayed, RetroArch itself will scale the output image to this resolution.

OpenDingux is an oddity in this regard because (a) we cannot determine the actual display resolution from the hardware itself and (b) display resolution is irrelevant, since we always output at the content resolution (as I explained). Thus `current fullscreen resolution at the point when the video driver is initialised` is essentially meaningless - all we do is set placeholder values corresponding to the minimum possible resolution of any OpenDingux device, and then the sdl_dingux gfx driver sorts out the rest (without generating logs, because output resolution changes *all the time* on OpenDingux, and there would be too much spam...)

> I've used RetroArch for years, but I'm just starting to actually contribute.

Contributions are always welcome!

**Comment by john-parton** [comment]
Okay, that makes sense. I'm currently trying to get dosbox-pure to compile for the mips32/rg350 platform, and there's a lot of finer details that I'm still trying to wrap my head around.
