### ISSUE TITLE
Softcore achievements issue with save/load states

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#11894]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

This issue described here: https://docs.retroachievements.org/Why-you-shouldn't-use-the-load-state-feature/

Earlier it was in all Retroachievements-supported emulators, now it happened only in Retroarch.

### Expected behavior

Achievements should triggered properly, so internal achievement information should be in save state too.

### Actual behavior

> 
> Example 1: Beat the game without passwordslink
> 
> Imagine a game with 5 stages and with the password feature.
> 
> Probably the conditions to trigger the "Beat the game without passwords" are (in a real cheevo there will be more conditions, but for this explanation let's consider only these ones):
> 
>     be at stage 1 (and memorize this event as something that happened)
>     be at stage 2 (memorize it)
>     be at stage 3 (memorize it)
>     be at stage 4 (memorize it)
>     be at stage 5 (memorize it)
>     finish stage 5
> 
> So to get this achievement you have to pass through all stages and then beat the game.
> 
> When you are at the stage 1, the emulator memorizes it, same thing for all other stages. And when you finish the stage 5 (beat the game) you get the achievement.
> 
> Now imagine this scenario:
> 
>     a softcore player started the game and played stages 1, 2 and 3
>     he needed to stop playing when at stage 4 and then he saved a state to continue later
>     he closed the emulator
>     later he could play again, started the game and loaded the state he saved
>     played stages 4, 5 and beated the game
> 
> In this scenario the achievement won't trigger.
> 
> After closing the emulator it "forgets" that you passed through stages 1, 2 and 3. When you run the emulator/game again and load the state being on stage 4, the emulator won't detect that you passed through the previous stages. Then the achievement won't trigger.
> Example 2: Defeat boss X without taking damagelink
> 
> Most likely the conditions to be met in a frame to make this achievement trigger are:
> 
>     entered the boss room (and memorize this event as something that happened).
>     if take any damage, forget it entered the boss room.
>     beat the boss.
> 
> In other words: to get this achievement the emulator must "know" that you entered the boss room, didn't get any damage, and beated the boss.
> 
> The important detail to pay attention here: when you get any damage, the emulator "forgets" that you entered the boss room. Then even if you load a state to a point where you didn't get any damage but already entered the room, the emulator won't detect that you entered the room. And then the achievement won't trigger.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 0bba2d4

### Environment information

- OS: All OSes
- Compiler: [In case you are running local builds]

**Comment by Jamiras** [comment]
The problem, as you've identified, is that the achievement runtime state needs to be included in the RetroArch save state.

Right now the RetroArch save state only holds the serialized data provided by the core. The achievement runtime already supports serializing its own state, which is how the RetroAchievements-managed emulators address the issue. We just need to figure out some way to include that data in the RetroArch save state.

At one point, I proposed using a container format to allow multiple pieces of data to be stored in the save state specifically so I could add this functionality, with the thought that it could be expanded to include other things like a screenshot or information about which core was loaded. I can't find that discussion, so I don't remember the exact details of the response. I think it was something along the lines of just appending the data, but that doesn't work very well when neither the core state nor the achievement state has a fixed size.

Another option would be to store the data in a file next to the save state, which is what the RetroAchievements-managed emulators do since each emulator has its own save state format.

**Comment by ofry** [comment]
And what prevents to store the data in a file next to the save state? As we already put screenshot of state by such way...
