### ISSUE TITLE
Permission/Thoughts on Integrating Retroarch with LaunchBox

### ISSUE THREAD

**Issue by jasonunbrokensoftware** [libretro/RetroArch#12241]
Hi there, Retroarch devs. My name is Jason Carr; I'm the developer of LaunchBox and Big Box. A few years ago I contacted the development team via email to ask if it would be okay to integrate Retroarch into LaunchBox, but the response was that the team would prefer if I did not integrate it, so I respected those wishes and did not.

However, just recently, we saw hizzlekizzle's post on Reddit here: https://www.reddit.com/r/RetroArch/comments/mib8rh/questions_about_what_retroarch_is_capable_of/gt3v3j6/?context=3

That was intriguing because it sounds like that stance has changed. I've also spoken to hizzlekizzle via PM, and confirmed that it would be okay for us to integrate Retroarch into LaunchBox, so long as we obeyed the license. That said, I absolutely do not want to continue with that and integrate Retroarch into LaunchBox unless we have full support from the team, and I want to make sure that there are absolutely no hard feelings from anyone before we proceed with the integration.

Sorry to reach out via a Github ticket; that's what hizzlekizzle recommended, so I hope this works to reach the whole team. Everyone's work on this project is so much appreciated, and I think if we were able to integrate it, it would be a big step forward towards making emulation easier for everyone, but I still want to respect the wishes of the core development team, and I will not proceed without mass approval from the team.

Thanks again everyone for all your work. I'm more than willing to discuss integration specifics as well if needed.

Jason

**Comment by jasonunbrokensoftware** [comment]
Sorry, I posted the wrong link somehow. Here you go: https://www.reddit.com/r/PleX/comments/mczs4a/another_reason_to_choose_retroarcher_over_plex/gt64yqj/?context=3

**Comment by hizzlekizzle** [comment]
To be clear: I (and I assume everyone else) would still prefer that people get RetroArch from us for a variety of reasons. However, the license (GPLv3+) is the real decider here. It's what allows people like Plex to use RetroArch with their product(s), and it allows you to do the same. I can't really give you any additional assurance beyond that, other than to say that if some problem comes up, we'll contact you about it to resolve it amicably rather than stirring up community/mob strife.

**Comment by twinaphex** [comment]
If you're going to do this, we would appreciate a link to our website (www.retroarch.com) and a Libretro/RetroArch logo so we still get traffic back to our website, since that is ultimately important to us. Do add a text in saying that this is not official and that Libretro/RetroArch are not associated in any way or shape with Launchbox. We want to make sure that part is clear at least. As for the rest, you'll need to make sure that it's in compliance with GPLv3, i.e. users need to be able to replace this copy of RetroArch with another version that they self-built, that kinda thing.

I'm not really sure how the GPL (and especially v3) deals with a commercial app that is closed source though. You'll have to look into the rules regarding aggregation there. We'd appreciate if you do this legal legwork all yourself since it would just take time away from us we could be spending ourselves on development.

Beyond that I'll leave things up to @hizzlekizzle 's discretion and you can defer to him.

**Comment by jasonunbrokensoftware** [comment]
Thank you both; I really appreciate your responses.

In order to proceed, we would need to either include Retroarch in the original download of LaunchBox, or automatically have the app just download it from the servers. We currently require the user to download and install Retroarch themselves if they choose to use it with LaunchBox (of course), but the main advantage of further integration would be reducing those required steps in order to get up and running quicker and easier for users. So I just want to make sure that there's no hard feelings there.

If we proceed, we'll definitely make sure to follow all the requested steps; thank you twinaphex for detailing those out. We have no issues with adding links and making it clear that it's not our software; we have no intentions of hiding any of that.

I have done the research on the GPL, and though it gets really hairy, the main stipulation is that we can't link to DLLs without distributing source code. I have distributed some source code recently in the past to fulfill those requirements with other products, but I don't see us linking to any DLLs for the Retroarch integration. Most likely we'll ultimately just be running the Retroarch EXE with command-line parameters, so legally I don't see an issue there. I will review the license with my lawyer though to make absolutely sure that it's not an issue.

Thank you both again for the transparency and the generosity here. The one thing I'm hearing that isn't preferred is the distributing or downloading of Retroarch directly in the app, which unfortunately would be required for further integration. If I have your blessing to proceed with that, we'll make sure to follow all the requests here in this thread, and we can proceed. Otherwise, I fully understand if either of you would really rather us not integrate it like that. The point of this conversation was to get a yes/no on your own personal opinions and convictions of whether we should integrate it, not to ask if we can "get away with it" legally. I want to respect the developers of the project, not abuse them by finding some kind of loophole in the license, which is why I've held off from doing it for all these years. I really want to make sure everyone feels good about us proceeding if we're going that direction; I don't want anyone to have a bad taste in their mouth.

I really do believe that Retroarch is the best solution out there for this stuff, so that is why I'm so interested in the integration, because I really think it would be a big step up for the community if we were to come up with an out of the box solution. I'm envisioning something more like Boxer on Mac, where things really just work out of the box (but with far more transparency in telling the user that Retroarch is doing the emulation).

Thanks again to you both; I'll look forward to hearing back, and I'll do my best not to elongate this conversation any further so you guys can get back to dev. :)

**Comment by hizzlekizzle** [comment]
Don't worry, you won't be exploiting any loophole, and there's no resentment on our end. We used to be more personally wrapped up in this kind of thing but it just ends up being bad with everyone walking on eggshells because it's not clear what's allowed and what's not. We believe in open-source, and that means embracing that we don't have absolute control over everything that happens.

Since you won't be linking against anything and are using the command-line interface, I think you would be fine either way, including shipping it pre-bundled (again, IANAL). However, including a hook to download it from us at runtime saves you from bundling a pretty large package (that is, it's a big download for people who may not even want it) and it does give us some information/analytics as to how many people are downloading it, etc., which is nice.

**Comment by jasonunbrokensoftware** [comment]
Cool, thank you HK. Assuming @twinaphex is okay with it as well, we'll start working on the integration here soon. I'm envisioning just automatically downloading Retroarch and any necessary cores from the Retroarch servers as part of the game import process. 

Thanks again to you both. Very excited to get this rolling. :)
