### ISSUE TITLE
[Feature Request] keyboard shortcut to disable shaders

### ISSUE THREAD

**Issue by vavelpo** [libretro/RetroArch#12242]
Please add a keyboard shortcut to disable shaders. It would be useful to be able to quickly disable shaders to compare with the default settings, or when shaders are causing a performance drop.

**Comment by wyatt8740** [comment]
I'd love this, too, but if you'd be okay with a stopgap solution for now, something that works for me is creating a new shader preset (I call mine `00_none.glslp` since my shader I'm comparing to is called `1_lut64.glslp`) that contains only the line `shaders = "0"` and alternating between it and the shader I'm working on using the next/previous shader keys.

It spits out an error (saying "failed to apply shader preset") on the OSD every time you switch to the 'none' shader this way, but it does work for me regardless.

**Comment by vavelpo** [comment]
Thanks for the reply.

I would like to work around the problem using the method you described until the feature is added.
