### ISSUE TITLE
Error on extracting several games in zip files since 1.9.4 on Windows 10

### ISSUE THREAD

**Issue by hkaaaa2304** [libretro/RetroArch#12476]
## Description
Error on extracting several games in zip files since 1.9.4 on Windows 10

[Description of the bug]
For instance : Error on extracting zip file on start of game with caprice32 (from mame cpc_flop , 6pakvol3.zip crc32 E64F2C8E)

### Expected behavior
Should extract this zip file with no errors, worked in 1.9.3, 7zip : zip is ok

### Actual behavior
Error on extracting zip file

[What is actually happening]

### Steps to reproduce the bug

Start game with caprice32 causes error message by retroarch 1.9.4

### Version/Commit
RetroArch 1.9.4 (Git c226bd8)

### Environment information

Win 10 19042.985
[6pakvol3.zip](https://github.com/libretro/RetroArch/files/6586633/6pakvol3.zip)

**Comment by bslenul** [comment]
Seems to be caused by the `#` in the rom filename (`6 pak vol.3 1a (dragon's lair) #2 (nongoodcpc).dsk`), remove it from the filename and it'll load fine.

I guess RetroArch is getting confused, because `#` is also used to mean "the file inside the archive", in the History tab for example instead of showing `6 pak vol.3 1a (dragon's lair) #2 (nongoodcpc)` it shows `6pakvol3.zip#6 pak vol.3 1a (dragon's lair) #2 (nongoodcpc)`.

I tried in 1.9.3 and it was working indeed, but ONLY if you used "Load Archive" instead of "Browse Archive", with the latter the core loads but it's confused as well and the rom isn't loaded properly.

**Comment by jdgleaver** [comment]
Oof... Seems we can't make any changes around here without unearthing ancient bugs...

Thanks for the report. This should fix the issue: #12477

**Comment by bslenul** [comment]
Works like a charm, thank you as usual! ❤️
