### ISSUE TITLE
Publish releases to WinGet repository

### ISSUE THREAD

**Issue by felipecrs** [libretro/RetroArch#12471]
It would be awesome if we could have automated deployments of new versions of RetroArch to WinGet. Currently, the last version on it is 1.9.0, which was probably uploaded manually.

More information on how this can be easily automated in CI can be found in the link below:

https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

So someone could easily run `winget upgrade retroarch` or get it upgraded automatically when running `winget upgrade --all` without any hassle.

**Comment by FurtadoPires** [comment]
Apparently someone is already maintaining through `winget upgrade Libretro.RetroArch` which pulls from https://buildbot.libretro.com/stable/

But it seems to not being pulling from the folder with the latest version, because right now it pulls the version `1.9.0`, and the most recent at the time of  this post is `1.9.10`

**Comment by LibretroAdmin** [comment]
Seems to be done now.
