### ISSUE TITLE
[OGA/OGS] Brightness is reset to 100% on exit

### ISSUE THREAD

**Issue by miwasp** [libretro/RetroArch#12560]
## Description

If you start any libretro core out of ES, the brightness is set to the value "screen_brightness" defined in (Settings->Video).
If you exit retroarch and go back to ES, the brightness is reset to 100%.

### Expected behavior

Brightness should on exit be set back to the value it was before starting retroarch.

### Actual behavior

Brightness is set to 100% on exit.

### Steps to reproduce the bug

1. Set brightness to 40% in ES
2. Start any game with any libretro core
3. Set screen_brightness to 20% in retroarch (Settings->Video)
4. Exit the game (resp. retroarch)
5. 
### Bisect Results

This worked in 1.9.3.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.5 / 7b47f5f49a2cc64a04a70e282647140b240522e6

### Environment information

- OS: EmuElec on OGA, OGS or Gameforce
- Compiler: [In case you are running local builds]

**Comment by miwasp** [comment]
Well, it worked half way in 1.9.3.
It seems that "screen_brightness" was ignored in 1.9.3 if it was set to 100%.
If you set "screen_brightness" to a value lower than 100%, 1.9.3 behaves the same as 1.9.5.

**Comment by miwasp** [comment]
Maybe its possible to add "OFF" or "IGNORE" to the setting "screen_brightness" to leave the brightness untouched?

**Comment by miwasp** [comment]
Code snippet out of file frontend/drivers/platform_unix.c, function frontend_unix_deinit():
```c
#ifdef HAVE_LAKKA
   /* Reset brightness to maximum */
   if (settings->uints.screen_brightness != DEFAULT_SCREEN_BRIGHTNESS)
      frontend_unix_set_screen_brightness(DEFAULT_SCREEN_BRIGHTNESS);
#endif
```
Why is this done?

**Comment by gouchi** [comment]
This is done only on Lakka as there is `ifdef HAVE_LAKKA` but I doubt that EmuELEC compiles RA with `HAVE_LAKKA `?

@davidgfnet should have some explanation about your request ;)

**Comment by miwasp** [comment]
EmuELEC indeed compiles RA with `HAVE_LAKKA`

Many systems use something like Emulationstation (not only EmuELEC) as a frontend and call libretro cores from there. In most of these systems you can already set the brightness in ES or OS, so there is no need to also set it in RA. If anything it is conflicting or confusing on such systems. So it would be great, if the brightness setting in RA could be disabled.

**Comment by davidgfnet** [comment]
As gouchi says, if you build with HAVE_LAKKA... you get Lakka behaviour.
I'm not sure whether you should disable the screen brightness management from within retroarch at all since your distro already provides a way to set it right?
Please also note that in retroarch.c, at startup (retroarch_main_init) Retroarch will also change and reset the brightness level to the previously stored brightness value. This was recently added, so perhaps Emuelec hasn't picked up the change yet (c378665af54).
This is sort of intended behaviour in Lakka: RA manages the screen brightness (since we did not have another way to do this before). For opting out of this behaviour we might need a config knob or something (instead of HAVE_LAKKA). In the meantime you can always patch it, sorry I dont have a better idea! ^^'

**Comment by miwasp** [comment]
For now RA in EmuELEC is patched to ‚sync‘ the brightness setting between ES/OS and RA.
Thanks anyway.

**Comment by bernardtkj** [comment]
Hi, I still having this issue on emuelec 4.3 test.

**Comment by miwasp** [comment]
> Hi, I still having this issue on emuelec 4.3 test.

This was fixed 3 test releases ago in EmuELEC. IF it still does not work for you, please open an issue in the EmuELEC repo.

**Comment by gingerbeardman** [comment]
Opened as https://github.com/EmuELEC/EmuELEC/issues/1136
