### ISSUE TITLE
Feature Request anothers cores for Atari 7800 , 3DO and Virtual Jaguar

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#12585]
Hello.

Retroarch current version emulate Atari 7800 using core Prosystem , but that core not is accurate (Pokey and graphics) and have problems with new homebrews roms.
A7800 is a Atari 7800 emulator very accurate and fast playing any current homebrew rom.
A7800 is exactly MAME only with a7800 driver.

3DO core is slow and Jaguar not is accurate being slow.
Phoenix is a 3DO and Jaguar emulator accurate and very fast being double performance if comparing with opera and virtualjaguar.

Raine is a Neo Geo emulator very fast and accurate.

Source code is available in links , but I not understand if Phoenix has source code available because the site is Russian.

http://7800.8bitdev.org/index.php/A7800_Emulator#Linux
https://raine.1emulation.com/download/latest.html
http://www.arts-union.ru/node/23

In moment I not has programmer skill to create Retroarch cores from emulator source codes above.
Thanks for read my topic and have a nice week.

**Comment by Langerz82** [comment]
Can we also get:
Parallel64 - https://github.com/libretro/parallel-n64
(Capcom 1) - cps1 - https://github.com/libretro/fbalpha2012_cps1
(Capcom 2) - cps2 - https://github.com/libretro/fbalpha2012_cps2
Apologies if cps1 and cps2 is added, but I could not switch to emulator in EmulationStation under advances settings for there respective folders.

**Comment by Cee123** [comment]
I would love Phoenix as a core of Retroarch. It actually runs 3DO and Jaguar properly. But that's not going to happen because they're closed source, as in the developer chose not to share the source code with anyone. I did reach out to the developer for Phoenix/IrataJaguar/Real3DOPlayer to see if he would ever consider allowing a Libretro port of his emulators, or at least compile an arm/arm64 version so it could run it on Raspberry Pie or Odroid but the first couple of times he didn't even respond. And probably the third time he replies he said "sorry I'm too busy". So I guess that's it. So unfortunately that's not going to happen.
