### ISSUE TITLE
[Feature Request] AMD FidelityFX Super Resolution (FSR) and/or other neuro rescalers?

### ISSUE THREAD

**Issue by DartPower** [libretro/RetroArch#12765]
What about implementing AMD FidelityFX Super Resolution (FSR) and/or other neuro rescalers?

https://github.com/GPUOpen-Effects/FidelityFX-FSR
https://github.com/igv/FSRCNN-TensorFlow
https://github.com/bloc97/Anime4K

Example: (My idea from here)
https://github.com/7Brandyn7/Magpie

**Comment by hizzlekizzle** [comment]
We have nnedi3 already, which is an older neuro rescaler.

I looked at FSR, but we don't currently have any way to apply computer shaders to the pipeline, and I was under the impression it's not designed for content that's as low-res as we typically deal with.

I've also made a few ports of Anime4K (and there's one from hyllian already in the slang shader repo), but they haven't looked appreciably different from bilinear, so something must be going wrong somewhere...

I'll see if any of the ACNetGLSL shaders will work, though.

**Comment by twinaphex** [comment]
From what @Themaister told me, FSR could be implemented as a slang shader.

**Comment by arrowgent** [comment]
https://gpuopen.com/fidelityfx-superresolution/

it needs to be DX12 or Vulkan
emulators that only use opengl, dx9/10/11, or software rendering wont benefit from this at all

ive done testing in linux wine/proton dxvk with an early example

in some cases the sharpening filter, lower resolution upscaling, FPS & GPU usage are beneficial
others there is no impact on FPS at all, although the GPU SM% is lower (using less gpu resources)
not all games are working using the FSR, but most games are working using the upscale (aka fshack in wine)

configuration options in the emulator + retroarch settings will be important
rendered resolution : native output desktop resolution
sharpening quality
MIP bias
are the current settings

while in some emulation this could prove excellent for upscaling
i feel that there is a modest loss in quality in most situations
others dont appear to impact FPS at all yet do lower the overhead on the GPU usage

testing with Grim Dawn on linux proton-ge-6.14-1 FSR release
https://imgur.com/a/SW8L5hz

GPU load effects FPS here decently, mainly effecting the Minimum FPS but not always the Maximum FPS


since its now open source i hope more work can be done to improve the scaling techniques used
maybe v2.0 will be a linear improvement over this first release version

**Comment by LibretroAdmin** [comment]
FSR shader was implemented .
