### ISSUE TITLE
RFC: new libretro environment callback to stop the background threads of a core

### ISSUE THREAD

**Issue by flyinghead** [libretro/RetroArch#12865]
### Rationale ###

Some cores (flycast, ppsspp, dolphin, ...) have running background threads that may call into the frontend to push audio or poll inputs at any time. This makes RetroArch crash when this happens at the wrong time, such as when reinitializing drivers or when a controller is connected or disconnected.

### Proposal ###

One way to avoid this issue would be for the frontend to ask the core to stop any background thread before starting such an operation. The core may still call the frontend while shutting down these threads, but not after returning from the callback. The core is then free to start new background threads in the next `retro_run()` call.

### Caveat ###

I'm not familiar enough with RetroArch internals to know how usable this would be from a frontend standpoint, or even if it would be useful at all. The other way to fix these issues is to use locks and mutexes in the frontend where needed.

### Implementation ###

The implementation could be as simple as this:
```
#define RETRO_ENVIRONMENT_SET_STOP_THREADS_CALLBACK 70
                                            /* const struct retro_stop_threads_callback * --
                                             * Sets a callback function used to notify the core when background threads must be stopped.
                                             */

/* Callback type passed in RETRO_ENVIRONMENT_SET_STOP_THREADS_CALLBACK.
 * Called by the frontend when the core must stop any running background thread.
 * This may happen when the frontend needs to reinitialize audio, video or other drivers.
 *
 * The core must stop and wait for completion of any running thread before returning from
 * this callback.
 */
typedef void (RETRO_CALLCONV *retro_stop_threads_t)(void);
struct retro_stop_threads_callback
{
    retro_stop_threads_t stop_threads;
};
```

**Comment by jdgleaver** [comment]
@flyinghead I started trying to implement this feature, but unfortunately it seems to be somewhat impractical. There are simply too many places and too many ways that things can break if cores use callbacks on background threads. I also think that it would give a false sense of security - i.e. the new callback could be used to fix the most egregious types of crashes caused by frontend driver reinits, but it wouldn't guarantee thread safety *everywhere*, leading to nasty edge cases that might get missed by devs during normal-ish use.

I'm really sorry about this... When I started on it, the new callback seemed like such a great idea... :(

I don't know the best way to approach a general thread-safety fix without major changes to RA, so in the meantime I guess it is optimal if cores do as much as they can on the main thread. In the case of flycast, I notice that you've already moved input polling onto the main thread, which pretty much leaves audio as the main thing that stands out. I've therefore made a PR that moves this onto the main thread as well: https://github.com/flyinghead/flycast/pull/442

I don't know how you feel about this, but it at least makes the core more 'safe' (and less prone to these frontend-related thread issues), and I see no obvious performance regressions.

**Comment by flyinghead** [comment]
I just merged your PR. Thank you for this.

If it makes this proposal obsolete then it's all good, since it was probably not the right solution to the problem.

**Comment by i30817** [comment]
This bug is giving me deja vu about Java's 'Thread.stop()'. A deprecated method way back in java 1.3 or 1.4 because making thread stop without their awareness is a fine way to create deadlocks and poisoned locks where there were none.

**Comment by jdgleaver** [comment]
> I just merged your PR. Thank you for this.

You are most welcome. Your work on flycast is the stuff of legend, and I'm happy to help in any small way that I can!

> If it makes this proposal obsolete then it's all good, since it was probably not the right solution to the problem.

It was certainly a neat idea, but the way RA is set up kinda confounded the solution. You are right that mutexes everywhere in the frontend is a more correct fix - but then again, there are benefits to the current model of requiring cores to do certain things on the main thread, since it allows the frontend to precisely synchronise input/audio/video in a well-defined manner. Flycast should be fine now that the main callbacks all happen in `retro_run()` - so hopefully as a core dev this isn't something you'll need to worry about again :)
