### ISSUE TITLE
When "save overrides" is used, Retro Achievements info (password & token) is saved in config files.

### ISSUE THREAD

**Issue by PurpTentacle** [libretro/RetroArch#12953]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When RetroAchievements are used along with using "Save Game Overrides" in the Overrides sub-menu, the lines for cheevos_password = “” & cheevos_token = “(token would normally go here, I removed it)” get saved in the cfg file. This can make it impossible to log into RetroAchievements as it uses the wrong token due to the overrides.

### Expected behavior

I expect the the "cheevos_password" & "cheevos_token" should not be saved as a part of saved overrides.

### Actual behavior

The "cheevos_password" & "cheevos_token" to not be saved in the cfg files when using "save overrides" command (either "Save Game Overrides" or "Save Core Overrides").

### Steps to reproduce the bug

1. Make sure to be logged into RetroAchievements account.
2. Click on the Overrides sub-menu, and then, "Save Game Overrides" or "Save Core Overrides".

### Bisect Results

No idea...

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.9 - Stable Windows 10 version

### Environment information

- OS:  Windows 10

**Comment by Jamiras** [comment]
The override functionality only saves the values that differ from the master settings file.

To actually reproduce this, you need to enter your retroachievements credentials and save the primary retroarch.cfg. Then load a game, wait for the login acknowledgement and then save the override. The login will blank out the password and set the token. Since those values now differ from the top-level file, the changes will be written to the override.
