### ISSUE TITLE
savestate_thumbnail_enable always saved into content directory

### ISSUE THREAD

**Issue by rtomasa** [libretro/RetroArch#12972]
## Description

When `savestate_thumbnail_enable = "true"` is set, no matter what path you have in `screenshot_directory` or `thumbnail_directory`, it is always saved into `savestate_directory`

### Expected behavior

Image should be saved as defined in `thumbnail_directory`

### Actual behavior

Image is saved in `savestate_directory`

### Steps to reproduce the bug

1. Set `savestate_thumbnail_enable = "true"` in retroarch.cfg
2. Load a game and save state

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.5

### Environment information

- OS: Raspbian Buster

**Comment by i30817** [comment]
This is on purpose, those snapshots aren't user snapshots, they're associated to the savestate and that's the easiest way to do it.

Besides, putting them on that dir would confuse users looking for 'legitimate' snapshots.

**Comment by rtomasa** [comment]
I honestly see more confusing having both `savestate_thumbnail_enable` and `thumbnail_directory` parameters sharing the thumbnail word in their names. Also the image generated by this functionality contains the word _auto_ in its name, so it is pretty clear to me the source, but if you confirm that this is the expected behavior it's Ok

**Comment by i30817** [comment]
There is also the fact that users sometimes delete their data manually, (and for savestates that's the only way). If the thumbnails weren't in the savestates dir, a lot of trash would accumulate when this happened since the thumbnails would only get reused/overwritten if the user played the same game and saved new savestates on the same slot position.

**Comment by i30817** [comment]
I guess this issue is actually about the option naming not making clear that 'savestate thumbnail' is a completely different thing than 'thumbnail directory'.

This could be kind of easily solved by calling the 'savestate thumbnail' option 'savestate screenshot' (although that's not 'as' technically correct as 'thumbnail' which implies 'small screenshot'). 

This and not vice versa for 'thumbnail directory' because that dir saves screenshots and box art.
