### ISSUE TITLE
Genesis Plus GX loading Double Dragon 2 much slow than real console

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#12985]
Core using default CPU 100 % speed.
Try load Double Dragon 2.
The game is extremely slow if comparing with console. Music run in good tempo , but controls and gameplay are much slow.
If you change CPU clock to 125 or 150 % not has slowdowns , but will break some others games.
Retroarch and genesis gx core previous versions before 06-21 not happen that issue.

**Comment by Ryunam** [comment]
Can you perhaps post this here? https://github.com/libretro/Genesis-Plus-GX/issues

Based on the information you are sharing, this appears to be a problem with the Genesis Plus GX core specifically, rather than something related to RA as a whole. So it’s better to document this in the issue section of the core itself.

**Comment by Augusto7743** [comment]
Thanks very much and excuse me for posting wrong here.
