### ISSUE TITLE
Unable to install cores, both through Retroarch and manually

### ISSUE THREAD

**Issue by canada-water** [libretro/RetroArch#13184]
When I attempt to install a core, it does not install. I have the list of cores available for me, and I can scroll through the library, but nothing ever actually installs. I attempted to install one manually (pcsx2), but I always get the error "Core installation failed: pcsx2_libretro.so" and nothing else happens.

Version: a9125fffaa
Compiler: GCC 11.1.0
OS: Arch Linux, running the Linux 5.14.15-arch1-1 kernel

**Comment by hizzlekizzle** [comment]
If you go to settings > directory and see where your core directory is located, does it exist and can RetroArch write to it (i.e., user-writeable)? If you installed through a package manager, those builds typically intend on you using their distro packages for cores, as well, instead of the online updater, and, since package managers typically aren't supposed to write to user-directories, they will put the cores dir somewhere owned by root (e.g., /usr/share/games or whatever)

**Comment by canada-water** [comment]
> If you go to settings > directory and see where your core directory is located, does it exist and can RetroArch write to it (i.e., user-writeable)? If you installed through a package manager, those builds typically intend on you using their distro packages for cores, as well, instead of the online updater, and, since package managers typically aren't supposed to write to user-directories, they will put the cores dir somewhere owned by root (e.g., /usr/share/games or whatever)

I checked, and it wants cores to be located in /usr/lib/libretro. I did install it through pacman, so should I remove it and get the github version instead?

**Comment by i30817** [comment]
You can either make that directory writable, which will get undone when you upgrade retroarch iirc, or you can edit the path options to the core to a writable directory on your home, which will not get undone.

**Comment by i30817** [comment]
There is also the 'problem' that some distros distributed retroarchs bend to the policy of the distros of not distributing downloaded dlls/executables, which is the reason they're putting the cores on a system read only dir (so they upgrade only on system upgrades).

Since you can download, you probably don't have the download updater disabled from source - but some distro retroarch distributed packages _do_ and that is enough reason not to use them.

**Comment by canada-water** [comment]
> You can either make that directory writable, which will get undone when you upgrade retroarch iirc, or you can edit the path options to the core to a writable directory on your home, which will not get undone.
> 
> I'd suggest to look at the other path options too, to see if any one of them that needs writing is on a read only directory.
> 
> For instance these are my options (4 images inside, notice my cache directory is the linux memory filesystem, so i'm not writing to disk when uncompressing, which is something you should only do if you have 8gb+, preferably 16 or 32 if you're going to try to play several cd games in a row without a reboot):
> 
> paths

Awesome, that worked. I just changed the directory for the cores. Totally should've looked into doing that before posting about it. Thank you!

**Comment by i30817** [comment]
If the directory for the 'core info' files is read only too, change that too.

**Comment by FeralSmurf** [comment]
Wondering if I could also get a helping hand here?

Here's my config snippet from .config/retroarch/retroarch.cfg
```
libretro_directory = "~/.config/retroarch/cores/"
libretro_info_path = "~/.config/retroarch/cores/"
```
and

```
ls -ld ~/.config/retroarch/cores
drwxrwxrwx 1 feralsmurf feralsmurf 0 Jun 11 22:02 /home/feralsmurf/.config/retroarch/cores/
```

Have not changed anything else. Out of share desperation, I temporarily disabled ufw. Still no joy.

On the other hand, Retroarch via Steam works perfectly.

**Comment by i30817** [comment]
nothing about that dir is suspect (well I don't remember the names of the cfg settings but I'm trusting you).

So that leaves you're using a "official" os package that disables the downloader, and either comes with a bunch of fixed codes (android does this iirc), or uses the OS packaging system to install cores (I think debian does this). For years and years I compiled RA myself and ran it from the build dir without installing now I'm in android, but only you can verify what's happening.

I think os packages that is disable core downloads tend to hide or code out completely the online updates menu. 


I'd suggest using the RA site installers yourself if this is the case. After uninstalling the RetroArch os package ofc. They tend to place things in the same place but come with the downloadable core features turned on because they're not using app store policies, at the cost of not autoupdating RA (but you can update the cores, so it is worth it ).

Not that RA doesn't have lots of cores that are unusable anyway. Curb your expectations.
