### ISSUE TITLE
Already obtained achievements displaying on game start v1.9.13

### ISSUE THREAD

**Issue by sammy2142** [libretro/RetroArch#13204]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Bug introduced with v1.9.13 (works as intended in v1.9,12)
Already obtained achievements pop up at the start of game every time I load in. This usually occurs for achievements for getting items in game.

### Expected behavior

Achievements already marked as obtained in retroarch menu and retroachievements website shouldn't show again (unless encore active etc)

### Steps to reproduce the bug

Load game with already obtained achievements (I have attached a save file if it helps) 

### Bisect Results

v1.9.13

### Version/Commit
You can find this information under Information/System Information

v1.9.13

### Environment information

Multiple (windows/ android etc)
[Legend of Zelda, The - Oracle of Seasons (USA, Australia).zip -- SAVE File](https://github.com/libretro/RetroArch/files/7496988/Legend.of.Zelda.The.-.Oracle.of.Seasons.USA.Australia.zip)

**Comment by Jamiras** [comment]
That set does not have save protection, so it's expected that a lot of the achievements would trigger again when continuing a game if the achievements were active. However, they should not be active if you've previously earned them and do not have Encore Mode enabled. It seems you've already verified that, and I can't reproduce. 

Can you capture and attach a log file associated with a run where the problem occurs?

**Comment by Jamiras** [comment]
Perfect thanks. This is the part I was looking for:
```
[INFO] [RCHEEVOS]: Fetched user unlocks 676
[INFO] [RCHEEVOS]: Fetched hardcore user unlocks 676
[INFO] [RCHEEVOS]: You have 15 of 59 achievements unlocked.
```
So it appears to be doing what it's supposed to be doing, but it is also clearly doing what it's not supposed to be doing:
```
[INFO] [RCHEEVOS]: Awarding achievement 1818: Ring Apprentice (Obtain your second ring case from Vasu.)
[INFO] [RCHEEVOS]: Achievement 1818: User already has this achievement awarded.
```
I'll continue to investigate.

**Comment by Jamiras** [comment]
Ok, I think I've got it.

Your unlocks are all non-hardcore. The code is activating them based on the fact that you haven't earned the hardcore version yet, but when they trigger (due to them being written without save protection), they try to unlock the non-hardcore (which is correct) and the "already awarded" log is generated.

They are tallied correctly in the "You have X of Y achievements unlocked" message, and appear unlocked correctly in the Achievement list. The only problem is that they're getting activated, which should not occur if you have hardcore off and have already earned the non-hardcore achievement. I'll get a fix shortly.

Thanks for your help.
