### ISSUE TITLE
[Feature Request] Can save/load states notifications specifically be disabled while all else are enabled?

### ISSUE THREAD

**Issue by Seyferto** [libretro/RetroArch#13239]
https://forums.libretro.com/t/retroachievements-onscreen-notifications/14155/8?u=seyfert

**Comment by Jamiras** [comment]
If I understand correctly, the original request in the linked topic is asking for a way to disable all notifications except those related to achievements. This request appears to be specifically asking to disable just the notifications associated to save states.

From the linked topic:
> Unfortunately, making it so each OSD message can be turned on/off separately would make quite a mess of the codebase, so I don’t think anyone is eager to do such a thing any time soon.

Widgets have been introduced since the original post. Unlocking achievements now show a widget instead of a notification. I believe that addresses the original concern as notifications can be disabled, but the user would still see when achievements are unlocked.

There are still a few other messages related to achievements that use the default notification system - such as those related to starting a leaderboard and reporting the value submitted for a leaderboard.

**Comment by Seyferto** [comment]
Not sure what you mean by a widget, but I tried disabling all notifications and nothing came for RA, either...

**Comment by Jamiras** [comment]
This is a widget:
![image](https://user-images.githubusercontent.com/32680403/142073758-3428a470-23db-4834-b704-fef56bbc4ed3.png)

Notifications appear at the bottom of the screen:
![image](https://user-images.githubusercontent.com/32680403/142074025-84025017-cf95-4874-9fc2-5ba114e6ba6b.png)

But I was wrong. Apparently you can't enable widgets without notifications:
![image](https://user-images.githubusercontent.com/32680403/142073804-e0287e95-d732-49cf-9a4d-fca7f9529d92.png)

![image](https://user-images.githubusercontent.com/32680403/142073849-f1be91c4-ccd9-49a7-b972-0e5891042389.png)

And disabling notifications does also disable widgets.

**Comment by Jamiras** [comment]
Apparently, I'm doubly wrong. With widgets off, the notifications change to just yellow text. Even the basic notifications are actually widgets.  Widgets are just stylized notifications.

**Comment by Seyferto** [comment]
So, this is still a feature that could be implemented?

**Comment by Jamiras** [comment]
Yes. It definitely _could_, but I'm not sure that anyone is going to be jumping at doing it.

As suggested in the original forum post, it would be a fairly significant overhaul to categorize every existing notification and add switches for each category.

**Comment by Seyferto** [comment]
It is? Even notifications for 'loading input remap files' can be turned off... but not for just 'loading'...?

**Comment by Seyferto** [comment]
Still no plans?

**Comment by babooncodes** [comment]
PLEASE?
