### ISSUE TITLE
(Menu) Make shader presets more portable

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1326]
Saving shader presets creates a cgp file with absolute paths, it would be better if the paths were relative to the cgp location so those can be easily exchanged between users.

**Comment by Quest79** [comment]
This doesn't seem like a change that needs 3 years to implement, it's a good one, hope to see it prioritized soon.

**Comment by fr500** [comment]
Again with the condescending tone...
Feel free to contribute

**Comment by twinaphex** [comment]
@Quest79  Please don't take for granted the developers/contributors that use their precious free time in order to implement, test and troubleshoot new features. This does not create a very hospitable environment.

I agree that it can be annoying that certain things have been overlooked in the past, regardless, apparently people are looking into it now, and that is all that matters.

**Comment by Quest79** [comment]
@twinaphex Agreed. Also we should not take for granted basic building blocks of a healthy application progression. The above function should be one of those healthy blocks and allowing it to be neglected also leads to a chaotic project.  Being a team lead in related things (in past work not related to github) gives me some of that insight. Contribution comes more from just committing code. No condescension intended. Thanks for your time, efforts and considering what Im saying.

**Comment by hizzlekizzle** [comment]
I believe this is done now. Closing.
