### ISSUE TITLE
[Core Request] Yuzu Emulator

### ISSUE THREAD

**Issue by Kiba-san** [libretro/RetroArch#13331]
### Yuzu Emulator Core Request

[So, i thinking a new core as Nintendo Switch called Yuzu, so what do you think?]

Note: this  iis an request, if u add it its a pleasure♡♡

**Comment by Klauserus** [comment]
i dont like, to make a new issue open. well, i agree but i would like to see a Duckstation on Nintendo Switch :)
THX

**Comment by kbdharun** [comment]
Yeah, It will be a nice addition to Retroarch as it allows us to emulate **Nintendo Switch Games**. 

> ### Yuzu Emulator Core Request
> [So, i thinking a new core as Nintendo Switch called Yuzu, so what do you think?]
> 
> Note: this iis an request, if u add it its a pleasure♡♡

**Comment by Augusto7743** [comment]
RETROARCH DEVELOPERS.
NOT ADD ANY CORE IF IS EMULATING CURRENT VIDEO GAME GENERATION.
EMULATING CURRENT GENERATION CREATE PROBLEMS FOR HONEST PROJECTS ... MAINLY MAME PROJECT.

**Comment by kbdharun** [comment]
> RETROARCH DEVELOPERS.
> NOT ADD ANY CORE IF IS EMULATING CURRENT VIDEO GAME GENERATION.
> EMULATING CURRENT GENERATION CREATE PROBLEMS FOR HONEST PROJECTS ... MAINLY MAME PROJECT.

I agree with you , even though the addition of this core will be appreciated, since it includes support for current generation Nintendo Switch console it would create problems and legal complications for retroarch.

**Comment by Augusto7743** [comment]
Retroarch need in controller add option to assign same console controller button to multiple game controller thus creating combo buttons helping NES and other games need press 2 buttons at same time and also allow turbo button for any console button.

**Comment by RobLoach** [comment]
Yuzu is still pretty young, and while it quite possibly could be possible to create a libretro port, it may distract from getting Yuzu stable in the first place. I would recommend supporting Yuzu over at https://yuzu-emu.org , and joining their Patreon, in order to help get it to a solid and stable state.

If anyone wants to have a hack at the libretro port in the mean time, don't let this issue stop you.

**Comment by Augusto7743** [comment]
EMULATE CURRENT GENERATION IS WRONG !!!
CREATE PROBLEMS FOR OTHERS EMULATOR PROJECTS !
UNHAPPILY HAVE USERS WAITING PLAY CURRENT GENERATION AND WISH UNDERSTAND IF WILL CREATE PROBLEM 
NINTENDO HAVE WAKE UP ABOUT IT ... THEY MAYBE CONTACT POLITICS CREATING LAWS AGAINST ANY EMULATOR PROJECT.

**Comment by muzzol** [comment]
I was curious about yuzo core and found a guy called Augusto screaming at my face.
I love internet.

by the way Augusto, emulation it's not and it'll never be illegal. you just need to own the games you play.

**Comment by jeois** [comment]
From a legal standpoint, it doesn't matter if you're emulating the current generation.  It all depends on whether you're following the rules with regard to copyright, and it doesn't matter what generation is the target hardware.  However, from a rights holding company's POV, it probably does matter to them, since they're looking to make more money off the current market.

Like people have said, it's definitely legal, as they have already tried to shut down emulation before through lawsuits, so it's been fully confirmed by the US courts that emulation is legal.  I doubt they'll test that again since the industry has been against emulation forever, and they haven't really done much about it and all that lobbying politicians hasn't amounted to much as of yet.  I could be wrong, but there's no reason to believe things will change without some solid evidence. 

IMO, you probably should consider including yuzu as it is fairly stable.  It would be nice to have it as an RetroArch core.

**Comment by Augusto7743** [comment]
Oh heavens ...
From an gamer only waiting play emulate current system is "correct" , but from an viewpoint of an professional game developer and emulator coder of mature projects emulate current system is totally wrong even if the law allow to do it.
Not is impossible Nintendo and others companies having contact with politics and changing the laws at point creating problems for other mature projects. Only reading an reply from an mamedev saying to stop wit it is enough to understand about it.
Unhappily an high percentage of PC gamers have done terrible actions demanding emulate and dump current comercial games ... all to avoid buy an console or even an recent released game doing problems from all sides.
I not believe here several gamers will reply with good sense saying to not add cores to current systems.
That's the because Sony and Nintendo add security protection in console OS.

Retroarch devs NOT add cores of current systems ... THAT IS AN OF MORE WORST PROBLEMS BEING DONE AGAINST MATURE PROJECTS ( MAME ).
If Retroarch continue using cores from before PS3 is all right and not any problem.

Now for example ... if is released an PS5 emulator and each PC have access to PS5 discs and that emulator is being extremely downloaded you believe Sony not will try to do the correct action ?
In past was tried stop some emulators (Connectix Virtual Game Station and others) ...
Today not is the same thing.
If Sony , Nintendo and any other company join to say about that problem to politics will happen problems.

Stop trying to do it. Buy the console or wait to next generation before demanding an emulator for current generation.
