### ISSUE TITLE
[Feature request] Add option to save by BIOS by core or content folder

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#13427]
Currently, the majority of BIOS files are saved directly in the "...\system\" folder (with a few exceptions like PCSX2, PPSSPP, Dolphin, etc...)

I maintain RetroArch installations across a number of devices (iPad, Fire Tablet, OGA) with a "complete" setup on Windows. When setting up a new installation, my option for transferring BIOS from my Windows installation is either: 1) copy the whole system folder over (which results in a lot of unneeded files being transferred), or 2) go core by core to identify the files needed and transfer over the files one by one (very time consuming). Adding the ability to store the BIOS by core (e.g. ...\system\beetlepsx\) or content folder (e.g. \system\Sony - PlayStation\) would allow me to quickly transfer over the needed BIOS for the systems I will use on the new device. This would align the BIOS folders with ROMs, thumbails, saves, save states, etc....

Thank you!

**Comment by Augusto7743** [comment]
Really a good feature to add

**Comment by barbudreadmon** [comment]
As a core developer, i think all of this should be left at core's discretion.

Cores determine their own paths to bios, it's up to them to use subfolders or not, i always use subfolders for mine, but i also add fallback paths to other core's bioses if they are likely to be compatible and my core can't find my own paths, because i know people forget about bioses, won't read logs either, and will come bother me in bug reports, so i want to maximize my chances at avoiding that.

Your proposition is preventing my fallbacks from working, giving me more work at "educating" users, no thanks. Instead you should ask the maintainers of the incriminated cores that made a mess of the root of that system folder to better handle this.

**Comment by trotsky40** [comment]
All good points. And thank you for the great FBNeo core, including the clean BIOS folder structure!

**Comment by RobLoach** [comment]
I have to agree here. Could implement it on the core-level, along with possible fallbacks. All the libretro API provides is the SYSTEM directory, what the core does with it is up to the core.

If you provide a list of cores that you'd like to add the subdirectories to, then that's something that we could likely work towards on a core-by-core level.

**Comment by trotsky40** [comment]
Personally, I think it should be across all cores. I can't claim to have used all of the cores but my current setup has 60 cores and, other than the 17 listed below, they could all use the feature. Even something like SNES9X that deesn't have any required BIOS should still put the optional BIOS in folders. If I needed to have a list of cores to target the change, I would say all of the Beetles (PSX, PCE, Handy, etc...), SNEX9X, Gearcoleco, fMSX, and Genesis Plus GX.

A list of cores that already have folders setup for BIOS:
FBNeo
Flycast
Dolphin
Citra
Kronos
NeoCD
NP2Kai
PCSX2
PPSSPP
QUASI88
ScummVM
VICE
blueMSX

A list of cores that don't appear to have any required/optional BIOS:
Stella
Beetle Cygne
Lutro
LowResNX
Play!

**Comment by trotsky40** [comment]
Thank you. Tested and works great!
