### ISSUE TITLE
Beetle PSX HW (Vulkan)

### ISSUE THREAD

**Issue by AmakusaKun** [libretro/RetroArch#13432]
Internal resolution is doing nothing, if I change to OpenGL it works but on Vulkan it doesn't
I tried installing everything again and it didn't make a difference
x1
![image](https://user-images.githubusercontent.com/53101602/147757778-760bfe26-c277-4a06-bb62-6959f1586665.png)
![image](https://user-images.githubusercontent.com/53101602/147757818-8d23cf3e-1f0b-4640-a713-d3ec40d8801d.png)
x16
![image](https://user-images.githubusercontent.com/53101602/147757839-99553d0d-6a7c-4164-bae5-4fb915e49880.png)
![image](https://user-images.githubusercontent.com/53101602/147757852-ace75ccd-13d7-4b72-89ff-b6c8d85b5796.png)

**Comment by hizzlekizzle** [comment]
supersampling option, which I notice you have ON, drops it back down to native res (for compatibility with shaders, real CRT output, etc.). OpenGL renderer doesn't have a supersampling option, so the downsampling doesn't happen.

Also, do note that the increased res isn't noticeable on 2D content, such as sprites.

Last but not least: this is a core issue and should have been opened at the core repo instead of the RetroArch repo.

**Comment by AmakusaKun** [comment]
> supersampling option, which I notice you have ON, drops it back down to native res (for compatibility with shaders, real CRT output, etc.). OpenGL renderer doesn't have a supersampling option, so the downsampling doesn't happen.
> 
> Also, do note that the increased res isn't noticeable on 2D content, such as sprites.
> 
> Last but not least: this is a core issue and should have been opened at the core repo instead of the RetroArch repo.

how do I disable supersampling? if I touch it RetroArch crashes, res is noticeable in this game when I tried OpenGL it looks better but I want to run it with vulkan
btw I never used github so idk about where to go
