### ISSUE TITLE
[CAP32] broken audio after merge audio-batch-frame-cap

### ISSUE THREAD

**Issue by DSkywalk** [libretro/RetroArch#13449]
## Description

Hello guys!! after @jdgleaver removes the audio batch frame limit from RA, the old caprice implementation of the sound is broken and slow as hell ;-)
PR https://github.com/libretro/RetroArch/pull/13333 merged @twinaphex 

Issue on cap32: https://github.com/libretro/libretro-cap32/issues/99
Thanks to @ToniBC @veganvelociraptor and @Adancete23

### Expected behavior

cap32 generates a 4096 audio buffer and when is filled, it calls the audio_mix to send it...

```
void retro_audio_mix()
{
   if(retro_computer_cfg.floppy_snd)
      retro_snd_mixer();
   memcpy(audio_buffer, pbSndBuffer, audio_buffer_size);
   audio_batch_cb((int16_t*) audio_buffer, audio_buffer_size);
}
```

https://github.com/libretro/libretro-cap32/blob/master/libretro/libretro-core.c#L1279

### Actual behavior

It seems that the RA buffer is out of sync or reading noise, plus the multiple calls make the emulator slow. could it be that some initialisation of the audio buffer is missing? That whole part I've never touched, maybe it's very outdated.

Any help is welcome, I'm on holiday and don't have my computer available. I would not want the next version of RA not work with Caprice32 :disappointed: 

### Steps to reproduce the bug

compile lastest nighty RA and caprice core.

### Bisect Results

PR https://github.com/libretro/RetroArch/pull/13333

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [d13f325216628031f2937b54e854c0922f4b5a54]

### Environment information

- OS: Linux, Windows
- Compiler: gcc 9.3.0

Cheers, guys!

**Comment by DSkywalk** [comment]
I have seen that by sending sample by sample (using audio_cb) the core works again as before, but I would have to change the whole sound system of the floppy drive that used to work with the audio_batch.

If you can't think of anything better, I could stop using batch...

**Comment by jdgleaver** [comment]
@DSkywalk The core is calling `audio_batch_cb()` with the wrong number of frames. It was only working by pure chance before the audio batch frame limit was removed! The improper value is also causing a heap buffer overflow (which segfaults on Linux). This fixes the issue:

```diff
diff --git a/libretro/libretro-core.c b/libretro/libretro-core.c
index 024077a..e047f80 100644
--- a/libretro/libretro-core.c
+++ b/libretro/libretro-core.c
@@ -1281,7 +1281,7 @@ void retro_audio_mix()
    if(retro_computer_cfg.floppy_snd)
       retro_snd_mixer();
    memcpy(audio_buffer, pbSndBuffer, audio_buffer_size);
-   audio_batch_cb((int16_t*) audio_buffer, audio_buffer_size);
+   audio_batch_cb((int16_t*) audio_buffer, audio_buffer_size/AUDIO_BYTES/AUDIO_CHANNELS);
 }
 
 void retro_PollEvent()
```

Note that the audio handling in general is a little suboptimal, since the way the buffer is handled means we have irregular sample pacing. It would be better to write to a ring buffer in `retro_audio_mix()`, and then output from this the expected number of samples per frame in `retro_run()`.

**Comment by jdgleaver** [comment]
> Really thanks for your help @jdgleaver

You're welcome! :)

> But I didn't understand you correctly, internally cap32 has a ring-buffer that is filled automatically and when it is completed it calls retro_audio_mix:
> It is always the same number of samples (the one with the configured size).

I was thinking of a second ring buffer, but yes, that's probably not required. Essentially, the issue is that the audio batch callback is out of sync with `retro_run()`. Each frame should upload `AUDIO_BUFSIZE` samples, but they're currently being 'saved up' and only output when `pbSndBuffer` is full - this adversely affects the frontend synchronisation, and can harm frame pacing. What should be happening is that `pbSndBuffer` should be written to pretty much as it is now, but then `AUDIO_BUFSIZE` samples get pulled from it inside `retro_run()`.

Anyway - sure, I can look at improving this! (I've done a similar thing with several other cores recently)

**Comment by DSkywalk** [comment]
Thanks for the explanation, mate!

I've been testing using samples and quickly got everything working and I understand that in this case there would be no sync problem with `retro_run()` either. It has also allowed me to remove some code that duplicated functions that RA already does. 

My goal is to get the emulator working on a 3DS, I'm already close, let's see if when I get home I do a couple more tests, because I'd like to achieve that goal this year :smiley: 

If you see anything else I can check, I'm watching for your answer. thanks again @jdgleaver :-)

**Comment by jdgleaver** [comment]
Ah! I didn't understand that you were planning to replace the batch callback with the sample callback... Indeed, there should be no sync issues now, but performance-wise this may require some benchmarking. The sample callback is very much slower than the batch one, since you're effectively interacting with (uploading and flushing) the platform's audio driver on every sample, as opposed to processing a whole frame's worth in one go. 3DS is probably a good device to test the impact of this change :)

**Comment by DSkywalk** [comment]
OK, I was worried about something like that, I'll check the performance as you said. I've left both options (samples vs batch) that I can activate with a couple of defines in my local repository, let's see when I get home what conclusions I get :wink: 

Thanks again @jdgleaver
