### ISSUE TITLE
SwitchRes Not Working in DRM/KMS (CRT) (x86_64)

### ISSUE THREAD

**Issue by LarsenDX** [libretro/RetroArch#13485]
## Description
SwitchRes is not available on Linux x86_64 in DRM/KMS video mode. 
Currently, only X and Raspberry Pi are implemented. Why?

### Expected behavior
SwitchRes should work precisely as in X video mode.

### Actual behavior
CRTSwitchRes menu is not available in DRM/KMS. If you edit the CRT settings in retroarch.cfg and restart RetroArch, it has no effect.

Actual stand-alone SwitchRes 2.0 (https://github.com/antonioginer/switchres) works just fine in DRM/KMS. Why is DRM/KMS SwitchRes not implemented in RetroArch?

### Steps to reproduce the bug
In TTY, start Retroarch.

### Version/Commit
- RetroArch: 1.9.14

### Environment information
- OS: Ubuntu

**Comment by LarsenDX** [comment]
@alphanu1 Can you explain why SwitchRes is not implemented for use with DRM/KMS?

**Comment by alphanu1** [comment]
@LarsenDX It is not as simply to change resolution on the fly in DRM/KMS. 

Currently Substing has it working on GrooveyArcade. Both RA and GroovyMame are switching resolutions in DRM/KMS with SwitchRes 2.0. However, this is not a simple process. It requires a modified Linux kernel and SDL2 driver. Both of which you would need to apply the diff/Patches too and compile and install before it will work. Also the modifications to RA are not even close to being ready for released.

If you wanted to do some testing you can always jump on the GroovyArcade discord with us. The next release of GA will include RA with KMS switching

Even if the modifications were ready to release. I don't really think this is something that should be in upstream RA. Its not something that can work out of the box because you need to modify so much of a standard install. To which most users will not even consider doing. I may be wrong here but I think the Libretro team would agree.

@hunterk what are your thoughts?

**Comment by alphanu1** [comment]
Also, With RA it takes control as the DRM master. So, SW is not able to grab the current FB control. So the RA implementation is a bit of a hybrid

**Comment by LarsenDX** [comment]
I am running off-the-shelf Ubuntu with a plain kernel and stand-alone switchres 2.0 switches just fine. I guess that's due the ATI GPU I'm running? Whereas patching kernel makes this work with virtually any GPU?

Fair enough, I will check out groovyarcade. Thanks, alhapnu1!

**Comment by i30817** [comment]
As was mentioned, it has to do with the security model of the linux kernel. Only the 'DRM master' can switch resolution and both RA and switchres would be fighting over it. I believe this is the same reason why it's very very easy to make RA crash if run on KMS/DRM and you have a login in another TTY. RA is not the 'DRM master' in that situation so a resolution switch by it or the core, crashes.

**Comment by LarsenDX** [comment]
Substring of GroovyArcade has patched Retroarch to work in KMS with modeswitching.
https://github.com/?q=substring 
https://gitlab.com/groovyarcade/packages/-/tree/master/package/retroarch

**Comment by hizzlekizzle** [comment]
is that patch working in conjunction with the kernel patching that alphanu mentioned?

**Comment by alphanu1** [comment]
@hizzlekizzle no, this is just a modified RA source. Very dirty code ATM hooking into RAs DRM driver.

it works quite nicely. But does need to be implemented better.

**Comment by hizzlekizzle** [comment]
oh that's great, then. Sounds like a promising start!
