### ISSUE TITLE
RetroArch Hangs When Prompted for Server Password

### ISSUE THREAD

**Issue by michael-myers** [libretro/RetroArch#13606]
## Description

RetroArch UI hangs when the prompt appears for the netplay server's password. On macOS this means the pinwheel mouse pointer and a Force Quit to get out of RetroArch.

### Expected behavior

The behavior in 1.9.14 was correct, and this is a regression bug.

### Actual behavior

At the server password prompt, the guest's RetroArch interface becomes unresponsive and hangs indefinitely.

### Steps to reproduce the bug

1. a RetroArch instance acting as the Netplay host has set a password "123", in the Settings->Network->Server Password.
2. a RetroArch instance acting as a Netplay guest uses Netplay->Connect to Netplay Host and successfully connects to this host, and receives the RetroArch menu prompt for the Sever Password.

### Bisect Results

It worked until updating from 1.9.14 stable to 1.10.0 stable. Simply replacing the 1.10.0 RetroArch with the 1.9.14 binaries (both guest and host; did not test just replacing one or the other) returns it to working again. So the problem appears to be code, not configuration related.

The bug appeared before this commit: 
https://github.com/libretro/RetroArch/commit/b71be7efd2126ad94759726d8e54724482cffde2

but after/since this one:
https://github.com/libretro/RetroArch/commit/06a23670081d46466198704ea5a3a8809a05291f

Note that the socket connection does establish, which we know because we receive the server password overlay prompt within RetroArch. So although there has been a lot of work recently on NAT traversal and UPnP and the server browser, I think this is unrelated to those commits. I would guess the UI thread is now deadlocking on the [network handshake](https://github.com/libretro/RetroArch/blob/cd74221d33d7cafc23829d7262ae9eadd2d74719/network/netplay/netplay_frontend.c#L905), for some reason.

### Version/Commit

- RetroArch: 1.10.0 macOS Metal

### Environment information

- OS: macOS 12.2
- Compiler: (not compiled from source, installed from stable RetroArch 1.10.0 release)

**Comment by Cthulhu-throwaway** [comment]
The only work I did on handshake_password for 1.10.0 was clean-up.
Tested passworded rooms with both correct and wrong passwords on both Windows and Linux; no problems.

I don't have access to a MacOS to test, so either you or someone else will need to provide more technical data on this.

**Comment by michael-myers** [comment]
Yea, I skimmed all the changes in the PRs related to netplay and didn't find anything that stood out as the cause, but, this is repeatable and happens on the client's side. I will gather more information; I can try to capture a stack trace of when it hangs. Or turn on filesystem logging and check the log.

**Comment by Chaos81** [comment]
Hey, I just tested a fix for this today. Go into RetroArch, go to Settings-User Interface, and turn off both settings of "Pause Content". I believe the main culprit is "Pause Content When Menu is Active". Set this to off. This allows the password screen to pop up and allow input without crashing RA on Mac OS. The same problem also happened when trying to use chat, and that works as well.

**Comment by michael-myers** [comment]
@Chaos81 thanks for that tip. Yes that does work around the issue (still present in RetroArch 1.10.2), so I think we're closer to understanding the cause.

"Pause Content When Menu is Active" does interfere with NetPlay generally (clients lose sync and disconnect after a few seconds) but that's not a new issue, and before 1.10.0 it was fine to have it on by default.

Without knowing more, I wonder if it is related to a similar problem that also appeared on Android in 1.10.0 related to content pausing disrupting NetPlay https://github.com/libretro/RetroArch/issues/13658

**Comment by Cthulhu-throwaway** [comment]
Pausing works just fine as long as the host allows it.

Pre 1.10.0 behavior of Allow Pausing == false: If a client pauses, the host will refuse to accept it, and wait a little bit before timeout'ing the paused client (game will freeze/pause for up to 5s for everyone before the timeout occurs and gameplay is resumed).

Post 1.10.0 behavior of Allow Pausing == false (clients running 1.10.X): The host will send its allow pausing setting to the client, which in turn will disable any pausing feature on the client side until the netplay session ends.

Post 1.10.0 behavior of Allow Pausing == false (clients not running 1.10.X): Fallback behavior for older clients that can't support the 1.10.0 behavior. Same behavior as pre 1.10.0.

The issue you've here and on Android is on the menu side. There is probably a race condition there that will cause a deadlock when pausing is disabled while in the menu just as content is loaded.
There won't be a fix from me on this because it's a problem with the menu code and only on specific platforms, platforms which I don't have access to.

Solutions:

1. Enable "Allow Pausing" as the host.
2. Disable "Pause Content When Menu is Active" as the client.

For host deadlocks (Allow Pausing == false): Start netplay before loading the content; this will prevent the conditions that lead to this issue.

**Comment by Cthulhu-throwaway** [comment]
More over, initializing netplay->allow_pausing to true instead of false on netplay_new *MIGHT* prevent the deadlock at password prompts.

Testing with people on these platforms would be required to confirm.

**Comment by Cthulhu-throwaway** [comment]
Still waiting for confirmation on whether the PR above fixed this issue for good.

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin This one should be fixed aswell, but there is no one around to confirm for sure.

**Comment by michael-myers** [comment]
Belatedly, yes, I confirmed using RetroArch 1.11.0 today that this bug is completely fixed

Thank you!
