### ISSUE TITLE
RetroArch Closes on New Achievement Unlocks when Sound is Enabled

### ISSUE THREAD

**Issue by Stixil** [libretro/RetroArch#13646]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch will hard-crash with no log when an achievement is unlocked while "play sound" is enabled in achievement settings. Achievement fails to award and progress is lost.

Log example:

[INFO] [RCHEEVOS]: Awarding achievement 45856: Mini-Mario vs the World I [m] (Start a new file and in one session reach and beat Lemmy's Castle w|o Powerups, Yoshi and !-Blocks.)

This is the only related log before crash.

### Expected behavior

Achievement should be awarded without crashing.

### Actual behavior

RA crashes on award.

### Steps to reproduce the bug

1. Enable achievements and sound
2. Unlock new achievement
3. Observe crash

### Bisect Results

Last working achievement awarded 12 Feb 2022. Something since then has broken this.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Git Version e76da47, build date Feb 17 2022

### Environment information

- OS: Windows 10 Pro 64-bit
- Compiler: MinGW (10.2.0) 64-bit

**Comment by Stixil** [comment]
Update: reinstalling fixes it but using my old configuration breaks it again. Here is the configuration file that causes the issue:
https://pastebin.com/iT3bd9sk

**Comment by Jamiras** [comment]
Using your config file and my credentials, I was able to successfully unlock several achievements without crashing. The only thing unusual I see in your config file is:
```
audio_device = "Steinberg UR22mkII"
```
Which could be related to the fact that you claim it's only an issue `while "play sound" is enabled`.

If you remove that line from the file so it will reset to default, does it fix your issue?

If not, could you look for differences between that file and the working file and try to identify which one is actually causing the problem?

I don't see any code changes between Feb 12 and Feb 17 related to sound. There are a couple of achievement-related changes, but nothing that would be happening during the process associated to unlocking an achievement.

The steps following the  `[INFO] [RCHEEVOS]: Awarding achievement 45856` log message are to queue the popup, start the server request to unlock the achievement, play the sound, and take the automatic screenshot. You appear to have `cheevos_auto_screenshot` enabled. Are the screenshots being captured?

Can you take screenshots normally (outside of the achievement being unlocked)? There have been issues in the past with taking screenshots using the vulkan driver. I think you've remapped that to F2.

As the issue seems to be specific to your configuration file (and potentially your computer), any additional information you can provide would be appreciated.

**Comment by Stixil** [comment]
Removing the `audio_device` line from config and using default `audio_device = ""` does not solve the issue.

I am able to save regular screenshots using F2, however the `cheevos_auto_screenshot` does not save.

Interestingly enough, I compared the working and broken configuration and found a line that seems to contribute to the crash.
When `audio_enable_menu` and `cheevos_unlock_sound_enable` are BOTH set to `true`, the crash occurs. If either or both are set to `false`, achievements work as intended. This appears to be why a default configuration will work when I enabled achievement sound, as menu sounds are disabled by default.

I did test with using an entirely different audio device in Windows, this time using audio from my GPU for audio, and the issue persists.

**Comment by Eduxki** [comment]
I'm Having the same trouble when I have both sound achievement pop up and menu sound activated on Android. The time I get an achievement Retroarch closes. I disabled menu sound and problem solved.

**Comment by Stixil** [comment]
> I'm Having the same trouble when I have both sound achievement pop up and menu sound activated on Android. The time I get an achievement Retroarch closes. I disabled menu sound and problem solved.

Seems to not be limited to just my computer then. Very weird issue we are both having.

**Comment by Nepiki** [comment]
> Interestingly enough, I compared the working and broken configuration and found a line that seems to contribute to the crash. When `audio_enable_menu` and `cheevos_unlock_sound_enable` are BOTH set to `true`, the crash occurs. If either or both are set to `false`, achievements work as intended. This appears to be why a default configuration will work when I enabled achievement sound, as menu sounds are disabled by default.

I can confirm that this is also what breaks RetroArch for me. When both are set to 'true', my RetroArch crashes whenever I get an achievement. If either or both are set to 'false', then the achievements unlocks no problem and RetroArch doesn't crash.

**Comment by Stixil** [comment]
Update: seems to be working again on version 1.10.3 for me.

**Comment by Eduxki** [comment]
Cool finally. Good job
