### ISSUE TITLE
[windows] lockups when using softfilters

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1372]
Some filters cause crashes, others seem to do nothing.
I just compiled from git, and built the filters myself, it leads to a lock up when starting content (or immediately if content was running already)

Notable exception is the blaarg filter, it does nothing, no crash and no change in the image.
The darken filter crashes bsnes immediately, takes a few seconds to crash with MAME

**Comment by fr500** [comment]
A sidenote, for some reason selecting the menu entry to go into the softfilter selection menu seems to reinit the driver, it should reinit until you actually select a filter

**Comment by Monroe88** [comment]
Blargg NTSC filters only work on cores that output 16bpp like SNES9x, it does nothing on 32bpp cores like bsnes because it doesn't have code to handle that output. IIRC, filters locking up RA on Windows was a threading issue and it was fixed for the NTSC filter by only using a single thread for that filter.

**Comment by fr500** [comment]
it's still locking up on the latest nightlies on win64, same questions I had on the DSP thread, are you on win32?

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/commit/206797c6f90fccb7dd46a54325667e66d5fc2fdb
fixed
