### ISSUE TITLE
Fix up audio stutters on Xbox series and Xbox one

### ISSUE THREAD

**Issue by Jackmath5** [libretro/RetroArch#13758]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Audio stutters from 0-11

### Expected behavior

Audio stutters and glitches occurred in 0-11 latency

### Actual behavior

Audio stutters is kinda bug and glitch

### Steps to reproduce the bug

1. I put latency to 0
2. I boot the.game
3. Audio latency stutters

### Bisect Results

Everytime that stutters and audios are glitchy

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.1

### Environment information

- OS: xbox one and Xbox series s/x
- Compiler: n/a

**Comment by GABO1423** [comment]
This has to be one of the least descriptive and vague issues I've seen filed here. Which latency setting are you using in the first place? Audio Latency? Frame Delay?

If it's the latter, setting that value too high will cause audio crackles galore with certain games because it's too much for the system to handle (not a RetroArch issue).

If it's the former, setting it too low will also cause crackling audio for the same reason. It's too much for the system (not a RetroArch issue).

You should try using Automatic Frame Delay and keep the Audio Latency at the default of 64 ms. And in the case of the Xbox One, it's underpowered CPU will perform poorly with certain cores regardless of the settings you have.

Unless you can actually give a better description, I think this is just you using unrealistic settings for the system.

**Comment by LibretroAdmin** [comment]
I think you're just setting way too low audio latency for the Xbox here. Note that by changing this value, you are not guaranteeing like '16ms audio latency' or '8ms audio latency' - you're merely making a suggestion as to how big/small the audio buffer size can be, which then dictates over all audio latency. Going to close this.
