### ISSUE TITLE
Kega Fusion On RetroArch

### ISSUE THREAD

**Issue by SopTheSop27** [libretro/RetroArch#13793]
Is It Possible To Add Kega Fusion Core For RetroArch

**Comment by AncientCarthage** [comment]
No, no one has created a Kega Fusion Cor for RetroArch.  Genesis Plus GX is better in every way though, so there would be no reason to use it anyway.

**Comment by hizzlekizzle** [comment]
Since Kega Fusion is closed-source, Steve Snake would have to do it himself. We would certainly welcome it, but I wouldn't hold your breath for it :)

**Comment by keithbowes** [comment]
> No, no one has created a Kega Fusion Cor for RetroArch. Genesis Plus GX is better in every way though, so there would be no reason to use it anyway.

Yeah, what I did was changed the settings in Genesis cores to imitate Kega Fusion (specifically, ALSA sound and FPS display, though I couldn't change it to imitate Kega Fusion's behavior of disabling sound in the config if the ALSA device was busy).  I only wish that there were a great FOSS Genesis core.  Seemingly, Mednafen uses an older version of Genesis Plus before it changed its license (though, it's far behind libretro's Genesis Plus GX, which is why it requires SMS Plus for Master System/Game Gear support).  BlastEm has an FOSS license, but it's slower than Genesis Plus GX and PicoDrive and is x86-only.
