### ISSUE TITLE
[Feature request] [Ozone] Multiple line scroll in Ozone playlists

### ISSUE THREAD

**Issue by jvook** [libretro/RetroArch#14134]
There is no feature to multi-line scroll in Ozone menu driver, only scrolling by full letter increments.  In large file lists it can take over a minute to scroll line by line to a title.  For the worst example, in a full MAME set, it can take over a minute to scroll past the mahjong titles alone.  Ozone driver needs a multiline scroll similar to pressing left/right d-pad in RGUI menu driver.

**Comment by Ryunam** [comment]
I believe in any playlist you can press R1 to do multi-line scrolling, as in advancing to the first entry in the list that has the next starting letter in the alphabet.

**Comment by jvook** [comment]
Yes I am asking for a regular multiline scroll, like the one in RGUI, because scrolling by a whole letter can be hundreds of titles.

**Comment by sonninnos** [comment]
Yep, not sure if we really need 2 different buttons (Left+Cancel) for returning from a playlist, as in Left+Right could/should be easily used for paging instead.

**Comment by Ryunam** [comment]
I totally agree with the idea of making Left+Right behave like in RGUI and instead restrict playlist navigation to Confirm+Cancel. As long as the change is consistent all across the Ozone UI, I don’t mind it at all.

**Comment by jvook** [comment]
> Yep, not sure if we really need 2 different buttons (Left+Cancel) for returning from a playlist, as in Left+Right could/should be easily used for paging instead.

This is the most logical solution to me, but it's worth mentioning that a couple other solutions exist:

1. Use left-right d-pad to scroll multiple lines, as in RGUI
2. Use L2/R2 to scroll multiple lines (or better yet, use L2/R2 to scroll by letter and L1/R1 to multiple line scroll)
3. Implement an accelerating scroll a la EmulationStation.  Holding the up/down button will scroll by a single line, then after a few lines it will accelerate to scrolling multiple lines.

**Comment by jvook** [comment]
> I totally agree with the idea of making Left+Right behave like in RGUI and instead restrict playlist navigation to Confirm+Cancel. As long as the change is consistent all across the Ozone UI, I don’t mind it at all.

There is some unfortunate inconsistency currently.  For example, in the Quick Menu, pressing left or right on certain elements (e.g., Start recording, cheats, etc.) will multiline scroll, while pressing on others (any save state option) will change the state slot.  This creates a situation where pressing left scrolls up, then pressing right changes slot instead of scrolling back.

Next inconsistency is that using the "Load content" menu items allows scrolling with left/right d-pad, but playlists do not.  The design philosophy behind this difference seems to be that when the "Vertical menu" on the left side is hidden (as in load content, quick menu, etc.), then left/right will act as multiple line scroll.  If the vertical menu is shown, as in playlists, then the left d-pad backs out and the right d-pad does nothing.  In order to make this fully consistent, the vertical menu should be hidden while in playlists.

**Comment by Cthulhu-throwaway** [comment]
Alternatively, you can use the search feature to reduce the number of entries you need to scroll through.

**Comment by i30817** [comment]
The reason left right exist for 'cancellation' is exactly because of the search function. Imagine you want to search for final fantasy games and the tag feature is it's usual underwhelming; either because you scanned manually or the database just doesn't have them. You can work around it by searching for 'final fantasy', pressing left and search the other playlists because the search continues active until you press cancel. 

I'm not going to tell you how to do your program but i feel this feature is more valuable when you want it than 'go down list fast', at least in the pc where you do have the search.

**Comment by Ryunam** [comment]
@sonninnos However, you can make a case about the Explore menu not working the same way as the search method does, because the Explore menu does not seem to detect custom playlist entries that do not rely on a database. 

I am seeing the same thing happen with some Arcade custom entries I made for myself: the Explore search does not find those pieces of content at all, while I can easily get them by searching for the same name manually and then inputting 'left' to switch from one playlist to another.

The name of the searched content is even appended to the Playlist menu when doing a manual search, which looks rather nice actually:

![image](https://user-images.githubusercontent.com/17614150/177537944-94f52ccf-1536-492a-b1fe-c7507c069bf3.png)

Considering this, I vote for the following approach:

- change L1/R1 to a multi-line scrolling that is identical to what happens in RGUI and allows very fast (or increasingly fast) movement in the playlist;
- set L2/R2 to behave like L1/R1 do right now, as in a method of scrolling that is based on the starting letter;
- provide a visual indication of both these controls in the UI footer.

**Comment by i30817** [comment]
BTW, i believe right now, due to the work of @jdgleaver, keeping 'down' pressed will increase the speed already, so i don't think it's a particularly good idea for the L/R buttons to have acceleration. I'd rather think you'd use it when you want precision (for searching for 'next/previous letter' or completeness/precision, when paginating up or down).

**Comment by jvook** [comment]
> > Considering this, I vote for the following approach:
> > ```
> > * change L1/R1 to a multi-line scrolling that is identical to what happens in RGUI and allows very fast (or increasingly fast) movement in the playlist;
> > 
> > * set L2/R2 to behave like L1/R1 do right now, as in a method of scrolling that is based on the starting lett

I'm happy with this solution

**Comment by jvook** [comment]
Doesn't it also make sense to remove the left/right dpad scroll that is currently used in e.g., the load content and settings menus?  Especially re: the inconsistency I discussed in second paragraph here https://github.com/libretro/RetroArch/issues/14134#issuecomment-1173133035
