### ISSUE TITLE
[Feature Request] UWP - Change Default Cores Directory to LocalState

### ISSUE THREAD

**Issue by seanocali** [libretro/RetroArch#14233]
The default cores directory is in the app folder ("Program Files\WindowsApps") which is inaccessible to the user and thus inaccessible to a frontend that wants to check which cores are available. 

Would it not make more sense to put it in the Packages\[AppID]\LocalState folder where all the other default folders are?

**Comment by GABO1423** [comment]
> The default cores directory is in the app folder ("Program Files\WindowsApps") which is inaccessible to the user and thus inaccessible to a frontend that wants to check which cores are available.
> 
> Would it not make more sense to put it in the Packages[AppID]\LocalState folder where all the other default folders are?

That folder is only inaccessible in Retail mode, on the intended use case of Developer mode it is perfectly accesible. Plus, due to the fact that UWP does not allow you to load dll files unless they are on the main installation directory (being the location you mentioned), a simple change of location won't cut it.
