### ISSUE TITLE
Netplay crashes on Android

### ISSUE THREAD

**Issue by LibretroAdmin** [libretro/RetroArch#14327]
Hi @Cthulhu-throwaway , we got reports on #netplay about crashes happening with netplay on Android.

It would be good to address these issues before we release a new stable.

Discussion can be found here:
https://discord.com/channels/184109094070779904/326960443157381120/1008384840829251714

> Not sure if it's a known issue or not but I just wanted to let someone know that Netplay freezes/crashes RetroArch on Android if I try to start a netplay session while the game is already loaded.   This happened on both my android cell phone and on my fire stick.   But if I start a netplay session first then start the game, everything works as expected.  Please let me know if this issue isn't known or if you need any additional info from me.  Thanks.

I have asked him to report these issues on Github from now on, and I have pointed him to this thread.

**Comment by LibretroAdmin** [comment]
If obtaining Android hardware is an issue, we can help fund it free of charge.

**Comment by Cthulhu-throwaway** [comment]
This is nothing new, see: https://github.com/libretro/RetroArch/issues/13658

And surprise, surprise, this has nothing to do with any of my code (new or old) and is related to bad menu code on Android/OSX that doesn't work properly when disallowing content pause on menu under certain circumstances.
No one has ever given me any debug information on this (yes, I already know it's related to disallowing pause on menu) and they keep shouting to the wind on discord where no one knows a thing about netplay.

I've bumped all outstanding netplay issues yesterday asking for tests on the current nightly (since content reload might actually fix this specific issue, lol).
No responses so far, and I am pretty sure a certain individual is shit talking me on discord right now.

It's either that or the achievements deadlock being worked on by @Jamiras, probably the one I've mentioned, since he explicitly names Android.

**Comment by LibretroAdmin** [comment]
I merged  the achievements PRs. We'll see if that fixes the achievements issues at least, which would leave the other ones.

**Comment by Cthulhu-throwaway** [comment]
Also, there are very simple workarounds for this problem on affected platforms, see: https://github.com/libretro/RetroArch/issues/13869#issuecomment-1106432399

The problem happens on their menu code and again, out of my "jurisdiction". I would still fix it if they stopped posting "netplay crash, plz halp" on discord and actually get me some useful information in here.

P.S. This has been around since 1.9.14, when allow pausing as a setting was introduced for netplay.

**Comment by Clutz450** [comment]
Hello @Cthulhu-throwaway and @LibretroAdmin and thank you for creating this issue report for me.  My apologies for posting this issue in discord first and not over here.  I was trying to see if this issue was already known to avoid creating any duplicate issue reports.  But going forward I will be sure to post any additional issues I find here first.

Anyway, I can try testing out the nightlies on my cell phone later tonight when I'm at work (is things are slow).  But I won't have time to test on my FireStick again until Friday evening.  Please let me know any specific steps (if any) you'd like me to take or any information you want me to obtain in order to help you out with this.  

On a side note, you mentioned you are having problems getting people to help you test netplay.  I have RetroArch on a number of hacked consoles, PC, FireStick, and cell phone.  So if there is anything specific you need help testing please let me know and I'd be happy to help.  Thank you again for your time. 

-Clutz450

**Comment by Cthulhu-throwaway** [comment]
@Clutz450 No problem, it's just that a certain person has been stirring up trouble with either incorrect or out of context info about some of my changes on discord.

It's important to bring any netplay related issues here because:
1. No one on discord seems to know much about the current system.
2. I am the only contributor working on netplay currently and this should be the preferred place for development-oriented discussions. If it's support related, I check the libretro forums daily and that can be posted there.
3. Too much fighting and ignorance towards RetroArch's netplay system on discord. I prefer to keep myself out of all that and can provide development-oriented discussions here.

Simply telling me the "Git Version" from your Android setup should be enough for me to tell whether the issue is the one already reported or not (Main Menu -> Information -> System Information).

**Comment by Clutz450** [comment]
I'm sorry you are experiencing negativity towards your hard work.  For what is worth, I really appreciate all that you do and your Netplay code is helping to keep my family together while being far apart by playing or favorite games together. 

Anyway, I only had time to test on my Andoid Samsung phone starting up a game and then starting up Netplay to see if it froze/crashed.  I was not able to try and connect to anyone and play or test on my FireStick. 

Git Version 102abb0 with a build date of May 2, 2022 is the one I was using when I experienced the issue. Tried it several more times and crashed every time.  The only work around was to start Netplay Host first then start the game. 

Next I downloaded the latest Android nightlie Retroarch.apk from the buildbot with Git Version 2acc7c4 and a build date of Aug 18, 2022.  This Version only crashed on me one time while trying to start Netplay while a game was already running.  I was switching back and forth rather quickly between cores, games and starting and stopping Netplay so I'm wondering if that has something to do with it.  But other then that one time (which I couldn't replicate in my short amount of testing) I got no freezing or crashing when starting Netplay with a game already running. 

I hope this helps you out.  I will have more time this weekend to test on my FireStick and to actually test connecting to another playing and play online if that helps.  If you ever need anyone to help you test anything Netplay related, please don't hesitate to contact me via DM on Discord (Clutz450#5167) and I'd be more than happy to help out.  Thanks again for all that you do. 

-Clutz450

**Comment by Cthulhu-throwaway** [comment]
> Git Version [102abb0](https://github.com/libretro/RetroArch/commit/102abb02238ff7118340fe20009b800b5a8ace36) with a build date of May 2, 2022 is the one I was using when I experienced the issue. Tried it several more times and crashed every time. The only work around was to start Netplay Host first then start the game.

As expected, this predates both the first content reload commit: https://github.com/libretro/RetroArch/commit/ab208fca915e07df7197d024b6e291306ea52a9c (merged Jun 30)
And the auto core updater for netplay: https://github.com/libretro/RetroArch/commit/ef022ffe9017bef06d5f82d479e472362a7b8ba7 (merged Jul 8)

This is a prime example of why you should come here about netplay issues, rather than rely in hearsays on discord.

> Next I downloaded the latest Android nightlie Retroarch.apk from the buildbot with Git Version [2acc7c4](https://github.com/libretro/RetroArch/commit/2acc7c4b3988cdc09063d7052f611ff35796ab7b) and a build date of Aug 18, 2022. This Version only crashed on me one time while trying to start Netplay while a game was already running. I was switching back and forth rather quickly between cores, games and starting and stopping Netplay so I'm wondering if that has something to do with it. But other then that one time (which I couldn't replicate in my short amount of testing) I got no freezing or crashing when starting Netplay with a game already running.

Yes, I as said in the original issue, content reload might actually fix this long standing issue with android. The crash you are experiencing may or may not be related to netplay; hard to say since you can't reproduce it other than that one time and you didn't provide/have a stacktrace of the crash.

This also could be a false positive; if the buildbot and/or your connection are/is slow, updating the core when starting netplay can take a few seconds, where RetroArch's graphics interface won't be running, this can give the impression that RetroArch has crashed/deadlocked while downloading the core. The fact that it only happened once points to this possibility, since the same core won't update again on subsequent starts (always wait up to a minute or so, if it's the first you've started netplay with this core for this day).

> I hope this helps you out. I will have more time this weekend to test on my FireStick and to actually test connecting to another playing and play online if that helps. If you ever need anyone to help you test anything Netplay related, please don't hesitate to contact me via DM on Discord (Clutz450#5167) and I'd be more than happy to help out. Thanks again for all that you do.

Yes, it does, by confirming that blaming either content reload or the auto updater for your crash was incorrect.

Please, let's continue this discussion at the original issue, which can be found here: https://github.com/libretro/RetroArch/issues/13658

@LibretroAdmin confirmed as duplicate; can be closed as further discussion can take place at the original issue, which already pinpoints it to dynamically disallowing pause on menu, and which might have been fixed by ensuring content is reloaded before starting netplay.

**Comment by LibretroAdmin** [comment]
Alright.
