### ISSUE TITLE
[PSP] current status

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1452]
The PSP core has a few inconsistencies I don't really understand
Settings such as "input_max_users" don't save, also it defaults to per-core configs, and it deliberately creates directories under the core directory, these might be intended but I don't really understand why.

Also the screenshot feature is broken, not really important I know but it's there so it should work.
Also there is a builtin framerate counter that can't be disabled.

**Comment by aliaspider** [comment]
the video driver still lacks the screenshot function, but I will try to implement it in the next days.
I will also disable the forced fps counter, since it was just intended for the first beta release.

per core config is the default for all console ports, not just the psp, it could have something to do with 
the fact that a different retroarch binary is executed there each time a core is loaded, not sure.

directories are created by default since the user has limited access to the file system, but maybe those directories in /cores should be moved in the root directory instead. 
was this inconvenient because you wanted to provide a default retroarch.cfg with different paths and it still created the default ones ?

**Comment by fr500** [comment]
Yeah I wanted to add a default cfg but even a basic one (collapse subgroups and some other option) caused a program failed to start.. dunno why, so I decided not to ship a config anymore, configuring everything afterwards works...

Weird issue eh? could it be a cfg file encoding issue? because it was a 3 liner config...

And yeah it still creates the paths even if I have configured different ones... it uses the configured paths though, so no big deal

**Comment by fr500** [comment]
By the way, fceumm is working now. It doesn't really like archives, not matter if I use the browse or load option, sometimes it causes my psp to reboot, but if I load the same game (uncompressed) it works.

I'm thinking a memory issue. Maybe the extraction code could be tweaked for memory limited platforms.

**Comment by aliaspider** [comment]
I never tried a 3 liner config, I just start the thing once, and then edit the generated default config. It could be that the config handling here is different from desktop RA, and that it doesn't generate default values if a retroarch.cfg file is present.

**Comment by fr500** [comment]
yeah, I'll leave the bundle "configless" for the time being
