### ISSUE TITLE
No option for overwriting existing core remaps, a big problem!

### ISSUE THREAD

**Issue by RobG66** [libretro/RetroArch#14708]
## Description

 Once a core remap is loaded, you can't make changes to controls and then save the updated override.  You have to delete the core remap first! The big problem with this is that it also removes/resets all your control override settings!  Who knows what other override settings are lost doing this.

 Allow overwriting of core remap without having to delete it first 

### Version/Commit 

Retroarch 1.13
Windows 10

**Comment by bslenul** [comment]
Since #13755 by default remap files work like overrides pretty much: if you have an existing one, any changes made to it will be saved on close content automatically.

Then #13894 added a setting to disable that new auto-save, as the PR explains if it's disabled then you'll see a new "Update Input Remap File" option in "Manage Remap Files".

So, manually or not, it's absolutely possible to overwrite remap files. Unless I misunderstood the issue, I'm not sure since you're talking about overrides as well, and remap files don't have anything to do with those.

**Comment by bslenul** [comment]
Like I said, if it's disabled a new "Update Input Remap File" will appear (in `Quick Menu > Controls > Manage Remap Files`), clicking it will update/overwrite the currently loaded remap file.

**Comment by sonninnos** [comment]
Indeed not actually a problem.

**Comment by seanstardev** [comment]
What is the harm in having update override available alongside auto update on exit?
