### ISSUE TITLE
Retroachievement causes save/load state delays

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#14717]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When RetroAchievements are enabled, load/save states causes 2 problems 1. it takes awhile for the save/load widget to appear 2. make loading/saving states very slow.

### Expected behavior

should be instantaneous 

### Actual behavior

see description

### Steps to reproduce the bug

1. enable retroachievement. load a game with achievements.
2. load a state or save a state
3. tested with mgba, vbam, pcsx_rearmed

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [git db9d3d3507ef7fbd214c9dd4c63a2d0ef2e16991]

### Environment information

- OS: archlinux and voidlinux
- Compiler:  arch: gcc 12.2.0, void: gcc 10.(something)

**Comment by Jamiras** [comment]
To clarify: There was a bug where the achievement badges were being redownloaded every time a game was launched. These downloads occur on the same task thread as the save/load processes, so while the task thread is blocked waiting on an HTTP response, the save/load cannot proceed.

This could still be an issue the first time a game is launched, as the badges do still have to be downloaded then. But the expectation is that the user won't save for at least a few minutes after starting a game, by which time the badges should all be downloaded. The problem was more prevalent when continuing from a load state in the next session.

To address the "first time" problem, either an additional task thread would be required so there wouldn't be any contention, or something needs to be done to the HTTP code so it doesn't use as much of the thread's time.

**Comment by negativeExponent** [comment]
thanks for the fast reponse.

this issue is now fixed.
