### ISSUE TITLE
[iOS - Non Jailbreak] - Failure to create directories causes app to crash

### ISSUE THREAD

**Issue by andrewgribben** [libretro/RetroArch#1486]
At app launch the following directories cannot be created:

/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/info
/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/shaders_glsl

This causes RetroArch to crash when trying to use the mupen64-plus core. 

NB When building the xocdeproject on a jailbroken device the app works as expected, I'm assuming the JB allows those directories to be created outside of the app sandbox.

Here is the console output

```
mkdir(/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/info) error: Operation not permitted.
Failed to create directory: "/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/info".
mkdir(/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/shaders_glsl) error: Operation not permitted.
Failed to create directory: "/private/var/mobile/Containers/Bundle/Application/5C4C8ABB-2467-478B-ABA0-295367748368/RetroArch.app/shaders_glsl".

```

This is on iPhone 6 Plus running iOS 8.1.3

**Comment by andrewgribben** [comment]
I've also checked on a non-jailbroken iPad Mini 2 running 8.1.1, just to be sure it wasn't an issue with the core on the 6+

**Comment by twinaphex** [comment]
Hi,

https://github.com/libretro/RetroArch/commit/29d546e49de22ae67f5eef99e6d37b6319b9e1f2

As of these commits I've started changing things.

Now, it should create all the user directories into the application's 'Documents' directory. You can access these from iTunes File Sharing and add stuff in it.

I'd recommend using iFunBox as it lets you drag and drop entire directories and its contents over instead of iTunes (which only lets you add separate files).

Here is basically what a nonjailbroken user should manually carry over (run fetch-submodules.sh inside the RetroArch directory first which should fetch all the subrepos needed):

* shaders_glsl - these are the glsl shaders that you can find in RetroArch's media/shaders_glsl directory (if you have run the Python script first that converts the Cg shader to GLSL; if it's unclear, just ignore - you don't really need shaders for normal operation)
* overlays -     Copy over the contents of the directory (RetroArch's media/overlays directory).
* assets    -    Copy over the contents of the directory (RetroArch's media/assets directory).
* rdb          -    Copy over the contents of the directory (RetroArch's media/assets/libretrodb/rdb)
* autoconfig - Copy over the entire directory (RetroArch's media/autoconfig/apple).

**Comment by andrewgribben** [comment]
Thanks, that seems to stop the warning but it's still crashing with N64 roms as soon as they open. What's the best way to debug that for you?

**Comment by twinaphex** [comment]
The N64 core is not related to RetroArch in any way, and I highly doubt the current Mupen64 source will still work on iOS. Just take the old Mupen64 core from 1.0.0.2 for now and just use that, you can't use the current code on iOS - numerous fixes to the dynarec would have to be re-backported.

**Comment by brujo5** [comment]
@andrewgribben 

if iu compiled latest RA 1.1 . mupen64 will crash because run in dynarec mode for default.

and you can not configure anything inside core options because these functions are not implemented yet. I also hope to do that

**Comment by andrewgribben** [comment]
Thanks for letting me know.
