### ISSUE TITLE
[PPSSPP] Enabling "Auto-Apply Cheats During Game Load" clears .ini file used by "Internal Cheats Support" when loading game.

### ISSUE THREAD

**Issue by ZachIsAGardner** [libretro/RetroArch#14861]
## Description

Enabling "Auto-Apply Cheats During Game Load" in Quick Menu/Cheats clears the .ini file used by PPSSPP's "Internal Cheats Support" option when loading game.

### Expected behavior

Don't clear the contents of the .ini file.

### Actual behavior

The .ini file is being reset to what is initially created when the "Internal Cheats Support" option is enabled in the PPSSPP core settings.

### Steps to reproduce the bug

1. Enable "Internal Cheats Support" in Quick Menu/Core Options/System
2. Enable "Auto-Apply Cheats During Game Load" in Quick Menu/Cheats
3. Put something in the .ini file generated. (Found in saves/PSP/Cheats).
4. Run a PSP game.
5. Notice that the .ini file you just edited has been reset.

### Environment information

- OS: Windows 11

### Remarks

I realize this may be a clash between RetroArch's cheat system and the PPSSPP core cheat system. In struggling to figure out how to get cheats working I encountered this.

**Comment by bslenul** [comment]
> I realize this may be a clash between RetroArch's cheat system and the PPSSPP core cheat system.

It is, kinda, the "Cheats" menu can be used to handle PPSSPP cheats since https://github.com/hrydgard/ppsspp/pull/16514, but if the list from that menu is empty, your .ini will be empty as well. So either use .ini manually added or use the "Cheats" menu to enter your cheats, but do not mix both.

If you add the .ini yourself all the cheats with `_C1` inside the .ini will be applied automatically anyway.

If you want to use the "Cheats" menu however, you'll have to enter the cheats there, as an example if you want to use the "Infinite Ammo" cheat in MGS Peace Walker, which is

> _C1 Infinite Ammo
_L 0x20101EDC 0xFFFFFFFF

you'll have to enter it manually, like this:

![image](https://user-images.githubusercontent.com/33353403/213032307-7e07b172-cca4-4293-b9c9-0ee8b0c0ce79.png)

so it appears in the list:

![image](https://user-images.githubusercontent.com/33353403/213032767-cd6e998d-ed3a-4498-8ff7-d1455500cf40.png)

and it will generate the .ini file in `retroarch/saves/PSP/Cheats/`.

**Comment by ZachIsAGardner** [comment]
thank you for your response! yeah i get it. it seems like this is just user error

**Comment by iamleont** [comment]
> ## Description
> Enabling "Auto-Apply Cheats During Game Load" in Quick Menu/Cheats clears the .ini file used by PPSSPP's "Internal Cheats Support" option when loading game.
> 
> ### Expected behavior
> Don't clear the contents of the .ini file.
> 
> ### Actual behavior
> The .ini file is being reset to what is initially created when the "Internal Cheats Support" option is enabled in the PPSSPP core settings.
> 
> ### Steps to reproduce the bug
> 1. Enable "Internal Cheats Support" in Quick Menu/Core Options/System
> 2. Enable "Auto-Apply Cheats During Game Load" in Quick Menu/Cheats
> 3. Put something in the .ini file generated. (Found in saves/PSP/Cheats).
> 4. Run a PSP game.
> 5. Notice that the .ini file you just edited has been reset.
> 
> ### Environment information
> * OS: Windows 11
> 
> ### Remarks
> I realize this may be a clash between RetroArch's cheat system and the PPSSPP core cheat system. In struggling to figure out how to get cheats working I encountered this.

Hi, I also got same issue and thanks for the guidance. Now I turn off cheat by befault then my PSP cheat won't be cleaned up automatically. Thanks a lot!
