### ISSUE TITLE
Playlist manually renamed not will show any thumbnails

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#15120]
Hello.
Simply use "Import Content" > Manual Scan > use System Name "custom" > use any custom name and finally Start Scan.
The playlist is created correctly and thumbnails are showed in right panel.
Close Retroarch and go to playlist folder.
Rename the playlist "custom" for any other name.
Start Retroarch.
The renamed playlist show and start correctly all games, but the thumbnails not will be showed in right panel.

Doing an playlist manual rename break Retroarch GUI showing any thumbnails.

PLEASE ADD JPG SUPPORT FOR THUMBNAILS VIEW ... RETROARCH BUILT-IN IMAGE VIEWER SUPPORT JPG ... JPG CODE IS INTERNALLY IN RETROARCH

Thanks for reading.

**Comment by i30817** [comment]
This is wrong. Renaming the playlist will not sabotage showing thumbnails, even a custom one, if it's created correctly. Just renaming games _in_ the playlist will 'ruin' the thumbnails.

You can use my python program to download images for custom names playlists: https://github.com/i30817/libretrofuzz

It uses a fuzzy string matching method that tries to match the current label in the playlist to a label on the server.

**Comment by Augusto7743** [comment]
"This is wrong. Renaming the playlist will not sabotage showing thumbnails, even a custom one, if it's created correctly."

\ Settings \ Playlist \
settings in sequence from above to below
OFF , 200 , ON , All Playlist , ON , OFF , ON , Always , Default , ON , ON , Per Core , YYYY-MM-DD HH:MM:SS , ON , OFF , ON  OFF , OFF , OFF , OFF

Save Playlist using old format is disable
Compress Playlist enabled
Fuzzy Archive Matching enabled
Scan without core match disabled

Import Content
System Name custom .. use an name example "12"
Default Core unspecified

In example here was done an test creating an playlist "12" and after configuring with the Fairchild Channel F core.
Thumbnails path correctly configured with boxarts "12".
The thumbnails are showed.

Now rename playlist "12" to any other name. Example 1222
Rename thumbnails path boxarts for "1222".
The thumbnails not are showed.

You need test the actions above.

About
"You can use my python program to download images for custom names playlists: https://github.com/i30817/libretrofuzz

It uses a fuzzy string matching method that tries to match the current label in the playlist to a label on the server which gives some more hits, and downloads those hits with the names in the playlist, at the cost of possible false positives."

Thanks very much for doing it.
I known your site with that tool. I not had tested yet.

**Comment by i30817** [comment]
> Rename thumbnails path boxarts for "1222".

Here is your mistake. As i said in the previous comment, the boxart path is made from the 'db_name' (except the extension) inside each entry in the playlist and the 'label'. Since you renamed the directory that corresponds to the 'db_name' without changing the entries inside the playlist, it can't find them.

**Comment by Augusto7743** [comment]
Really changing the path using the name used in renamed playlist break the thumbnails show.
For me reading in Retroarch Docs is searched in path using the same name used in playlist. Now see not is exactly it. Strange.

Perhaps not will be more simple if the software search thumbnails only using the current path name ?

"And btw, converting to jpg won't work either. Retroarch is looking for pgs both on the server and the local cache after it downloaded."
Retroarch thumbnail downloader really is an great feature , but need allow jpg too.
Not is complex add that feature in code.
Have another features used for years in others emulators not present in Retroarch. Is as in eacn new release the priority is almost totally in sync input.

**Comment by i30817** [comment]
It's done this way so that retroarch config file can be portable. If it recorded the path of the thumbnail itself, it would break as soon as you tried to move the retroarch config directory/playlists to another computer. It's done correctly, for sure.

The reason 'why not jpg' is because the server only has png. It's a _lot_ of work to keep the thumbnail database working with the names updates from the various dump projects and having duplicate files, thus double the number of actual files in the repos is too much.

Just _locally_  for a user, is a possible request for enhancement, but people that require less space usually don't actually use thumbnails because it wastes a lot of space for big collections (about 10gb and i don't even have all systems or complete romsets).

And it also slows down the display of the thumbnails if it checked first png and then if it didn't exist jpg. People would complain. They _DID_ complain about 'slower' thumbnails a while ago for milliseconds of difference.

**Comment by i30817** [comment]
If on the other hand the request is about using a thumbnail database from another project that uses jpg; one thing you could is use something like image magic to mass convert all the jpgs to pngs. Although retroarch requires some size restraints to work optimally with thumbnails (512 pixel width, and preferably 512 height, but only if it doesn't break the aspect ratio).

**Comment by Augusto7743** [comment]
"It's done this way so that retroarch playlist file can be portable"
make sense.

"The reason 'why not jpg' is because the server only has png"
Yeah .. only png in server.
However will be correct and good allow user to use jpg too.

"And it also slows down the display of the thumbnails if it checked first png and then if it didn't exist jpg. People would complain. They DID complain about 'slower' thumbnails a while ago for milliseconds of difference."
Browsing files using Retroarch fil browsing is showed jpg with not any slowdown in an CPU 1 GHz.

"If it was done as a 'setting' (use png for downloads, convert to jpg, then only check png locally) people would complain again that retroarch was 'slow' when the code to convert the png download to jpg happened and would also complain that 'there are too many settings, why is there a setting to use jpg, it's not even lossless, use png"

Not need add jpg images in server or any other settings.
Only allow showing png and jpg at same time as file browsing code does.
