### ISSUE TITLE
 [Feature Request] Bring back Video Layouts (.lay)

### ISSUE THREAD

**Issue by Starman99x** [libretro/RetroArch#15146]
There's also a newer .lay structure introduced later in MAME, and it would really be helpful if both structures become supported in RetroArch since there are all sorts of lay files that use one of the two structures only.

**Comment by hizzlekizzle** [comment]
Yeah, that's part of why we dropped it. That, and the guy who implemented it in the first place did so as part of a bounty (and we greatly appreciate all of the work he did), and nobody else was interested in maintaining it or extending it to the other video drivers (and "gl" driver is likely to move into more of a legacy priority on most devices in the future).

**Comment by LibretroAdmin** [comment]
The format being a moving target for another project is one big issue, and the other big issue is that like @hizzlekizzle said, the original implementation was not done in a way so that every video driver would benefit from it.

Any other next stab at this would have to satisfy the latter requirement since that is ultimately what sealed video layout's fate and led to its removal. In hindsight we should not have awarded that bounty based on half complete work.
