### ISSUE TITLE
(android) version not updated

### ISSUE THREAD

**Issue by bobrosspainting** [libretro/RetroArch#15205]
Hi

The android version is still at version 1.9.12 on the play store.
Why is it not updated aymore?

**Comment by retroarchgirl** [comment]
I remember in the past it got updates in the play store but now it doesn't 😭😭😭

**Comment by retroarchgirl** [comment]
also retro arch plus is not updated anymore in the play store.

Can somebody tell me why?
I LLOOOOOOVVVEEE retro arch so I really would like the updates again for android!

**Comment by hizzlekizzle** [comment]
Unfortunately, Google will not allow us to update those packages unless/until we implement their "scoped storage" requirements, but they haven't provided a way to hook into that API using the development tools we use. Unless/until that changes, we recommend sideloading the apk from our website.

We also hope to get the F-Droid repository up-to-date for automatic updating.

**Comment by retroarchgirl** [comment]
Hi

I installed latest 64 bit version for android. Eveything is working but compared to version 1.9.12 from play store, I have following problems I can't solve:

- MAME current core is 0.251 while in 1.9.12 it was 0.253. Why is 0.253 available?

- for some reason I can't make savestates anymorein current mame core while this worked in1.9.12. Is the older mame core maybe the reason for this?

Thx

**Comment by hizzlekizzle** [comment]
Hmm, I'm not sure why it would be showing a newer version. Checking the git history, it was last synced back in January.

For the savestates, you can go to settings > core and set 'bypass core info save states features' to ON/true and it should bring the savestates entries back even for cores that don't fully support them (e.g., MAME).

**Comment by retroarchgirl** [comment]
Great! The savestates work!

Can you maybe try to find out why we can't have the 0.253 MAME in latest android version?
I updated everything inside retroarch (core info files, databases, ... So everything) and als did update of all cores but for MAME it says the core 0.251 is latest version. Maybe it only works in 32 bit retroarch for android and there is 64 bit core MAME ready yet? (I'm not a developer). I want to test any ideas you have since MAME is my most used core. :(

However in the google play store's retroarch it installs MAME 0.253 immediately :s

**Comment by hizzlekizzle** [comment]
I think you must be mistaken about the version because there is no 0.253 core available in RetroArch/libretro. We haven't updated the codebase since January.
