### ISSUE TITLE
[Feature Request] iOS: access iCloud Drive without jailbreaking

### ISSUE THREAD

**Issue by DarkPaladin125** [libretro/RetroArch#15211]
RetroArch on iOS runs sandboxed, on an isolated environment, and can only access its own designated directory, located on **On my iPhone** from the Files app.

I would like to request for RetroArch to be able to access other directories; if necessary, to include the prompt for the user to allow RetroArch to read/write directories outside its own.

I have asked Discord about saving to **iCloudDrive**, but it's really not possible to set your saves directory to a directory on iCloud; current solutions are only through syncing, but they are nowhere effective near to be possible to set a directory for RetroArch on iCloud.

Thanks a lot.

**Comment by warmenhoven** [comment]
No.

I really wanted to make this work. On tvOS, you're limited to 500kb of persistent storage; everything else goes into the cache directory and can be deleted by the OS whenever it decides it needs to reclaim space. After having to reimport my library yet again recently, I went looking for a solution.

iCloud as it stands cannot be that solution.

The iCloud Drive isn't a true filesystem and isn't accessible using those APIs. On macOS and in the Files app it looks like a filesystem but actually what you're seeing is a clever UI hiding those details. On macOS you can actually point to a subdirectory hidden in your home directory that looks like it is the iCloud Drive, but actually it's a cached copy, and there are various OS daemons using CloudKit keeping that directory in sync with iCloud Drive. That cached directory and those daemons do not exist on iOS.

So fine, instead of pointing RetroArch at a non-existent directory, maybe instead it could just use CloudKit directly to keep those files in sync. Now we run into the problem of RetroArch not being an officially distributed app. The CloudKit API wants to limit the apps to a CloudKit container that is identified by the tuple (Developer, App Group, User). (App Group is a way for a developer to have multiple apps sharing data; the default app group for an app only has that single app in it.) That container needs to be pre-configured by the developer through the iCloud Developer website before the app can use it. Because RetroArch is not officially distributed, it needs to be side loaded, which effectively replaces the developer ID with your own Apple ID. In that world, each user would need to have a paid Apple Developer account and set up their iCloud container before they could use iCloud for syncing.

This must go against the Apple TOS somehow. I don't know it for a fact, I just know that it's true. And it would be really easy for them to prevent this whole thing.

Backing up a step, let's go back to the idea of RetroArch doing its own syncing, but using some other cloud drive service. On desktops, that sounds like a really bad idea: there are already external apps that do exactly that, so why devote a bunch of time trying to make a subpar version of something that already exists? But for iOS and a handful of other OSes that RetroArch runs on that don't have apps like that available to them, it might be reasonable.

**Comment by DarkPaladin125** [comment]
I see. Thanks for the through explanation.

**Comment by brianus** [comment]
But surely now that RetroArch is on the App Store, the above reasoning app no longer applies and iCloud sync can be implemented, yes?

**Comment by warmenhoven** [comment]
@brianus Not like the original request is asking for.

The original request effectively was to be able to change the directories in Settings -> Directory to be iCloud directories. Yes, now that RetroArch is on the App Store it does open the possibility for using iCloudKit. However, RetroArch's VFS is not well suited for a networked file system, as there are too many places where it assumes that certain operations can be performed synchronously. Building a new VFS implementation on top of NSFileManager is onerous enough, but trying to make it performant and not randomly freeze the UI while waiting on certain blocking networking calls is beyond the scope of what I'm willing to work on.

However, I have added to my todo list, to be able to use iCloudKit/iCloud Drive as a cloud sync backend. The cloud sync implementation already naturally assumes network calls and happens on a separate thread; there are still some main thread blocking concerns but not as pervasive as a generic VFS implementation would be. This would be almost the same as the original request.
