### ISSUE TITLE
[BUG] RA ignores per core's config save path

### ISSUE THREAD

**Issue by RagnaStrife** [libretro/RetroArch#1541]
I found a problem with the save folder in RetroArch from the 2015-03-02 build, and which probably persists even now or was before:

I recently manually set each core configuration with a separate saves folder, like "RetroArch->Saves->Super Famicom" or "RetroArch->Saves->PlayStation", and so on.

As I said, the problem is RetroArch ignores the saves path set on the different cores config files, which is a problem
if people want to have everything well organised and not a mess of different systems save files in the same folder.

Probably, the fix would involve reading the core's config file and set the current RetroArch saves path to that once the core has loaded, as it seems now it only makes use of the saves path written in the RetroArch config file, not the core's one.

**Comment by fr500** [comment]
Which cores did you test?

**Comment by RagnaStrife** [comment]
It happens with every core I tried, which, if I remember correctly are:
bsnes balanced, desmume, fba, fceumm, gambatte, genesis plus gx, mednafen psx, mupen 64, nestopia, picodrive, ppsspp (well maybe not, I think this one uses another path...), vbam, yabause...

**Comment by fr500** [comment]
PPSSPP definitely does not use the save dir.

**Comment by RagnaStrife** [comment]
I hope it is an easy fix, because it really is annoying and I have to rely on tricky methods to somehow make it work in a limited manner.

**Comment by SAKUJ0** [comment]
RagnaStrife, first make sure you are not using a Front-End that overrides things. If you launch RetroArch with the -s -S options on ROMs that save games via sram, it will override any config to my knowledge and use the CLI options.

Second, if you are interested you can try a newly added config system. You can disable core specific configuration and instead maintain your configs like following. Let <configdir> be the path in which your retroarch.cfg resides.

<configdir>/mupen64plus_libretro/mupen64plus_libretro.cfg
<configdir>/mupen64plus_libretro/Super Mario 64 (USA).cfg

You can set up default settings that apply to most your emulators inside <configdir>/retroarch.cfg. Now, instead of maintaining full copies of your retroarch.cfg, you can store only the deviations from your retroarch.cfg inside the two cfgs above. It can be as simple as swapping your a and b keys (it is recommended to use core input remapping to achieve that) in 2 lines of config.

Let me know if you happen to see this as this is brand new.

**Comment by RagnaStrife** [comment]
I always use plain RetroArch with the GLUI driver.
I don't think I get how to set up that new config thing, though...
Anyway I would prefer whatever bug lies here or missing code to be fixed instead of changing my configs.

**Comment by SAKUJ0** [comment]
We will need some more information as for instance with mupen64+ i cannot
replicate your issue. saves go in a Nintendo 64 path for me. if i use the
CLI setting, it won't work from RGUI - that requires a proper setting
inside retroarch.cfg. i would suggest you do 2 things:

set save and srm path via CLI manually and see if the problem persists.

add your full retroarch configuration and log output with verbosity enabled
so i can try and replicate your issue on my installations.

**Comment by fr500** [comment]
RA most definitely reloads the config file when reloading but  yeah somethings aren't affected by that.
I sent a PR that fixed that in the new overrides system so that will probably fix this issue as well.

I don't user per-core configs so I don't really know if this happens.

**Comment by fr500** [comment]
I tried many different approaches to make this work to no avail. core initialization is delicate and no matter what I did I was never able to override the save dir and the save state dir.

**Comment by robcross** [comment]
I've been trying to get the new overrides system working in order to find a way to implement #1673 with configurations.

After looking through the code a bit I think I've managed to override the save path per core. From my limited understanding of the code, I think once a save path gets set, it will never be able to be set again due to global->has_set_save_path being True.

In the 'config_load_override' function, under the 'if(should_append)' block of configuration.c, I've changed the following code:

```
char buf[PATH_MAX_LENGTH];
      //Store the libretro_path we're using since it will be overwritten by the override when reloading                                                                                                                         
      strlcpy(buf,settings->libretro,sizeof(buf));
      //Allow a "reset" of the save path for overrides                                                                                                                                                                          
      global->has_set_save_path = false;
      if (config_load_file(global->config_path, false))
      {
         //Restore the libretro_path we're using since it will be overwritten by the override when reloading                                                                                                                    
         strlcpy(settings->libretro,buf,sizeof(settings->libretro));
         global->has_set_save_path = true;
         rarch_main_msg_queue_push("Configuration override loaded", 1, 100, true);
         return true;
      }
      //Dunno, make sure everything is set back to what it should be                                                                                                                                                            
      global->has_set_save_path = true;
```

I have no idea if there are any repercussions to my change, and the same should work for the save state path by changing global->has_set_state_path = false before reloading the appended configuration.

**Comment by fr500** [comment]
Can you post a diff instead of this? it's hard to understand what you've done like this.

**Comment by fr500** [comment]
ok I think I get it, I will give it a shot and some testing

**Comment by robcross** [comment]
I haven't looked into it too much but doesn't the config_unload_override load everything up from the default config file again? Maybe that function would need a has_set_save_path = false so that it can be written again?

**Comment by fr500** [comment]
Yes that would be it, but I need to make sure there are no other side
effects, if I can't find any issues I'll send a PR with this by the weekend

**Comment by robcross** [comment]
If you look in the code, I think that overrides are disabled when per-core configs are loaded.
```
if (settings->core_specific_config)
      {
         RARCH_LOG("Can't use overrides in conjunction with per-core configs, disabling overrides\n");
         return false;
      }
```

Also, one quick question. I have no idea where to ask this, but is the "core name" used for overrides stored anywhere??

When I load a core it seems to load $CORENAME/$CORENAME.cfg where $CORENAME isn't the name of the .so file, nor is it any name in the .info file. I think it's pulling some completely different string out of the .so file and it's really making it a pain in the butt to configure...

**Comment by fr500** [comment]
I know, I wrote that code, still it should be done for per-core configs as the issue was present there originally.

I made it use that instead of the library name so it would be portable across platforms (ie, you can move the overrides from windows to linux or psp or whatever and use them without renaming) I don't want to change that.

**Comment by robcross** [comment]
Understood, but is there a programmatic way to pull all the library names? If it's used as a config name it really should go in the .info file somewhere...

**Comment by fr500** [comment]
I guess there is a way to retrieve it yeah but I have no idea.
I'm using system.info.library_name for the path name which is retrieved from the core itself. We don't want to depend from info files for functionality

**Comment by fr500** [comment]
an oddity with this, I can set it to whatever but a subdirectory of my main savestate dir

**Comment by fr500** [comment]
nevermind it works but you have to create the paths manually

**Comment by fr500** [comment]
hmm, well this approach doesn't reset the paths once we unload overrides, I already tried so we need something else for that

**Comment by fr500** [comment]
I sent a PR here https://github.com/libretro/RetroArch/pull/1675
I haven't tested with per-core, only with overrides, sotest and let me know

**Comment by robcross** [comment]
I've tested switching between cores with and without overrides, both save states and save files, I don't see any issues. If a core doesn't have an override, it will just dump the saves in the path specified in the main config file.

**Comment by fr500** [comment]
ok, I updated the PR, now it's no longer needed to use overrides to use this functionality, just enable the toggle in general settings.

One condition is that the subfolder must exist beforehand, I'll fix that later.
Please test with as many cores as possible (weird cores like dosbox, mame, ppsspp specially), let me know.

**Comment by fr500** [comment]
Please reopen if the issue persists
