### ISSUE TITLE
[Feature Request] Enable CSO hashing for RetroAchievements in the frontend

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#15477]
The PPSSPP core (pulled from upstream) recently added the ability to hash CSO files for RetroAchievements: https://github.com/hrydgard/ppsspp/commit/431a0551b21e487798b9208a35c5355eaa157295

However, it doesn’t work in RetroArch.

**Comment by trotsky40** [comment]
That is most likely what I am requesting #notaprogrammer

**Comment by trotsky40** [comment]
> > CSO uses [Deflate](https://en.wikipedia.org/wiki/Deflate) compression with nine levels of presets, usually with 2 KiB blocks handled individually (they could be uncompressed).
> 
> The [original implementation](https://sourceforge.net/p/ciso/code/HEAD/tree/trunk/) was apparently [GPLv2(not plus)](https://sourceforge.net/p/ciso/code/HEAD/tree/trunk/license), but [this more modern version](https://github.com/unknownbrackets/maxcso) is permissive ISC license and can use 7zip's deflate, so potentially something we could add-on there to our existing internal 7zip dep (assuming they don't use a drastically modified version or something; I didn't look very closely).

FWIW. I used maxcso (the more modern version) to compress my ISOs and it triggered the RetroAchievements in the PPSSPP standalone.

**Comment by trotsky40** [comment]
Closing due the pending support for CHD, which will give achievements with a compressed format.

**Comment by retroNUC** [comment]
It's just missing "cso" in the explicit extension list as part of [rc_hash_initialize_iterator](https://github.com/libretro/RetroArch/blob/14cb3732eb331c2329e759ae6a07944d9de41c3e/deps/rcheevos/src/rhash/hash.c#L2466C18-L2466C18). Because of that, it falls back to incorrect full file hash:

````
[INFO] [RCHEEVOS]: Found 0 potential consoles for cso file extension
[INFO] [RCHEEVOS]: Trying console 4
[INFO] [RCHEEVOS]: Opened 3rd Birthday, The (USA).cso
[INFO] [RCHEEVOS]: Hashing first 67108864 bytes (of 1278354793 bytes) of 3rd Birthday, The (USA).cso
[INFO] [RCHEEVOS]: Generated hash f09556d043e181fe198bee65b3673bed
````
If it had the hint to go via [rc_hash_psp](https://github.com/libretro/RetroArch/blob/14cb3732eb331c2329e759ae6a07944d9de41c3e/deps/rcheevos/src/rhash/hash.c#L2466C18-L2466C18), it'd probably work in RetroArch, as I think the PPSSPP core would have registered its own cdreader functions by then and can handle CSO/ZSO/etc. Just wouldn't work standalone in rahasher and such unless @Jamiras were to reimplement the custom cdreader.

**Comment by Jamiras** [comment]
> It's just missing "cso" in the explicit extension list as part of rc_hash_initialize_iterator
> ...
> If it had the hint to go via rc_hash_psp, it'd probably work in RetroArch, as I think the PPSSPP core would have registered its own custom cdreader functions by then and can handle CSO/ZSO/etc.

You're half right. It does need the hint to go to the appropriate function. And a custom cdreader is required to process the cso file. Unfortunately, the custom cdreader is (currently) scoped to the frontend. So unless code is added to the `intfstream` infrastructure, the hashing code won't know what to do with the file.

This is true for all compressed formats. Unless the frontend knows how to decompress them, the hashing code can't process the contents. Allowing the core to expose a custom cdreader is an interesting idea, but not something that's currently supported.

**Comment by Jamiras** [comment]
See also #10841. While the core can load a .chd, without `HAVE_CHD`, the frontend can't identify which game is running.
