### ISSUE TITLE
Multiple mice not working properly anymore with Windows raw driver

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#15485]
## Description

Pretty much the same issue that I made a while ago: #13839, it was fixed by #13840 but it's now broken again.

### Expected behavior

Each mouse should start at its own position.

### Actual behavior

The cursor starts at the last known position of the last used mouse.

### Steps to reproduce the bug

1. Switch to raw input driver and select the proper mouse indexes for ports 1 and 2.
2. Start a game with Flycast or Beetle PSX (or Beetle PSX HW, but switch to software renderer).
3. Set device type to light gun for players 1 and 2.
4. Turn ON crosshair for both players in core options.
5. Move mice.

### Bisect Results

Still worked in stable 1.13.0 (ce9051f), broken in stable 1.14.0 (e3c92b0). Not making any promise but maybe I'll be able to bisect properly tomorrow if needed.

### Version/Commit

- RetroArch: 1.15.0 / 62af42a

### Environment information

- OS: Windows 10

**Comment by sonninnos** [comment]
Works fine here..

**Comment by bslenul** [comment]
Hm interesting, I wonder if there's a setting affecting this somehow 🤔 But even with a fresh retroarch.cfg it doesn't work properly for me anymore.

For what it's worth, bisected to ce1e59615a5fef7df1ed16011edddf744f975dca

**Comment by sonninnos** [comment]
As hinted in the bisect comment and code there, the only possibility I can think of and can replicate is having overlay and "show mouse cursor with overlay" enabled, since pressing the overlay items won't work without reading OS position instead of raw movement.

Menu needs and does the same thing. Or rather it does "work", but position will not match with the OS mouse cursor.

No idea why on earth those both options are enabled by default though.. Mouse cursor option rather could and should be disabled by default, and why not also when the preset is empty, as it also seems to be by default.

**Comment by bslenul** [comment]
Ah yeah, I was confused about that bisect since I don't use any overlay, but indeed "Display Overlay" is enabled by default and disabling it fixes the issue!
