### ISSUE TITLE
Adding, Retiring & Organizing XMB Themes

### ISSUE THREAD

**Issue by baxysquare** [libretro/RetroArch#15686]
Over on [Retroarch-assets](https://github.com/libretro/retroarch-assets), I have added a new theme called FlatUX.  The theme has technically been a part of the repository for a year, as the theme was intended to merge the FlatUI and Retroactive themes and replace them both.  

For now, [I believe we should keep both FlatUX and FlatUI themes and let the community decide if FlatUI should be retired](https://github.com/libretro/retroarch-assets/pull/457).  However, it is officially time to retire the Retroactive and Neoactive themes.

To complete these efforts, I need some help.  I went through the docs and found out how to [add menu options](https://docs.libretro.com/development/retroarch/new-menu-options/) and I was going to try and do it myself. I believe I'd cause more problems than I'd solve, so I chose to open this issue instead. I'll be the first to admit I'm an artist and not a coder. 

Here's what I need in order to add, retire & organize the XMB Themes:

* Add FlatUX theme to the menu
* Remove Retroactive theme from the menu
* Remove Neoactive theme from the menu
* [Optional] Organize the themes in Alphabetical Order (Automatic, Automatic Inverted, Custom, Daite, Dot-Art, FlatUI, FlatUX, Monochrome, Monochrome Inverted, Pixel, Retrosystem, Systematic)

**Comment by sonninnos** [comment]
Unfortunately altering the display order of the themes would result in all old configs to break, since config saves only the enum, but then again that will happen regardless if any items are removed between first and last, so I guess we'll just have to bite that bullet..

Sure would be nice in the future to be able to save the conf string instead so that enum order does not matter. This is not at all the only setting where that would be useful. Either that or create some other mechanism for showing them in different order, like RetroPad binds currently does.

But other than that this is fairly trivial.

**Comment by baxysquare** [comment]
@sonninnos The reason I listed alphabetical organization as the last bullet and made it optional was because I wasn't sure if it would break things.  If it's going to cause more problems than it solves, please don't worry about it.  To me it would make more sense to list them alphabetical, but those who are switching between themes likely don't notice or care.
