### ISSUE TITLE
Game goes windowed when you enter the desktop menu (desktop UI broken)

### ISSUE THREAD

**Issue by riggles1** [libretro/RetroArch#15807]
Since 1.16.0 (functional in 1.15.0) the game screen goes windowed when you use the desktop UI (F5), the desired result is that it stays fullscreen since many of use use multiple monitors. Further explained below, but in short, to have it behave the same as in 1.15.0.

For example in my setup I use a CRT with RA CRTSwitchres while I sometimes pick games from the desktop UI as showcased in this video clip:
https://www.youtube.com/watch?v=Fdo5z1mQ748

But now whenever I press F5 to use my mouse on the "desktop menu" the game will be windowed. The games will launch in windowed mode as well through there, ruining the usability of the desktop mode for a lot of us. This also messes with CRTSwitchres as that functionality requires the game to be fullscreen for modeline switching to occur.

Hope a toggle can be implemented that reverts the behavior and allows for the games to remain fullscreen like before.

I suggest putting it in settings>user interface and naming the toggle: Desktop mode launch in fullscreen ON/OFF.
With the description: For multimonitor users. Makes content stay in fullscreen at the same time as the desktop mode is used.

**Comment by aserrallerios** [comment]
I'm also experiencing this and it's very annoying, making the multi-screen setup less ergonomic.

Just to add more context, the problem seems to be that the Desktop Menu is impossible to focus with the mouse (you can use the keyboard) while RA is in exclusive fullscreen (it might be worth checking with borderless windowed full screen). RA main window and the Desktop Menu seem to exist as a single entity, so while RA is maximized in screen A, the Desktop menu on screen B is also "on top" of everything else, and the mouse just stays behind it.

So in order to fix this I think it's not enough to avoid exiting fullscreen on Desktop launch (@riggles1 proposal), but in addition to that it would also need to make the two screens (RA and Desktop menu) fully independent so I can alt+tab to either of them and focus them in isolation.

**Comment by riggles1** [comment]
I should add that in 1.15.0 it worked perfectly, so reverting the behavior to what it was like in that version would be a good solution.

It worked like this:
- Launch RA (fullscreen)
- Hit F5 to launch the desktop UI (puts your game in windowed once letting you align windows on your desktop)
- Hit the Fullscreen hotkey put your game in fullscreen again on your gaming monitor
(now you have the desktop UI on one monitor, and the game on your primary monitor you game on)
- From that point the game stays fullscreen no matter what and your desktop mode window is windowed elsewhere.
- F5 now makes the desktop UI grab your cursor. Without windowing the fullscreen game.

F5 shouldn't make the game windowed again, hit your fullscreen hotkey if you want the game windowed again.

Here's a different setup, where the desktop UI is used to adjust scaling and shaders on the other monitor live. Not possible in 1.16.0.

https://i.imgur.com/WDY44fP.mp4

**Comment by riggles1** [comment]
Issue wasn't an issue, I had just forgotten that my method to accomplish the above was with winkey as mousegrab, to move the mouse back to the desktop mode and keeping the game in fullscreen, games will launch in fullscreen from desktop mode this way as well.
