### ISSUE TITLE
Joypad config generation doesn't work on Android

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#16049]
## Description

I follow the guide to generate joypad config on Android:

https://www.retroarch.com/index.php?page=controller-autoconfig

> The first step is to proceed to a manual mapping of your pad. For this, unplug all the other joypads, and use Settings->Input->User 1 Binds->User 1 Bind All. Make sure that your mapping is perfect by testing every button in the menu and in some games.

### Expected behavior

Should have Settings->Input->User 1 Binds->User 1 Bind All

### Actual behavior

I cannot find Settings->Input->User 1 Binds->User 1 Bind All

### Steps to reproduce the bug

1. Install RetroArch Android
2. Open RetroArch
3. Open Settings -> Input

### Version/Commit

- RetroArch: 1.16 from F-Droid

### Environment information

- OS: Android 13
- Compiler: no

**Comment by hizzlekizzle** [comment]
Yeah, those directions should still work but the names for things have changed since they were written. 

It's now in settings > input > retropad binds > port 1 controls, and 'bind all' is now 'set all controls'

**Comment by guoyunhe** [comment]
@hizzlekizzle Thanks, I found the menu item. However, I cannot find a way to export the joypad config, so that I can submit it GitHub.

**Comment by hizzlekizzle** [comment]
that should be "save controller profile", but it's going to put it into your 'autoconfig' directory, which is probably not easily accessible (unless your device is rooted). You can change your autoconfig directory to somewhere user-writeable and then go through the process, though.

**Comment by guoyunhe** [comment]
> that should be "save controller profile", but it's going to put it into your 'autoconfig' directory, which is probably not easily accessible (unless your device is rooted). You can change your autoconfig directory to somewhere user-writeable and then go through the process, though.

Thanks, I will try to map autoconfig directory and see if I get any luck :smile:

**Comment by davidhedlund** [comment]
# Issue
In the default RetroArch configuration file (retroarch.cfg), the joypad autoconfig directory is set to "/data/user/0/com.retroarch/autoconfig". Due to this setting, RetroArch is unable to extract files to this directory.

# User solutions
I just added this an Android section in our Joypad Auto Configuration guide: https://docs.libretro.com/guides/controller-autoconfiguration/#android-configuration

# Development solution
This improvement streamlines the process for users, eliminating the need to follow the Android section in our Joypad Auto Configuration guide (https://docs.libretro.com/guides/controller-autoconfiguration/#android-configuration) in order to generate autoconfig files for Android users.

## Update configuration file
Modify the retroarch.cfg file to replace the default joypad autoconfig directory path with a user-accessible location:

```
joypad_autoconfig_dir = "/data/user/0/com.retroarch/autoconfig"
```

Proposed setting:
```
joypad_autoconfig_dir = "/storage/emulated/0/RetroArch/autoconfig"
```

## Autoconfig file migration
To ensure independence of the `Update Controller Profiles` option for the controllers to work by default, I suggest that RetroArch automatically copying the system autoconfig files from `/data/user/0/com.retroarch/autoconfig` to the newly designated user directory `/storage/emulated/0/RetroArch/autoconfig` directory.

**Comment by gouchi** [comment]
@guoyunhe is it ok using latest message ? If it is ok, please close this issue. Thank you.

**Comment by davidhedlund** [comment]
@gouchi My message propose changes in Retroarch so users don't have to follow the guide. Hopefully these changes are applied to RA, so I can remove this section from the guide. It's better to keep things simple.

**Comment by guoyunhe** [comment]
> @guoyunhe is it ok using latest message ? If it is ok, please close this issue. Thank you.

Look good to me

**Comment by davidhedlund** [comment]
Merged to:
* https://github.com/libretro/RetroArch/issues/16799
*
