### ISSUE TITLE
[Feature request]: Autosave settings

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16114]
Settings are not saved automatically. In GNU/Linux settings are always saved when you close the program (either from RetroArch, or by pressing the close button on the window). It would be useful if it was possible to autosave settings every time a setting is modified for Android so you can omit the mandatory step to save them: Main Menu -> Quit RetroArch

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16113

**Comment by hizzlekizzle** [comment]
You can save them through main menu > configuration file > save current configuration, though that admittedly takes as many steps as quitting.

We've purposely avoided autosaving settings because it increases the risk of people getting stuck with incompatible settings. There may be some sort of compromise that would hypothetically work, like flushing whenever you exit a menu or go back to the game or something /shrug
