### ISSUE TITLE
[CTR] Error compiling

### ISSUE THREAD

**Issue by Rinnegatamante** [libretro/RetroArch#1626]
Tried to compile RetroArch for 3DS and got thess errors on Griffin:
In file included from griffin/griffin.c:652:0:
griffin/../runloop_data.c: In function 'rarch_main_data_iterate':
griffin/../runloop_data.c:998:22: error: 'struct <anonymous>' has no member named 'threaded_data_runloop_enable'
    if (settings->menu.threaded_data_runloop_enable && data_runloop->alive)
                      ^
griffin/../runloop_data.c:998:67: error: 'data_runloop_t' has no member named 'alive'
    if (settings->menu.threaded_data_runloop_enable && data_runloop->alive)
                                                                   ^
make: *** [griffin/griffin.o] Error 1

**Comment by aliaspider** [comment]
that error is old, did you pull the latest version ? 
how are you compiling it ? using ``make -f Makefile.ctr``  right ?

**Comment by Rinnegatamante** [comment]
Yes, i'm using make -f Makefile.ctr and i downloaded the very latest commit from your fork.

**Comment by aliaspider** [comment]
don't use my fork since it is just used to make pull requests, this is why it lacked the commit that fixed the error you had.
just pull from this repository and it should work.

you also need to compile a core first with ``make platform=ctr`` ( or ``make -f Makefile.libretro platform=ctr``) and copy the resulting static lib as ``retroarch/libretro_ctr.a``.

use gambatte-libretro or gpsp-libretro since only those two have the platform=ctr target implemented currently.

**Comment by twinaphex** [comment]
I guess we can close this issue now.
