### ISSUE TITLE
Thanks for allowing rename playlist, but has an issue ...

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#16379]
Thanks for reading my topic.
Retroarch in recent version was added the feature allowing rename playlist. Thanks.
However has an problem. If you rename an playlist and even if was renamed the thumbnail path directory using both the same name not will be displayed the images thumbnails.
Example.
Playlist "Atari VCS" > Thumbnail directory "Atari VCS"
after was renamed to
Playlist "Atari 2600" ... even renaming the thumbnail directory for "Atari 2600" break showing thumbnails.

Only reporting.
Have an nice day.

**Comment by zoltanvb** [comment]
I am not aware of playlist rename feature, anyway it is possible by renaming the playlist file. But that should not impact thumbnail paths much.
Can you provide a debug level log of browsing the non-working playlist, where on-demand thumbnail downloads are enabled? (It is not important for the thumbnails to be available online, but this will print out some detailed information this way.)

**Comment by Augusto7743** [comment]
That issue not happen in Retroarch 1.17 build cfd79a9.
Thanks for your replies.
Closing.

**Comment by Augusto7743** [comment]
Unhappily I had done an wrong action closing that issue. Excuse me.
Doing more test the problem continue happening.
I have uploaded the log files. However I not see inside logs any detail about the thumbnails images path.

Playlist name "Nestopia" and image path directory "Nestopia > show the images
Renamed the playlist to "FC Nestopia" not changing the path directory "Nestopia" > show the images
Renamed the playlist to "FC Nestopia" changing the path directory to "FC Nestopia" > not show the images

Have an nice week.

[logs.zip](https://github.com/libretro/RetroArch/files/14738488/logs.zip)

**Comment by zoltanvb** [comment]
OK, reproduced. This is as expected.
When doing manual scan with custom system name, the database entry for the playlist items will look like the playlist name:
` "db_name": "Nestopia.lpl"`
There is no such database, but RA internal logic will use this entry also for thumbnail lookup.

If you rename the playlist (.lpl file), this entry will remain inside the file. To adapt this, run a search-replace operation on the file with any text editor, so that it looks like this for all entries:
` "db_name": "FC Nestopia.lpl"`

**Comment by Augusto7743** [comment]
Doing manual scan using a simple custom name using the same name for thumbnail directory.

" There is no such database, but RA internal logic will use this entry also for thumbnail lookup."
If user use compacted playlist not is possible edit the file. Not is an good alternative. 
The correct good sense is RA read the thumbnail directory using only the playlist file name and not any detail inside of file. Only does problem.

Better is the solution above.

**Comment by i30817** [comment]
Playlist rename affects the downloaded thumbnails path because there is a conceptually missing scan_* manual playlist property. 

Read https://github.com/libretro/RetroArch/issues/16031 carefully to understand, particularly the part where I talk about options to fix it and mention disentangling file name from system name.

**Comment by i30817** [comment]
If the problem is code outside of the playlist code using playlist filename to setup thumbnail cache or download paths, a alternative to saving scan_system_name would be to save scan_display_playlist_name, ie you would read the playlist to show it's name on the menu and that would be what 'renaming' a playlist would do.

Dunno if it's any better for UI performance than reading for the thumbs path though since changing the playlist names that way would force playlist parsing on start of retroarch. In fact might be worse, I just mentioned it as a idea, not a sure thing.

**Comment by i30817** [comment]
Thinking about it some more, my the hypothetical scan_system_name should just be system_name, ie: be a property of all playlists, not just manual playlists (except history).

The reason is that you also want to be able to rename normal playlists.

**Comment by Augusto7743** [comment]
@i30817
Thanks for sharing #16031 and #16378 .

"this is a real bug, and saying that 'this is expected' and telling people to run search replace in text editors is particularly annoying"
You are correct ...
annother issue is saying about allow thumbnails using jpg and seeing reply saying "not is possible because the files in server are png" even if retroarch internally has jpg support =(
I had done an test converting my all png images had drop from almost 10 GB to less of 2 GB !
Totally no sense not allowing use jpg in thumbnails because "not has jpg files in server".

In moment is better create the playlist using the correct naming and avoid renaming.
Have an nice week.
