### ISSUE TITLE
App Store Release (iOS, iPadOS, tvOS)

### ISSUE THREAD

**Issue by kimar** [libretro/RetroArch#16415]
As per Apples changes to the App Store Guidelines from April 5th 2024 Retro Game Emulators are now explicitly permitted on the App Store. (Section 4.7)

![image](https://github.com/libretro/RetroArch/assets/126418/044eddb0-0af5-453b-a687-d5340c3dce45)

Are there any plans to release RetroArch to the App Store?

If there is help required I'm happy to support on this matter.

Cheers,
Marcus

**Comment by Timbo303** [comment]
Since retroarch already supports jailbroken iphones its likely a no brainer.

**Comment by kimar** [comment]
Yes you can also easily sideload by re-signing the binary so it should be trivial. I'll try to re-label the issue, thx.

**Comment by dpark12300** [comment]
I second this. This would be amazing.

**Comment by dpark12300** [comment]
Also, Mac app store would be great too.
Steam bugs out on my mac

**Comment by hizzlekizzle** [comment]
We don't have any plans for this at the moment, since it doesn't really sound like they're opening the doors to general purpose/BYO-ROMs emus. I believe the author of Yaba Sanshiro has submitted it, so we'll see how that goes and reassess.

**Comment by Tipcat-98** [comment]
First real emulator that has been found.
It functions as you'd expect from an emulator, though the author is shady.
It's just a stolen GBA4IOS.

https://www.reddit.com/r/ios/comments/1c34khj/the_appstore_just_got_its_first_emulator_igba/

**Comment by tannerellen** [comment]
Yep looks like emulators with roms are being allowed. So I don’t see why RetroArch wouldn’t be. I just installed iGBA and it works great and you can load your own roms, when you launch it a folder is created you can copy the roms into, or you can launch them from files and it adds to iGBA automatically. There is a C64 emulator too now. https://appleinsider.com/articles/24/04/14/game-emulators-arrive-in-app-store-following-rule-changes

**Comment by AaronKelley** [comment]
There was some drama around iGBA and it was pulled, but Delta is up now, and it supports loading any ROM file you can point to in the file browser.
https://apps.apple.com/us/app/delta-game-emulator/id1048524688

**Comment by nenge123** [comment]
> There was some drama around iGBA and it was pulled, but Delta is up now, and it supports loading any ROM file you can point to in the file browser.
> 
> https://apps.apple.com/us/app/delta-game-emulator/id1048524688

delta game emulator is not a html5。

so retroarch it can up not with (3ds ns ps2 ps3 core)

**Comment by LibretroAdmin** [comment]
Warmenhoven is looking into this. Any further enquiry at this point is not necessary. We will see what happens.

**Comment by TCB13** [comment]
> There was some drama around iGBA and it was pulled, but Delta is up now

Yes, there was drama.

Riley Testut (the author of the original GBA4iOS and Delta) decided not to launch on the App Store at first and someone forked his old project and released. He later on bitched about it and got Apple to pull iGBA because there were a few assets (images, not code) that was included on iGBA that belonged to him.

Testut then proceeded to launch Delta on the US App Store and exclusively on the US Store. For Europe he decided to show the middle finger to everyone and make it available on the AltStore that is payed.

![image](https://github.com/libretro/RetroArch/assets/6315832/2236fa8a-3a86-440f-bc1c-6914d217b790)

He's clearly leveraging Delta to get people into his AltStore. This isn't okay and I really hope we get RetroArch into the App Store because 1) is it objectively better and 2) the developers - unlike Testut - are good people.

Thank you.

**Comment by Shimmer2** [comment]
期待Retroarch 登陆apple store！

**Comment by Panky55** [comment]
> > There was some drama around iGBA and it was pulled, but Delta is up now
> 
> Yes, there was drama.
> 
> Riley Testut (the author of the original GBA4iOS and Delta) decided not to launch on the App Store at first and someone forked his old project and released. He later on bitched about it and got Apple to pull iGBA because there were a few assets (images, not code) that was included on iGBA that belonged to him.
> 
> Testut then proceeded to launch Delta on the US App Store and exclusively on the US Store. For Europe he decided to show the middle finger to everyone and make it available on the AltStore that is payed.
> 
> ![image](https://private-user-images.githubusercontent.com/6315832/323569144-2236fa8a-3a86-440f-bc1c-6914d217b790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Mjg3MDAsIm5iZiI6MTcxNTYyODQwMCwicGF0aCI6Ii82MzE1ODMyLzMyMzU2OTE0NC0yMjM2ZmE4YS0zYTg2LTQ0MGYtYmMxYy02OTE0ZDIxN2I3OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTkyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFlMDA1NGQyMDIwZTE0Mzk0NTgwOTM5NWM1M2NiZWUzYjhiNmRiODQ4ZjdiMDcwZDEzYzk2ZWYxZWYxNWRmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kaDpPSas47Ns4p44CZBshkgh6GG46o2UVRKolrWICUk)
> 
> He's clearly leveraging Delta to get people into his AltStore. This isn't okay and I really hope we get RetroArch into the App Store because 1) is it objectively better and 2) the developers - unlike Testut - are good people.
> 
> Thank you.

How about you read the eu guidelines before shit talking the delta developer

**Comment by TCB13** [comment]
> How about you read the eu guidelines before shit talking the delta developer

You should be the one doing the reading: https://developer.apple.com/support/core-technology-fee/

> The Core Technology Fee (CTF) is an element of the new business terms in the European Union (EU) (…) Developers can choose to remain on the App Store’s current business terms or adopt the new business terms for iOS apps in the EU. Developers can choose to remain on the App Store’s current business terms or adopt the new business terms for iOS apps in the EU.

I’m not saying he wants to profit from this, it’s all about pushing people into the AltStore. I don’t even believe the AltStore pricing is sustainable [unlike he says on the announcement](https://rileytestut.com/blog/2024/04/17/introducing-altstore-pal/)… he’s most likely have to increase the price later on once he gets more Apps over there.

**He just wanted to release the AltStore and for that he was forced to accept the “new terms”. This in turn lead to the current situation where Europeans have to pay more**. He could’ve still done it and proceeded to publish Delta on the EU App Stores and charge the fee there instead of pushing AltStore down people’s throats. **OR he could’ve not accepted the terms all together and distributed Delta for free on EU Stores / without being charged the CTF (losing AltStore in the process)**.

Another thing he could’ve done was release the AltStore under a different developer account so the Delta account could use the old terms (no Apple Tax) and the AltStore one would use the new terms.

Look, I was even okay with paying 0,50€, 1€ or 10€ for the App but only if it was distributed through the App Store. It would take care of the potential > 1M download CTF fee and he would profit as well. No harm there. What he did instead was to gatekeep the app from the App Store in order to force people into the AltStore. Forcing people into the AltStore and a yearly fee is at least less than ideal.

**Comment by Panky55** [comment]
> > How about you read the eu guidelines before shit talking the delta developer
> 
> You should be the one doing the reading: https://developer.apple.com/support/core-technology-fee/
> 
> > The Core Technology Fee (CTF) is an element of the new business terms in the European Union (EU) (…) Developers can choose to remain on the App Store’s current business terms or adopt the new business terms for iOS apps in the EU. Developers can choose to remain on the App Store’s current business terms or adopt the new business terms for iOS apps in the EU.
> 
> I’m not saying he wants to profit from this, it’s all about pushing people into the AltStore. I don’t even believe the AltStore pricing is sustainable [unlike he says on the announcement](https://rileytestut.com/blog/2024/04/17/introducing-altstore-pal/)… he’s most likely have to increase the price later on once he gets more Apps over there.
> 
> **He just wanted to release the AltStore and for that he was forced to accept the “new terms”. This in turn lead to the current situation where Europeans have to pay more**. He could’ve still done it and proceeded to publish Delta on the EU App Stores and charge the fee there instead of pushing AltStore down people’s throats. **OR he could’ve not accepted the terms all together and distributed Delta for free on EU Stores / without being charged the CTF (losing AltStore in the process)**.
> 
> Another thing he could’ve done was release the AltStore under a different developer account so the Delta account could use the old terms (no Apple Tax) and the AltStore one would use the new terms.
> 
> Look, I was even okay with paying 0,50€, 1€ or 10€ for the App but only if it was distributed through the App Store. It would take care of the potential > 1M download CTF fee and he would profit as well. No harm there. What he did instead was to gatekeep the app from the App Store in order to force people into the AltStore. Forcing people into the AltStore and a yearly fee is at least less than ideal.

Course he wants altstore buddy I don’t see the issue considering you will also get other apps 😂

**Comment by TCB13** [comment]
> Course he wants altstore buddy I don’t see the issue considering you will also get other apps 😂

No thanks. The issue is that he's forcing people into subscriptions, no thanks.

**Comment by Panky55** [comment]
> > Course he wants altstore buddy I don’t see the issue considering you will also get other apps 😂
> 
> The issue is that he's forcing people into subscriptions, no thanks.

He isn’t forcing anyone to do anything and if you wanna keep complaining over this shit then just sideload the damn app

**Comment by TCB13** [comment]
> He isn’t forcing anyone to do anything and if you wanna keep complaining over this shit then just sideload the damn app

Yes, because having to refresh the App every 7 days it totally fine while US users get it for free with a simple tap on the App Store.

**Comment by Panky55** [comment]
> > He isn’t forcing anyone to do anything and if you wanna keep complaining over this shit then just sideload the damn app
> 
> Yes, because having to refresh the App every 7 days it totally fine while US users get it for free with a simple tap on the App Store.

There’s trollstore jailbreaks and buying apple developer certificates from people if you wanna keep bitching go ahead just know your petty af

**Comment by TCB13** [comment]
> There’s trollstore jailbreaks

Yet another bullshit. As if trollstore was permanent / as straightforward as downloading an app from the store and didn't require very specific versions of iOS and reloads. You're delusional that's what you are.

**Comment by Panky55** [comment]
> > There’s trollstore jailbreaks
> 
> Yet another bullshit. As if trollstore was permanent / as straightforward as downloading an app from the store and didn't require very specific versions of iOS and reloads. You're delusional that's what you are.

It’s not bullshit and it’s pretty straightforward if you can’t follow simple things as not updating and some simple introductions then you need education and how tf am I delusional lmao

**Comment by TCB13** [comment]
> It’s not bullshit and it’s pretty straightforward if you can’t follow simple things as not updating and some simple introductions then you need education and how tf am I delusional lmao

Fist, the [TrollStore is **not** a jailbreak](https://ios.cfw.guide/installing-trollstore/
) and they say it it's just a way to "permanently sign and install any application with almost any entitlement with the help of a CoreTrust bug"... and then:

> If your device is on iOS 14.0 beta 1 or earlier, is running iOS 16.7.x (excluding 16.7 RC (20H18)), or is running iOS 17.0.1 or newer, it will never be supported by TrollStore.

Seems like you're the one needing education, because unlike you, I do read.

**Comment by Panky55** [comment]
> > It’s not bullshit and it’s pretty straightforward if you can’t follow simple things as not updating and some simple introductions then you need education and how tf am I delusional lmao
> 
> Fist, the [TrollStore is **not** a jailbreak](https://ios.cfw.guide/installing-trollstore/) and they say it it's just a way to "permanently sign and install any application with almost any entitlement with the help of a CoreTrust bug"... and then:
> 
> > If your device is on iOS 14.0 beta 1 or earlier, is running iOS 16.7.x (excluding 16.7 RC (20H18)), or is running iOS 17.0.1 or newer, it will never be supported by TrollStore.
> 
> Seems like you're the one needing education, because unlike you, I do read.

I know TrollStore isn’t a jailbreak dumbass I simply just didn’t put a comma and why do you think I said “not updating” clearly you can’t read

**Comment by Panky55** [comment]
Simply wait for RetroArch if your ass gon be like this

**Comment by hizzlekizzle** [comment]
This is not the place for squabbling. Please cut it out.

**Comment by Panky55** [comment]
> This is not the place for squabbling. Please cut it out.

 😂🫡

**Comment by AaronKelley** [comment]
It's out.
https://apps.apple.com/us/app/retroarch/id6499539433

**Comment by herrlado** [comment]
Thank u so much. Already uploading the games 👍

**Comment by LibretroAdmin** [comment]
> It's out. https://apps.apple.com/us/app/retroarch/id6499539433 No announcement. Is this an official release?

It's official.

**Comment by kimar** [comment]
Great! Thank you very much!

**Comment by Shimmer2** [comment]
感谢非常！！

**Comment by Shimmer2** [comment]
期待java核心接下来

**Comment by ethanaobrien** [comment]
Is there a reason the app on the App Store requires 14.2 or later, while the download page has as far back as iOS 9? Or is this just some weird Apple restriction thing

**Comment by warmenhoven** [comment]
@ethanaobrien Both. App Store rules are currently that apps must be built with Xcode 15, which only supports back to iOS 12, so that will be as far back as can be supported on the App Store build. However, as you note, right now the build only supports back to 14.2. That is due to a bug in the way that some of the cores are built, which inadvertently get marked as being built for 14.2. Additionally, the Arrow Menu overlay that has the on screen keyboard, mouse, and rotation lock, requires iOS 13. I do intend to fix these things so that iOS 12 is fully supported on the App Store but haven't had enough time and have had other higher priority things to work on.

**Comment by ethanaobrien** [comment]
> App Store rules are currently that apps must be built with Xcode 15, which only supports back to iOS 12, so that will be as far back as can be supported on the App Store build

This makes me wonder how [VLC media player](https://apps.apple.com/us/app/vlc-media-player/id650377962?platform=iphone) is still releasing updates for iOS 9. My iPhone 4s (a 32bit device) got an update for VLC not too long ago. I'm guessing these rules are only applicable to new apps?

**Comment by warmenhoven** [comment]
I assume but I don't know. If there's a way to publish a build for older iOS versions I'm happy to look into that but the documentation I have from Apple says I can't. I assume VLC can because it's been on the App Store long enough that it supported those iOS versions originally.
