### ISSUE TITLE
Retroarch Ignores Macro/Simulated Keypresses

### ISSUE THREAD

**Issue by royaltongue** [libretro/RetroArch#16438]
## Description

I have tried using multiple macro/simualted keypress programs to map my foot pedal (which simulates pressing F4) to load a save state in Retroarch. The programs I have used are:
1) [Hass.agent](https://github.com/hass-agent/HASS.Agent), as my foot pedal runs off of ESPHome, and this is the most direct method
2) AutoHotKey, which I tried once Hass.agent didn't work. I prepared a macro that waited 500 milliseconds, then pressed F4. I tried using `SendInput`, `SendPlay`, and `SendEvent`, but all had the same results.
3) The [SuperMacro plugin](https://marketplace.elgato.com/product/supermacro-62195fec-7bcb-403d-b650-c342e9dfec67) for the StreamDeck. When I pressed a button on the StreamDeck, it pressed F4

With all of these methods, the F4 keypress is registered on any keyboard tester website, such as https://keyboardchecker.com/

### Expected behavior

Save state to be loaded / simulated keypress registered

### Actual behavior

Retroarch does not respond to any of them. Whether it's in-game or in the hotkey rebinding meny, the keypress isn't registered at all.

### Steps to reproduce the bug

1) Use any of the programs listed above to simulate a keypress
2) Try to use keypress in Retroarch to trigger hotkey action

### Bisect Results

See description

### Version/Commit

- RetroArch: 1.17..0/ad8975c

### Environment information

- OS: Windows 10 22H2
- Compiler: MinGW (10.2.0) 64-bit

**Comment by sonninnos** [comment]
AutoHotkey works and has been working here always.

**Comment by royaltongue** [comment]
Can you provide a working AHK script that I can test?

**Comment by sonninnos** [comment]
There is nothing special about it, and my scripts are too complicated to simply copypaste around as an example.

I suggest first making sure that `WinActive` is working properly with some random `msgbox` prompts. After that there is no way that `Send` won't be picked up. And does not matter what the RA input driver is, as in dinput and raw both work fine.

And I also suggest first trying to script a keyboard press, since certain xinput controllers and `GetKeyState` with `1JoyX` is not guaranteed to work. Which means that you need to create a loop that uses `XInput.ahk` for reading the input.

**Comment by royaltongue** [comment]
Decided to go a different route, using an ESP32 with ESPHome to emulate a Bluetooth HID keyboard

I think it may have been related to key press timing, as Retroarch was flakey on acknowledging the input until I set to release delay to ~500ms. Now that it's set, it works perfectly
