### ISSUE TITLE
Playlist on Steam Deck picky with upper- and lowercase letter differences with boxarts and screenshots

### ISSUE THREAD

**Issue by Gagert** [libretro/RetroArch#16742]
I have the very same setup for RetroArch on both my Windows 11 PC, Android smartphone, Android tablet and Steam Deck. I'm using playlists for all the devices, where all of the following has to match to make the selected game show boxart and screenshot:

Titlename
Name of boxart
Name of screenshot

This works as intended on my Windows 11 PC, Android phone and Android tablet, where boxart and screenshot can be viewed for each game in the playlist as long as the filename for the images matches the given titlename.

If however there are some upper- and lowercase differences between the titlename, boxart and screenshot of a given game (the and The for instance), my Steam Deck won't show either one- or both of the images for that specific game. This is not an issue with my Windows 11 PC or my Android devices, this is only an issue on my Steam Deck.

**Comment by zoltanvb** [comment]
Windows file system is case insensitive (unless configured otherwise), Android would be case sensitive, but the storage often has FAT32 file system which is again case insensitive. On case sensitive file systems, this is normal and expected.

Having said that, this does not help much with the user experience. Are there any specific thumbnails where you encounter such problems? The database naming should be mostly consistent in this respect, thumbnail repos may have some variation, but it will be probably better to fix there.

**Comment by Gagert** [comment]
Well, I sometimes used thumbnail repos, and sometimes not. The thumbnails that I named are the ones with inconsistencies I guess.

This explains a lot. I didn't know that the file systems themselves was guilty for the case sensitivity in RetroArch, thus not an issue with RetroArch itself. I guess that I just need to do a little bit of cleanup manually to keep the names consistent then.

Feel free to close this issue, well at least if there's no simple workaround codewise for RetroArch to make it ignore case sensitivity.

**Comment by zoltanvb** [comment]
Unfortunately, there isn't. Making thumbnail finding case insensitive across platforms would result in more complicated loading scenario (repeated each time menu is scrolled), and for thumbnail download it would be even worse.

**Comment by Gagert** [comment]
OK, I understand. I'll close this issue then. Thanks for the replies.
