### ISSUE TITLE
[Feature Request/macOS] Add sdl2 input and controller drivers

### ISSUE THREAD

**Issue by DJtheMan2101** [libretro/RetroArch#16838]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Just as the title says. I did not see any other issue specifically about this, so I made one. Looks like these drivers are already present on Windows and Linux, but not macOS. macOS has only the cocoa input driver, and the mfi and hid controller drivers.

I have no idea how difficult it would be to bring the SDL2 drivers to macOS, though some other macOS apps do use it (like ES-DE, Dolphin, and PCSX2).

Hopefully, this would provide increased/better controller support, and also sidestep [an issue](https://github.com/libretro/RetroArch/issues/16136) I reported that involves the hid driver (and does not occur in the aforementioned apps).

**Comment by warmenhoven** [comment]
I took a look at this a while back and again today after seeing this filed, and I'm not planning on looking at it anymore. I'm not fundamentally opposed to the idea, I just don't think it's worth the time to get it working.

It's not that hard to get it compiling. I'm quite a bit leery of putting a dependency on having homebrew install it as there aren't any such dependencies right now.
* Actually there is for Qt but that build is disabled by default and not part of the buildbot.
* This is also the reason that ffmpeg support hasn't been included yet.
* For moltenvk the binaries got checked in, partly also because there are retroarch-specific patches in the moltenvk code, but this is also a very bad solution. For moltenvk there's not really a great alternative though.

Once you get it compiling the problems begin:
* There's no way to selectively include SDL drivers; you get them all (video, audio, microphone, input, controller) or none.
* The video and input drivers are broken in that they do not interact with ui_cocoa correctly at all. ui_cocoa makes many assumptions that the only possible video drivers are gl/glcore and vulkan/metal, and the only possible input driver is cocoa; and those drivers are in cahoots with ui_cocoa in a not-clean way. Fixing SDL video and input drivers to work correctly here I fear will make it even less clean.

The audio driver is fine. It doesn't work better or worse than coreaudio. Not surprising as it's just using coreaudio under the covers.

The controller driver would be nice, and it does fix the Switch Pro Controller over USB issue. However, SDL2 is just providing a wrapper around hid/iokit that the hid controller driver is already using. Admittedly there are several bugs in the hid driver that should be fixed, which would address #16136 among others. I'd rather spend my time working on that.

Similarly for the microphone, I'd rather implement it using the coreaudio APIs directly.

**Comment by warmenhoven** [comment]
Oh right, I forgot to add in the part about build dependencies, it needs to be a universal binary, which homebrew isn't set up to provide. Also the libraries aren't provided by the platform and so have to be bundled (or statically linked). These are all solvable problems but they don't have a great way of integrating with the current buildbots in a way that doesn't involve committing binaries to git. That's what happened for moltenvk largely out of necessity and it's a horrible solution that I don't want to repeat if I can avoid it.

**Comment by warmenhoven** [comment]
Ok, so. I did actually go down the path of trying to fix the hid driver to support the Nintendo Pro Controller correctly using sdl2 as a guide. As it turns out, although there is a sdl2 joystick/gamecontroller driver that does just use iokit directly, that's not what is used for that controller, and if you try, you get similarly poor results as the current retroarch hid driver. The controller is properly supported using the hidapi library, along with some additional integration pieces in the sdl2 driver. That's not just an API wrapper around the underlying platform library; there's a lot of important logic there that would be annoying/duplicative to try to replicate. So, I think I have figured out a reasonable way to include optional libraries.
