### ISSUE TITLE
[Feature] Adding support for special characters in video_driver_set_osd_msg

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#1690]
Hello,

I would like to know if that would be possible to add support for special characters in `video_driver_set_osd_msg` ? Each time I try to draw an accentued message (created in a array using `strcpy`), I've got `??` instead of each accent.

I've tried using a wide string (using `L`) but if I do so I only have the first letter of the array, being an `?` if it's a special character.

If I edit the `FT_ATLAS_COLS` to 32 (instead of 16) in `freetype.c` and try to print `L"é"`, it works fine, but it ignores which succeeds the `é`.

Thanks !

**Comment by natinusala** [comment]
Okay I've found a fix, but I don't know if it's clean, or safe, or cross-platform or anything, could you tell me if it is the right way to do it ?

1. Change FT_ATLAS_COLS to 32 in order to extend the glyphs array and include accentued characters
2. Add the `-fexec-charset=iso-8859-1` compilation flag so that GCC encodes the strings right in `strcpy`

**Comment by twinaphex** [comment]
That doesn't sound too portable to me.

Also, I'd recommend that we hold off on these features until I can get a stable RA 1.1 out. I have to start introducing a feature freeze so that we can get most of the niggles sorted out and a stable release pushed out, otherwise it is an endless session of whack-a-mole.

**Comment by natinusala** [comment]
Okay, I understand. When do you think that RA 1.1 will be out ?

**Comment by Alcaro** [comment]
-fexec-charset sounds like barking up the wrong tree. To start with, MSVC needs something different, and according to what I can find on Google, the equivalent (#pragma execution_character_set("x")) likes to randomly disappear between versions.

And more importantly, it would paint us into a corner if we want to use non-Latin characters, for example for localizations into Greek, Russian or Japanese. We'll want something based on UTF-8, that's the only one that can handle all weird characters correctly.

RA 1.1 will be released once it's done, but I can't pinpoint any timeframe. It's been "almost done" since January; we keep finding random must-fix bugs all over.

**Comment by Kivutar** [comment]
What about this issue now? The atlas have been increased. And I could print some é in the messages. So we should close it.

**Comment by natinusala** [comment]
Okay sorry for reopening this now, but how did you manage to print the accents ? I can't get anything but `Ã©` instead of special characters in my messages, do I need to use `wchar` or the `L` prefix ? It doesn't match with the signature of `set_osd_msg` anyway so I don't think it's that. Maybe a missing compilation flag ?

**Comment by Alcaro** [comment]
Looks like you saved your source file as UTF-8.

Unfortunately, RetroArch demands ISO-8859-1.

We do wish to lift this limitation. It's blocking us from merging #2088.

**Comment by natinusala** [comment]
It works, thanks ! Good luck for the UTF-8 integration !
