### ISSUE TITLE
Huge memory leak if all shader "#pragma parameter" values are 0.0

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16958]
## Description
Shaders that have labels with the following  numerical values are problematic when one open the parameter list and select the parameter "SOMETHING"
```#pragma parameter SOMETHING "SOMETHING ELSE "  0.0 0.0 0.0 0.0```

### Expected behavior
To see a list with just one value: 0.0

### Actual behavior
Retroarch stalls indefinitely, leaking memory under the hood till the crash.

RetroArch: 1.18.0

### Environment information

- OS: Archlinux

**Comment by fishcu** [comment]
I can confirm that this still happens with recent nightly builds. I have tested as recent a version as 1.19.1.

`htop` shows the memory usage slowly creeping up indefinitely, also confirming the memory leak.

![image](https://github.com/user-attachments/assets/01546ecb-4238-48de-ad2a-4c566274e9cd)

**Comment by bslenul** [comment]
I can reproduce on Windows 10 as well, and it goes up pretty fast:

https://github.com/user-attachments/assets/b9855233-2ecf-49d9-8c1d-7ddbd6ac6dac

**Comment by gouchi** [comment]
I confirm the issue also on Linux but strangely enough I could not get any interesting [debugging information using ASAN](https://docs.libretro.com/development/retroarch/debugging/#asan-linuxmacbsdandroid) ?

**Comment by LibretroAdmin** [comment]
For me that issue only happens when I press 'Confirm' on that entry.

It happens because the menu is trying to allocate memory for the entire range of numbers to create a dropdown list for, and this list is apparently too big to fit into RAM. There's a similar issue in the Cheat Manager menu when it needs to create a dropdown list for all 16bit and/or 32bit numbers.

Either we change instances like this to text-based input or we find a way to fix this excessive RAM usage when having to create so many menu dropdown entries.

**Comment by kokoko3k** [comment]
> It happens because the menu is trying to allocate memory for the entire range of numbers to create a dropdown list for, and this list is apparently too big to fit into RAM. There's a similar issue in the Cheat Manager menu when it needs to create a dropdown list for all 16bit and/or 32bit numbers.
> 
> Either we change instances like this to text-based input or we find a way to fix this excessive RAM usage when having to create so many menu dropdown entries.

I don't think that's the issue.

To clarify, as per the #pragma line, the list should have just one element, 0.0, because min=max.
Hence the step should be not relevant, but being it 0.0 too, RA is probably trying to allocate infinite entries.

**Comment by LibretroAdmin** [comment]
Since it only happens when clicking on the element it definitely has to do with the dropdown list allocation and the range involved.

I agree it is not good this happens, so far it has only happened in the menu in extreme situations like trying to list all 16-bit range values and/or 32bit for cheat codes. I suspect the way to solve this though will be pretty hard. The menu structs are prob way too big as is and need a significant reduction in size so that there isn't this massive heap space allocation going on when having to allocate x amount of entries. 

More to the point, this specific entry in the shader parameters list, is it even meant to be modified or was it just meant as a general 'text note'? Like a line of text to read and by accidentally clicking on it it tries to allocate a 'list' which perhaps was not intended/accounted for? I don't think when designing the shader parameters we really intended for text lines like this so perhaps some shader authors just took some liberties here with how they made some of these parameters and now we have to maybe figure out some solutions here how to deal with it.

**Comment by kokoko3k** [comment]
Yes, A lot of shaders, mine included, use 1 element lists to display descriptive texts.

The syntax of the pragma lines is:
parameter parameter-description default min max step, those items are not meant to be selected, indeed.

When using 0 0 0 0 leaks occur, using 0 0 0 1 does not trigger the leak.

The code that handles the list creation does not handle 0 0 0 0 well, it seems.

I'll try to trace what happens, no ETA tho.

**Comment by fishcu** [comment]
> Since it only happens when clicking on the element it definitely has to do with the dropdown list allocation and the range involved (the range could be wrong and unintended for this particular entry in this case I suspect, see third paragraph).

It doesn't just happen when you try to view all values. It also happens when you try to set the value to the "default" value ("start" with default mappings). In that case, no dropdown list allocation should be invoked at all.

This may be a divide by zero error, as the parameter step size in this case is zero. So calculating the number of elements needed (param range divided by param step size) is indeed infinite or NaN, even if the range itself is also zero.

> I suspect the way to solve this though will be pretty hard and long-term.

Why is that? It seems like adding a simple safety check for zero parameter ranges and/or zero step size should solve the issue.


> perhaps some shader authors just took some liberties here with how they made some of these parameters 

The best solution IMO will be to introduce a new `#pragma` that is intended for titles and separators. This usage is extremely common among the shader codebase.
In the same direction, it would be very useful to be able to add docstrings / tooltips to parameters (right shift / "select" with default keybindings) by specifying a longer string / `char[]`.

**Comment by kokoko3k** [comment]
I just pushed a possible fix.
The cause was a "for" loop with the exit condition being influenced by the code inside the loop, and in turn that code was influenced by the step size, leading to infinite menu_entries_append() calls.
