### ISSUE TITLE
(WIN) GLUI issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1696]
GLUI is looking better and better as the default menu driver but there are a few issues that might (or not) be present on other platforms

- Long text strings overlap
- Some shaders produce upside down and squished output when the game is running on the back
- Some shaders make it impossible to see the game running on the back
- Even without a shader set sometimes you just can't see the game running in the back when the menu is showing up
- The highlight on top/bottom should be configurable too
- Wallpaper doesn't change on the fly anymore

**Comment by twinaphex** [comment]
Regarding wallpaper not changing on the fly - it will change on the fly if you start RA with a wallpaper already loaded.

The issues with the game no longer being visible in the background when a shader is loaded seems to be some issue that crept up when me and maister were trying to get GLUI GLES-compatible. It might still be another blending issue probably.

**Comment by Tatsuya79** [comment]
I'd like to be able to modify the vertical spacing between text strings.
It's quite big since mid-April changes.

For the "shader breaks game visibility in the back" I can slightly see the game screen in the "glass effect" there is on the GBA border (a transparent-white gradient) if that can help figuring what's going on.

**Comment by Kivutar** [comment]
The shader issues should be fixed now!
