### ISSUE TITLE
core autodetection when started from the cmdline

### ISSUE THREAD

**Issue by eadmaster** [libretro/RetroArch#1704]
When retroarch is started from the commandline with a ROM file passed as argument is it possible to have the correct core auto-selected?
(like when using "Load Content (Detect Core)" in the RGUI)

**Comment by fr500** [comment]
What if there's more than one usable core?

**Comment by eadmaster** [comment]
in this case the GUI is started and the core selection dialog is shown...

**Comment by AnthraxLeprosyPi** [comment]
Any update on this?

**Comment by fr500** [comment]
its's a feature request, doesn't mean it's gonna be implemented

**Comment by AnthraxLeprosyPi** [comment]
Yeah, I was just curious.

The problem is whenever I looked into some quick old school gaming fun in the last 15 years or so I ended up loosing all my precious time by tinkering with obscure settings and reading hundreds of forum posts before ever starting a game.

So it was just a short glimmer of hope...

best regards
Anthrax

**Comment by RobLoach** [comment]
Duplicate of https://github.com/libretro/RetroArch/issues/746 .
