### ISSUE TITLE
Content appears twice in XMB

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1908]
Content appears twice if you chose a core for it and scan again the directory:

-- Scan a directory with content
-- Chose a core for the content
-- Scan again the directory
-- Take a look at the new list, the previous content will appear twice

RA should delete the previous *.lpl to avoid confusion. Or give the user an option to delete the content in the list.

**Comment by twinaphex** [comment]
A better solution would be if the scanning process would be able to decide if the entry we're about to push already exists, and if so, either update that entry or avoid pushing it again.

However, this would also make the scanning process much slower, so I'm not sure what we will ultimately decide on here.

Just removing the lpl is no solution since that would not make it possible to 'append' stuff to the collection.

**Comment by Kivutar** [comment]
Deleting the .lpl have the good side effect of not letting entries for content that have been removed. But I would still vote for the updating of entries instead, because deleting the .lpl would loose all the core bindings already done.

**Comment by sergiobenrocha2** [comment]
"deleting the .lpl would loose all the core bindings already done."

This could be avoided if there was a "global" config core / smart choice

**Comment by Kivutar** [comment]
I admit I would prefer that core binding to be global... having to set it for each entry require too much effort.

**Comment by Kivutar** [comment]
Would it slow down the scanning process that much if we implemented a dedpuplication during the addition of new entries?

**Comment by fabioxgn** [comment]
I have the same issue I add the content from a usb drive, now I have everything duplicated and half of it doesn't work without the drive.

Is it possible to reset the content list so I can scan again?

**Comment by hizzlekizzle** [comment]
@fabioxgn 
Delete the lpl playlist file and rescan.

**Comment by sergiobenrocha2** [comment]
Fixed 2af0708
