### ISSUE TITLE
XMB Start Content option isn't first in a list (NES playlist)

### ISSUE THREAD

**Issue by Great-Dragon** [libretro/RetroArch#1921]
As per subj it's related to NES only (at least Genesis and SNES is OK). Maybe some other system has the same issue but I don't have a media to test.

![retroarch_bug](https://cloud.githubusercontent.com/assets/12208533/8552720/97b5093e-24e7-11e5-8eb4-b60cdfd9d2e7.PNG)

**Comment by Kivutar** [comment]
And some entries are duplicated. I don't know why it happens on NES.

**Comment by sergiobenrocha2** [comment]
libretro/libretro-database#17

**Comment by sergiobenrocha2** [comment]
@fr500 said will update the dat and build again properly soon (old database, problem with "Super Mario Bros. 2 (USA) (Rev A)")

**Comment by Kivutar** [comment]
I think this is fixed and can be closed.

**Comment by RobLoach** [comment]
* [Our DAT](https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20Nintendo%20Entertainment%20System.dat#L1376-L1380) f599a07e
* [DAT-o-MATIC BattleCity](http://datomatic.no-intro.org/?page=show_record&s=45&n=0215) 7E053E64

Here's a screenshot of 1.3.0....

![nes](https://cloud.githubusercontent.com/assets/25086/11761532/91412f50-a094-11e5-9220-da152c6c80a0.png)

The CRCs are correct in both DATs, since No-Intro and clrmamepro support the header-skip. It runs in FCEUMM just fine.

**Comment by sergiobenrocha2** [comment]
Good catch RobLoach.

Man, this will become unmaintainable...

@twinaphex @Kivutar is it possible to RA skip the first 16 byte to calculate the hash? So we can update the database.

**Comment by sergiobenrocha2** [comment]
I guess it was right before then? --> https://github.com/libretro/libretro-database/commit/95050f6b64c2311fbfdb28789fb9a22923af0049

**Comment by Kivutar** [comment]
I'd like to be sure about what the problem is.

Why our DAT is not the same as DAT-o-Matic? I guess it's because headerless roms won't launch in our cores?

If we use old DATs for NES, I suggest also using an old DAT for the NES developer field.

Adding a special treatment at scanning time for NES roms is certainly possible. If you can come with a simple implementation, I would not vote against it since we are going to have core specific code for FBA and MAME scanning anyway soon or late.

**Comment by sergiobenrocha2** [comment]
Yeah, because the cores does not load headerless roms, even with the xml in system folder. Also, the headerless roms are not very common.

**Comment by sergiobenrocha2** [comment]
CRC is hardcoded in the zip header already :/

**Comment by Kivutar** [comment]
So the only option left is finding a version of https://github.com/libretro/libretro-database/blob/master/metadat/developer/Nintendo%20-%20Nintendo%20Entertainment%20System.dat from 2003, when the CRCs were still corresponding to ROMs with headers.

**Comment by sergiobenrocha2** [comment]
They updated since then... with new good dumps, like Super Mario Bros. 2 and Mega Man 3. Like I said, it'll be unmaintainable.

**Comment by Kivutar** [comment]
What about this thread saying that they are going to add headers back https://www.reddit.com/r/emulation/comments/3f17kc/nointro_nes_roms_dont_work_on_any_of_the_libretro/ ?
