### ISSUE TITLE
[Feature Request] Disable Video/Audio filters option.

### ISSUE THREAD

**Issue by Great-Dragon** [libretro/RetroArch#1930]
It's nice to have those filters on but it's also good to have them off sometimes. And there is no way how they could be turned off in the menu.

The only way I've found is to delete corresponding line in cfg.

**Comment by twinaphex** [comment]
you can press 'Start' on Video Filter/Audio Filter and that will reset them entirely.

**Comment by Great-Dragon** [comment]
Thanks. Definitely it's not something obvious. Help doesn't provide any information about start button functionality.

**Comment by jvook** [comment]
This solution didn't work for me.  Maybe because I have "Start" mapped to the Enter key.  In any case, I just put in some null video and dsp filters as a workaround.  Extract the attached archive to the filters directory and you will have a none.dsp and none.filt in audio and video, which remove the currently set filters.
[null-filters.zip](https://github.com/libretro/RetroArch/files/171288/null-filters.zip)

**Comment by gingerbeardman** [comment]
I would have never figured this out if it wasn't for @twinaphex answer - so thanks!

**Comment by diegomontoya** [comment]
This feature should really mapped to something else, like the select button or delete key value. It really doesn't make much sense for "start" to perform delete.
