### ISSUE TITLE
[Win64] GLUI DPI setting not working

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#1941]
Setting force dpi at 200 on win7 x64:
07-07 nightly= http://postimg.org/image/m7qqf0gut/
07-09 nightly= http://postimg.org/image/ahcsxmo2d/

On 07-09 changing the DPI setting does not work.

Notice how the long names get shortened. 
This was already a recurring issue on every nightly before 07-07 if you changed the DPI to anything under 200. (Strangely only DPI 200 had the full names)

I'd really like to see a lot more lines with full names, smaller fonts and less empty space between each lines. (PC monitor scenario at close range)

**Comment by Kivutar** [comment]
On non mobile, we switched to another behaviour where the dimensions are proportionnal to the window size.

What we can do:
- hide those dpi override options on desktops (but this will not fix your problem)
- instead of testing if we are on mobile or not, we test if we are in fullscreen or not. This way, the dpi settings will work in fullscreen, and the windowed mode will be scaled.

Is this acceptable?

**Comment by Tatsuya79** [comment]
I'm not sure how you can do it code-wise.
I'd like to get something close to older nightlies (2015-04-15): http://postimg.org/image/xydt0946x/full/

I think it would need a new setting to reduce the vertical spacing which is there for touch devices.
It would also need to calculate how long the text can be horizontally to show full names.

**Comment by Tatsuya79** [comment]
I'm closing this as the DPI is working now, thanks for the fix!

...just need some vertical spacing option imo.
On xmb UI as well, seeing just a few lines because of the spacing around the selected entry is a bit annoying. We scroll through long lists all the time here and seeing few lines makes it difficult to navigate.
