### ISSUE TITLE
Multitap not working for NES and SNES

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1965]
Many people reported that the multitap option, even if recognized by the core, is ignored in RA in a way that it is impossible to set the user#3 and user#4 and user#5 to *SNES Joypad*

 * https://www.google.fr/search?q=retroarch+multitap&ie=utf-8&oe=utf-8&gws_rd=cr&ei=J56lVZqMH4KsUc-PgcgP
 * https://github.com/RetroPie/RetroPie-Setup/issues/232
 * https://github.com/libretro/Lakka/issues/184

It happens with all snes cores so far.

**Comment by fr500** [comment]
It works fine with snes9x for me.
Multitap works fine with genplusgx too.

I think we should change the implementation like this:
- Use core options to enable multitap
- Use the controller interface for actual devices

In the future as @Alcaro mentioned in IRC once, maybe it would be better to move multitap, and emulated devices into core options since after all they are core options.

Same for crop overscan even if it's unrelated.

**Comment by Kivutar** [comment]
I noticed the issue with snes9x-next, bsnes-mercury-balanced and pocketsnes, testing with bomberman 5.

Are you able to set the 3rd pad to **SNES Joypad**?

**Comment by fr500** [comment]
These are core issues and should be opened in the respective trackers I guess

**Comment by Kivutar** [comment]
I don't think that those are core issues, since it affects all cores.

Here are more informations: https://www.raspberrypi.org/forums/viewtopic.php?t=31681&p=747137

**Comment by objectchris** [comment]
works fine for me on the raspberry pi (2). 
just use lr-snes9x-next and add the following line to your retroarch.cfg:

'input_libretro_device_p2 = "257"'

(removing input_libretro_device_p2 line if it already exists!)

- this is all explained in the URL your thread links to.

be careful with the quotes - copying and pasting sometimes puts in the angled quotes, rather than the straight ones, if that makes sense.

**Comment by Kivutar** [comment]
You're right, this bug affects specifically snes9x-next with bomberman5.

**Comment by Z4N** [comment]
Still having the issue on Bomberman 5. 
Pad 1 works, 2nd one working as multitap but in game the 2nd pad is linked to player 2, 3, 4...

No issue on Bomberman 3.

**Comment by Kivutar** [comment]
This bug has been fixed long time ago

**Comment by Z4N** [comment]
Well I'm using latest recalbox and it is still impossible to play with more than 2 players on Super Bomberman 5. Working fine for all others up to the 4.

**Comment by hizzlekizzle** [comment]
I just tested this with Snes9x2010 and it worked fine with Bomberman 5. If the problem still affects Recalbox, they must be using a very old build of the core.
