### ISSUE TITLE
[Android] Make it possible to force landscape mode upon launch

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1972]
It can be annoying to always have to enable the `Auto-rotate` feature in Android just to be able to use RetroArch in landscape mode. I think there should be an option to control the orientation straight from RetroArch rather than having to rely on system-wide settings.

**Comment by Zeitwaechter** [comment]
Hey there!

Is there any ETA when this enhancement is arriving?
Could anyone link the specific line?
Or is it already committed and I just can't find it in the settings?

**Comment by hizzlekizzle** [comment]
It hasn't been implemented, no.

**Comment by phcoder** [comment]
Now it can be closed: just go into setting and choose orientation 270

**Comment by seracohw** [comment]
you SIR are a fucking dumbshit for suggesting and directing people to tinker with options and settings that can ruin their devices.

It IS my fault for being stupid enough to listen to you because I should have known better, BUT, when you do not read the question and DO NOT know wtf you are talking about, STFU and stay quite.

I have a dead phone now cause I brainlessly followed your advice.

THANK YOU!

**Comment by phcoder** [comment]
> you SIR are a fucking dumbshit for suggesting and directing people to tinker with options and settings that can ruin their devices.
> 
> It IS my fault for being stupid enough to listen to you because I should have known better, BUT, when you do not read the question and DO NOT know wtf you are talking about, STFU and stay quite.
> 
> I have a dead phone now cause I brainlessly followed your advice.
> 
> THANK YOU!

Retroarch options do not brick your device. At most they can force you to reinstall RetroArch. So you're accusing people for unrelated problems

**Comment by twinaphex** [comment]
@phcoder Dealt with the situation. No need to worry anymore. Sorry for the inconvenience and for not having interfered sooner.
