### ISSUE TITLE
Linux screensaver suspend malfunctioning

### ISSUE THREAD

**Issue by edrex** [libretro/RetroArch#2026]
My experience is that that the Linux screensaver suspension doesn't work properly.

**Observed behavior:** Display is prevented from blanking, but the screen still fades to black and is locked after 10 minutes when running Retroarch. Additionally, after quiting Retroarch, display blanking is still disabled (I have to run `xset dpms 300` to restore).

**Expected behavior:** Display blanking / screen locking is "suspended" (poor choice of term there) while I am running Retroarch, and is restored when I quit Retroarch.

**Setup:** Retroarch (git) under Gnome 3 Shell on Arch Linux with Gnome set to suspend the display and lock the screen after 5 minutes of inactivity.

More investigation is needed. It's possible that this is a bug in some other package such as Gnome Screensaver itself. I'll follow up with more info and hopefully a recommendation.

## Related issues

 * #30, #33
 * #1349

**Comment by edrex** [comment]
The dbus interface (which I think `xdg-screensaver` calls, seems sensible for RA to avoid the lib dep and just use the cmdline interface):

- http://standards.freedesktop.org/idle-inhibit-spec/latest/re01.html
- https://people.gnome.org/~mccann/gnome-screensaver/docs/gnome-screensaver.html#gs-method-Inhibit

**Comment by Ram-Z** [comment]
Can confirm using `xautolock`, screen will turn off after set amount of time.

```sh
xautolock -detectsleep \
          -notify  600 -notifier "xset dpms force off" \
          -time     20 -locker   "i3lock -nc 000000" \
          -killtime 70 -killer   "systemctl suspend" 
```

**Comment by hadess** [comment]
Using the org.freedesktop.ScreenSaver D-Bus interface is definitely preferred, it will work on both GNOME and KDE. Do *not* use the org.gnome.ScreenSaver interface, it's deprecated, and an implementation detail.

Please try not to use xdg-screensaver either, it's an utter piece of junk.

**Comment by nguillaumin** [comment]
Here's an example with `dbus-send`, seems to work for me:

```
$ dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call --print-reply /ScreenSaver org.freedesktop.ScreenSaver.Inhibit string:"RetroArch" string:"Playing game"
method return time=1473117960.304007 sender=:1.31 -> destination=:1.231 serial=306 reply_serial=2
   uint32 117063356
```

Un-inhibiting with the previously returned cookie:

```
dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call --print-reply /ScreenSaver org.freedesktop.ScreenSaver.UnInhibit uint32:117063356
method return time=1473117973.417980 sender=:1.31 -> destination=:1.232 serial=311 reply_serial=2
```

I could have a look at implementing this since it annoys me enough, but I wouldn't know where to start... Could someone give me a few pointers in which file that should be implemented? I'm a bit confused between the "drivers" and the "drivers context".

Also that would add a dependency to DBus, would that be acceptable?

**Comment by hadess** [comment]
SDL has a barebones implementation that dlopen()'s the dbus shared library that you might be able to use to avoid a hard dependency on D-Bus. FWIW, a GLib dependency would certainly be easier, and using GDBus.

**Comment by nguillaumin** [comment]
Thanks for that, actually it seems SDL2 directly has [DBus helper functions to inhibit the screensaver](http://code.metager.de/source/xref/SDL/2.0/src/core/linux/SDL_dbus.c#172), so that looks promising.

**Comment by nguillaumin** [comment]
Actually, even simpler: https://wiki.libsdl.org/SDL_DisableScreenSaver

https://wiki.libsdl.org/FAQUsingSDL#Why_does_SDL_disable_my_screensaver_by_default.3F seems to say it's supposed to happen by default, so not sure what the story is...

SDL 1.x also supports similar behaviour (but via `XResetScreenSaver` rather than DBus), so in practice with SDL 1.x or 2.x the screensaver should *already* be disabled. Odd.

**Comment by nguillaumin** [comment]
@t-paul indicates in #3547 that `xdg-screensaver` works for him on Gnome 3 + Debian testing, however I can't get it to work (on Arch).

@t-paul: what's the command you're using? I'm using something like `xdg-screensaver suspend 0x1E00006` where `0x1E00006` is the ID of a window I got with `xdotool getmouselocation`.

**Comment by t-paul** [comment]
This shows what's actually executed. For me that's basically a short inline Perl script calling `org.gnome.SessionManager` via DBus. (Using an already running `xlogo` as reference window)
```
bash -x /usr/bin/xdg-screensaver suspend $(xwininfo -name xlogo | grep ^x | awk '{ print $4 }')
```

Snipped from that output:
```
# Inhibit idle detection (flags = 8) with window name and ID.
# We have no reason so just send the window name again.
my $bus = Net::DBus->session();
my $sm_svc = $bus->get_service("org.gnome.SessionManager");
my $sm = $sm_svc->get_object("/org/gnome/SessionManager",
			     "org.gnome.SessionManager");
$sm->Inhibit($window_name, hex($window_id), $window_name, 8);
```

Just for completeness, this is with Debian/testing and:
```
xdg-utils: Installed: 1.1.1-1
gnome-shell: Installed: 3.20.3-1+b1
gnome-screensaver: Installed: 3.6.1-7+b1
```

**Comment by nguillaumin** [comment]
Hm, that's interesting, I actually don't have `gnome-screensaver` installed at all, so it seems it's the power management features that kicks in? That being said, I just tried on a Debian Testing VM which doesn't have `gnome-screensaver` installed neither (doesn't seem to be installed with the base install), and it still works.

What are you power management settings set to? Mine are set to blank screen after 5mn.

I have the same version of `xdg-utils`, and you'd think that by going through the session manager (rather than the screensaver) it would also inhibit power savings... Weird.

**Comment by ProfessorKaos64** [comment]
suspend screensaver also does not work for me on Arch Linux, Cinnamon Desktop, xdg-utils installed (which provides xdg-screensaver):

```
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [WARN] :: Could not suspend screen saver.
```

**Comment by t-paul** [comment]
@ProfessorKaos64 try running the example using `xlogo` I posted and paste the full output?

**Comment by lucidmachine** [comment]
@ProfessorKaos64 FYI, xdg-screensaver hasn't released since adding Cinnamon support. See: https://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=066b46418f454c0b7e1b5e1478f5f94d91276c14

**Comment by ProfessorKaos64** [comment]
@lucidmachine , hmm wonder if anything can be compiled to add that. I'll check that out soon, thank you.

```
mikeyd@archboxmtd ~  $ xlogo
xlogo may be found in the following packages:
  extra/xorg-xlogo 1.0.4-2	/usr/bin/xlogo
```

**Comment by hadess** [comment]
@twinaphex I commented on a few things in the commit itself, let me know if that's the way you want feedback. Rest of the patch looks good.

**Comment by nguillaumin** [comment]
This issue needs to be re-opened, since #3588 disables DBus support by default (a bit sneakily by @orbea  I must mention since no mention of this issue was made in the PR, I only saw it because I still had the problem with the latest master version).

This DBus issue solves a real problem for users, and while I understand some people may not want the DBus dependency (but in that case, why have the lib on your system at all?) and agree it should be disablable, I think it should be enabled by default (Set to `auto` in `config.params.sh`). One could argue other people doesn't want `xdg-screensaver` for various reasons, but that doesn't mean it should be disabled by default.

I don't think we can really say one method is better over the other, there are arguments for and against both, so I believe doing both by default is a reasonable compromise, not sure who can make the final decision @twinaphex ?
