### ISSUE TITLE
(Menu) Alternative Scanning Method

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#2033]
Many users complain that their content checksum are missing in our database. So we could have an alternative scanning method where we first select the system (for example Nintendo 64) and then select a folder, and generate a playlist.

We can also have an hybrid scanning, where we provide a system and a folder, checksums are checked, and if the content have no matching checksum but matches the extension, the filename is still added to the playlist.

**Comment by kurumushi** [comment]
It might be possible also to have a less accurate scan, where file names are matched instead of checksums. This would still require users to have the files named properly, but then at least they wouldn't need to have the exact version of the rom.

**Comment by SwedishGojira** [comment]
Or if we could just use playlists and ignore the database. As it is now we can not add any fan-translations to the content lists easily, and that is my major use for RetroArch. I tried adding them manually, but I can not start them since they don't match anything in the database :(

**Comment by Kivutar** [comment]
Ah, this is a real problem :(

**Comment by garnieretienne** [comment]
+1 for two scanning systems: database based and folder based.

Why a database based system? 
----------------------------------------

Some emulators require roms from a specific romset to work. I'm thinking of Arcade systems (Mame and Final Burn Alpha).

I don't known how people obtain their roms, but in every romsets I've obtained (NoIntro, Mame, Redump, etc...) a DAT is given with basic rom info in it (at least the name and the CRC). I think these DAT files are build in the clrmamepro format (or romvault). We can build a tool to convert these DAT files in the specific format used by retroarch (which is the same used in openEmu I think?). I could work on a script to do that if you are interested.

A database can also support additional info that could be used later in the lakka UI (years of the game, covers, etc...).

Why a folder based system?
------------------------------------

Some roms (custom, homebrew, translated) are not present in common romset or tracked by any group. Some people do not download any romset, they just download their roms from various sources or even could dump their roms themself. 

As the minimum for building a playlist is the name of the game, a simple system as you described (extracting the name of the rom from the file name in a folder dedicated to one playlist/system) could be the solution for this.

Maybe the 'Add content' should be more Playlist oriented
------------------------------------------------------------------------

* Create a new Playlist
  * No Metadata
  * Extract Metadata From Database
* Add an entry to an existing playlist from a file
  * Playlist 1
      * No Metadata
      * Extract Metadata From Database    
  * Playlist 2
  * ...
* Remove an entry from an existing Playlist

**Comment by blackman91** [comment]
I second the folder based system, the ability to add any rom to the game system tabs would be perfect and would make the feature easier to the average user and would make retroarch more known.

**Comment by lollo78** [comment]
Hi to all!
See a wonderfull project like Retroarch remain incomplete (and castrated) for issues like this... it's really so sad.
I really love Retrogaming (and I really love Retroarch), but playing to a Magnavox Odyssey 2 roms is not exatcly the same thing of playing an Arcade rom (Mame and FBA). 
I think too that find a solution to the actual issues, like to give all the users the possibility to scan arcade games directly inside Retroarch, is more important that add new features. A really working arcade section, could attract many other user on Retroach: we know that mame/fba are between the most platforms required by the users... 
So, at least for mame/fba, try to include an alternative scanning method, or a workaround waiting a major fix.
To all devs: please do it as soon as possible.
Life is short :D

@kivutar: if this is not the right post... I could copy/paste in the right place. Tell me only where :smile:

**Comment by fr500** [comment]
I don't see how it makes RetroArch castrated. I agree it makes the rom scanner incomplete but I don't see the big deal.
It's something important for sure, but it's not a critical problem.
Just my opinion though.

**Comment by Kivutar** [comment]
Yeah, it doesn't prevent to launch roms. But from an end user point of view, in lakka, where playlists are the primary way to launch a game, it does look incomplete.

I will try to modify the scanning code to support arcade roms. What about checking the sums of every rom in the zip? We don't need to calculate the crc32, since those are already in the zip header. We loop over rom entries in the game entry in the db, and compare it to all the sums in the zip header. With a counter, if all match, we add the game to the playlist.

**Comment by fr500** [comment]
I think the first order of business it to check how the mame/fba datfiles work, then come out with something that adapts to that.

It is in fact quite complex, mame dats for instance might tell you the romset is incomplete since the neogeo bios roms are missing (but they are storeed in another file)

**Comment by lollo78** [comment]
Hi fr500, of course mine was only a provocation.
Like described from Kivutar, I think that the focus is always for the "user point of view". 
Not all the people have great skills, so... if something does not work as expected end up immediately in the garbage. And this is an huge pity if happens to Retroarch, considering the immense effort of all you, guys.
My flame was: "before to add new (and great) features, maybe it's more important to stabilyze and improve the existent ones. When you have a solid base, you can edify what you want.

**Comment by RobLoach** [comment]
Currently, under "Add Content", there is "Scan Directory", "Scan File", and "Download Content". **Scan Directory** will:

1. Search the *given directory*
2. Look at the checksum of each file
3. Add the file to the associated core for the checksum

Perhaps adding a new option to **Add Directory to Core**, which takes two options:

1. User chooses which *Core to Use*
2. User chooses which *Directory to Scan*
3. Scan through the directory, making each file associated with the given core

**Comment by Kivutar** [comment]
That's not a bad idea.

**Comment by lollo78** [comment]
I really appreciated the new fa alpha scan included into the new retroarch. THX
But how the system does it? Cold be done for mame? There is an active discussion about mame scan?

**Comment by Kivutar** [comment]
It can be done for MAME too. All we need to do, is generating a new DAT from a MAME ROMset. Using the CRC of the zip itself, instead of the CRCs of the files contained in the zip.

But I scare that if we maintain both database, scanning an arcade ROM will end up being associated with MAME instead of FBA, or vice versa.

**Comment by cudencuden** [comment]
just fyi about mame, don't get the merged romset because those are the 7z ones.

**Comment by lollo78** [comment]
Hi guys, I need an advice.
I'm tried to create a .dat file for mame2003 (romset 0.78) with clrmamepro.
I created it, but I'm unable to do something like you have done for FBA.

FBA: in name you show the game name and not the archive name; only one CRC calculated on ZIP file (and not a tons of CRC calculated on the archive content). 
```
game (
	name "Bubble Bobble (Japan, Ver 0.1)"
	releaseyear "1986"
	publisher "Taito Corporation"
	rom ( name "bublbobl.zip" crc 4fea6af9 )
)
```

This is the best that I've reached with clrmamepro:
```
game (
	name 1941j
	description "1941 - Counter Attack (Japan)"
	year 1990
	manufacturer Capcom
	cloneof 1941
	romof 1941
	rom ( name 4136.bin size 131072 crc 7fbd42ab sha1 4e52a599e3099bf3cccabb89152c69f216fde79e )
	rom ( name 4137.bin size 131072 crc c6464b0b sha1 abef422d891d32334a858d49599f1ef7cf0db45d )
	rom ( name 4142.bin size 131072 crc c7781f89 sha1 7e99c433de0c903791ae153a3cc8632042b0a90d )
	rom ( name 4143.bin size 131072 crc 440fc0b5 sha1 e725535533c25a2c80a45a2200bbfd0dcda5ed97 )
	rom ( name 41_09.rom merge 41_09.rom size 65536 crc 0f9d8527 sha1 3a00dd5772f38081fde11d8d61ba467379e2a636 )
	rom ( name 41_18.rom merge 41_18.rom size 131072 crc d1f15aeb sha1 88089383f2d54fc97026a67f067d448eee5bd0c2 )
	rom ( name 41_19.rom merge 41_19.rom size 131072 crc 15aec3a6 sha1 8153c03aba005bab62bf0e8b3d15ec1c346326fd )
	rom ( name 41_32.rom merge 41_32.rom size 524288 crc 4e9648ca sha1 d8e67e6e3a6dc79053e4f56cfd83431385ea7611 )
	rom ( name 41_gfx1.rom merge 41_gfx1.rom size 524288 crc ff77985a sha1 7e08df3a829bf9617470a46c79b713d4d9ebacae )
	rom ( name 41_gfx3.rom merge 41_gfx3.rom size 524288 crc 983be58f sha1 83a4decdd775f859240771269b8af3a5981b244c )
	rom ( name 41_gfx5.rom merge 41_gfx5.rom size 524288 crc 01d1cb11 sha1 621e5377d1aaa9f7270d85bea1bdeef6721cdd05 )
	rom ( name 41_gfx7.rom merge 41_gfx7.rom size 524288 crc aeaa3509 sha1 6124ef06d9dfdd879181856bd49853f1800c3b87 )
)

```

I'm using the wrong tool?

**Comment by Kivutar** [comment]
I think that having all those RDB will result in a scanning bug. The scanning process stops when the game matches an rdb entry. Since those RDB have a lot of checksums in common, you would end up with 4 incomplete playlists when you scan one single romset.

**Comment by lollo78** [comment]
I always put my roms in dedicated folders (one for Atari2600, one for SNES, one for FBA and so on) and performed scanning on each single directory. With this approach I never had issues. But I have to try whats happens with 3 different MAME databases.

If you wanna preserve only one MAME.rdb, I think that we have to concentrate our efforts only on MAME2003, considering that this is the best MAME core available on Retroarch.

I tested my MAME commits (https://github.com/lollo78/libretro-database/commits) and seems that works fine. I need only to remove BIOS entries and correct some invalid filesystem characters in game names.

**Comment by Kivutar** [comment]
Why MAME 2003 is the best core?

Have you tried to scan FBA roms while your MAME databases are here? I know that some roms have the same checksums, and will appear in mame and not in fba..

**Comment by lollo78** [comment]
mame4all use a very old romset (with few games).
Mame2010 could be the best solution (it's based on a more updated romeset), but for what I remember is weighty and unstable (needs another work from developers?).
Mame2003 is really rock solid (in my experience: Rpi2/Rpi3) and a good compromise (for now) between stability and romset (0.78 is better than 0.37b5, but worst compared to 0.139u4).

I have a FBA playlist in my Retroarch, and after scanning with my MAME.rdb I don't notice strange things. 
Of course I scanned 2 full romset of more than 4000 games each one and do a manually check or counting it... it's so difficult.
This request could help a lot at least for a quick control if all the games are scanned.
https://github.com/libretro/Lakka/issues/263

**Comment by lollo78** [comment]
o_O
I just discovered this:
https://github.com/libretro/mame2014-libretro/issues
and this: 
https://github.com/libretro/Mame (it's not a libretro core, but a standalone application right?)

Now I'm really confused. How many other mame libretro porting exist?
Why seems that the more developed is Mame2003 that, respect Mame2010 and Mame2014, use an old romset?

**Comment by dankcushions** [comment]
@lollo78 because some systems (raspberry pi, etc) cannot handle the more recent mame cores - the emulation is more accurate and the games are more recent so the system requirements are far higher. that's why i personally prefer mame2003 for me needs, anyway.

i believe https://github.com/libretro/Mame (current mame) is well suppported, though

**Comment by lollo78** [comment]
So, https://github.com/libretro/Mame is always a core like all the others?
And it works on Rpi?

**Comment by dankcushions** [comment]
re-read my comment

**Comment by lollo78** [comment]
OK :dancer:

About FB Alpha v0.2.97.38: I created a new and updated .dat/.rdb. But I can't release it because the complete set that I found (the only one available all over the Web?) had clones merged to parents. So it's not good for CRC. :(
Sorry

**Comment by markwkidd** [comment]
What about a second mode for the ROM scanner. Step 1 is to select a folder, and step 2 is to select the database file it should be checked against.

Most users are probably already putting their ROMs into subfolders based on the name of the emulated system. They will know what system's database the ROMs should be checked against, because they had to seek it out in order to reach this point in configuring the emulator anyway.

Step 1) 'Select a ROM folder' ---> MAME 2014 ---> 'scan this folder'
Step 2) Select a ROM database' ---> MAME 2014 (ProgettoSNAPS MAME 0.159 Non-Merged) ---> confirm.

Thumbnail packs for 'alternate' systems or systems with likely CRC32 conflicts could have similarly descriptive filenames in the RetroArch frontend downloader.

**Comment by pralima87** [comment]
Was looking around why my roms list is so incomplete and found this issue! 
Any news on this folder-to-system scan?
Right now PBP files are not recognized and a lot of roms are left out of the list :/

**Comment by i30817** [comment]
Personally, i believe it's not retroarch bussiness to be a inferior and less featureful romcenter. I guess it's true that certain emulators will bug out or fail at loading roms that are outdated dumps or not on their database, but that isn't really the front end job to prevent IMO.

Saying that, there is a nice compromise. If you'd add a setting and a GUI indicator (say a green dot or or even just a green console symbol to the red of the ones unrecognized, you could have a easy indicator that the rom could be outdated or bad and still show everyone of them.

**Comment by Kivutar** [comment]
I'm going to try to implement it as @RobLoach proposed.

**Comment by i30817** [comment]
A good option for organized people.

**Comment by barbudreadmon** [comment]
On top of @RobLoach's suggestion, i would add a way to ignore crc/sha1 and only rely on filename when scanning, it would be awesome for scanning arcade romset (it would solve both the split/merged/non-merged issue and the non-torrentzipped issue)

**Comment by RobLoach** [comment]
Building off of https://github.com/libretro/RetroArch/issues/2033#issuecomment-190310220 to make it a bit simpler for us...

1. User selects choose *Import Content* -> *Add Directory*
1. User chooses which directory to add
1. RetroArch creates a Playlist by the name of the selected directory
1. User must then visit Settings -> Playlists and choose the core associated with the playlist manually

**Comment by Kivutar** [comment]
This look simple enough to implement.

**Comment by markwkidd** [comment]
@RobLoach and @Kivutar , [the latest post from RobLoach](https://github.com/libretro/RetroArch/issues/2033#issuecomment-310947634) seems like an elegant solution.

Do you think that can be the specifications for the new scanning method moving forward? Is there any other consensus to build in order to adopt that as the goal?

**Comment by RobLoach** [comment]
One problem with the suggested above is that it may or may not work with zipped sets. We need the CRC information in there so that netplay would work.

**Comment by i30817** [comment]
Is it my impression or scanning got even more broken recently? I already mentioned the '.' bug but right now if i scan a dir everwhere i get a flash of something too fast to read on the notifications but which definitely includes the word 'null' and then 'scanning of directory finished' and nothing added.

**Comment by markwkidd** [comment]
@RobLoach is that not just one more (sub)step?

The existing playlist scanner already has the ability to check CRC against the databases, so wouldn't this be a matter of calculating CRC and writing it to the playlist rather than comparing against the RDB?

1. User selects `Import Content`  -> `Add Directory`
2. User chooses which directory to scan ("SNES Hacks")
3. RetroArch calculates the CRC of non-ZIP ROMs, or uses the ZIP manifest to determine the CRC of zipped files
3. RetroArch creates a Playlist called "SNES Hacks.lpl"
4. User enters the `Settings` -> `Playlists` menu and manually chooses the core associated with the playlist

**Comment by yenic** [comment]
This is the script I use to work around RetroArch in this regard. https://www.reddit.com/r/RetroArch/comments/43dj1n/playlist_creator_for_retroarch_on_windows/ It works very well. If you could just duplicate what it does as an option that would be enough.

**Comment by markwkidd** [comment]
**Two Approaches**
Note that I'm assuming that the new arcade databases are going to address the needs of arcade emulators, so that doesn't need to be taken into account by the Alternative system. I think there are only two major proposals out there. Am I right about that?

**Proposal A: Add a new, filename-only scanner**. This mode exists in addition to the database-based playlist scanner.
1. User selects `Import Content`  -> `Add Directory`
2. User chooses which directory to scan. Let's say the directory is called "SNES Homebrews"
3. RetroArch calculates the CRC of non-ZIP ROMs, or uses the ZIP manifest to determine the CRC of zipped files
3. RetroArch creates a Playlist called "SNES Homebrews.lpl" that includes the CRCs
4. User enters the `Settings` -> `Playlists` menu and manually chooses the core to associate with the playlist

**Proposal B: Implement one unified, hybrid scanner**.
1. User selects `Import Content`  -> `Add Directory`
2. User chooses which directory to scan. Let's say the directory is called "SNES Homebrews"
3. RetroArch calculates the CRC of non-ZIP ROMs, or uses the ZIP manifest to determine the CRC of zipped files
3a. ROMs that match the RA database get named in the playlist with their 'correct' names
3b. Only ROMs which do not match any database are named by their filename, with their CRC calculated and added to the playlist.
3. RetroArch creates a Playlist called "SNES Homebrews.lpl" that includes the CRCs
4. User enters the `Settings` -> `Playlists` menu and manually chooses the core to associate with the playlist

**Comment by i30817** [comment]
I have another idea that is more radical (it would need the user to use a utility to rename hack files.

Currently i'm creating Dats for the libretro-database project by just having the hacked games and a pointer to the version and romhacking page (if it exists) and [rhdndat](https://github.com/i30817/rhdndat)

This creates entries like this for hacks and translations respectively:```

game (
    name "Castlevania: Symphony of the Night - Quality hack [Hack by paul_met]"
    description "Castlevania: Symphony of the Night - Quality hack hack by paul_met version (1.2)"
    rom ( name "Castlevania - Symphony of the Night (USA) (Track 1).bin" size 538655040 crc 0431c247 md5 6674f4a75ea11fd9422669f247ec27fd sha1 1fa7cd542e15f9ce281e83320eedd24daace79e8 )
    comment "http://www.romhacking.net/hacks/3606/"
)
game (
    name "Yutona Eiyuu Senki - TearRingSaga (Japan) [T-En by Aethin]"
    description "English translation by Aethin version (1.04)"
    rom ( name "Tear Ring Saga (Japan).bin" size 594054048 crc ca9bf988 md5 7f67daa021705a01ce322aa47edd1695 sha1 17066296885b81dc7511597c002fa867b4f178d3 )
    comment "http://www.romhacking.net/translations/2812/"
)
```

Currently retroarch is transitioning to serials when using cdrom games when possible (they're much faster to 'check' although a serial isn't actually a checksum, i approve in general because i never thought it was RA job to check integrity).

However this falls down for hacks and different versions of the same game because not using a checksum for the 'actual' game file (the bin) introduces false positives.

A way to avoid this would be to to use names, *if the names could be assured to be unique and correct*.

I'm thinking for all cd based games that adding a new field to be used in combination with 'name':
```
game (
...
    name "Castlevania: Symphony of the Night - Quality hack [Hack by paul_met]"
    index ( filetype "cue" size whatever crc whatever md5 whatever sha1 whatever )
...
)
```

Then to recognize a game, RA would always 'salt' the index file filename onto the serial or index name
ie: checksum(cue file) + checksum(cue filename).

This is not as radical as it seems if retroarch is already using serials (which are not unique remember) because cue and gdi files already have the other filenames inside them so the cue file filename is most likely the correct one from the dumping group because if one of the others was changed RA wouldn't recognize the file without editing the cues.

I don't want to change the 'rom' in order to point to the index cue or gdi file itself because that checksum is *not* the checksum of the hack, which is what actually uniquely identifies the disc and that is important info for if we want full verification.

Then retroarch or even i could do a simple tool that takes those dats, checks the 'roms' and renames a collection 'index files' (and only them, because remember, index files refer to the other track files filenames ). This would require users to recreate m3u files but it also means that RA could use 'filename+cue crc32' or 'filename+serial' (if i added a 'parse serial' functionality to rhdndat) to identify all games which would make scanning much faster after a single mass rename (that wouldn't even change redump files, just cd-type hacks).

**Comment by i30817** [comment]
BTW the 'serial' in my example above could be any kind of string. For instance, for chdv5 it's probably better if the 'serial' is the internal sha1sum on the header that uniquely identifies a dump not the actual console 'serial' per-se.

Therefore it probably should be renamed 'id' or something...

**Comment by rszasz** [comment]
Would adding the libretro-db tools to the build cycle be a possible stopgap? For those of us who are on windows systems, and have a rom manager, it would be nice be able to look inside or create rdb files (in my case I would like to use the DAT I already made for my playstation backups in pbp format)

I guess I could use a linux VM or a posix build environment to do it, but it would be nice to just have the tools built when changes/fixes are made.

**Comment by RobLoach** [comment]
I've used the [RetroArch Playlist Editor](https://www.marcrobledo.com/retroarch-playlist-editor/) as an online tool to build playlists. Best solution would be to have it part of RetroArch itself rather than an external tool.

**Comment by i30817** [comment]
The important part of the Playlist for RA is the connection between the games and the metadata. Often times a hashcode _is_ the metadata necessary, for example for netplay matchmaking.

Just having something that rubberstamps whatever content the user has on disk is not applicable to get metadata working.

**Comment by rszasz** [comment]
Assuming getting netplay working is secondary (people making sure they use the same rdb file to import roms would solve that, and would be an advanced method most would never use) would making a standard .dat file from a rom manager, importing it with the db tools to form a rdb file, and placing the file in the correct place in the retroarch install allow retroarch to identify the roms?

**Comment by RobLoach** [comment]
Feel free to submit DAT changes to [libretro-database](https://github.com/libretro/libretro-database) as well. There are a few non-standard additions in there. Check the hacks folder.

**Comment by QuaiGoner** [comment]
Any progress on that issue? RA would become somewhat open-sourse alternative to frontends like LaunchBox

**Comment by diegopau** [comment]
I am very new to RetroArch and have little knowledge about the internal works of it. I am using Retroarch in a Playstation Classic (Retroboot). I think I can be considered the "regular user" so I wanted to share my experience with this issue:

When I first tried Retroarch I moved my collection of Mega Drive roms to a "megadrive" folder and then I used the Scan Folder functionality inside Retroarch. Honestly I expected this to just work since all the roms are either .gen, .md, .smd or a zip file with the rom in any of those formats and all I wanted is have them on a playlist that can be quickly accessed. After scanning them I found out that around half of the games where there, the other half not. 
My reaction to this was to take a look to the folder structure and try to match the folder names of thumbnails, playlists, roms folder. This time i was really convinced I understood what the problem was, I even renamed a few name files to match the thumbnail names. I thought: if all the folders have the same name, Retroarch will already know that these are Mega Drive files because I am matching the name "Sega - Mega Drive - Genesis" everywhere, and the thumbnails have same name as the files... this has to work.

After another scan the problem was still there. I could see some thumbnails now, but big part of the roms were not there. Those roms come from different sources across time, some are hacks and translations, all or at least most worked always with different emulators.
I then found out about how Retroarch is trying to match every single file to a database and if it doesn't the game it is not added. It was a disappointment, I tried to see the database file but it doesn't seem to be in plain text. I gave up. My father was also struggling with the same thing when adding his ZX Spectrum games, some that he programmed himself decades ago.
Yes you an always manually load a game and add it to favorites, but it is not the same, what we love about Retroarch is precisely that feeling of having your full collection there, tidy, with playlists and thumbnails, and right now it is only possible with lots of manual editing to manually build playlists to basically bypass Retroach's way of doing things.

Another problem I see with not having an option of building playlists bypassing the database matching is that it really takes a huge amount of time in some cases, and if you have a big collection and you just added one new game it seems like it would try to match it all again, sometimes that means hours of leaving there the Playstation Classic working on it. For some people like me we wish to just add the games in a basis of 1 entry per file or 1 entry per subfolder, and skip completely any match against a database. Then the thumbnails just have to match the filename, which is much easier to understand for the average user in my opinion than trying to understand what specific ROM you have to get (if you can) so it is accepted or to manually edit playlists (I actually tried and I wasn't successful with that).

I just wanted to share my point of view as a new user. Maybe many of the things I comment here or suggest comes from too much ignorance about how it should work and they are just not possible. Thank you for reading. And big thanks for Retroarch!

**Comment by hizzlekizzle** [comment]
@QuaiGoner You can bypass the database scanners via the desktop menu (F5).

**Comment by thericeking** [comment]
Please make this feature exactly like OP said "first select the system (for example Nintendo 64) and then select a folder, and generate a playlist."
I added $10 to the bounty. I wish I could give more. That's how bad I want this alternative scanner added.

**Comment by desperateCoder** [comment]
i'd love this feature as well! select a folder and a system. that would be great!

**Comment by therealmaxmoon** [comment]
I've found a [custom script](https://www.reddit.com/r/emulation/comments/3imlri/i_wrote_a_batch_script_to_add_unsupported_roms_to/), which will add local roms to the database, but it is written in Batch (Windows). 

Does anyone have a Bash script for Linux, which does the same or if it is in Python, it would be even better.

Redownloading all the roms would be very annoying, because after the 10th download, it still could be the "wrong" rom.

Is there any progress or workaround for this issue, because it's almost 5 years old.

**Comment by i30817** [comment]
This feature already exists now, it's just not 'streamlined' like the op wanted. It's called 'manual scan'

**Comment by RobLoach** [comment]
Yup....
![Screenshot at 2020-03-11 11-38-06](https://user-images.githubusercontent.com/25086/76435841-e9aa1d80-638d-11ea-9162-46d9ddc42d5a.png)
