### ISSUE TITLE
tarball should not have prebuilt files

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2052]
Is it possible to exclude these prebuilt files? I sent the debian packaging to mentors, and I received some feedback about it. The lintian warnings:

source-contains-prebuilt-java-object:
* android/phoenix/libs/googleplay/libs/google-play-services.jar
* android/phoenix/libs/appcompat/libs/android-support-v7-appcompat.jar
* android/phoenix/libs/appcompat/libs/android-support-v4.jar

source-contains-prebuilt-javascript-object:
* emscripten/browserfs.min.js

http://mentors.debian.net/package/retroarch
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792608

**Comment by twinaphex** [comment]
I'll try and see if I can get rid of android-support-v7-appcompat.jar and android-support-v4.jar. However, getting rid of google-play-services.jar might not be possible.

Same maybe for browserfs.min.js since the Emscripten port depends on it. I'd have to check if it's possible to do it another way.

**Comment by twinaphex** [comment]
I got rid of android/phoenix/libs/appcompat now at least.

I don't think I can get rid of the googleplay libs. Unless I want to bake it out of the Android port altogether but then we would exclude location API support hooks for the libretro API. 

Regarding emscripten/browserfs.min.js - I'd have to look at what the reasoning was for including it like that.
