### ISSUE TITLE
[Feature Request] Hide Cursor when using an overlay

### ISSUE THREAD

**Issue by ochief** [libretro/RetroArch#2056]
If using an overlay as opposed to a shader/nothing when you load a game you see the mouse cursor regardless of whether or not you have moved the mouse.

I don't believe there are any options to hide this, although pressing F11 does remove the cursor.

Can whatever is stopping it from being shown in the menus etc. be applied to when using a overlay?

**Comment by fr500** [comment]
I see the problem but can you clarify this:
    Can whatever is stopping it from being shown in the menus etc. be applied to when using a overlay?

**Comment by Stu1983** [comment]
Just noticed this myself. It seems more like a bug that an enhancement.
There seems to be 2 cursors. There is the RetroArch 'skinned' cursor that appears on top of the system cursor.
When you enable an overlay it seems to auto enable mouse and touch support. I'm using a joypad only so don't require to see the mouse. My overlay is simply an old tv border to fill the black borders on sides of the 16:9 monitor.
I go back in to menu settings to disable the mouse and touch, this hides the 'skinned' cursor in the main menu but the system cursor is still there while in game and the overlay is shown... makes using the overlay for this purpose pointless.
Another way to show this is, keep mouse and touch disabled so you have no visible mouse in the main menu.
Now in the overlay menu set "Hide overlay in menu" to off. You will see the overlay and also see the system cursor rather than the 'skinned' cursor in the main menu.

**Comment by RagnaStrife** [comment]
I was going to open an issue on this but I'm glad this was brought before (yet worried it's still not fixed).

So, is there news on this?
It's bugging me a lot since I use it for a very light scanline effect on top of other shaders,
and I can't seem to reproduce this specific combination using classic scanline shaders.

At least the F11 key works but I must go to use keyboard again anytime I change from
game to game... so it sucks a bit.

Any chance you could put in an option for disabling system mouse cursor when overlays are used?
Though it seems more like this issue is a bug.

Thank you.

**Comment by Firefoxian** [comment]
input_overlay_show_mouse_cursor = "false"
