### ISSUE TITLE
Savestate/Savefile sorting not working for all the cores that have needs_fullpath

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2113]
As it turns out, when retro_set_environment is called the "new" save location is still not set, it's correctly set when retro_init is run so I guess this change has to happen earlier.

**Comment by ProfessorKaos64** [comment]
Is this similar to the issue I am experiencing?

I found that I can save state fine with a fresh game, no saves, using a button, but loading fails. If I use the overlay, save and load work perfect. Is this due to the default save slot not being set? After the initial overlay save/load, I can use the gamepad state save/load just fine

**Comment by fr500** [comment]
no it's not related at all, this is only an issue for very specific cores that don't implement the correct interfaces

**Comment by fr500** [comment]
I think I fixed this, and I made the feature and I reported it so I'm closing it.

**Comment by ProfessorKaos64** [comment]
@fr500 , thank you very much for getting back to this.
