### ISSUE TITLE
[iOS CocoaTouch] Core updater

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2157]
Click on core updater, and nothing happens.

But if you scroll, the entries will show up.

**Comment by twinaphex** [comment]
I have somewhat of a workaround/hack here -

https://github.com/libretro/RetroArch/commit/e133df155d715c4638e2bf28c8896976b8861852

The problem is that the CocoaTouch UITableView is an event-driven UI. This means that the main loop observer only keeps running when we do an UI interaction, such as scrolling/dragging, clicking on an entry, etc, but it will eventually stop calling this loop observer after the UI determines no event is taking place.

This is a problem for us as our main data runloop is being called from our main observer loop. What we do now instead is immediately after pressing something, we check if there have been any new tasks added to the data runloop or if there are still existing ones that have yet to be handled. If so, then we iterate 32 times over rarch_main_data_Iterate() to make sure that data runloop tasks have been processed before the menu entry operation finishes.

Very hackish, bug-prone and ugly, but looks like it might work for now. I'm not happy about it though and a more fundamental solution should be arrived at in due time.
