### ISSUE TITLE
Don't run correctly in iOS 9

### ISSUE THREAD

**Issue by vincentsaluzzo** [libretro/RetroArch#2180]
As discussed in an issues, event in UI aren't correctly managed due to bad use of event loop.
But there is a lot of lack : 

* No core run when tap on it
* Core Updater ran randomly 
* zero logic in it's navigation processus.

Also, I'm interested to help you for debug problem but I've a lack in C/C++ and OpenGL development but I'm pretty good to develop for iOS platform.

**Comment by twinaphex** [comment]
what is 'zero logic' about the navigation process? I will admit that the UI is still pretty rough around the edges but you have to understand this is pretty far from a garden-kitchen variety CocoaTouch implementation, it is mainly C code that is driving the UITableView and everything is being built up dynamically. It is VERY, VERY tough to do it this way but it absolutely has to be done this way because we are not going to be putting up with any kind of additional code maintenance for settings just for one particular platform (iOS) - we have to be able to have one codebase and have all other ports and external UIs all updated at the same whenever we update the main core codebase.

To help us with improving the CocoaTouch UI you need a solid grasp in C/C++ and the necessary CocoaTouch/UITableView experience. So far we have been struggling finding a developer that knows both, it is always one or the other and that isn't going to do us no good.

**Comment by fr500** [comment]
Feel free to reopen the issue if you're willing to add some context to your statements.
