### ISSUE TITLE
Input not working with joypad connected upon opening

### ISSUE THREAD

**Issue by asimonf** [libretro/RetroArch#2241]
I have the latest version of Arch Linux running as a minimal system with KMS enabled. The kernel is based on version 4.2. I compiled both the latest commit (bbcd49b) and the one tagged for version 1.2.2 and this problem presents itself on both versions, though slightly differently. I modified permissions of events* on /dev/input so that any user can read and write them, and I ran Retroarch as a root as well to make sure permissions weren't the issue. I have my computer to autologin to a user and immediately open Retroarch. 

Whenever I open Retroarch without my gamepad connected, input works just fine. If I plug the joypad it isn't autoconfigured (this isn't true on the 1.2.2 version, but is true on the latest commit; I have downloaded autoprofiles using online uploader), but if I go to the input section and bind it, it works fine (when it works).
 
The problem is if I open Retroarch with the gamepad connected. Sometimes it works fine (especially if I have plugged and unplugged it several times before opening Retroarch), but if I run Retroarch after booting with the gamepad plugged all the way through, input locks. Neither the gamepad nor the keyboard work. If I unplug the gamepad, the keyboard unlocks and I can use the program, but upon replugging, the gamepad won't work. I know that Retroarch detects it on both scenarios because the OSD displays information about the gamepad upon opening and upon connecting if it wasn't connected.

When this happens, if the gamepad doesn't work the first time, it won't work even if I close Retroarch and open it again, though this time the keyboard won't lock itself. On 1.2.2, the keyboard is locked always under the same circumstances, as if the user running the app didn't have permissions for /dev/input/events*, but on the commit tested, at least the keyboard works on succesive runs as long as I have at least unplugged the gamepad once.

This gamepad isn't really a gamepad, its a regular USB gamepad adapter for Wii Classic Controller accesories for the Wiimote (http://www.mayflash.com/Products/PCUSB/PC052.html).

I'm going to try with other gamepads today. I have a PS4 gamepad and an Xbox One gamepad. However, I don't have any other regular USB gamepad to try with so I don't know if the problem is the adapter, driver, retroarch, some of them or all of them, though at the very least, if the driver is part of the problem, the keyboard shouldn't be locked out anyway, and since the behavior has changed between versions of Retroarch (if only very slightly), there has to be a Retroarch component. The solution probably isn't entirely on Retroarch's hand, but since this is the context I see it presented, I'm bringing it to you for further research. I, however, am entirely available for any testing and or anything else I can provide you with.

**Comment by Quickgold74** [comment]
I have the same behavior happend to me in windows with a generic USB gamepad, RA detect my pad but it won't bind any button, only the keyboard if I unplug and plug again (here is random the first tiem that you setting up the INPUT), the last working nightly without issues for me It was 2015-10-10

**Comment by fr500** [comment]
Since you're running linux, can you try to bisect the issue?

**Comment by twinaphex** [comment]
Must be due to the new input behaviour changes I made - it now checks if the input comes from either the input driver (in which case it assumes it is a keyboard), or if it comes from the joypad driver (in which case it assumes it is a joypad). Previously you'd have to specifically set a 'Bind Mode' to either keyboard or gamepad which was very inconvenient so a better solution had to be made. Unfortunately it doesn't seem to cover all the edge cases.

I guess your pads fall into a kind of nowhere man's territory.  Not sure about how to proceed though, maybe rewrite the entire input binding so it can handle both keyboard and gamepad at the same time.

**Comment by fr500** [comment]
Yes Twinaphex that's the case
Actually having the toggle was good just because of this.
Maybe instead binding mode we can had a User 1 bind all (joypad) and User 1 bind all (kbd)

**Comment by Quickgold74** [comment]
I can confirm that this issues is happend to me with android too, I make a fresh install with the last nightly in four devices (Archos gamepad, OUYA, Shield Console and Nexus 7 with a NES30 Bluetooth Gamepad) and RA try to bind a keyboard no joystick, even with the right device index name

**Comment by fr500** [comment]
It's not happening on android for me and autoconf definitely works

**Comment by lugaidster** [comment]
The problem is probably related to issues with both the driver and Retroarch. I haven't seen this problem yet with Xbox One gamepad, but with a regular USB device, it happens. The problem is that it locks me out of using the keyboard until I unplug the gamepad. Lately, I haven't been able to make work at all. I might have a go at bisecting the issue during the weekend, I have less free time than I'd like and I'm already investigating #2248.

**Comment by twinaphex** [comment]
I added this as  a workaround for now until we can structurally improve the detection so that it takes care of these edge issues:

https://github.com/libretro/RetroArch/commit/d800f7b8d96ef93863e2e95e2c40ec22ff7d4d92

Bind Mode is back. The default is 'Automatic' which gives you the behavior it does now, where it tries to autodetect if the input device is a keyboard or joypad device. The other two options are 'RetroKeyboard' (for keyboards) and 'RetroPad'( for joypads).

**Comment by Quickgold74** [comment]
in Windows with Atomatic (in my case) only detect the Keyboard for bind, even with device index showing the gamepad conected, the only way is selecting Retropad, it works fine again.

**Comment by parkerlreed** [comment]
Same here. (Arch x86_64 udev input) "Auto" doesn't seem to detect RetroPad in most cases. Manually selecting RetroPad lets me assign the controller buttons.

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/61623dcdcea4044eadf6ccced5328b1f539ed183

Starting as of this commit, the toggle should no longer be needed so I removed it, you should be able to bind both the keyboard and the gamepad now at the same time. Let me know if this works.

**Comment by Quickgold74** [comment]
Hi, works fine here with keyboard and gamepad at the same time, I'm testing with a blank config and  by the moment I don't found any issue with this new bind mode.

**Comment by parkerlreed** [comment]
Working fine here too. Thanks!

**Comment by Kivutar** [comment]
Works for me too
