### ISSUE TITLE
Dynamic Recompiler crashing RetroArch

### ISSUE THREAD

**Issue by MaquinaDelMisterio** [libretro/RetroArch#2345]
I have an iPad Air 2, every time i change from interpreter to Dynarec it crashes retroarch. This can be fixed?

**Comment by sergiobenrocha2** [comment]
uh, dynamic recompiler from what core? Is it not better to report in the right Core repo?

**Comment by MaquinaDelMisterio** [comment]
N64 iOS 9.

**Comment by bronnel** [comment]
This also happens on iOS 8.4 although dynarecs is working fine in other cores like pcsx rearmed only mupen 64 crashes , I know if you change core options to cached interpreter it works , but its laggy , the only way for N64 to run fully is with dynamic recompiler and iOS 8.4 fully supports that because it's jailbroken with taig

**Comment by MaquinaDelMisterio** [comment]
So the problem is Pangu? Oh, i see!

**Comment by bronnel** [comment]
On iOS 9 yes it's pangu, but on iOS 8.4 this crash shouldn't be happening because it has dynarec permission, this needs to be fixed

**Comment by MaquinaDelMisterio** [comment]
We need Dynarec urgently, my battery dies at half every day i use N64 core.

**Comment by twinaphex** [comment]
This is not a RetroArch bug. Move it to the respective repo of the emulator you are talking about.
