### ISSUE TITLE
[3DS] Add in argument passing for *hax 2.5 shortcuts

### ISSUE THREAD

**Issue by shutterbug2000** [libretro/RetroArch#2378]
With the new *hax 2.5 being able to pass arguements to a .3dsx, I thought it'd be a good idea to make it possible to have a shortcut to a game be possible, so we could have shortcuts to emulated games.

**Comment by aliaspider** [comment]
the arguments are specified in the xml or how does that work ? do you have an example ?

**Comment by shutterbug2000** [comment]
In the eshop .xml, there is a category called <arg> that passes an argument.

**Comment by shutterbug2000** [comment]
Wow, just realized it didn't post the tag. Let's try this again, without the tag.

*less then* arg *greater then*

That should work to pass an argument to a .3dsx

**Comment by aliaspider** [comment]
added in bf407606bc99ab87934e16f44d35cefd413d8184
works with both the shortcut and from 3dslink. only the fullpath to the content file is supported, adding more argument will not work since the shortcut doesn't properly split them in an argv array.

fun fact: passing an argument to the 2048 core will make it work xD
