### ISSUE TITLE
[regression] annoying behavior in this new "Settings Tab"

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2603]
There's an annoying behavior since Settings went to its own tab.

Go to any settings like Video or Configuration, then come back to the main Settings tab, you'll notice it'll be in the same position of the list, i.e. you entered Video then came back, it'll be exactly in the Video position. This is the good behavior.

Now try with Input and Playlists, you'll notice that it'll be at Driver when you come back. Bad behavior.

The same thing happens inside Input: enter "Input Hotkey Binds" or "Input User 1 Binds", when you come back it'll be at "Max Users".

Inside the Directory settings something similar happens after you choose the path of any option, it come back to the Settings tab, i.e., one level above. It behaviors nicely when you instead choose some path you cancel with B.

**Comment by Kivutar** [comment]
Yes, this is a known bug. But it is not due to settings being in their own tab.

The cause of this bug, is that Input and Playlist are **action** menus. And action menus are a special case in the menu system, their parent is hardcoded to the root. So when you hit cancel, you go back to the root, the main menu, instead of comming back where you should...

I tried to fix it, but it is very difficult. It require refactoring. Twinaphex may be able to do it though, since he created those, and know better than me the internals of the settings menus.

**Comment by fr500** [comment]
changing the label to minor since this is annoying but not a breaking bug

**Comment by RobLoach** [comment]
I believe this is fixed.
