### ISSUE TITLE
[$30] Metal API support for iOS and OSX to improve CPU rendering overhead.

### ISSUE THREAD

**Issue by me4502** [libretro/RetroArch#2622]
Currently the rendering appears to be abstracted out across OpenGL, DX, and a few other platform-specific systems, so adding one for Metal could improve rendering performance and comparability on Apple devices.

**Comment by cmmc38** [comment]
This would be fantastic if able to be implemented.  Are there any iOS devs with Metal experience out there?  I wish I could help.

**Comment by RobLoach** [comment]
Vulkan may be a good option too.

**Comment by fr500** [comment]
Vulkan is the only sane option

**Comment by twinaphex** [comment]
Metal might become a hardware context option for the libretro API - it's too early to tell yet, it will depend on whether or not there are measurable gains to be found (only thing I can think of is maybe for Reicast since the Metal API on iOS purports to be very close to how the PowerVR's rasterizer works, and we would need something to offset the general disappointing lack of a 'real' dynarec on Apple TV), but it's too early to make a decision yet.

Also, it depends on whether Apple will not eventually come around and start supporting Vulkan as well. I hope honestly that we are not forced into having to support yet another completely different API in the current libretro GL cores, back before Apple went its own way with Metal and MS went with D3D12 there was a brief period where GL could be assumed to be running everywhere and it was high on every vendor's priority list. Crossplatform considerations weigh stronger than anything else for this project.

Anyway, I'll let you know once I have something more concrete.

**Comment by me4502** [comment]
I can't see apple not supporting Vulkan on Mac OSX, however with iOS and tvOS it may be a bit different. The reason I suggested Metal, is it will probably be faster than Vulkan on those devices as it is built with those devices in mind, whereas Vulkan still has a level of abstraction to it. As the devices are lower power, it's worth getting all the performance out of it as possible.

**Comment by fidelis1** [comment]
Are there any updates on this? So far it looks like Apple is all in on Metal with the release of Metal 2. It seems highly unlikely at this point that they will ever support Vulkan or even a version of OpenGL newer than 4.1 or ES 3.0. Adding support for Metal would likely result significant performance gains on MacOS and iOS.

**Comment by fidelis1** [comment]
@me4502 @twinaphex @twinaphex I posted a $30 bounty for this over at Bountysource. Could someone add the bounty label and add [$30] to the end of the title?

**Comment by twinaphex** [comment]
I'm going to drop in a $100 for this bounty starting as of April.

**Comment by benneq** [comment]
@twinaphex I hope that wasn't an April's Fool

**Comment by twinaphex** [comment]
OK, we can consider this issue solved. Let me know if you want to claim the bounty @stuartcarnie. If not, maybe you could tell me how you feel the money should be reappropriated, as in, should it go to an existing issue/bounty or a new one?

**Comment by twinaphex** [comment]
@me4502 Would you consider the bounty solved already or do you want it to work with iOS first?

**Comment by me4502** [comment]
I didn’t post the bounty, however the reason I made the issue was for iOS - so I wouldn’t consider the issue solved if it doesn’t work for iOS

**Comment by stuartcarnie** [comment]
I'm working on making the Metal renderer work with iOS and tvOS

**Comment by twinaphex** [comment]
Reopened.
