### ISSUE TITLE
Only RGUI menu interface works

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#2676]
Hello,

If I use another menu interface than RGUI, retroarch crashes.

This is my log terminal:

http://pastebin.com/rfcmAij1

and the gdb log:

http://pastebin.com/RxpHMhZ8

Thank your for your help.

config:
Ubuntu 15.10 Wily 64 bits
NVIDIA GeForce GTX 770
official Ubuntu Nvidia drivers 352.63 resolution 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM
Retroarch/Libretro compiled from git 25/01/2016

**Comment by twinaphex** [comment]
That's your problem -

RetroArch [INFO] :: Found menu display driver: "menu_display_null".

It is defaulting to menu_display_null instead of menu_display_gl like it should. GLUI, XMB and Zarch require a GL driver right now, 'null' or 'd3d' won't do.

**Comment by twinaphex** [comment]
In case you want to keep using the SDL video driver, check at least if it works now with this -

https://github.com/libretro/RetroArch/commit/8d7290b30010282e872f0adf61239ac1da1c4c38

What it should do now is, it should try to detect if your video context driver has the name 'sdl_gl'. If it does, then it should default to the menu display GL driver instead of the menu display null driver. This should make it possible for GLUI/XMB/Zarch to work with the SDL driver (as long as it defaults to the SDL GL context).

At the same time though, after you have confirmed this works, I'd suggest you use the plain GL driver directly.

**Comment by legluondunet** [comment]
Yes! I can now use the xmb interface, very nice look, thank you.
I used sdl because on Linux most of the emulators and games use this driver, it has become a reflex.
But for the moment why let people choose sdl?
Why let people choose another menu interface (zarch, xmb...) whereas sdl is activated and this going to crash retroarch?
For me it's a bug.

if sdl driver choosed
-->> activate rgui menu interface only
or you could  inactivate the menu interface when sdl is active.

**Comment by twinaphex** [comment]
We can look later at a graceful rollback to the RGUI driver in case the video driver can not support hardware accelerated menu graphics (like SDL2 video driver right now I suppose).

**Comment by twinaphex** [comment]
This should be addressed now, the D3D drivers now support XMB and MaterialUI.
