### ISSUE TITLE
Cannot launch RetroArch 1.3 in Windows 10 Pro 64 or Mac OS X El Capitan

### ISSUE THREAD

**Issue by djtechonline** [libretro/RetroArch#2689]
Being a MAME user for many years, I have heard many good things about RetroArch and decided to give it a try.  I downloaded the latest stable release v1.3 for my arcade system running Windows 10 Pro 64 but it will not launch.  I then tried the 32-bit version, same problem:
![capture](https://cloud.githubusercontent.com/assets/7561947/12769886/88e6326e-c9e9-11e5-818f-f7b5fd3e2f04.PNG)

I decided to give it a go on my Mac (OS X El Capitan), but that fails also:
![screen shot 2016-02-02 at 8 14 54 pm](https://cloud.githubusercontent.com/assets/7561947/12769906/ab3e6ed0-c9e9-11e5-9aa5-c9af8543b420.png)

I then downloaded v1.2.2 which does run on my Mac, but v1.2.2 will still not run on my Windows PC.  I tried signing up for the forums, but there is a problem in the registration page where the Captcha does not display any image, so I cannot register.  I decided to give github a try.  If this is a stable release, then why won't it launch?  Am I missing a prerequisite of some kind?

Please help.  Also, please fix registration form on web site.

**Comment by MaximeMorel** [comment]
About RetroArch 1.3 on your Mac, did you installed Nvidia CG toolkit ?

**Comment by djtechonline** [comment]
Thank you MaximeMorel - I just installed the Nvidia CG toolkit on my Mac and RetroArch now works with OS X.  It is concerning, however, that Nvidia states it is no longer in development.  

My arcade cabinet runs Windows, though.  So I still need a solution for this.  Is there a similar solution for Windows setups?

**Comment by fr500** [comment]
We have a non-cg bundle too for OSX.
On windows you're probably missing directx

**Comment by twinaphex** [comment]
The total lack of support for Cg and how they dont even want to open the source despite clearly no longer caring about wanting to support it is really, really shitty. Might be the last time we go for one of these proprietary APIs really where either the spec is not open or there is not some standards body behind it that will ensure we are not in trouble once it is no longer interesting to some companys bottom line.

Anyway, we are not really dependent on Cg, we support GLSL as well and for the upcoming Vulkan support we will have to gradually move towards making Cg a second class citizen since it will just hold things back for us (cant even use it with a GL core context for instance). 

As for now, I think it might be best if we just ship two binaries inside the package, one with Cg support and one without. Might create bigger zips but honestly, users are already having a hard time getting familiarized with RA and setting it up apparently, lets not even make it even more of a bother to set it up. We have all this nice stuff going for us with RA but none of it is going to matter if we dont make it easy for the user to set up.

**Comment by djtechonline** [comment]
I totally agree that installation needs to be simple and straight-forward, especially on both Mac and PC platforms.  I expected to unzip the archive, double-click on the RetroArch.exe icon and be on my way.  Unfortunately, this was not the case.  

As for my Windows 10 installation, I have installed DirectX from the Microsoft Web Installer and when I run dxdiag, it shows no problems were found.  It setup DirectX version 10 (I see no way to downgrade to DX9).  I am still unable to launch RA.  Any other ideas?

**Comment by fr500** [comment]
can you try this?
https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

**Comment by fr500** [comment]
Closing this due lack of feedback.
Please reopen if anything arises

**Comment by ravdarkknight** [comment]
Downloaded the direct x files. It's still not working
