### ISSUE TITLE
License Violation in CTR

### ISSUE THREAD

**Issue by 173210** [libretro/RetroArch#2697]
The CTR version is statically linked with Snes9x-next and Genesis Plus GX. They have are licnesed only for non-commercial purpose, which is incompatible with GPL.

See http://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary for the incompatibility of GPL with non-commercial licenses.
See http://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs for the issue of linking with libraries incompatible with GPL.

There are some options:

* Add an exception to GPL

See the FAQ of GPL I mentioned the above.

* Use another license

LGPL is a valid option since they are open source.

If you choose either of the above options, you need to contact __all__ copyright holders.

* Abandon

Abandon Snes9x-Next and Genesis Plus GX.

**Comment by fr500** [comment]
CTR? as in 3ds?

**Comment by roflcopter777** [comment]
What the deuce? Who is this dude anyways?

**Comment by hizzlekizzle** [comment]
Eke gives us a waiver on genplusgx, as I understand it, or at least he knows and doesn't care. He's the maintainer of the libretro-ization for that core and he is well-aware that it gets statically linked on the console ports.

For snes9x, no rightsholders have complained. OV2 is/was also well-aware of us and the libretro-ization is upstreamed there, as well.

**Comment by roflcopter777** [comment]
Then who is this OP to call out on a "violation" if the all clear is given? Some anon white knight?

**Comment by 173210** [comment]
Then which should follow if I use RetroArch, unrestricted redistribution or non-commercial purpose only?

**Comment by roflcopter777** [comment]
These apps are free and will always be non-commercial, the authors of Genesis Plus and Snes9x have given their OK

**Comment by hizzlekizzle** [comment]
If you're not trying to sell statically-linked RA+snes9x/genplusgx, go nuts. Redistribute it however you like. If you are trying to sell it, we won't like it but I very much doubt anyone will hassle you over it too much (see also: Retron5 and Retro Freak consoles).

**Comment by 173210** [comment]
If it's GPL, embedding RetroN 5 should be allowed. Of course, they should release their source code. You can't request both demands at the same time unless you change the license: to force them to release the source code of RetroN 5 and stop using Snes9x Next and Genesis Plus GX.
http://www.libretro.com/index.php/retroarch-license-violations/

I believe the best way to conceive them is to change your license. How can you claim their violation while you're violating yourselves?

**Comment by fr500** [comment]
have you seen the date of that post? we have given up already, also hyperkin rolled back to older versions of genplus and snes9x that are GPL compliant.

**Comment by hizzlekizzle** [comment]
There are several licenses at play in the Retron5 situation. They provably had our GPL code in their frontend at one point but removed that bit when we complained. They may have more of it still in there but we can't prove it. So, the GPL/source-sharing is moot at this point.

They are selling Snes9x-Next but no one seems to care, and they basically said "emu licenses don't really mean anything, so we're just going to use it unless/until we hear from a lawyer." They're also selling genplusgx but they rolled back to a previous version that was GPL-licensed.

So, while statically linking to noncomm cores may technically be a violation of the GPL, we're violating our own license and with the (at least tacit) permission of all rightsholders and we're not selling anything or otherwise violating the noncomm licenses.

**Comment by 173210** [comment]
Why don't you write that somewhere? Any newcomer will not know that. And, as a way to do that, I'm suggesting to license under LGPL. The license itself is to show what you permit and what you don't.

**Comment by hizzlekizzle** [comment]
It's true, the licensing is confusing/misleading and we've discussed various other licensing schemes. The only reason we haven't switched to MIT is that the GPL at least scares away some scummy companies and maintains compatibility with the many GPL cores we link to.

**Comment by 173210** [comment]
@hizzlekizzle You have other options than MIT. Adding an exception or using LGPL are good alternatives.

**Comment by fr500** [comment]
Moving to LGPL would be no good in this regard, migh as well go MIT.
Also now that @hizzlekizzle mentioned it it's perfectly fine we're only violating our own license, not Snes9X's or GPGX's.

So yeah I guess @Twinaphex could write an exception for thes binaries, it would just be a formality.

**Comment by mudlord** [comment]
Won't suit these nutters, they want GPL or else.

**Comment by 173210** [comment]
So adding an exception for Snes9x-Next and Genesis Plus GX?

**Comment by fr500** [comment]
are you asking me if we're gonna do that? I don't know.
It would just be a formality and there is little to gain here.

**Comment by roflcopter777** [comment]
My, he really is hellbent on making your guys' life a living hell, ain't he?

**Comment by 173210** [comment]
LOL I just wanted to make sure what @hizzlekizzle says:
> It's true, the licensing is confusing/misleading and we've discussed various other licensing schemes. The only reason we haven't switched to MIT is that the GPL at least scares away some scummy companies and maintains compatibility with the many GPL cores we link to.

I have no other intention. I appreciate your GPL (I also often use GPL)

**Comment by roflcopter777** [comment]
Whatever you say lol

**Comment by twinaphex** [comment]
Meanwhile Mr. head SDL dev is taking extreme liberties with how he can mix and match a 16 year old MAME version that is licensed under the old, noncommercial MAME license, and putting that inside a Steamlink SDK github repo, right next to other code that is GPL-licensed or BSD licensed, but does anybody give a shit? No, neither mamedevs seem to give a shit or anybody else. Why? Robably because these are a bunch of corporation-worshipping nerds who just selectively feign outrage at this kind of stuff depending on

1) whether you are from a big company or not, and
2) whether or not it will 'help' their project publicity wise

But yeah, lets make huge drama out of this instead. For a 3DS release on jailbroken consoles nonetheless.

**Comment by 173210** [comment]
@twinaphex 
> whether you are from a big company or not,

No. I'm just a hobby gaming console developer, but particular about licensing. (Google me)

Anyway, I don't think it makes difference for commercial use, since Snes9x-Next and Genesis Plus GX would keep their licenses. I just want to make clear those exceptions.

**Comment by twinaphex** [comment]
I was not talking about you being from a big company or not, I was talking about what the likely reason is that these licensing guys never seem to go after the obvious license violations that now exist in Retron 5, Retro Game Freak, steamlink SDK, etc. I really want to know what is the reason for the lack of any 'heckling' is there, because it is making all of this heckling seem rather hypocritical.

Anyway, you will have to talk to @aliaspider I guess since he is the main 3DS dev, whatever he decides we will go with. As for me, in the past I might have cared about this issue but after seeing how next to little to no support we received from either the FSF or any other organization when there were clear instances of TIVOization going on, I am beyond caring really.

**Comment by 173210** [comment]
As far as I know, it is impossible to link them dynamically on *hax, which is the most common homebrew environment. That is because of XN bit (eXecute Never).

Fixing the license issue is important also for preventing TIVOization. Those companies claim your license is trivial.
> They are selling Snes9x-Next but no one seems to care, and they basically said "emu licenses don't really mean anything, so we're just going to use it unless/until we hear from a lawyer."

You should validate your license to oppose them. Although I'm not a lawyer, this issue is obvious even for me.

**Comment by twinaphex** [comment]
Those companies dont claim anything and they are even more clueless about open source licensing then some random guy on the street. They just do whatever they want since they know there is no repercussions anyway, and because they have a 'little bit of money' with which they can fight off any kind if legal threat that might emerge. It is a calculated business move that it makes them short term money and nobody is likely to do anything against it. And I guess this entire community just gives them the right to do that basically since nobody is doing anything against them.

**Comment by 173210** [comment]
Probably you're right.

**Comment by twinaphex** [comment]
Anyway I will ask some of the other members about this issue and we will see.

**Comment by roflcopter777** [comment]
This is why we can't have nice things, people always bitching about something not being done right, in this case, so-called licensing that can't even be enforced.

**Comment by twinaphex** [comment]
@fr500 correction, there is no version of SNES9x that is GPL compliant, its just that the snes9x team decided they 'could not be bothered' (Koots words) and all the other (what remains if it anyway) teammembers apparently decided that was the end of it, Pathetic but what can you do really.

**Comment by twinaphex** [comment]
I've asked @aliaspider and he thinks this is not worth pursuing. 

He also finds it to be weird that people who jailbreak/mod consoles to begin with would have any issues with licensing to this extent to begin with.

Anyway, I'd feel inclined to try to reach some common ground but honestly, by telling us that our options are either 1) relicense as LGPL and seek authorization of all contributors, or 2) drop snes9x next / genesis plus gx, those are not really realistic choices and I think you know it as well.

**Comment by 173210** [comment]
You should refer to [COPYING.NEWLIB](https://github.com/devkitPro/newlib/blob/devkitARM/COPYING.NEWLIB). newlib itself is not GPL.

**Comment by twinaphex** [comment]
I guess he highlighted the COPYING document for Devkitpro instead then instead of newlib.

Anyway, doesn't the same point still stand? Wouldn't there be a similar license incompatibility problem there then with any non-GPL compliant licensed code linked to devkitpro?

**Comment by 173210** [comment]
@twinaphex COPYING is not of devkitPro one, but of newlib project. newlib project contains some files else newlib.

Maybe, but at least both of I and you don't know.

**Comment by 173210** [comment]
Take it easy: several documents (RetroArch license and emulators' licenses) had a clear contradiction to be fixed. That's it.

**Comment by roflcopter777** [comment]
Or you could stop making a big f*cking deal about it and let them do whatever they feel best instead of sticking your nose where it doesn't belong.

**Comment by twinaphex** [comment]
What licensing issue though? Linking against SNES9x Next or Genesis Plus GX is a decision made by the user, and the SNES9x and Genesis Plus GX cores are separate entities. Plus, by jailbreaking you are breaking a license in one form or another anyway, the EULA of whatever console you are jailbreaking.

I am not going to just 'abandon' SNES9x Next or Genesis Plus GX, sorry. Those will remain as repositories inside the libretro organization. 'Abandoning' them makes zero sense when they have nothing to do with RetroArch to begin with.

**Comment by roflcopter777** [comment]
@twinaphex  Don't listen to that punk, he's trolling, plain and simple. You guys deal with enough BS as it is without his kind fucking things up.

**Comment by fr500** [comment]
Locking this, it's not constructive at all
