### ISSUE TITLE
Compiling and installing: Linux

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#2730]
Hi,

For Linux, I think README.md is perhaps no completed :

sudo apt-get install -y make git-core curl g++ pkg-config libglu1-mesa-dev freeglut3-dev mesa-common-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev

You must add :

libcg libcggl nvidia-cg-dev nvidia-cg-toolkit

**Comment by twinaphex** [comment]
These shouldnt be hard dependencies though, and we are going to steadily divorce ourselves from requiring Cg support now with Vulkan merged and SPIR-V/GLSL becoming the new way forward.

Cg will always remain though, but it will probably become completely optional.

**Comment by ProfessorKaos64** [comment]
@twinaphex , any idea when? Not looking for an exact timeframe. I'll keep my eye on the nightlies for when I will repackage for SteamOS. I'd imagine it'd be a whole new release point.

**Comment by twinaphex** [comment]
There will remain backwards compatibility, since RetroArch is in large part about that.

However, there will be a new shader spec for both GL GLSL and Vulkan moving forward. The old shader spec simply won't do moving forward.

Spec is not finalized yet so just wait. In any case, it should be a seamless transition.

**Comment by newhoa** [comment]
Just wondering if there has been any change with this?
There is a [RetroArch PPA](https://launchpad.net/~libretro/+archive/ubuntu/stable), not sure if it's official or sanctioned by you all (seems like it may be), but in order to install RetroArch from the PPA you have to enable the non-free repositories so it can install libcg and libcggl. In Ubuntu the only solution to avoid having to enable the non-free repositories is installing it from the official Ubuntu repositories where they are stuck on RetroArch 1.4.1. Is libcg and libcggl still a requirement or are the packages in the PPA being built with that as the default?

**Comment by hizzlekizzle** [comment]
You can use the snap package, which does not include Cg.

**Comment by orbea** [comment]
I don't think its fair for us to document the dependencies for every distribution which the developers may not even use. Any documentation for distro packages should be provided by the respective distros and if its not please ask the appropriate maintainers to provide that information. You should be able to find the maintainer contact information at repology.org.

https://repology.org/

As for the PPA package being built with cg support, its probably best if someone using that package to contact the PPA maintainer and ask them to rebuild without it. This can be done by building without nvidia-cg-toolkit installed or with passing `--disable-cg` as a configure argument.

Additionally the dependencies should be already documented briefly in `README.md` and further with `./configure --help` so I don't think there is anything left to do here so I am going to close this issue. Please let me know if there anything I missed.
