### ISSUE TITLE
IPAC and Mouse Mapping

### ISSUE THREAD

**Issue by NJDave71** [libretro/RetroArch#2783]
I am very new RetroArch and figured i give it a try.  I have a custom controller that use an I-PAC2.  so the buttons and controls emulate the keyboard and mouse and its controls match MAME.ini controls.

two of my Buttons are mapped to the left and Right mouse button and these can be mapped in MAME.  How can i duplicate this in RestroArch.

Thanks

**Comment by fr500** [comment]
we don't have functionality to use mouse as buttons.

**Comment by dankcushions** [comment]
probably new functionality since this issue but you can use left/right/etc mouse buttons now. eg: https://github.com/libretro/mame2003-libretro/blob/master/src/libretro/libretro.c#L356

more mouse functions listed that i didn't use: https://github.com/libretro/mame2003-libretro/blob/master/src/libretro/libretro.h#L170

so i guess this is now a core issue - whatever mame core @NJDave71 is using needs to be hooked up to the mouse stuff like mame2003 is.

**Comment by dankcushions** [comment]
(sorry, ignore that comment, misread the issue!)

**Comment by hizzlekizzle** [comment]
We can now map retropad functions to the mouse buttons, so I'm going to close this. Feel free to reopen if needed.
