### ISSUE TITLE
keyboard / mouse support

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2901]
@diablodiab 
just tested kbd support in RetroArch Android, it's working nicely... mostly
My Logitech Combo K240 works fine, it's detected as a kbd and it just works.
My Logitech K360 is detected as a gamepad for some reason

Also, did you add mouse support too? the Shield Portable always emulates mouse apparently so it kinda works in the menu (but the pointer is not RetroArch's pointer) and it doesn't work in-game

**Comment by diablodiab** [comment]
Mouse support was not added - only keyboard.

I haven't found a 100% correct way to distinguish between a gamepad and keyboard when it is detected. The thing is that some keyboards report to Android that they are both a gamepad and a keyboard if they have special buttons that are usually found on a gamepad. In those situations the keyboard is detected as a gamepad. That might be the problem with the K360.

When I did the implementation I tried to make it as automatic as I could, but because of problems like the one you describe for the K360, it might be better to extend the autoconfig functionality and add a "type" to the controller detected where "type" can also be keyboard. Then you can add config files for keyboards as well as gamepads.

**Comment by twinaphex** [comment]
@diablodiab - There is an interesting thread here where some other Android dev is trying to solve the issue of multiple buttons not being registered at the same time (needed for button combos, etc.) It could maybe require your input.

https://github.com/libretro/RetroArch/issues/2043

**Comment by diablodiab** [comment]
Yes, I have some thoughts about it, but I haven't been able to crack it.

I think the problem occurs because multiple buttons need to be registered within a single frame. When looking at runlook_iterate in runloop.c, I'm guessing that button presses are registered by comparing changes to the input states in the current frame compared to the input state in the previous frame (cmd.state[0] and cmd.state[1]).

I think the problem might occur because input events are handled so fast on Android that input events are not queued up but handled individually in separate frames.

I tried experimenting with timers in android_input_poll in android_input.c to try to force input events to only process them every 100ms or so, so there would be time for them to queue up, but it didn't work out the way I had hoped.

Any of you others have thoughts on this?

**Comment by twinaphex** [comment]
Can you also post this in that other thread so that the others there can read it?
