### ISSUE TITLE
Shader spec violation being accepted by Retroarch

### ISSUE THREAD

**Issue by Hyllian** [libretro/RetroArch#2916]
Some commands at presets (.cgp) are wrong according to the shaders specs and yet they are accepted by Retroarch.

The command is: scale_type_0
That command is present in many presets (even made by me, sorry).

The specs allow these:  scale_typeN, scale_type_xN, scale_type_yN

The underline shouldn't be allowed by Retroarch.

**Comment by Themaister** [comment]
I suspect that it does strstr on scale_type, then strtould on "_0" which would return 0, and error is not correctly handled.

**Comment by LazyBumHorse** [comment]
RetroArch does not accept scale_type_0.
https://github.com/libretro/RetroArch/blob/402607537a73e284577f947269910fd9c9cfbea2/gfx/video_shader_parse.c#L206-L207

It ignores it and defaults to "source".
https://github.com/libretro/RetroArch/blob/402607537a73e284577f947269910fd9c9cfbea2/gfx/video_shader_parse.c#L225-L233
Since _all_ (but one) presets that use the wrong syntax try to use scale_type "source" anyways, they happen to work fine.
Even the one exception happens to work, because it tries sets the scale_type of the last shader in the chain to "viewport", which does the same as not setting it, see under ['Exceptions'](http://docs.libretro.com/development/shader/cg-shaders/#scale_typen-string)

Pull requests for fixing the wrong syntax are on it's way, despite not changing anything.

This can finally be closed.
