### ISSUE TITLE
Option to let me chose core in playlist?

### ISSUE THREAD

**Issue by Rhymezz** [libretro/RetroArch#2922]
first time you press on a rom in a playlist you get to chose what core to use if no core is loaded. the next time you press on the rom it autostarts the last used core, is it possible to let me chose to not autoload a core in a playlist and let me chose core again?

**Comment by Kivutar** [comment]
I tried to implement a behaviour like this some time ago. It could be useful to in a use case like Lakka to never save the used core in the playlist.

However, I remember that it was not easy at all. I require a lot of refactoring, because the code of the playlist is also the code of the history list, where saving the core is mandatory.

**Comment by Rhymezz** [comment]
If I remember correctly chosing a core didnt overwrite the lpl file before. Or maybe I just dont remember.

**Comment by Kivutar** [comment]
Linked to https://github.com/libretro/RetroArch/issues/2959

**Comment by fr500** [comment]
let's close the second bug and discuss just on the most recent one?
