### ISSUE TITLE
Fullscreen breaks fast forward

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#3021]
Windows 10 Pro
Intel Core i5-6300U
NVIDIA 900m Series Optimus GPU (exact name is obfuscated. best guess is 940m)
Buildbot date: May 23, 2016
Git version: 1be1c6a

Fast forward refuses to work in fullscreen. Both in the held and toggled versions. If you enter fullscreen while fast forwarding, fast forwarding will stop. Exiting fullscreen will restore fast forwarding. I performed a clean install of NVIDIA's 365.19 drivers and haven't changed any settings from default. Changing the state of "Windowed Fullscreen Mode" in retroarch has no effect. My driver's vsync settings for retroarch is to default to retroarch's settings.

**Comment by hizzlekizzle** [comment]
Something must be preventing RA from disabling vsync. Can you check whether your driver has a "performance vs quality" setting, particularly for video?

**Comment by tony971** [comment]
I didn't see anything but I force disabled vsync for retroarch in my driver's settings and it still didn't work.

**Comment by tony971** [comment]
Forcing use of the integrated graphics fixes* the issue but defeats the purpose of having a dedicated graphics card.

**Comment by hizzlekizzle** [comment]
From looking on the internets, it seems Optimus often has issues with this sort of thing.

**Comment by tony971** [comment]
It appears that the mupen64plus core is unaffected by this. Fast forward works fine in fullscreen using that core. Cannot say the same for gambatte, mgba, nestopia ue, bnses mercury, or mednafen psx.

**Comment by fr500** [comment]
the core doesn't really affect how retroarch works, but it being a GL core could mean your driver is doing something differently.

I can't repro this on standalone NVIDIA graphics.

**Comment by fr500** [comment]
Can't reproduce this, and noone else has reported the issue. May be specific to the OP setup.
Needs more information

**Comment by DJMATTTAM** [comment]
Microsoft Windows 10 Home
AMD Ryzen 5 1600 Six-Core Processor, 3200 Mhz, 6 Core(s), 12 Logical Processor(s)
NVIDIA GeForce GTX 970
RetroArch v.1.7.3 (Sorry I don't have a build version to give you, I downloaded this straight from the website today if that helps though :/)

I'm having the same issue.  I'm using the mGBA core on my machine and I've also noticed this.  If I run RetroArch in a window, the fast forward feature works well, but once I fullscreen RetroArch, the game stops running in fast forward.  Only solution I have is to run RetroArch in windowed mode in order to use the fast forward feature.  It's nothing stopping me from using RetroArch, but kinda annoying.

**Comment by fr500** [comment]
You're probably forcing vsync via control panel

**Comment by DJMATTTAM** [comment]
Ah, you're right.  I had the setting set to "Use 3D application setting" instead of "Off".  Sorry for that!  Thanks for your help!

**Comment by lodgerz** [comment]
i have same problem: fast forward works only in windows mode, if i set fullscreen nothing happens.
My configuration:
CPU: Intel J1900 with integrated GPU Bay Trail
OS: ArchLinux 64bit with Linux 5.4.13
Version: retroarch 1.8.4-1
