### ISSUE TITLE
Allow Scanning ScummVM Games

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#3092]
With https://github.com/libretro/libretro-database/pull/138 , we added a [ScummVM.dat](https://github.com/libretro/libretro-database/blob/master/dat/ScummVM.dat) file that indexes [all ScummVM short names](http://scummvm.org/compatibility) in `.scummvm` files so that we can automatically launch games without going into the ScummVM interface.

Now that the DAT file can be indexed by RetroArch, we need to have it scan the `ScummVM.rdb`, and create a playlist out of the found `.scummvm` files. Anyone know how to do that?

### Test

1. Make sure to have [the latest ScummVM core](https://github.com/libretro/scummvm/pull/40)
1. Load the RetroArch ScummVM core and add Atlantis in the ScummVM interface
1. Create a `atlantis.scummvm` file with the contents `atlantis`, without a new line character at the end.
1. Scan the directory
1. Expected is to see a new ScummVM playlist with *Indiana Jones and the Fate of Atlantis* as a menu item, but that currently doesn't work.

**Comment by lollo78** [comment]
Hi!
I done some test. Here it's very late. I'll retry better tomorrow ;)
It doesn't work also for me (complied commit 611b95f).

But f the file is .scummvm Retroarch doesn't see it (try to load it from Select File).
If I rename it in .scum I can load the game directly, without to see the ScummVM GUI (black/green).

At the same time, if the file is .scummvm the scanning procedure finish quickly (it can't see any file inside the folder). But with .scum the scanning routine found the file, but it doesn't create the ScummVM.lpl file inside the playlist folder. :(

I tried with "The Dig" game. But I had to change your .dat and convert it in .rdb, because my scummvm file have different size and CRC...
```
game (
	name "The Dig"
	description "The Dig"
	rom ( name "The Dig.scum" size 7 crc 3151476635 )
)
```
This happens because I use the italian version of the games. So, if for you "dig" is the right word to put in the .scum file, for me is "dig-it". 
For this reason, create an universal .dat could be very difficult. 
But if it will work could be so nice!!! 
I just done an alpha icon set for ScummVM :D 
https://github.com/libretro/retroarch-assets/pull/28
lol!  


I think that crea

**Comment by Kivutar** [comment]
The default scanning process is based on the CRC of the content of the zip. And it also requires the ZIP extension.

So you have two choices:

 * Enabling scummvm extensions in the task_database and give it the same behaviour as a zip + having the crc of the content (a single file) in your RDB
 * Adding scummvm to the list of supported extensions in scummvm's core info file, and having the crc of the zips in your RDB, like we do for FBA.

**Comment by Kivutar** [comment]
What does those .scum contain? Are they text files or archives?

**Comment by RobLoach** [comment]
Indiana Jones and the Fate of Atlantis.scummvm
```
atlantis
```

Without a newline at the end.

**Comment by RobLoach** [comment]
I believe this is working now. Just needs a rebuilt `ScummVM.rdb`.
