### ISSUE TITLE
(Cheevos) Tries to load cheevos for built-in ffmpeg core, causes big delay in startup time

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3210]
@leiradel When achievements are enabled and we load a movie file from Load Content (with the built-in ffmpeg core - Windows), cheevos thinks it's a NES ROM and tries to load cheevos for it. 

This takes a long time before the movie file is actually started up. I think we should disable this code for movies.

**Comment by RobLoach** [comment]
Should libretro ask the core whether or not cheevos are supported? Or have it toggle an environment variable if the support is there?

**Comment by leiradel** [comment]
There is an environment call `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` that cores can call to signal the front-end that they support achievements. It was added because some cores would give random achievements to the player out of nothing.

For now RetroArch must assume all cores support achievements because not all cores are calling `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS`. We should add that to the ones that do support achievements and make RetroArch assume cores don't support.

When that environment call was created, it was assumed it would be a temporary solution to the problem of players receiving random achievements, but maybe we should consider leaving it there to avoid the front-end going to RetroAchievement to recognize the content when it shouldn't.

**Comment by leiradel** [comment]
The `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` call was created as a temporary solution to prevent a situation while we took care of core compatibility with cheevos. Now that we have this issue, I wonder if we should make it permanent, or if there's some other way to solve the issue without the call.

@Alcaro, do you see a different solution for this issue, or are you ok about making the call permanent?

**Comment by Alcaro** [comment]
Adding an env for a too specific use case will make us look unprofessional to everyone else trying to use libretro, especially if it's just a boolean and the front is expected to find the cheevos by itself.

Instead, the following solutions are approved:
- Make chev loader non-blocking. Chevs don't need to run from the first frame, anyways, there's no achievement for "defeat the mysterious boss known as the title screen".
- Making the ROM detector less dumb. If it specifically detects NES, then there is a detector and we can make it return "definitely nothing here" for videos; if it just md5s and sends to retrochev, then the issue is stupidly worded.
- An env that says "hi, I'm a NES emulator" and lets the front interpret it however it wants - but then I expect that present on cores that don't support chevs as well. If we need this env back after that, we could put a flag in the info files or something? They're not part of the API, we can break them if we want.

**Comment by leiradel** [comment]
#1 is desirable independently of this issue, but it alone wont't prevent RetroArch from hashing a huge ISO and contacting RetroAchievements to check if it's a known game.

The ROM detectors were not our choice, we're only using what RetroAchievements use, so I don't see if #2 can be implemented.

Putting a flag into the `.info` file stating that the core supports cheevos seems like the best options to me. If everyone agrees I'll start to implement it and remove the environment call afterwards.

**Comment by Alcaro** [comment]
If RetroAchievements does something silly, submit a PR. If we can't do that, fork it.

Hashing sounds like a different issue, but far easier to solve: Find the biggest ROM supported by Ach (or guess that it's 32MB) and hardcode that size in RetroArch, and don't bother asking for chevs for anything bigger. Or return 0000000000 or something, that shouldn't give any results.

Or dump it on a thread or something.

**Comment by leiradel** [comment]
So adding a flag to the info file it is?

**Comment by Jamiras** [comment]
I believe this can be closed. 

>  Find the biggest ROM supported by Ach (or guess that it's 32MB) and hardcode that size in RetroArch

There's been a 64MB limit to the hashing code for quite some time:
https://github.com/libretro/RetroArch/blob/a2cfc881a479cb7cd27731e38ba36dc3c80a1cb5/cheevos/cheevos.c#L2331-L2333

It still hashes the 64MB, but that's better than trying to hash a multi-GB movie file.

Additionally, if the core specifically sets `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` to false, we won't even try to hash the file at all.
