### ISSUE TITLE
Opening Privacy submenu locks you in

### ISSUE THREAD

**Issue by Axiphel** [libretro/RetroArch#3216]
If you go into the Privacy submenu you can't back out of it. The only way to leave is to just close out of Retroarch.

**Comment by parkerlreed** [comment]
_Too private_

**Comment by twinaphex** [comment]
This probably only happens when there are no camera or location drivers available. This might happen on certain system configurations if you compile RetroArch from scratch, or maybe on targets like Windows where none of the two are currently available.

Anyway, I will add a default 'no entries' entry in case there is none to it, that should fix it.

**Comment by twinaphex** [comment]
Should be fixed now with this -

https://github.com/libretro/RetroArch/commit/1035029a89d719bd3dc1f05793eb0f3dfe0a839d
