### ISSUE TITLE
File picker does not work with special characters.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3273]
`RetroArch-1.3.6-x86_64-1_SBo`

Any files or directories that have special characters like `#` will fail to display properly  in the RetroArch file manager.

For example I have `Echo Night #2 - Nemuri no Shihaisha (J)(ENG).cue` where the file manager will only see `2 - Nemuri no Shihaisha (J)(ENG).cue` and expectingly will fail to properly load the cue file.

A simple work around is to of course just rename the file to not include any such characters, but it should just work as almost all if not all unix file managers do not trip on this.

**Comment by fr500** [comment]
Hmmm yes this is an issue. 
Problem is we use # to define a compressed archive (someone contributed that code and we kept using the convention I guess)

**Comment by Alcaro** [comment]
Problem 2: We can't switch it to | or > or some other character that Windows doesn't support and therefore nothing uses, since SRAMs and similar are saved to /home/orbea/roms/mario.zip#mario.srm.

Problem 3: Every other character in the ASCII table is used by something (except controls, but they're crazy in their own way, and high-ASCII, which we don't want since that's not valid UTF-8).

One possible solution (possibly the only one?) would be switching the archives to use a multi-byte delimiter, but that requires a fair amount of effort nobody has stepped up to do.

**Comment by bparker06** [comment]
What about checking if the pre-# part of the file exists before treating it as compressed? Is that an acceptable solution?

**Comment by orbea** [comment]
Its now solved for me, thanks!
