### ISSUE TITLE
Request for Addition of FFIII Nes Translated into RetroArch XMB

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#3359]
game (
	name "Final Fantasy III (Japan)"
	description "Final Fantasy III (Japan)"
	rom ( name "Final Fantasy III (Japan).nes" size 524304 crc 74F03BBF md5 E67E650FC4762FADEE5805713801310E sha1 E183203762D2621B719CFBD5C6F65BA0051E04AA )
)

Final Fantasy III (J) [!] [En by A.W.Jackson+Neill Corlett+SoM2Freak v1.1].nes

^ Patched rom info

Original Rom Info:

    Final Fantasy III (J) [!].nes - GOODNES 3.14
    CRC32: 170163F1
    MD5: 4E9BDCDD1071FF48638A3AA0FDA325FC
    SHA-1: C4443FC24625E3C2BB859525EB44B6B3A80E7C35

Translation Patch used:
http://www.romhacking.net/translations/141/

I would like for this version of the rom to be able to be shown in the RetroArch xmb. The original game shows fine. But the translated one does not. The Nestopia library was used.

**Comment by MarcoEstevez** [comment]
Well... while adding a rom-hack to the officially releases dat files could be a non sense, I kind of miss the ability to add modified roms to playlists, and I can easily imagine the complexity on doing that, but would it be possible for retroarch keep track of 2 files internally for playlist, the official one, and a custom one, so the users can manually add entries to that so that way then RA shows on the UI, basically fill the entry with the name of the file and CRC, then users can manually add Boxarts and maybe son more info.

There are quite many good translations out there and rom hacks worth to treat them on RA amazing GUI.

**Comment by shinra358** [comment]
For retroarch to apply the ips patch itself instead of the user manually patching it would also be a good idea and would allow for no extra additions to the dat file.

**Comment by MarcoEstevez** [comment]
Well... I'm not sure if for all roms (on any core) can be applied patches on the fly.

**Comment by shinra358** [comment]
A few of the original emus can do it. So hopefully it could be coded in to do so in some form or fashion.

**Comment by Alcaro** [comment]
Our ROM list is No-Intro, and we'd rather not mess with it.

We have softpatching support already, via --ips/--ups/--bps. At least for most cores (can't really softpatch 600MB PlayStation ISOs or multi-file Dosbox setups), but NES shouldn't have any trouble.

Not sure if it's possible to trigger from the GUI, though.

**Comment by fr500** [comment]
You literally don't have to do anything, it applies the patches immediately if found.
Anyhow this isn't a retroarch issue, if you want something in the database this is the correct repo
https://github.com/libretro/libretro-database

**Comment by shinra358** [comment]
Okay, didn't know that. Where should I place the ips patch for it to locate it?
