### ISSUE TITLE
Multiple Mice Support, Lightgun etc

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#3443]
Many games featuring multiple light guns, steering wheels, spinners, etc. are well emulated by libretro cores but cannot be enjoyed in RetroArch.

From my understanding, this limitation exists within the RetroArch input system. It would open up a lot of functionality if there was a way for multiple mouse devices to be used to support more than one player in these games.

**Comment by markwkidd** [comment]
It might be a way to address this use of mouse devices as well: https://github.com/libretro/RetroArch/issues/2783

**Comment by Dagnillo** [comment]
I second this.  I've yet to find an emulator for Android that handles the SNES mouse properly.  I don't know if it's a system limitation or something that can be implemented, but it would be nice.

**Comment by dankcushions** [comment]
@Dagnillo libretro cores do support a single mouse (or 'pointer', for absolute coord devices) no problem (IF the core implements it). This issue is for more than one mouse (and i guess pointer also)

But yeah, multiple mouse support would be really cool for https://github.com/libretro/mame2003-libretro and other arcade cores. Some arcade games use more than one trackball/spinner etc.

**Comment by Dagnillo** [comment]
Somehow I missed the "multiple" in the title, now I feel stupid.

**Comment by markwkidd** [comment]
This exists now. Closing!
