### ISSUE TITLE
Setting to confirm before quit

### ISSUE THREAD

**Issue by jjnilton** [libretro/RetroArch#3485]
Quit key (<kbd>Esc</kbd> by default), quits the application without any confirmation. Could have an option set it to ask to confirm before quit or maybe a different input option that would quit with confirmation only, to avoid quitting the application by mistake.

**Comment by brandleesee** [comment]
Happened a couple of times to `Esc` while Online Updating with the intention of minimising from full screen....

**Comment by twinaphex** [comment]
Some would consider this a feature, in some Japanese games on PC, Esc will immediately quit the entire application.

Some don't like this in the west, the best we could do is add an option so that the 'quit behavior' could be modified, maybe bringing up a 'warning' dialog. But anyway, the point is, the current behavior is not 'wrong' or a 'bug', it is simply something that your preferences do not align with. We can try devising a workaround but it will be optional for you to toggle on/off.

**Comment by Dem-Gainz** [comment]
Short Story: Do NOT make this default.

Long Story: This feature sucks. Creates more issues. Just another option to change. You made it by default too. The solution was for the individual user to change their hotkey. Isn't Start + Select one of the most popular ones since people use controllers on console games, and not a keyboard? Are people accidently pressing this multiple times in a game? How would a confirmation prevent accidently button presses twice? Why not make it 10x on default? That was sarcasm proving a point to not create a feature when someone doesn't want to change their existing settings. And you gave in AND made it default. 

Also can you create more menu options in the settings? I can't even find this one, but soon will. Please create more with more options so people can rely on Reddit to find anything in the app. Thanks!

**Comment by Dem-Gainz** [comment]
Since google sucks at finding this option and redirects me here, and your sweet merge comment with no useful information, for the majority now looking to disable this, go to Setting -> Input -> and scroll down to "Confirm Quit" to disable this. 

Since it is 2022, and there is lots of frontends, not to mention the classics that have always been here, creating one more to do item for a frontend is not user friendly. Remember in Jurassic Park, when Jeff Goldblum suggest that just because the scientist could do something should NOT imply they should do something. Great question to ask when considering new features.

**Comment by hizzlekizzle** [comment]
Everyone thinks their usecase is the only legitimate one, and their preferences are the "correct" ones for everyone.

In any event, rants like this are not an effective way to communicate with people who work to create, maintain and support any software, but particularly not open source software. Not only does it contribute to burnout--which is already an epidemic among OSS developers--but it simply isn't likely to convince anyone to implement your request.

**Comment by Dem-Gainz** [comment]
I am not the only person using Frontends. RetroPie, Batocera, Dig, Launchbox / BigBox, Retroid Pocket Launcher, and many many more. Not only is your hyperbole false, but in product development, making new features enabled on by default that didn't exist before might break things it relies on like Frontends and Current User behavior. At a real company, with real money, they make decisions with this in mind. If there were actual OSS developers who actually wanted to improve Retroarch, I can go on and on. Create a JIRA ticket. Create test cases in some software like Testrail. I don't have those options. I have Github.

You are avoiding the issue of the problem, and instead want to question my communication effectiveness and over dramatize it by talking about burnout and calling it an "epidemic." I find your comment ineffective. I find changing the subject to how people need to act and communicate for your personal prejudice can lead to burnout for the community. 

I am here to make the product better, not make OSS developers emotionally complete. I am not your QA Engineer. I am a end customer. Go work for a real company, and see how real customer communicate. There are way more brutal, and I could only imagine how dramatic your language would get in response.  

Before I go I will reiterate the organization of the settings are a mess, and lots of the default configurations are questionable.  Configuring a controller is a nightmare. Look at the DINPUT support vs XINPUT support. 25 to 195. What is the default setting? XINPUT on Windows. What are all but one of 8bitdo controllers configured under? DINPUT. Which doesn't support rumble. So it thinks its an xbox controller instead. ALL of it is bad product design. Period.

**Comment by hizzlekizzle** [comment]
Feel free to raise a ticket with our Customer Satisfaction Department and they'll issue you a full refund.
