### ISSUE TITLE
Make livestreaming to Twitch intuitive

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3745]
It's already possible to do this right now but it requires a lot of manual configuration which is outside the skill level of most users.

**Comment by fr500** [comment]
There are two ways to connect to twitch, we either build an authorization client and get the data ourselves, user would need to enter user and password, needs SSL too.
https://dev.twitch.tv/docs/authentication

Or we use an API key (which is the only we we can stream now)
In any case the limitation is inputting long text strings, so that would be the first thing to do.
