### ISSUE TITLE
"Load Archive With Core" Broken When Loading 7z [Regression]

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#3767]
Trying to load 7zipped single ROM files causes RetroArch to instantly close in the latest nightly. Then I have to kill it from the task manager. I have a nightly from 9/22 where they work fine. Uncompressed and zipped ROMs still work fine on the latest nightly.

**Comment by fr500** [comment]
Maybe @bparker06 can take a look, re-factored this a few weeks ago.

**Comment by bparker06** [comment]
Hi @Awakened0, I'm not able to reproduce the issue... can you provide some more information? A good start would be:

- the git version of your nightly build (Information -> System Information -> Git version)
- the platform you're running RetroArch on
- the core that is being used (and do you load the core before the content or are you choosing one after selecting "load with core"?)
- the output of "7z l somefile.7z"

Since you mention that RA doesn't technically close, but you're having to kill it, are you able to provide a gdb backtrace from that point? If not, we can start with the above information and see if that leads us anywhere first. Thanks

**Comment by Awakened0** [comment]
Git Version: 9561b55
OS: Windows 10 Anniversary
Core: I've found it happening with Glupen64, Genesis Plus GX and PCE_Fast so far.
Output: Dunno what you mean by this. I'm testing the same games that work in the old nightly.

When I backtrace, I get a second command prompt for retroarch_debug that stops on the line:

> RetroArch [INFO] :: Environ PERFORMANCE_LEVEL: 5.

Then all I can do is close that prompt. When I then type "bt" in the gdb prompt I get "No stack."

**Comment by bparker06** [comment]
By output I mean running the 7z command-line utility on the file in question so that it will show things like the compression method and file listing within the archive... I understand that it worked for you before, but since I cannot reproduce it, I wanted to see if there was a fundamental difference between your archive and the ones I test with.

Regarding the backtrace, what are you doing before running bt exactly? Did you already kill the process? To see what RA is doing that's preventing it from moving forward, we need to interrupt its execution at the point where it "goes away" but before you kill the process, this should mean pressing ctrl-c in gdb to pause the process, where then you can get the backtrace. Perhaps a paste of the full gdb output would be helpful... also "thread apply all bt" instead of just "bt" will probably be more useful.

**Comment by Awakened0** [comment]
Ok, here's 7z's output:

> 7-Zip [64] 16.00 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-10
>
>Scanning the drive for archives:
>1 file, 714646 bytes (698 KiB)
>
>Listing archive: Advanced Busterhawk Gleylancer (Japan) [En by MIJET v20061023].7z
>
>--
>Path = Advanced Busterhawk Gleylancer (Japan) [En by MIJET v20061023].7z
>Type = 7z
>Physical Size = 714646
>Headers Size = 234
>Method = LZMA2:20
>Solid = -
>Blocks = 1
>
>   Date      Time    Attr         Size   Compressed  Name
>------------------- ----- ------------ ------------  ------------------------
>1996-12-25 00:32:00 .....      1048576       714412  Advanced Busterhawk Gleylancer (Japan) [En by MIJET v20061023].md
>------------------- ----- ------------ ------------  ------------------------
>1996-12-25 00:32:00            1048576       714412  1 files

As for gdb, this time I tried leaving the RetroArch command prompt up after RetroArch itself closes. Doing ctrl+c on the gdb prompt didn't let me type anything, but ctrl+c on the RA prompt let me do the "thread apply all bt" in the gdb prompt: http://hastebin.com/yoxutiteva.php

**Comment by Awakened0** [comment]
Woops, would have helped if I hit Enter a few times to get the rest of the output. Here's the rest: http://hastebin.com/equlobeyiz.tex

**Comment by bparker06** [comment]
Can you try with a simple filename for the 7z? It looks like it may be getting confused with the special characters.

**Comment by Awakened0** [comment]
Ok, here's with AlienSoldier.7z: http://hastebin.com/ubigajawap.cs

**Comment by bparker06** [comment]
Hmm, that doesn't make a whole lot of sense. Do you have any kind of antivirus/spyware/etc. software running? If so can you try disabling it temporarily?

**Comment by Awakened0** [comment]
No, I have anything like that running.

**Comment by Awakened0** [comment]
It pry doesn't help much, but the build I have that works is git version: 9179b6b

**Comment by Awakened0** [comment]
Ok, this should narrow it down more. There are a few old builds on the buildbot, so I tried a few and the last one on there that works is the 2016-10-08 one, git version: 5f5571e. So something between that and 9561b55.

So it was something recent. The only major change I know between those two is the new command prompt hiding feature when verbosity isn't enabled.

**Comment by bparker06** [comment]
fixed in f0d1a73.

**Comment by Awakened0** [comment]
Confirmed!
