### ISSUE TITLE
XMB shortcut between QuickMenu and Settings

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3789]
Please consider adding a "Go to General Settings" at the bottom of Quick Menu.
It would just bring you there, at the 2nd list of the horizontal menu.

Then to go back to Quick Menu you just have it on your left in the 1st list.
(or add a "Go to Quick Menu" in this list too perhaps? doesn't hurt to have it in different places as many people starting with Retroarch seem to miss it)
(it could be renamed "In-Game Menu" btw)

Right now it's quite tedious to go through all those playlists (some quite long to load), especially when testing stuff.

**Comment by fr500** [comment]
Well, even sony embraced our term "Quick Menu" in the PS4 :p

**Comment by Tatsuya79** [comment]
Alright, people should get it now then! :)

**Comment by lasers** [comment]
There are several cores that had nothing to do with the `Game Menu`as it is mostly for emulators only. We could stay with `Quick Menu` or to something generic like `Core Menu`. One day, RetroArch might break their promise because there was nothing `Quick` about that `Menu` anymore. 

* `Game Music Emu` (Play music)
* `Imageviewer` (View images)
* `PSP RemotePlay` Display video from a real PSP
* `2048` (A game itself)
* `Dinothawr` (A game itself)
* `RemotePad Remote` (Use controller on a different RetroArch)

While we're still here about `Quick Menu`, I would like to suggest that we make a new menu (just like Cheats and Shaders) for `Saves`.

* `Save Slot`
* `Save State`
* `Load State`
* `Undo Load State`
* `Undo Save State`

**Comment by Tatsuya79** [comment]
Or perhaps a key that would bring you back at the "Main Menu" root?
R2 or something unused.
