### ISSUE TITLE
Different results for NES ROM hashes in cheevos.c

### ISSUE THREAD

**Issue by leiradel** [libretro/RetroArch#3855]
The way NES ROM hashes are computed are completely different depending whether the core needs the content's full path or not, and the correct one is the one that reads the ROM contents from the file system.

**Comment by meleu** [comment]
@leiradel is it still an issue? can you give some examples/ways to reproduce?

**Comment by leiradel** [comment]
Actually no, this has been long fixed.

**Comment by retro-wertz** [comment]
im not sure if this is related but NES often misses detecting the game ID, for example Contra is suppose to be 1447, but most of the time its detected as 8928 which give you 0 of 0 Achievements... and YES, i have a stable internet and standalone ranes works just fine with regards to connecting to achievements.

**Comment by leiradel** [comment]
@retro-wertz can you post the log output when you start this game?

**Comment by retro-wertz** [comment]
here is log if cheevos is not detected properly:
https://hastebin.com/icuzadeyeq.sql

here is when its fine:
https://hastebin.com/suyofosada.sql

thanks

**Comment by meleu** [comment]
Looks like a network problem/lag on the server side resulting on a timeout when trying to get the game ID using the hash calculated with the "NES-method". And then RetroArch tries to get the game ID using the plain MD5 hash.

The plain MD5 hash is clearly bad linked. I'll try to fix it tonight.

@retro-wertz thanks for the report.

**Comment by leiradel** [comment]
I'll change the cheevos implementation to stop trying to get the game ID if there's a network error to avoid this situation.

**Comment by meleu** [comment]
@leiradel is timeout considered a network error?

I'm asking this because although RetroArch failed to get the game ID for the NES-style hash, it succeded to get the game ID for the plain MD5 hash. It makes me believe that there is NOT a network error, but just a timeout due to a lag on the server side.

**Comment by retro-wertz** [comment]
i am not sure if the latest update is suppose to help this issue, but im constantly getting this instead:
```
[INFO] [CHEEVOS]: got game id 0.
[INFO] [CHEEVOS]: this game doesn't feature achievements.
```
i have not been able to succesfully connect yet since the merge.

interestingly, ranes doesn't seem to have problems connecting, even if i always cleanup RACache folder to get data directly from the server.

**Comment by retro-wertz** [comment]
not sure if there are recent commits related to NES cheevos, but the mis-identification of game ID is back, and since commit, i had more 0 achievements issues than before, its mostly not connecting

**Comment by fr500** [comment]
If it fails there it's probably a server error...

**Comment by retro-wertz** [comment]
standalone RAnes is able to connect all the time...

**Comment by fr500** [comment]
Well... 
I'm just sayin' that I'm on the latest trunk for  RA and fceumm and I cannot reproduce...

![image](https://user-images.githubusercontent.com/1721040/31415116-fd62ca3e-ade6-11e7-87bf-1d00e39ac56a.png)

**Comment by retro-wertz** [comment]
good for you then... i wonder how many times you reloaded core and get success rate. 

as far as my testing goes, ranes has no issues connecting while retroarch (quicknes or fceumm) OFTEN if not all the time connects to a wrong game ID.

if thats not valid test since it seems looks like im just making something up, then its fine with me................. disregard the testing updates and thank you.

**Comment by fr500** [comment]
I tried right now 10 times all of them succesful.

Try to relax, I'm not disregarding anything or saying you're making it up. I'm just saying that I can't reproduce the issue. That's all.

**Comment by meleu** [comment]
hey @retro-wertz , you deleted your comments but I have them on the email.

Did you solve your issue? Should I ignore your reports? Please, help us to make RetroArch more compatible with RetroAchievements.

**Comment by retro-wertz** [comment]
No, i have not solved it, although i think i know what is going on...

First, this seems to affect only Linux(currently using Arch). Windows 10 doesnt seem to have this issue.
Second, this only seems to happen with NES( and who knows it could just be me and my system).
Third, i think cheevos is trying to connect too fast or too early(ill explain later) hence the error.

From my understanding, when connecting with NES, it calls NES_MD5 then the md5 is used to GET_GAMEID. when this fails, GENERIC_MD5 gets called instead to recompute for game ID hence the wrong ID and 0 of 0 Achievements.

Now, my workaround(and is no way a fix but probably have will give idea how to fix this) is since when NES_MD5 fails due to whatever reasons(my guess is it tried to connect early or to quick during the 1st loop) and it passes to GENERIC_MD5, i just copy the code from NES_MD5 into GENERIC_MD5, so that when 1st run fails, it will re-process the nes md5(since we replaced it with nes md5's code) from GENERIC_MD5 instead, and this method worked fine and i dont have incorrect game ID.

The issue is in CORO_SUB(HTTP_GET), specifically HTTP = net_http_new(CONN); returns false hence the error, I am wondering, if CONN is valid, maybr a retry to HTTP is needed incase this fails the st time.

@meleu

**Comment by meleu** [comment]
I was thinking about adding the plain MD5 hash to the Contra hash library on RetroAchievements database. I think it will solve your issue. But maybe would disserve your investigation... Would you like that I fix this on RetroAchievements database?

**Comment by leiradel** [comment]
I talked to GameDragon about NES hashes and they're not being updated, so the issue is on my side and I'm pretty sure it's related to network timeouts.

Retro Achievements user base has grown recently and the servers are having some difficulties in keeping it up with the requests, and since RetroArch gives up on the first error, games are not being recognized.

I'll implement retries for achievement network connections.

**Comment by retro-wertz** [comment]
thanks for looking at the issue, please let me know if there are tests i can help with.
