### ISSUE TITLE
Regression: option of quit confirmation is absent

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#3938]
Hello.

This regression related to #3485 and #3486.

This option (confirm on exit) doesn't exist anymore in Retroarch UI.

**Comment by lasers** [comment]
https://github.com/libretro/RetroArch/commit/5d28029be893db3edd43c13b87e48d83148a9a36

**Comment by ofry** [comment]
Thanks for bisecting.

@bparker06 Why you deleted this option?

**Comment by twinaphex** [comment]
It wasn't working correctly so it got taken out for now. It's not a regression.

**Comment by movisman** [comment]
@twinaphex 

Hi there,

Randomly stumbled on this issue whilst looking for this very option. Will it be something that may be reintroduced one day? For my use case, having a 'confirm on exit' option is useful when guests accidentally press hotkey+exit (which is what I have configured to quit).

Also, having a "confirm on exit" means I could actually just have my center Xbox icon button configured to exit rather than having a requirement to hold a hotkey first, which makes it easier for people to quit out, but still asks them if the button is accidentally pressed.

Would be a good feature I think for those wanting to run in a kiosk style mode.

Cheers
