### ISSUE TITLE
Retroarch hangs on mupen/glupen on Linux/radeonsi

### ISSUE THREAD

**Issue by BPaden** [libretro/RetroArch#3986]
Using a git version of retroarch and the nightly version of mupen/glupen, running an n64 title will hang indefinitely for me. There is no console output unless you enable verbose mode.

The cores do work with Retroarch 1.3.6.

I'm uploading two files, the verbose log and also a backtrace of the running process after it hangs.

[rarchlog.txt](https://github.com/libretro/RetroArch/files/587106/rarchlog.txt)
[backtrace.txt](https://github.com/libretro/RetroArch/files/587107/backtrace.txt)

**Comment by orbea** [comment]
Using the nouveau (nvc0) which is another mesa gallium driver I can not reproduce this.

Can you please take some steps to help debug this?

* What commits of RetroArch, mupen64plus-libretro and GLupeN64 are you experiencing this with?
* Can you reproduce this with a fresh configuration file?
* What distro and mesa version are you using? Does it still occur with a git version of mesa?
* Does it still occur with llvmpipe? Mesa will need to be compiled with llvm and you can test if you can use it with:
```
$ LIBGL_ALWAYS_SOFTWARE=1 glxinfo | grep 'OpenGL renderer'
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.8, 128 bits)
```
And you can use it with RetroArch:
```
LIBGL_ALWAYS_SOFTWARE=1 retroarch -L /path/to/core /path/to/game
```
* Can you bisect it between RetroArch's 1.3.6 and its master?
* Can you install apitrace and get a trace of the crash? It can be done with:
```
apitrace trace retroarch -L /path/to/core /path/to/game
```
It can be replayed with:
```
apitrace replay foo.trace
```
And before you upload it somewhere you should compress it.
```
xz -9 foo.trace
```
* If the issue is still not clear please contact amd devs and show them this issue along with the above information.

**Comment by BPaden** [comment]
Hm, sorry, it's a bit of an obvious step, but the cores do seem to work with a fresh config dir, which means just my configuration was broken in some commit. I don't know if you support configs between releases - if not this can likely be closed.

**Comment by orbea** [comment]
If you still have your old config you may be able to narrow down the problem to a specific setting by copy pasting sections of it into your current one until you can reproduce and then narrow it down similar to a bisect. It may take some work on your part, but it could be helpful if it finds a problematic setting.

**Comment by marioevz** [comment]
Hi, I had the same problem, latest mupen64 and latest retroarch would crash when loading a game. A clean config file seemed to correct the problem. So I went through the process of copying every parameter from conflicting config file to the clean config file. The problem appears to be the setting "savestate_auto_load". When set to "false", games run as usual, but when set to "true", retroarch crashes with a Segmentation Fault error. It seems like mupen doesn't like previous versions savestates.

**Comment by BPaden** [comment]
This is going to be a different issue, because I was experiencing a hang rather than a segfault, and I don't really use savestates. When I get a chance, I'll go through my old config and see if I can't reproduce exactly what was causing the issue.

**Comment by orbea** [comment]
@BPaden Can you try again with a nightly and a recently built core? There were some improvements that should hopefully have helped with radeonsi and GLideN64.

See PRs https://github.com/gonetz/GLideN64/pull/1960 and https://github.com/libretro/mupen64plus-libretro/pull/81.

Also this is a core issue and not a RetroArch issue, your experience will probably be better with parallel-n64 or using upstream mupen64plus + GLideN64. If its still a problem and you want to pursue it more open a issue for the core tracker.

https://github.com/libretro/mupen64plus-libretro/issues

Or if its a problem upstream too then try there.

https://github.com/gonetz/GLideN64/issues
