### ISSUE TITLE
[Android] RA is not opening, no crash apparently

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#4017]
RA is not opening on android, no crash apparently. It was working until yesterday.

**Comment by sergiobenrocha2** [comment]
Trying with 750165a, still closing

**Comment by retro-wertz** [comment]
try to clear apps cache, or reboot device. else try to get debug mode to get to work(no idea on android version) or better a logcat.

**Comment by Quickgold74** [comment]
the same thing happend to me with android 4.1 and 4.2 (but for some reason works fine in 4.4.2) I did all clear cache, reboot device and nothing, 1.36 stable works fine for me like and old nightly version.

**Comment by twinaphex** [comment]
One commit pushed 18 days ago broke Android 2.3 compatibility for me, so I fixed that at least here - 

https://github.com/libretro/RetroArch/commit/e27940e64696e58922e90f08a8a7eb09c552ee5e

Not sure if this is related to this issue here though. Try out if the latest version of the trunk still crashes on your end, or wait for the latest latest nightlies.

**Comment by sergiobenrocha2** [comment]
It's working, thanks!
