### ISSUE TITLE
(Menu) Pressing Enter key confirms twice when doing a search.

### ISSUE THREAD

**Issue by Monroe88** [libretro/RetroArch#4073]
Pressing X or "/" to bring up the OSK for a search, typing in a term, then pressing the Enter key causes the search to confirm then immediately confirms what was selected. 

Pressing Start on the gamepad does not confirm twice and the search simply jumps to the entry that matched the search.

**Comment by lasers** [comment]
Do you have `input_osk_overlay_enable = "false"`? Try again with true. Same behavior?

**Comment by Monroe88** [comment]
It was false and setting it to true made the Enter key only confirm once. Is there a purpose for that setting anymore since the OSK is always on now?

**Comment by lasers** [comment]
Great news! You're not alone. I experienced this bug too. https://github.com/libretro/RetroArch/issues/3982

I don't know why it's always on despite the setting and I can recall seeing no keyboard in the earlier verisons. I just think OSK is either not perfect or broken because as you mentioned, that setting really should make OSK really go away.

Also, keeping it `true` does not make the problem fully go away. It reduces the said problem from 100% down to at least 5% so you will still experience the occasional hiccups.

**Comment by fr500** [comment]
`diff --git a/input/input_keyboard.c b/input/input_keyboard.c
index db4d979..35d510f 100644
--- a/input/input_keyboard.c
+++ b/input/input_keyboard.c
@@ -99,7 +99,7 @@ static void input_keyboard_line_toggle_osk(bool enable)
 {
    settings_t *settings = config_get_ptr();

-   if (!settings->osk.enable)
+   if (!settings->osk.enable && !input_driver_is_onscreen_keyboard_enabled())
       return;

    if (enable)
diff --git a/menu/widgets/menu_input_dialog.c b/menu/widgets/menu_input_dialog.c
index b6e232c..83fbd07 100644
--- a/menu/widgets/menu_input_dialog.c
+++ b/menu/widgets/menu_input_dialog.c
@@ -93,7 +93,8 @@ bool menu_input_dialog_get_display_kb(void)

 void menu_input_dialog_display_kb(void)
 {
-   menu_input_dialog_keyboard_display = true;
+   menu_input_dialog_keyboard_display = true;
+   input_driver_set_onscreen_keyboard_enabled();
 }

 void menu_input_dialog_hide_kb(void)
`

Try that diff

**Comment by lasers** [comment]
Let me know if I did it wrong. I used "git apply lol.diff" -- It didn't work. Good thing it's only two lines... What am I looking for in this new changes? I got it on `false` and the OSK keyboard are still being displayed. Is this to get rid of that last 5%?

**Comment by retro-wertz** [comment]
is this related to pressing ENTER on keyboard is like pressing ENTER twice while START on gamepad behaves as one ENTER key should be? like when doing a game search instead of moving to the game tile, it selects it instead? or when you enter credentials like username/password in user accounts pressing enter returns you to the input screen?

**Comment by lasers** [comment]
Yes. Yes. Yes (If you're talking about getting stuck in the keyboard screen prompt).

Check if you have `input_osk_overlay_enable = "false"` too.

**Comment by retro-wertz** [comment]
yes. its false. running ra_x86_64

**Comment by lasers** [comment]
Switching to `true` should make it go away. RetroArch x86_64 here too.

**Comment by fr500** [comment]
the workaround doesn't work in the current code because the overlay OSK is
no more
It will be fixed soon enough

**Comment by bparker06** [comment]
Commit b9c6fa5 fixed this for me.

**Comment by Monroe88** [comment]
Confirmed fixed. 'input_osk_overlay_enable' has been removed too so it no longer shows up.
