### ISSUE TITLE
Remove Filter unknown extensions

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#4090]
Pressing `Start` should toggle `show_hidden_files` and refresh the list in same place.

**Comment by fr500** [comment]
Pressing start # WHERE ?

**Comment by lasers** [comment]
Anywhere as long as you're browsing in some directories. Could that be done?

**Comment by fr500** [comment]
See that actually could be a good idea.. but when you just say stuff with no explanation it's either annoying or ignored.

**Comment by Kivutar** [comment]
It's difficult in xmb to add/remove menu entries on the current list without causing glitches.

**Comment by lasers** [comment]
@fr500 I don't like to use filter. Every time I go in, I toggle it off... only to get it back later on my next visit because there is no such setting to keep the filter off. I think it's trivial to focus on supporting game extensions and just go with all.

@Kivutar How about making a new list and push the user to that new list just like one would navigate through directories or settings? We would see the pleasure effect happening and if possible, avoid the bugception (looping directories).

**Comment by fr500** [comment]
@lasers we won't change complete behaviors because of "**I don't use it**
There are more users than just you

**Comment by lasers** [comment]
Phhft. I think it's best to take advantage of `show_hidden_files` more often than you do right now. Abuse that option all you want. Two options. All or normal.

I brought this up not because I don't use it (Well, I kept trying to turn it off, you guys just won't let me)... but also because I think `Filter unknown extensions` can be confusing and a tad frustrating sometimes due to lack of feedback. Take it from somebody who are also testing things just like you.

I agree with @sergiobenrocha2 that "Parent directory" does not make sense in zipped directories, but this "remove filter unknown extension" problem may be coming from looping directories because I'm having such a hard time "opening archive as folder" to see if there are something inside. It's always empty and `No items.` inside. I know this is absolutely not true.

**Comment by mudlord** [comment]
shut the fuck up

**Comment by jedinjapan** [comment]
Instead of removing it like suggested, simply adding an option to "Remember Status of Hidden Files" that stores the toggle status and defaults to off would be enough to satisfy power users while also not being burdensome to the current design, no?

Having it redraw the XMB immediately would be annoying to implement, but if it remembered you wouldn't have to. Moving the "show all files" toggle to the settings menu one day might be possible, but Retroarch cannot plan for every possible acceptable file extension for every future core, so for future proofing it might stay where it is I expect. If you implemented ffmpeg or LAV as a video core option for example, and wanted to run *all it's filetypes* that could be a near infinite list.

**Comment by lasers** [comment]
>It's difficult in xmb to add/remove menu entries on the current list without causing glitches.

I'll close this to reduce clutters / more work for the team. I would suggest to always display all game extensions regardless instead of the core supported extensions, but in any case, all files should stay relevant.
