### ISSUE TITLE
[XMB] Settings loop right but not left

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4184]
All settings only loop to the right, but not to the left.  This was especially inconvenient when I discovered that audio volume goes from 12.0 dB to -80.0 dB.

**Comment by lasers** [comment]
Known Menu issue https://github.com/libretro/RetroArch/issues/3899. For now, you can use `Start / Default` to reset the number.

**Comment by AlexFolland** [comment]
That seems to list a bunch of different settings with which this happens, but it seems like it affects every setting.  Why fix each individually?

**Comment by lasers** [comment]
I'm not the person you wanted to answer this question. If I have to give one right now, I say it is only a list of known menu bugs... even if they're same in different places. This could be helpful in narrowing down a bug to a keyboard input issue or something very vague.

While the behavior for each setting may look same outside, each setting likely have their own chunk of codes because all settings had to have different options and had to have different rules too... so maybe that's why they're fixing each individually.

**Comment by AlexFolland** [comment]
My question was rhetorical.

**Comment by fr500** [comment]
I didn't say each setting has to be fixed individually. Basically it's not implemented
https://github.com/libretro/RetroArch/issues/3899

**Comment by AlexFolland** [comment]
Wait, closed?  But you just said it's not implemented.

**Comment by fr500** [comment]
There is an issue that covers this already
