### ISSUE TITLE
PS3 most recent stable - is not so stable?

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#4190]
Hey guys, I installed the latest PS3 retroarch pkg - but not sure why the UI seems corrupted whenever I try to launch it and then use the UI.. The app just seems to corrupt itself as I try to navigate through the UI to download cores - and also takes two attempts to quit from the RetroArch UI menu... Is it possible there is a more stable build that I might try?

**Comment by twinaphex** [comment]
There might have been some breakage. Ezi0 stopped regularly testing it so now he has found out numerous problems and now we have to backtrack months in order to figure out what went wrong. Thats pages and pages of commits that has to be bisected. Not fun and not productive.

One of the patreon goals is that we start doing per weekly checking from now on to prevent this from happening again. It will likely require paying some of these testers on various platforms to keep tabs on things so that we are at least assured things get regularly tested which so far hasnt happened.

**Comment by futurepr0n** [comment]
obviously i am of one of the smallest subsets of the user base with this lil problem here, but I do appreciate the efforts of the team to even bother including such platform. Is there any notes or members of the team which could possibly throw out a version number that was last known to be pretty stable? 

I'm really sorry to raise this as an issue, definitely appreciate the response! thanks twinaphex

**Comment by twinaphex** [comment]
Unfortunately I can't tell you which version was the last stable. I think it's not productive to look back anyway and we should just fix the current issues. It will take some backtracking.

**Comment by futurepr0n** [comment]
Thanks Twin, hope to see some progress! Take care
