### ISSUE TITLE
"RetroArch button" in Android kicks me back into the game

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4256]

**Comment by twinaphex** [comment]
This is a latching issue to do with overlay keys. I think so far, only keyboard and gamepad input is properly latched, but not overlay input. 

The two main parts of RetroArch that interact with each other can be found in two files -

input/input_driver.c

and

input/input_overlay.c

**Comment by loganmc10** [comment]
I don't really know enough about input code to easily know how to fix this, hopefully someone can figure it out, it's easily the most annoying thing about RetroArch for me, since I do most my gaming on Android.

**Comment by loganmc10** [comment]
Other issue I have with the overlay: If I have it minimized, and i'm using a controller, when I'm in the RetroArch menu and hit "Resume", the overlay un-minimizes itself, even though I have a controller connected and I went into the RetroArch menu with it minimized (by using controller hotkeys)

**Comment by fr500** [comment]
The issue still exists. If it bothers you unsubscribe.

**Comment by twinaphex** [comment]
@loganmc10 It's good to see that my generosity for getting an nvidia engineer to send you some hardware which you said you needed resulted in this kind of bullshit on your end,where not only did you cut and run and try to act like we did you wrong, but you try to close issues now which we have never told you to close. 

I'll think twice in the future about showing some random stranger some generosity next time around. I don't like people who go air their dirty laundry on public venues especially when we never did you wrong. We never once tried to drag your name through the mud, even as you tried to grandstand and make big sweeping statements like 'N64 emulation no longer sucks!' in an effort to self-advertise yourself on (of all places) Reddit. Well guess what - it has not sucked, and that's because I don't use garbage like a Raspberry Pi. That's your first mistake right there.

Good luck with your mupen64plus frontend. I have no ill will towards you except for the fact that you have been quite the backstabber when I literally showed you nothing but support. So fuck you for that, quite honestly.
