### ISSUE TITLE
Garbage audio in XAudio when using 44100Hz 

### ISSUE THREAD

**Issue by Ramirez57** [libretro/RetroArch#4301]
A **very loud** and unpleasing noise is generated when trying to use 44,100Hz output rate when using the XAudio driver. It seems rates between 44100 and 47999 cause this. Using 44099 works, but then the sound is not perfect. Rates like 22050 and 11025 seem to be working fine, it's only 44100-47999 causing the garbage audio.

dsound and sdl are unaffected by this issue.

Sometimes opening and closing the RGUI menu, or going in and out of full screen, temporarily solves the issue, but then audio seems randomly garbage.

I am using Mednafen PSX core (software renderer). My goal was to hopefully bypass audio re-sampling by matching the PS1 sample rate of 44100Hz.

Using Windows 7 64 bit.

**Comment by ape123** [comment]
There have been similar topics from other users before without much response. I don't think the libretro team is interested in audio to be honest. Have you tried mednafen standalone? It can be tricky to use because of its command-line based interface, but it allows you to disable its own resampling. It also supports WASAPI exclusive mode, which bypasses the Windows audio mixer, meaning that Windows also will not resample your audio (Note that WASAPI shared mode does NOT bypass the mixer, nor can XAudio2 or DSound bypass it).

**Comment by Ramirez57** [comment]
Oh shame. Yes, I still use mednafen on its own, but RetroArch is such a good front-end and libretro is simple to compile for. The audio drivers for Windows could be better though.

**Comment by twinaphex** [comment]
@ape123 The Mednafen/beetle psx libretro core doesnt use resampling at all, and libspeex was completely ripped out (unlike standalone). So, honestly, the only resampling that is still going on is on the frontend level, and the resampler is necessary anyway for dynamic rate control.

In mednafen standalone, setting it to 44khz out bypasses libspeex. with the libretro core, libspeex is not even there to begin with.

if anything, its far more optimal, and the resamplers that are in libretro common are very optimized and stress tested.

as for wasapi, honestly, most of the main devs so far are linux fans and treat windows as second fiddle. Last I checked WASAPI isnt all it is cracked up to be anyway.

**Comment by ape123** [comment]
@twinaphex Yeah, I understand that beetle-psx itself isn't resampling anything, but RetroArch using DSound or Xaudio2 means the audio is processed twice - first by RetroArch, and then by the Windows mixer. WASAPI alone doesn't change this, but if it's used in "exclusive mode", then the audio has a straight path all the way to the user's receiver or speakers.

I know this because I have checked the sample rate on my receiver and it's being changed from Windows' sample rate to the game's sample rate when using WASAPI in "exclusive mode" on other emulators, and it works even with exotic rates like 32khz.

I understand that you're Linux users, but is the audio situation actually better on Linux? Is an equivalent to WASAPI exclusive mode used there? Last time I tried Lakka, I concluded that on my end RetroArch actually works better on Windows. If this got reversed I would switch over immediately and recommend it to others.

Now please don't take this as complaining. I'm just stating my experience and was trying to help Ramirez57.

**Comment by twinaphex** [comment]
If you want WASAPI in RetroArch, you can volunteer to write a WASAPI audio driver. 

You are right that we are Linux users/developers first and that you have to pretty much force us to code anything for Windows. This makes us the total opposite of most emulator projects out there but we like bucking trends I guess.

XAudio2/DSound driver is more than competent for our purposes on Windows. I am not going to get into any back and forth arguments regarding Linux vs. Windows. There is a plethora of information out there listing all the pros and cons, we don't need to be having this discussion.

If byuu can get audio drivers provided to him and even copyright reassign them to himself for all sorts of 'reasons', then I think asking volunteers to do their part in contributing to RetroArch in the areas where we either lack the time or the dedicated devs to make it happen is not that much to ask.
