### ISSUE TITLE
Shared Context improvements

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4368]

**Comment by loganmc10** [comment]
If someone gives me a few pointers on how to accomplish the 2 threads/2 contexts thing I'd be willing to play around with this a bit, I'm not super familiar with the RA graphics code and I'm not really a threading pro either so I'm not really sure where to get started.

**Comment by twinaphex** [comment]
@Themaister loganmc10 has been doing quite some work on RetroArch's GL driver already. He is probably best positioned to finally make 'shared context' the default mode for GL cores. Would be great if you could provide him with some feedback on the things he requested advice on.

**Comment by loganmc10** [comment]
I'm hoping we can somehow make use of the current "threaded video" feature and have all the RetroArch rendering happen inside that thread and all the core rendering happen in the main thread

By the way, that is probably why threaded video doesn't currently work with GL, it is trying to render in a thread that doesn't have a context set.

**Comment by twinaphex** [comment]
Yes, so far, libretro cores that utilize GL have had the limitation that GL calls have to be performed on the 'main thread' (i.e. the thread that RetroArch lives on). 

It's for this reason that making a Dolphin port to libretro is so difficult without resorting to cutting the thing up in a thousand little pieces.

**Comment by twinaphex** [comment]
@loganmc10 If you're all butthurt because you left a project on bad terms, that is one thing. What is quite rude and deliberately annoying, though, is when you remove the initial post so that none of us had any idea what you were talking about here, generally messing up the conversation flow we had going here. The issue could have still been useful to have, regardless of your particular feelings or misgivings on our project.

I really advise that you stop deliberately being obstructive at this point. Remove yourself from issues, fine, but don't remove entire posts so we have no idea of what was being said or what the actual issue was. I think you know exactly what you are doing and that you are intentionally trying to be annoying.

**Comment by twinaphex** [comment]
@fr500 Radius you still happen to have the initial comment before @loganmc10 deleted it? I guess now we no longer know what this issue was about.
