### ISSUE TITLE
Add a toggle option for Slow Motion

### ISSUE THREAD

**Issue by MrDrumble** [libretro/RetroArch#4397]
I love the slow motion feature. I used to play around with the slow motion feature on the NES Advantage for hours as a kid. However, it's nearly useless to me in its current form. As someone that uses an Enable Hotkeys button, I need to hold down two buttons to activate slow motion, which makes doing anything else in a game pretty difficult.  Even without that, having to hold a button down for an extended period gets tiring fast.

Adding a toggle option would make it more consistent with the fast forward options.

**Comment by RobLoach** [comment]
Correct... There is currently "Fast forward toggle" and "Fast forward hold". While there is "Slow motion", there is no "Slow motion toggle".

**Comment by loganmc10** [comment]
https://github.com/libretro/RetroArch/issues/4352

**Comment by fr500** [comment]
From @lonewolvf:

Is there a way to slow down game speed? There are games that I would love to play but I am unable to because they're too fast paced (I'm disabled). If you can slow down a game, could you add a percentage slider? What would also be great to have is a keyboard hotkey that toggles between 2 speeds. It wouldn't just be between normal and a slower speed, but also a slow and slower speed.

Thank you,
Michael

**Comment by megamanzteam** [comment]
I have been looking forward to this feature, and it has not yet been implemented. Do you have an ETA when this could be implemented?

**Comment by fr500** [comment]
We never have any ETAs

**Comment by Ryunam** [comment]
The new 'slow motion toggle' option I added under Input Hotkey Binds has been merged now.
@MrDrumble, please take a look at it and check if we can consider this issue closed.

**Comment by RobLoach** [comment]
Posted a screenshot in the PR! It's pretty fancy. Thanks a lot, Ryunam.

**Comment by MrDrumble** [comment]
Works great!  Thanks, Ryunam.
