### ISSUE TITLE
Loading content / Quick Menu behavior

### ISSUE THREAD

**Issue by JuanVCS** [libretro/RetroArch#4498]
## Description

The quick menu action will be affected by whatever menu preceeded it.

In this case, when loading content from a playlist, the quick menu will pick up on the thumbnail, superposing it over the actual options.
![Thumbnail superposed to options](http://i.imgur.com/agvtK8nl.png)

### Expected behavior

Pressing the quick menu button to always show you the quick menu (preferably just above the main menu) regardless of whatever steps were taken before or after accessing it.

### Actual behavior

When leaving the quick menu for a lower level menu and cycling thru the quick menu button, you'll actually go back to whatever menu was visited last.

### Steps to reproduce the bug

1. Load content from a playlist (with thumbnail attached)
2. Access the quick menu to see the overlaid thumbnail
3. Move outside the quick menu and cycle thru it via the key/button mapped to quick menu

- RetroArch: git 4b476cfe5

### Environment information

- OS: Arch Linux kernel 4.8 x86-64

**Comment by Alex793** [comment]
Hi, I up this because it still present on iOS version from 1.4.0 to 1.5.0, no problem on 1.3.6, the text was "on top".

RA 1.3.6 : ![image](https://cloud.githubusercontent.com/assets/428805/26143509/8c54d540-3ae5-11e7-9d8d-679721335fc2.png)

RA 1.4.0-1.5.0 : ![image](https://cloud.githubusercontent.com/assets/428805/26143477/6ccfdb98-3ae5-11e7-968d-b60a503aa5e7.png)

(Look "per bios")

**Comment by orbea** [comment]
This seems to have been fixed and now the thumbnail will not show up in core options or other menus.

**Comment by orbea** [comment]
Also a duplicate of https://github.com/libretro/RetroArch/issues/4549.
