### ISSUE TITLE
The English text in Retroarch needs to be polished

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#4555]
I think it would be a pity to put out a big new release of Retroarch when truthfully there's a few cases of incorrect grammar or inconsistencies in the some of the menu sub-labels. If you want, I could help out with this.

P

**Comment by twinaphex** [comment]
Examples please, we can't delay this any longer and you should have gotten straight to the point here and listed specific examples already.

**Comment by pepedopolous** [comment]
Well now I might seem like a real pedant! However, for me it does spoil the slick XMB interface.

Examples.

Saving
Change settings for the saving --> Change settings for saving

      The same problem is in the sub-label for Recording, Achievements, Playlists.

For Network, 'Change network settings' would be better.
For Privacy, 'Change privacy settings' would be better.

For Video, Audio, and Input, it would be more consistent if the labels started with 'Change...' instead of 'Adjusts...'

Load Core --> Select a core to use
Load Content --> Select game or media to load [Just a suggestion]
Help --> Learn how to use RetroArch
Information --> Display information about the system [Just a suggestion]

P

**Comment by twinaphex** [comment]
I didn't write most of those labels.

As for Load Core - I think it's fine.

I think nothing in here is really worth it delaying the release for at any rate.

**Comment by pepedopolous** [comment]
Sure. It's not stopping anyone using the program, just minor aesthetics.

**Comment by twinaphex** [comment]
We can focus on it after release maybe.

**Comment by RobLoach** [comment]
Just having the labels is amazing, gives us a good base to work off of. If you provide updated text, I can create PRs to fix them.

**Comment by RobLoach** [comment]
> Load Core --> Select a core to use

Doesn't describe what a core is, or what "Loading" means.

> Help --> Learn how to use RetroArch

This text doesn't apply on Lakka.

**Comment by pepedopolous** [comment]
> Load Core --> Select a core to use
Doesn't describe what a core is, or what "Loading" means.

I think it follows that any user installing RA has internet and so can and must find out for themselves. A 'core' is an 'application' but in this case the developer terminology 'core' is less confusing to a user. The UI is not the place to explain the meaning of 'core'.

If a user happens to have the correct roms and cores, they only need to scan their games directory and use the resulting playlists; they would never need to use 'Load Core'.

> Help --> Learn how to use RetroArch
This text doesn't apply on Lakka.

If we can't use the name 'Retroarch' in the UI, fair enough, but the current label 'Learn more about how it works' is just ugly in English. Sure, maybe in some other language it sounds perfectly fine. However, in English it is unclear what 'it' refers to. If my first suggestion isn't good then maybe something like 'Learn more about how to use this application'.

**Comment by micochops** [comment]
I'd like to propose other changes to the English text and submenu labels for consistency, brevity, and clarity 👍

Note the strikethrough, here it means the text is in RetroArch but I think it's better to removed or altered. Bold here means text is added.

Main Menu:
Load Core -> Select which **core** ~~application we wish~~ to use.
Load Content -> Select which content ~~we wish~~ to start.
Online Updater -> Download add-ons, components, and content~~s~~ for RetroArch.
(removed the "s" in contents, note that I also added a comma after "component" i.e., making use of the Oxford comma if that's ok)
Information -> Display core, network, and system information (also added the comma after network).
Help -> Learn more about how ~~it~~ the program works. (for consistency purposes. I used "the program" instead of "it" because if we look at the label for Quit RetroArch, it says "Quit the program.")

Settings Menu: (i'd like to echo @pepedopolous's comment about consistency)
Driver -> Change drivers **used** ~~for this~~ by the system.
Video -> ~~Adjusts~~ Change **video output** settings ~~for video output~~.
Audio -> ~~Adjusts~~ Change **audio output** settings ~~for audio output~~.
Input -> ~~Adjusts~~ Change joypad~~s~~, keyboard, and mouse settings ~~for joypads, keyboard and mouse~~. (removed the "s" in joypad, also added a comma after "keyboard")
Core -> Change **core** settings ~~for the core~~.
Saving -> Change **saving** settings ~~for the saving~~.
Logging -> Change **logging** settings ~~for the logging~~.
Onscreen display -> Change **display and keyboard overlay,** ~~display overlay, keyboard overlay~~ and onscreen notification~~s~~ settings (note the comma after the first "overlay", also removed "s" in "notification")
User Interface -> Change **user interface** settings ~~for the user interface~~.
Achievements -> Change **achievement** settings ~~for the achievements~~.
Playlists -> Change **playlist** settings ~~for the playlists~~.

What do you guys think? I can also go over the submenus for each item if you think the above changes are good so far. Hope I was able to convey properly what each setting does.

Thanks all!

**Comment by RobLoach** [comment]
While I'm not a technical writer, I think it may carry more impact if we described what changing the settings does. For Video, for example, if the user scrolls over "Settings", and then scrolls down to "Video", it is assumed that they already know it will change "Video Settings". Describing what results when they make those changes will be more helpful:

Making changes to the *Video Settings* will...

> Improve performance and video output quality.

Making changes to the *Achievement Settings* will...

> Track achievement progress on RetroArchievement.

Making changes to the *Directory Settings* will...

> Change locations where RetroArch expects files to be.

Making changes to the *User Interface* settings will...

> Affect how the user interface and menu looks and behaves.

In your mind, say "Making changes to this will..." and then use whatever you say next.

**Comment by micochops** [comment]
This is a valid point. We just have to find a way to somehow combine describing what changing each setting _does_ with what it is _about_.

**Comment by micochops** [comment]
With the sub labels now in effect, I was just wondering if we still need msg_hash_us.c? I noticed this is the text displayed when a user presses the Select button. Is it not a redundancy? Or is msg_hash_us.c used for something else other than for the purposes specified above?

**Comment by micochops** [comment]
Hey! Thanks for these @vffhr 

Volunteering myself to make another PR updating the English text if guys here deems it appropriate/necessary.

**Comment by orbea** [comment]
@vffhr and @micochops Has anything been done to resolve these inconsistencies or other issues listed here?

**Comment by micochops** [comment]
Hey @orbea, sorry bout this. Been busy with holiday season stuff. Will get to it this week. Thanks for the reminder!
