### ISSUE TITLE
Cross-Platform Netplay

### ISSUE THREAD

**Issue by webodan** [libretro/RetroArch#4630]
Hello, 

I've attempted running netplay between windows and linux versions of retroarch and even after downloading the cores built the same day for both versions they were unable to start and I had a message saying that "implementations differ", so I'm not sure whether if it's just a misconfiguration or cross-platform isn't really a feature at this point, so i'd like to ask: is it a plan or it's just not there yet? I'm curious because I didn't find anything about this in the announcement for version 1.4.1 or in the bug reports here so there.

**Comment by hizzlekizzle** [comment]
I've personally played Linux vs Windows and fr500 often tests Windows vs Android, so yeah, cross-platform definitely works. It can be finicky, though, as you need the exact same cores and the same version of RetroArch, which can be hard to pin down.

**Comment by rootfather** [comment]
@webodan, the "implementations differ" error message indicates that you are not running the exact same retroarch/core version on all netplay clients/hosts.

**Comment by webodan** [comment]
Oh, I see. Is there any way I can get the exact same versions of the cores between platforms so that it would work? My only way is loading the core into retroarch after downloading them all and then seeing the build number in the bottom left corner, and by that point I've wasted quite a bit of time to check whether they are in fact the same or not.

Thank you for the swift response and for the new netplay code it's really amazing.

**Comment by hizzlekizzle** [comment]
Unless the buildbot is currently in the process of building the core (which only happens when there's a new commit), the best way is just to have both players pull a fresh build from the buildbot.

If you're using RetroArch from the PPA, it only builds once per day (I think) and patches out the online updater, so you might want to build RetroArch yourself and set a new core directory in settings > directory and use the ones from the online updater for netplay.

**Comment by webodan** [comment]
Hi again,

By pulling it from the buildbot, do you mean downloading the source code for the cores and compiling them both for the platforms where I want to run them?

Thank you.

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by hizzlekizzle** [comment]
By "buildbot" I mean from the Online Updater within RetroArch.

**Comment by gnutechs** [comment]
webodan, the reason you're getting the implementations differ error message is because you have  different core versions. Unfortunately at the moment, the buildbot automated system which compiles the latest cores is behind for the Windows versions. Unless you can find an older version of the Linux core you want to use which matches the version of the Windows core, or the automated Windows core builds are updated, then you won't be able to play together.

**Comment by hizzlekizzle** [comment]
@gnutechs 
I see Windows cores that were built today.

**Comment by webodan** [comment]
I think it would greatly help if there could be stable versions of cores outside the ones being built nightly.

**Comment by fr500** [comment]
Cross platform netplay is already implemented.
If a particular core is not compatible across platforms and ABIs the issues should be opened in the respective core issue trackers.

**Comment by markwkidd** [comment]
Could cores tag releases for github and thereby solve this issue? https://help.github.com/articles/creating-releases/

That way the buildbot could build the most recent 'release' rather than the most recent commit. It would provide build consistency even if the releases were still tagged in an automated way (such as last commit every 24 hours in the GMT time zone, last commit every week).
