### ISSUE TITLE
input_max_users set to 1 breaks pointer in DeSmuME

### ISSUE THREAD

**Issue by SigmaVirus** [libretro/RetroArch#4667]
## Description

In RetroArch 1.4.0 and 1.4.1, if you set input_max_users to 1 the pointer in DeSmuME breaks.
If you however set it to 2-5 it works again.

### Expected behavior

I expected the pointer to work with input_max_users set to 1 just like it did in 1.3.6

### Actual behavior

What is actually happening is that the pointer stops working when set to 1 until you change input_max_users to 2-5 again.

### Steps to reproduce the bug

1. Load RetroArch
2. Change input_max_users from default 5 to 1
3. Load a game in DeSmuME
4. No pointer

### Bisect Results

It started to happen in RetroArch 1.4.0 as 1.3.6 is unaffected

### Version/Commit
RetroArch 1.4.0 and 1.4.1

### Environment information

Windows 10 64-bit
i7 4790K at stock speeds
ASUS Nvidia 1060 6GB
16GB Corsair XMS3 DDR3 RAM

RetroArch and cores downloaded from here:
http://buildbot.libretro.com/nightly/windows/x86_64/

**Comment by orbea** [comment]
Can you bisect 1.3.6 and 1.4.1? It would be helpful to find a specific commit.

**Comment by SigmaVirus** [comment]
Aye aye aye, now that could be a real problem.
1. I'm not familiar with the code from RetroArch
2. There have been TONS of commits since September 2016 so I don't even know where to start looking or what to start looking for
3. The builds are gone???

So finding a specific commit, at least for me would be impossible and like finding a needle in a haystack and besides if I were psychic that would have mean that I had to travel back in time, download every single build from September up until 1.4.0 hit the scene unless the Libretro/RetroArch team have a secret stash of all builds ever made.

**Comment by orbea** [comment]
@SigmaVirus 

1. clone the repo: `git clone https://github.com/libretro/RetroArch/`
2. Use `git log` to find an older commit and check it out: `git checkout 123456` (Use the real commit hash ofc)
3. Build it with `./configure` and then `make`.
4. Is the issue still present?
5. If it is then go back another month or so and try an even older commit, do this until you find one good commit and at least one bad commit.
6. Now you want to git bisect.
7. `git bisect start`, `git bisect bad 123456`, `git bisect good 654321` (Of course with the real commit hashes)
8. It will now pick a commit between the good and bad commit you singled out, you build it much like above and then test again.
9. If its good: `git bisect good`,  if its bad: `git bisect bad` and if you cant test it because of a build failure or another reason: `git bisect skip`.
10. Repeat this until it tell you what the first bad commit was and then past that output here.

**Comment by SigmaVirus** [comment]
This issue is not resolved but I think I'll just close it anyway as I seriously don't have the time or energy to dig deeper.
Change the value from 1 to 2-5 and it works.
