### ISSUE TITLE
RetroArch crashes when tries to open a ROM from a .7z with too many files

### ISSUE THREAD

**Issue by denius72** [libretro/RetroArch#4717]
## Description

RetroArch crashes when tries to open a ROM from a .7z with too many files inside. Tried GBA and SNES with multiple cores and it crashes on Android. Apparently it doesn't occur on my Windows computer.

ROMs compacted in .7z with not so many files will load normally.

I don't know if this happens with all Android devices, but so far it occurred on two devices of mine. 
This kind of stuff can happen:
- RetroArch may hang.
- The entire device may reboot.
- It's rare, but sometimes the game will actually load. This one is exclusive to Xperia Z2 (see devices tested below), so I can tell that it depends on the device processing power to load from .7z.

##### "Well, then why don't you extract 'em and then play?"
You see, my ROMs are inside .7z files do I can conserve as much storage as I can. Also, I don't think that this should happen.

### Steps to reproduce the bug

1. Get a .7z file with a lot of ROMs inside (like 300 files)
2. Go to Load Content and browse to inside the .7z file
3. Try to open any ROM.

### Bisect Results

This is from way back when I started to use this software, like version 1.3.6 and it still happens.

### Version/Commit

- RetroArch: [1.4.1 / Play Store Version]

### Environment information
Devices tested: 
- Xperia Z2 (Android 6.0.1) powered by Qualcomm MSM8974AB Snapdragon 801 (ARMv7 32 bit processor)
- Xperia M2 (Android 7.0 OMNI) powered by Qualcomm MSM8926 Snapdragon 400 (ARMv7 32 bit processor)

**Comment by retro-wertz** [comment]
ive never heard of such method of conserving space to play roms. not
because RA can browse inside compressed files that it has to be used this
way, not to mention on an arm device with limited processing speed and ram

**Comment by denius72** [comment]
If the feature is there, it should work... right?

This behavior is just weird. Why it crashes? Well, I thought it was my fault at some point, but c'mon, Xperia Z2 has 3GB of RAM and a SD 801, Android barely uses 1GB of the RAM. Everything loads very fast, except those files that just hangs the entire software.
Also, it was mencioned above that I have no problems with .7z with not that many files inside (which I'll separate the big .7z into small ones). 

Nevertheless, thank you for your time.

**Comment by i30817** [comment]
If you're rooting your device in order to install RA with linux, there is a simple and performant alternative to depending on application layer compression of multiple titles if you don't mind your rom 'bundle' being read only. The kernel has support for loading squashfs archives as filesystems (made with mksquash 

something like this added to your fstab after creating games.sqsh and the directory Games on the right places (on a normal pc here though):
`/media/i30817/Huggin/Documents/Games/games.sqsh /mnt/Games squashfs ro,nofail,noexec,nodev,nosuid,noauto,users,x-gvfs-show 0 0` 

should allow you stable and tested transparent compression. The main problem is that you won't be able to write anything or modify anything.

But... you can even play dosbox games that need R+W access with this script that redirects writes to a writable portion of the filesystem with FUSE unionfs. I made this script myself, it probably wont work on strange phone distros? I dunno.

https://gist.github.com/i30817/12a91a7e79a94ebadc3da1839bfc0e6d

**Comment by i30817** [comment]
btw the main reason you're getting OoM is that rar/7z/zip are simply not made for transparent mounting like this. They're archive filesystems first and foremost, which means that their 'seeking in-file' behavior is very bad because they're optimizing for compression in the assumption that everything is going to be decompressed at once to the main fileystem.

Rar and 7z can even go further than this and have a option to make the compression of the later files depend on the results of the compression of earlier files (to optimize size). This is actually pretty dangerous in itself because a byte error in the previous files may corrupt the rest of the archive. But for reading and seeking beheaviour when mounted as a filesystem it's horrible too, since if you want to 'seek' to a place, you 'need' to decompress all previous bytes. In fact, if you need to seek 'before' where your current decompression cursor is, you need to reset the decompression.

squashfs makes sure that the compression is per block, not per file, so seeking behavior 'mostly works' to optimize latency at the cost of some compression. It's a compromise of incompatible requirements and i think for mountable filesystems that are not only archives, the right one.

**Comment by denius72** [comment]
I see.
I really appreciate your technical comment. Even if this is not really a _bug_ and it is my device running out of memory, I'll try squashfs (on Linux) and other workarounds to get stuff going. 
Thank you for your time and for your explanation.

**Comment by i30817** [comment]
No prob. I'm rocking a 273 gb squash file myself currently and even then i'm not even at 10% of the USA psx collection (not to count the 90 gb uncompressed of that that are dosbox games) so i know pretty well how a sizable ROM collection can grow out of control. I haven't had latency problems with squash lz4 with it all compressed into a single file, modern software engineering really is wonderful and FUSE is a very clever design i hope spreads into windows so more programs can take advantage of the massive cheat that it's externalizing more things to filesystems in userspace.
