### ISSUE TITLE
No way to disable filters in Video options

### ISSUE THREAD

**Issue by notnsane** [libretro/RetroArch#4843]
## Description

No way to disable fixters in Video options

### Expected behavior

A way to disable filters in Video options

### Actual behavior

Once you set a filter, it cannot be disabled

### Steps to reproduce the bug

1. Go to Video
2. Go to Video Filter
3. Select a filter

### Bisect Results

-

### Version/Commit
1.500

- RetroArch: 1.5.0

### Environment information

- OS: Windows 10 x64

**Comment by twinaphex** [comment]
Have you tried pressing 'Start' (on your gamepad) on the Video Filter ? This should undo the filter.

NOTE: The 'Start button' on your gamepad resets a setting to its defaults.

**Comment by retro-wertz** [comment]
press Start

**Comment by notnsane** [comment]
So no way to do it with a mouse or keyboard? That's pretty bad UX.

**Comment by twinaphex** [comment]
No, you can do it with a keyboard. You can press the spacebar to do a 'Start button' call.

I think your problem is that you speak first and make assumptions before asking questions. 

And actually, RetroArch IS designed around a gamepad. That is the entire 'user experience' if you want to trot out fancy marketing lingo like that - its purpose is to look, feel and act like a games console with a game console UI.

**Comment by notnsane** [comment]
@twinaphex I'm all for it since I'm a gamepad user mostly, but then you should include [button prompts](https://marketplacecdn.yoyogames.com/images/assets/183/screenshots/363_original.png?1404425889) to indicate that pressing Start resets that option, even if it's for that single option. I think that's not explained anywhere in the app, and even if there were a help menu somewhere in that menu jungle, it should be way more obvious to a first time user (or someone like me that's struggling with it for more than a week).

I'm allowed to open an issue for that? I think I can also provide documentation on why using button prompts on menu is good practice (basically it avoids issues like this).

**Comment by twinaphex** [comment]
If the official PS3/PS4 OS shows button indicators like this onscreen inside the menu, sure, make a Github issue about it.

**Comment by DaVince** [comment]
I had to Google this to find out how to reset the filter.

To prevent confusion a little, it might be a good idea to mention this in the description for the option, or add a toggle on/off option above it.

**Comment by KentWayne** [comment]
Hello, I also ended up here because I had to google how to disable the filter. Not sure how I was supposed to guess that start does it, or that spacebar equals start. Doesn't seem instinctive to me.
I wouldn't even bother complaining since I found the solution in seconds anyway, but since the same exact thing happened to the person above, I thought I'd mention it. Consider adding a "start/spacebar to disable" prompt or a "none" option among the filters. Seems pretty reasonable.

**Comment by DaVince** [comment]
> or that spacebar equals start. Doesn't seem instinctive to me.

Weird; the default is enter. But in any case, the default keybindings are what they are for a reason and they can be looked up on the excellent [Getting Started guide](https://www.libretro.com/index.php/getting-started-with-retroarch/).

But to stay on-topic, since RetroArch can bind any kind of input to the one fixed "A/B/X/Y/Start/Select" etc. scheme it wouldn't make sense to mention the space bar explicitly. The message would have to be limited to just mentioning the start button since that's an explicitly defined input in RetroArch. If you've set up your controls, you'll already know then what the start button would be.

**Comment by extracampine** [comment]
How do you save the video filter option? I can turn it off and save core ovverides, but when I restart RA the video filter is turned on again.

**Comment by Architector4** [comment]
I, too, had to search for this on the internet, to then stumble upon this. Thanks for making RetroArch, seriously, but, yeah, getting thrown to it for the first time with no gamepad is kind of jarring.

**Comment by thericeking** [comment]
I came here because I had the same issue today. Maybe there should be a text or something on that menu that says press Space Bar to disable. Something more obvious. Took me a while to find the solution. Thnak you.

**Comment by cupantae** [comment]
This should be written somewhere or give an explicit option <Reset to default> in the filters list.

**Comment by hizzlekizzle** [comment]
> 
> 
> This should be written somewhere or give an explicit option "Reset to default" in the filters list.

I believe the nightly builds do have an explicit removal option.
