### ISSUE TITLE
UI: Have a list with favorite / starred games

### ISSUE THREAD

**Issue by tolitius** [libretro/RetroArch#4910]
## Description

There are thousands of games and dozens of playlists. Instead of keep navigating to a specific list and scrolling / searching for a specific game it would be really helpful if the one could `star` a game which would add it to a separate "favorite" / "star" UI view.

### Expected behavior

* an ability to star / unstar a game
* a single view with all the starred / favorite games

### Version/Commit

- RetroArch / Lakka: commit `2a13af5` (as displayed in lakka's sysinfo)
- Build date: `Apr 24 2017`

### Environment information

- OS: Lakka image on RaspberryPi 3

**Comment by legluondunet** [comment]
I would like to ask for the same feature, would be very useful.

**Comment by chrissbarr** [comment]
I'd also like a feature like this, though I did have a different idea on how it could be implemented.

I think it would be handy if we could 'star' or 'favourite' items within an existing playlist, and then swap between the current playlist view, and a filtered view that shows only the 'starred' items in the current playlist.

That way, assuming we have playlists for different consoles, as seems standard, we could nominate favourite games in each playlist, and then hide everything else. If the UI remembered which view was last used (filtered/unfiltered) for a given playlist, it would be a really handy way of presenting a concise list of games for each console, while still having the option to view the full library as needed. Ideally, starring/unstarring games could be a one-button operation, so that people can quickly scroll through the list and add games that they want. This would allow people to have per-system favourites, compared to the current favourite system which seems to mix everything in together.

I don't know how rigid the playlist files are, but it occurred to me that an extra line could be added to each game's entry, to signify if they're favourited or not - perhaps that would break backwards compatibility though.

That's just my take on it, as that's what would be pretty much the ideal system for my purposes.

**Comment by orbea** [comment]
A favorites list was implemented so I am going to close this, please make a new issue if you have any specific problems or suggestions for the favorites list, thanks!
