### ISSUE TITLE
Cannot set OSD font

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#4919]
### Steps to reproduce the bug

1. In any menu driver, go to Settings -> Onscreen Display -> Onscreen Notifications -> Onscreen Notification Font
2. Choose path to a font file, I chose a .otf in C:\Windows\Fonts
3. Core selection screen opens instead of setting the font

### Version/Commit
- RetroArch: b13ca2d (May 14 2017)

### Environment information

- OS: Windows 10, Linux

**Comment by Kivutar** [comment]
I started fixing this issue on this branch https://github.com/libretro/RetroArch/tree/fontfix

The only remaining problem is this hardcoded "/" here https://github.com/libretro/RetroArch/commit/534fa27c6cb55e4a56eebfc0c59dd67e729a99a8#diff-13645b72f12713a997ec744106d68e33R318

I don't know why, but using an empty string here makes it impossible to see TTF fonts in the browser. This also affects the "recording config path" and some other path settings (but not all of them, for example the menu background path).

Note that this patch fixes the menu font, but fixing the OSD font can be achieved the same way.

We just need to figure out why using an empty string instead of "/" breaks the feature.

**Comment by aliaspider** [comment]
https://github.com/libretro/RetroArch/blob/master/menu/menu_displaylist.c#L6679
file type is lost there and replaced with `FILE_TYPE_DIRECTORY` when the path is `NULL` or `""`.

**Comment by bparker06** [comment]
@aliaspider There is no line 6679 in that file

**Comment by aliaspider** [comment]
it moved since the comment.
this one : https://github.com/libretro/RetroArch/blob/54ce598a00dc233c605dd3b6770d9cacdc98764b/menu/menu_displaylist.c#L6646

**Comment by fr500** [comment]
Is this still a problem?

**Comment by Kivutar** [comment]
We fixed it some weeks ago
