### ISSUE TITLE
"Use this directory" option is missing in settings>directory

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4920]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Cannot set RA's directories using from xmb. the "Use this directory" option is missing.

### Expected behavior

After selecting the new directory, you had to choose "Use this directory" so RA will default to this directory the next time it runs.

### Actual behavior

"Use this directory" which saves you selected directory is missing in Settings>Directory 

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

bad commit (https://github.com/libretro/RetroArch/commit/17837ec81da81f29beb33323e9af733c2ef112c1)
![retroarch](https://cloud.githubusercontent.com/assets/23315382/26068381/e3d3789c-39cf-11e7-9cd6-71e4504173e4.jpg)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.5.0/17837ec81]

### Environment information

- OS: Windows 10 x64
- Compiler: MinGW 6.3.0 64bit

**Comment by twinaphex** [comment]
@kivutar This seems to be a confirmed regression.

**Comment by Kivutar** [comment]
Thanks for the report, it's indeed due to my commit. I'm going to fix this.

**Comment by retro-wertz** [comment]
this issue is not totally resolved yet, as the option still disappears, but in a different way.

current commit:  140ad6ab9
win 10 x64

How to replicate:
-run RA
-go to Settings>Directory
-select something to change and select a directory "Use this directory" option should still be there.
-go to main menu
-Load content, then select Start Directory or Downloads
-go back to main menu
-go to Settings>Directory and choose a setting to change and select a folder
-"Use this folder>" is missing now.

**Comment by twinaphex** [comment]
Yeah, that's because 'Load content, the select Start directory or downloads' would set the filebrowser type to 'SELECT FILE' mode again.

The problem there is that when we 'exit' the filebrowser mode, that this isn't communicated back to the filebrowser type state. So it still thinks it's in SELECT FILE mode and when we go select a directroy then again (Settings -> Directory), we don't see 'Use this folder' anymore.

@kivutar Try to look into this. This is the general kind of crappiness of the current filebrowser menu code. Hopefully you and others can improve this.

**Comment by twinaphex** [comment]
@kivutar In addition to this, another regression -

'Load Content' no longer shows thumbnails for images now.

**Comment by LOCOxCHAPA** [comment]
hi!, 2023 and i have the same problem, any solution?
thanks!
