### ISSUE TITLE
Netplay not working on RetroArch latest nightly on Android.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#5055]
Using latest 1.6.0 nightly on both android devices, same core (Snes9x) and same rom (Street Fighter II) and retroarch crashes when joining the host. Tried other cores and roms and the same thing happens

**Comment by bparker06** [comment]
Can you provide a logcat output of the crash? What kind of internet connection was being used on the two devices?

**Comment by blackman91** [comment]
Wifi, how do you take a logcat on android? Also it seems other android users have this problem too:
https://www.reddit.com/r/EmulationOnAndroid/comments/6f74t9/cant_connect_to_netplay_on_retroarch/

**Comment by bparker06** [comment]
There are tons of "logcat viewer" apps on the play store, if you download one of those and reproduce the crash, then paste it somewhere like hastebin.com, we might be able to tell what is causing it or at least narrow down what to do on our end to find the exact cause.

**Comment by blackman91** [comment]
[Retro.txt](https://github.com/libretro/RetroArch/files/1067016/Retro.txt)

**Comment by bparker06** [comment]
This is not a crash but an ANR (application not responding):

06-11 22:05:25.010 I/RetroArch(28890): Connecting to netplay host
06-11 22:05:32.980 I/InputDispatcher(388): Application is not responding

This means the client was unable to connect to the host, and the OS gave up waiting because we (mistakenly) told it not to do anything else until it connects.

So there's 2 problems here. We shouldn't block the entire application waiting for a netplay connection (if it's even our fault, don't know yet)... and your host has an issue with reachability of the port it is listening on.

Probably your host is behind some kind of firewall/NAT or UPnP isn't supported/working properly on the router. The host may have to manually forward the port to get it to work, or if that doesn't work then they might have to fall back to using our MITM server to relay the connection.
