### ISSUE TITLE
The testing ppa doesn't have the new cores built.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5080]
https://launchpad.net/~libretro/+archive/ubuntu/testing

I may be jumping the gun, but since the core releases were announced, i thought to inquire. Of those announced, only dolphin is there, not openlara, redream or citra.

**Comment by hizzlekizzle** [comment]
They just haven't gotten recipes yet. In the meantime, you can download the ones from the buildbot and point to them manually with the -L command line switch. We're also in the process of adding a menu option to show/hide the core downloader, so if you want to use the buildbot cores instead of the ones from the package manager, you can do that.

**Comment by fr500** [comment]
Certainly not an issue for this repo.
