### ISSUE TITLE
Replace "per-core" overrides and shaders with "per-system" overrides and shaders

### ISSUE THREAD

**Issue by kevinfishburne** [libretro/RetroArch#5100]
The existing functionality for core overrides is excellent with the exception of cores which emulate more than one system (Genesis Plus GX does SMS and Genesis, MAME does countless). For example there is no way to use one set of core overrides for SMS and another for Genesis because they both use the same core.

This is an issue because cores emulating multiple systems interpret the original hardware's framebuffer differently and have different resolutions, offsets, cropping/overscan, brightness/contrast/saturation, etc. which cannot be corrected by per-core overrides and per-core shader settings (image-adjustment, for example) since their granularity does not include the actual hardware being emulated, but the emulator itself.

The real-world use case scenario in which this is a serious problem is working with Mike Chi of the RetroTINK to create a custom Lakka image using 2048x240 hdmi timings and per-core custom viewport, core options and shader settings to accurately match original hardware on CRT televisions in 240p.

While this might be challenging to implement for MAME (unless the specific board is documented in the game information and thus could be queried), it should be fairly straightforward to implement using the algorithm which determines which roms belong to which system.

**Comment by hizzlekizzle** [comment]
Not gonna happen. RetroArch doesn't know anything about systems, only cores, and that's a key design decision. We don't want the frontend to be deciding things based on specific content, just taking those content files and passing them to the core to handle.

However, if you want to have different settings for multiple content types supported by a given core, you can compile additional copies of the same core by changing the internal name in its libretro.c/pp file, like I did here:
https://forums.libretro.com/t/i-compiled-some-split-cores/4370
And you can devote these additional copies to different systems (e.g., the genplusgx-sms and -gg cores I made).

We've also talked about doing playlist-based overrides but @fr500 has done most/all of the override work and he's happy with the current behavior.

**Comment by rtissera** [comment]
I ran into the same problem that @kevinfishburne has reported.

While I agree it is not doable with the current architecture it would be fairly easy to extend the libretro interface in order to have a core return the emulated system. It's definitely not easy as it sounds since you have to take care of systems regions and variants, but it might be a worthy addition and improvement IMHO.

I can guess meanwhile the split core solution (or duplicate genesis plus gx core into three separate ones) is an easy workaround.

**Comment by fr500** [comment]
Not gonna happen with the current API

**Comment by thatman84** [comment]
Is there a possibility to open this conversation again in a way that provides a compromise for end user and design decisions?

Overrides is an awesome feature but compiling split cores or individual game overrides is a little beyond most users imo. Also in my couple of years I have seen this issues raised many many times.

My only suggestion is to allow for overrides to be saved/loaded from the content directory (as an extra feature)
So long as the user organises their games per system it would cover most use cases for consoles at least. Mame arcade is different and im sure others are but imo could be a valid feature

**Comment by fr500** [comment]
For starters let's be clear.
**I won't replace the existem overrides. Period.**

That said, That's the most sensible idea I have heard. I still don't really like it though.
Saving in the content dir that is.

But I could load/save an override to the config dir with the last dir as the name, if I make it so it would look for overrides in this order:

- Core
- Content Dir
- Game

Example
- Genesis Plus GX/Genesis Plus GX.cfg
- Genesis Plus GX/Sega Megadrive.cfg
- Genesis Plus GX/Sonic.cfg

I was actually gonna change the current behavior since now it loads Core, and if there is a Game override it loads Game and it ends up being a mess, so I want it to always load only one but I haven't decided.

Not making any promises though but I kinda like this idea.

What would I name the option though?

**Comment by thatman84** [comment]
1st off thanks for entertaining this again. 

I would never expect the override system to be replaced. It is great and only ask to improve certain aspects.

Just to be clear if i had my roms located in the folder name MD (for mega drive) the override would be saved to

Config/Genesis Plus GX/MD.cfg

That would be a reasonable solution.

I would suggest the option name to be "save per system type config" or "save per machine type config"

I hope this makes it into the LONG to do list once its had some thought. :)

**Comment by fr500** [comment]
but it's not really saving per-system or per-machine

**Comment by thatman84** [comment]
I guess so...i was going by use case.

Maybe "per content group"

**Comment by Kondorito** [comment]
Override per system (or folder) would be a great addition!

**Comment by DukeOfDelmar** [comment]
+1 10/10 I could really use this feature.
