### ISSUE TITLE
Cores remembered for a game - Causing Issues

### ISSUE THREAD

**Issue by Forsakened** [libretro/RetroArch#5149]
## Description

When loading a game the core is remembered, when a game fails to load (Such as a black screen, the next time you load the game off the list, it will use that core again.

Perhaps an option to "disable remember core" could be possible?

Currently everytime this happens I have to delete the playlist for that console and delete content history. OR just edit the playlist file.

- RetroArch: 1.6.0

- OS: Windows 10

Thank you.

**Comment by Elmazz37** [comment]
Instead of deleting the playlist, open it with notepad (or notepad++ if available).
Now you see that every game takes 6 lines of information in the playlist file. Replace the 3rd and 4th lines with "DETECT" for a game you get issues running with a "remembered" core and save the file. The next time you launch the game it will give you an option to choose a core again.

**Comment by Elmazz37** [comment]
Or a 4th option in the contect launch menu, like after the "information" you could have "Select core", so you dont have to go and edit the playlist files. BUMP.

**Comment by RobLoach** [comment]
There's an option to reset core selection now. Feel free to test it out and re-open the issue if it doesn't satisfy your needs.

![screenshot at 2018-07-29 15-43-56](https://user-images.githubusercontent.com/25086/43370058-3b79e498-9346-11e8-87ff-deeffa7bcce2.png)
