### ISSUE TITLE
Change Timezone from UI

### ISSUE THREAD

**Issue by rejurime** [libretro/RetroArch#5183]
## Description

It would be great if a user interface option to change the time zone could be added to RA.

### Expected behavior

Can change Timezone from UI in Lakka/RA

### Actual behavior

To change the timezone in Lakka you have to do https://github.com/libretro/Lakka/wiki/Timezone-settings and for some people it is difficult.

### Environment information

- OS: Lakka 2.1rc3 in Raspberry Pi 3

**Comment by fennectech** [comment]
Howo do you manualy configure timezone in retroarch?

**Comment by albertvolkman** [comment]
@fennectech here is the updated link referenced by @rejurime-

https://github.com/libretro/Lakka-LibreELEC/wiki/Timezone-settings

**Comment by bparker06** [comment]
Unless you're talking about changing the system timezone programmatically (which I don't think belongs in RA), I don't think this is possible (portably) without some kind of cross-platform timezone library that would need to be constantly updated. Better to just set your system to the timezone you want to see everywhere anyway.

**Comment by orbea** [comment]
I suppose that could be possible as a Lakka only feature, alternatively it might be possible to change the timezone in RA independently of the system time, but I'm not sure it would be very useful...

**Comment by gouchi** [comment]
Hi,

You can try to  use [this ifdef HAVE_LAKKA](https://github.com/libretro/RetroArch/search?q=HAVE_LAKKA) then you can update [RetroArch package in Lakka](ttps://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/retroarch/package.mk).

Thank you.

**Comment by TheLastProject** [comment]
I've written some code in https://github.com/TheLastProject/RetroArch/commit/baa7578c5b72c9fc24dcf27b46e77811db0d6bf4 but I'm having trouble making anything appear in the menus (been at it for hours):

![image](https://user-images.githubusercontent.com/1885159/84600737-ceaee400-ae7b-11ea-8cdb-e80a57c7ba20.png)

Any pointers?

**Comment by Rstation4** [comment]
I agree with having this feature. I know some games actually make clever use of the system time. Like for instance Metal Gear Solid 3 is a clever time progress in which one of the bosses die if you wait like weeks to fight him, going from your ps3 system time/date. Im not sure if which of the cores do use your system time/date in any manner.

I use lakka os so i made my own timezone document which I just drop in Lakka_Disk/.cache/

-text file named "timezone" no txt or any file extension names to it
code: TIMEZONE=America/Los_Angeles

Just erase the file extension .txt otherwise it will not work
[timezone.txt](https://github.com/libretro/RetroArch/files/6139818/timezone.txt)

![Lakka timezone](https://user-images.githubusercontent.com/73009731/111125034-12e52700-8569-11eb-9002-691b646fc10b.png)
