### ISSUE TITLE
CLI: Scan Directory/File

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5191]
## Description

Allow scanning directories of files from the command line interface. This is from @skpy over at https://github.com/libretro/Lakka-LibreELEC/issues/182 .

### Expected behavior

Have the ability to run something like the following to scan and add to the playlists:
```
retroarch --scan-directory="path/to/dir"
```

### Actual behavior

Right now, in order to create playlists, the user must add the directories manually. Would be nice to have the ability to set up a script to trigger `retroarch --scan-directory` to create the playlists so that users wouldn't need to do it manually.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `1cf6f2f20f496e4e21d59d54ac93977ceda00aec`

### Environment information

- OS: Linux
- Compiler: gcc

**Comment by hizzlekizzle** [comment]
I'm not really seeing the benefit of this. Playlists only work through the GUI, so there shouldn't be any point at which a user wants to use a playlist but isn't in a position to create them. Right??

**Comment by RobLoach** [comment]
Correct, this is just about creating the playlists from the command line.

**Comment by i30817** [comment]
This would be much more valuable if cores could be specified so specializations of the scan not based on file crcs could happen.

Scummvm will soon be able to be given a absolute path and return a 'yes it's this game' or 'no it isn't a game' and this would be much much better than asking users to create hundreds of files, one for every game scummvm supports.

Another case where specialization would be useful: the dreamcast TOSEC set is the best for actually playing because it hasn't some of the known dumping problems redump has on dreamcast (broken audio) but it's full of duplicate crcs because the .gdi files have often the same contents and they're used as index to the rom crcs.

These hypothetical better methods being selectable individually, or to at least per core so they can be tried sequentially without the performance drain of all the rest would be great for people who know what they're doing. I'd like to have actually working dreamcast metadata, or not need to create or move files to random dirs in order to have a playlist.

**Comment by bparker06** [comment]
With large folders this would be awfully slow (and a waste) if you're just adding a new file here and there. Something that watches the filesystem for new content that's not already in the playlist, and then only scans that, would be more appealing IMO. A cross-platform version of something like [this](https://github.com/mackron/dr_libs/blob/master/dr_fsw.h) would be nice.

**Comment by Kivutar** [comment]
Playlists are also used for netplay, it can be useful if we make a CLI version of the netplay lobbies

**Comment by paperbenni** [comment]
+1 for this idea, I'd like to automate scanning for my lakka station.

**Comment by r37r0m0d3l** [comment]
Still no progress 😭?

**Comment by RobLoach** [comment]
No.

**Comment by DocMAX** [comment]
second this! my game folder content changes constanly and i whould like to dynamicly update. a perfect solution would be to trigger with cron or even inotify a command line like retroarch-cmd --refresh-libraries.
