### ISSUE TITLE
Dont run in background not being able to turn on android

### ISSUE THREAD

**Issue by Alejandro787** [libretro/RetroArch#5225]
So I open retroarch and I decide to turn on user interface it won't 
Let me turn off  don't run in background... This is a problem because when in online net play you can't text your friends. So I hope this gets fixed or at least add a chat system inside the retroarch app.

Sincerely  Alejandro de La Torre

**Comment by bparker06** [comment]
That feature does not do what you think it does. "Running in the background" refers to the game running while you are inside the RA menu, not while using other apps on the device. It is not possible to do what you want with the current version of RetroArch, and I don't see this happening any time soon as the core would have to be always running inside of a java service instead of the normal foreground activity that it uses now... which would be a major change in how the program works.

**Comment by Alejandro787** [comment]
That's fine I don't need it

**Comment by parkerlreed** [comment]
Would like to show my interest in having this as an option. I have both aarch64 and armv7 RA on one device and I want to control one with the remote retropad from the other. Currently only Samsung explicitly allows all windows to be in the resumed state (via a hidden toggle)

Other Android devices with multi screen support don't seem to offer this. If I could have the main RA instance continue execution, this could be done without the toggle.
