### ISSUE TITLE
(Menu) Auto-update installed cores

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#5346]
## Description

Keeping libretro cores completely up-to-date takes a fair amount of effort from the user.  First, you need to read the blog often (and be able to understand it) to know which cores have updated.  Then, you need to go through a long list of all available cores and pick out the ones you have installed (sometimes, I forget which ones I am using).

### Expected behavior

A menu command that checks which of your installed cores have newer versions available, then installs them.

### Actual behavior

Manual updates.

### Version/Commit

- RetroArch: 1.6.7 / Git 2ff6bee

### Environment information

- OS: Windows 10

**Comment by bparker06** [comment]
Who would be paying for all that extra bandwidth? This would place considerably more load on the server as well.

**Comment by brianblakely** [comment]
I already update more cores every time they are changed, it's just a very manual and meticulous process at current.

**Comment by brianblakely** [comment]
Speaking of saving bandwidth, it seems like there are already a number of solutions that do this, and they are rapidly growing in popularity:

* https://forums.libretro.com/t/i-made-a-nightly-updater-program/5617

* https://www.reddit.com/r/emulation/comments/6ym4ax/another_retroarch_cores_updater_windows/

* https://github.com/cpinkus/cores_updater/

If RetroArch were to implement core updates directly, I think the vast majority of users would use it instead of one of these solutions.  That being the case, you could then do things like download updated cores via BitTorrent, which would greatly reduce bandwidth usage.

**Comment by RobLoach** [comment]
Here's an older issue about this: https://github.com/libretro/RetroArch/issues/2912

**Comment by ofry** [comment]
About paying...

If we check first is we need to update smth, are we really get big impact of bandwidth of server?

**Comment by meleu** [comment]
Hey guys, what about an option to "update all installed cores" instead of an auto-update?

**Comment by michellabbe** [comment]
After all the nice stuff that has been added in the last years (even live translation!), I can hardly believe this basic feature still hasn't been implemented.

A simple alternative would be to add some visual flags (icons, or "installed" / "update available") in the core updater list so we at least see which cores are already installed or not and/or have a newer version available.

As for bandwidth server load, I would tend to think most people do like me.  I update these only every couple weeks/months, and it's a real pain: I don't remember which cores are installed or not (and don't know which ones have an update available or not).  Checking the files in the cores folder versus the cores list in the core updater (not in same order) is a pain too so I tend to blindly update (too many) cores just to be sure the few I actually use are updated to the latest.  I probably "update" some of them more than once too because in the middle of the process I'm not 100% sure if I did these already or not.

So I think it would actually **save** server bandwidth (and certainly remove some real annoyances) if there was a menu option (or at least visuals) to easily update only the cores that actually need to be updated.

**Comment by gouchi** [comment]
- [Enhancement](https://github.com/libretro/RetroArch/pull/8350) that can help this issue but it has been revert, don't know the cause.

**Comment by RobLoach** [comment]
![Screenshot at 2020-01-21 08-35-32](https://user-images.githubusercontent.com/25086/72809230-3c3a4980-3c29-11ea-822e-9df55acd2356.png)

**Comment by meleu** [comment]
@RobLoach out of curiosity, could you tell me in which PR/commit was it implemented?

**Comment by RobLoach** [comment]
A few weeks ago in https://github.com/libretro/RetroArch/pull/9885 .... @jdgleaver gets all credit :rocket:
