### ISSUE TITLE
[Request] Auto-update RetroArch

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#5347]
## Description

Updating RetroArch is still a manual process, while Lakka has had an "update" command for some time now.

### Expected behavior

A menu command that updates RetroArch to the latest version.

Also good: an option for RetroArch to update itself whenever a new version releases.

### Actual behavior

Manual updates.

### Version/Commit

- RetroArch: 1.6.7 / Git 2ff6bee

### Environment information

- OS: Windows 10

**Comment by JesterIOS** [comment]
Not bad idea.

**Comment by ensra** [comment]
I would appreciate a flag to disable this feature at build-time, being a downstream distrbutor for a non-buildbot platform.

**Comment by RobLoach** [comment]
There are package managers and software centers for this kind of thing. While it makes sense for something like Lakka, it may save us a lot of work if we just use the desktop's preferred method of software updates.

**Comment by fr500** [comment]
On windows it would be pretty damn easy
Rename the current exe to retroarch.exe.old or whatever (from within RA), download the new one and close RA

The user can the start it over and be up-to-date.
On linux it's a crapshoot because of dependencies and install locations.

On android it could be done from the java realm and even auto restart the native activity

**Comment by rz5** [comment]
Since RA has an 'online updater' to refresh assets, cores, groceries and whatnot, I too would like an option there to auto-update itself, pulling new redist files as needed. 

Ideally it would auto-restart itself too. If RA has read-write privileges on its directory, a successful auto-restart would consist of (building upon the previous post):
1) Old instance renames its .exe to .exe.old;
2) Old instance fetches new .exe;
3) Old instance forces a save to the retroarch.cfg file;
4) Old instance starts new instance (new instance is now in focus);
5) Old instance kills itself;

**Comment by fr500** [comment]
You missed a little part, it should instance the new instance with the same args that were passed originally via cli. That might be important in case people have the config in a different folder.

At least always preserve the --config argument.

**Comment by RobLoach** [comment]
With the WIMP updates, can this be closed?

**Comment by orbea** [comment]
I'm going to close this given the WIMP updates.
