### ISSUE TITLE
1.6.7 x64 Windows 10 Installer fails if install directory changed

### ISSUE THREAD

**Issue by ceeeb** [libretro/RetroArch#5382]
## Description

I attempted to install RetroArch using the 1.6.7 windows 64 installer. The install folder was changed from the default directory to C:\Program Files\RetroArch\

### Expected behavior

RetroArch should install to the specified directory.
Default install folder should be the typical place for the current OS, not buried in APPDATA.

### Actual behavior

The installer only modifies the system registry and creates start menu shortcuts.
No actual program files are created/installed.
Start menu shortcuts and uninstall entry in the programs list are all broken.
Unable to uninstall as the registry entries point to non-existent files.
Unable to re-install as the installer tries to install into the same directory with the same behaviour.

### Steps to reproduce the bug

1. Run installer.
2. During install change the install directory to:
  C:\Program Files\RetroArch\

### Version/Commit
You can find this information under Information/System Information

- RetroArch-1.6.7-x64-setup.exe

### Environment information

- OS: Windows 10 Home 64bit

**Comment by fr500** [comment]
uh...
Right-click, run as administrator.

IT IS INTENDED TO INSTALL IN THAT LOCATION, you would need to run RA as administrator too if you install on that location until we have a platform driver that uses %userprofile%

**Comment by bparker06** [comment]
@ceeeb Like @fr500 says, this is not RA's fault but an issue with newer Windows OS's filesystem permissions. By default, normal users who aren't administrators cannot write to the Program Files folder, and this has been true since Windows 2000 (although user accounts weren't non-admin by default until Vista).

So even if you ran the installer as administrator to get it to install to the Program Files folder, RA would never be able to save its own configuration inside that folder unless you also ran RA as administrator every time, which is strongly not recommended.

Unless, however, you first created a Program Files\RetroArch folder manually, and gave it appropriate permissions so that your normal user account could write to it... *then* the installer might work and you won't have to run anything as administrator.

**Comment by Moth-Tolias** [comment]
this is still happening. why is the issue closed?

**Comment by Sonen10** [comment]
The fix is really simple, you just have to run the installer as an admin by right clicking a selecting _run as administrator_. Simple.

**Comment by fr500** [comment]
and then you have to run RA as administrator, it's not a bug. It's supposed to install to a user location, not an administrator location.

**Comment by archon810** [comment]
This is an odd one - all other installers manage to install into Program Files without having to run them as Administrator, but RetroArch can't. There has to be a way to do this so that the manual Run as Admin workaround is unnecessary.

**Comment by rakslice** [comment]
A quick note: If you've changed the installation path in the installer, and you want it to go back to the default, you can run `regedit` and delete the registry key for RetroArch in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths`
