### ISSUE TITLE
[Android] Touch Controls always default to Landscape orientation regardless of display orientation

### ISSUE THREAD

**Issue by Trevonn** [libretro/RetroArch#5387]
## Description

When in portrait mode the touch controls for landscape will be displayed resulting in distorted controls. This can be fixed by pressing the refresh icon but this is then reset if the game is closed or the app is exited.

### Expected behavior

Portrait controls shown in portrait mode

### Actual behavior

Landscape controls shown in portrait mode

### Steps to reproduce the bug

1. Open Retroarch
2. Launch game
3. Look at controls

### Version/Commit

- RetroArch: 1.6.7/Git Version: a235c0b

### Environment information

- OS: Android 7.0

Below is photo evidence of the issue
[Incorrect](https://user-images.githubusercontent.com/3117355/29931173-62dbfac8-8e68-11e7-881a-75a206963892.png)
[Correct](https://user-images.githubusercontent.com/3117355/29931174-62dcef00-8e68-11e7-8812-c99348661df5.png)

**Comment by hizzlekizzle** [comment]
Most people play in landscape, so we made that the default. If you want, you can open the overlay files in a text editor and change all of the overlay0s to overlay1s and vice versa and that will make the portrait configuration the first one that loads.

**Comment by Trevonn** [comment]
Thanks I'll try that. Any plans to make it switch automatically based on orientation?

**Comment by milesrotaru** [comment]
They didn't think of that when they wrote the overlay spec so they're not even labeled "horizontal" or "vertical". Hooking orientation detection into the overlay system would involve editing every single overlay.

**Comment by hizzlekizzle** [comment]
We thought of it, there just wasn't (and still isn't, I think...?) any way to handle that in a native activity.

**Comment by Ferk** [comment]
Native activity has an "onConfigurationChanged" event that receives the Configuration object. This objecf contains the orientation as one of its properties.

https://developer.android.com/reference/android/app/NativeActivity.html

**Comment by Ferk** [comment]
Maybe the simpler way to implement this and yet allow flexibility and less changes in current overlays would be having landscape overlays have a "portrait_switch" with the number or the portrait overlay and that portrait overlay would have a "landscape_switch" indicating the number of the corresponding landscape overlay to switch to when changing to landscape.

If there's no label indicating an alternative overlay, then the overlay won't be changed, just like happens now.

This way previous overlays would still work, they just won't change orientation automatically.

**Comment by FayneAldan** [comment]
Can't you just check the current resolution to determine the orientation? If the width is greater than the height, it's landscape. Otherwise, it's portrait.

**Comment by foolishgrunt** [comment]
Not that there was any doubt about this issue existing, but I can also confirm it. And since I don't see it already mentioned in the thread anywhere, I'll mention that even after I switch the controls from landscape to portrait, they switch right back as soon as I open the menu (really annoying if all I want to do is save the state and continue playing).

I would love to see the controls select portrait or landscape automatically based on the screen orientation, but I'll settle for a workaround. Re: hizzlekizzle's suggestion in the first comment, am I correct that this would only be possible on a rooted phone? (My phone is not rooted, so the only RetroArch files I can access are in /storage/emulated/0/RetroArch.)

**Comment by hizzlekizzle** [comment]
@foolishgrunt They go into the root area by default, but it's easy to fix: make a new directory in the user-writeable area, go to settings > directory and change your overlay directory to the new location, re-fetch them from the online updater, Profit!

**Comment by andreyorst** [comment]
So I also have this problem. Whenever I go to the menu, to adjust settings, or restore a savestate my controls start to look like this:
![image](https://user-images.githubusercontent.com/19470159/60566460-9d72fc00-9d6f-11e9-91af-838143c2f212.png)
Why Retroarch can't at least remember user's choice for current session? I'm explicitly pressing the rotation button, and it changes some setting in the app for sure. Why it is lost when going to the menu? Why I can't save this as a core parameter? If you can't detect screen rotation, maybe make a setting that will set the screen rotation just like other emulators are doing?

> Most people play in landscape, so we made that the default. 

Fair enough, but I don't like to play in landscape, because 40% of the game is now covered with controls and my thumbs, but I've turned on my auto screen rotation only to discover this abomination:
![image](https://user-images.githubusercontent.com/19470159/60566578-f773c180-9d6f-11e9-8ff7-49d24abc3579.png)
The controls are not even working, touch areas are all in wrong places. I've enabled developer option that displays the touch point on the screen (white circle) and you can see, that <kbd>R1</kbd> button is active on this screenshot, but my thumb is pressing just above the start button:
![image](https://user-images.githubusercontent.com/19470159/60566721-69e4a180-9d70-11e9-87a2-c7401c1b0733.png)
Which only means that touch area is still 90 degree rotated.

This is mGBA core, on Retroarch 1.7.7 from play store, on Android 8.1.0 Nexus 5X with custom DPI set to 485 in developer options ("Smallest width" parameter) if this matters.

**Comment by hizzlekizzle** [comment]
Yeah, the rotation is ... weird, to say the least. It should look correct if you start in landscape mode instead of rotating after RetroArch is launched.

**Comment by andreyorst** [comment]
I've figured out that landscape scretch is because of vulkan driver. this doesn't happen on gl driver. However I still do not understand why there's no detection mechanism or setting to lock into specific rotation

**Comment by hizzlekizzle** [comment]
I believe this has been resolved with the automatic overlay rotation, so I'm going to close this issue.
