### ISSUE TITLE
1.6.7 zip install can't download cores

### ISSUE THREAD

**Issue by mangopipeline** [libretro/RetroArch#5412]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Core Updater throws the following error when i try to install some cores...
Task Failed: downloading .index-extended

### Expected behavior
I should get a list of core for download

### Actual behavior

i get an empty list

### Steps to reproduce the bug

1.  unzip retroarch 1.6.7 windwos 64 7z file
2. run retro arch, and attempt to load a core
3. click on the download core opiton

- RetroArch: 1.6.7

### Environment information

- OS: windows10
- Compiler: msvc2010

**Comment by fr500** [comment]
Web server error, it should correct itself in a few minutes (I hope)

**Comment by OGWHID** [comment]
Anyone who is having this problem (Seems to be a lot of people) follow these simple directions:

1. Go to your install directory of retroarch.  In the base folder, there is a file called retroarch.cfg.  Make a copy of this file as a backup in case your screw up the next step.
2. Open this file in a text editor.
3. Search for the line: "core_updater_buildbot_url" (Should be the 2nd-ish line in the file)
4. Your problem is that URL.  If you go to it, it does not exist. So...
5. Go to http://buildbot.libretro.com/nightly/ - and drill down for your OS...For windows, the path that worked for me was http://buildbot.libretro.com/nightly/windows/x86_64/latest/
6. Save your changes, and relaunch RetroArch.  
7. Try the download process again.  Success.

**Comment by cawoodm** [comment]
http://buildbot.libretro.com/nightly/windows/x86_64/latest/ is currently missing (404 not found).

Is it the case that there are different cores (dlls) depending on if retroarch is run as 32-bit or 64-bit?

**Comment by fr500** [comment]
Yhy ar eyou using the msvc release? use the normal windows x64 release.
And yes the cores are architecture specific.

**Comment by fr500** [comment]
why are you using the msvc release? use the normal windows x64 release.
And yes the cores are architecture specific.

**Comment by cawoodm** [comment]
Yeah, that was it.

**Comment by sambob220** [comment]
I used the installer to install retroarch 1.7. And I can't get retroarch to connect to the web for anything within the interface. Core Updater brings back "Task Failed: Downloading Index etc." for every update option I try under the online updater, I get "task Failed: Downloading [corresponding file name] errors. 

I have tried double checking appropriate lines in the cfg file. They currently look like this, and I'm running a windows 10 machine: 

core_updater_buildbot_url = "http://buildbot.libretro.com/nightly/windows/x86_64/latest/"
core_updater_buildbot_assets_url = "http://buildbot.libretro.com/assets/"

Those urls look accurate and direct me to the appropriate places. So I have no clue what's going on. Even manually loading the cores leaves me with strange errors. Scanning a directory only adds a few of the roms instead of the 14 I had in there.

I've tried reinstalling, installing without the installer, changing the directory of installation, and runing as administrator, and nothing has an impact. Any thoughts...

**Comment by bparker06** [comment]
@sambob220 

>manually loading the cores leaves me with strange errors

I'm guessing this means it's not RA's fault but something else on your system is wonky. Try disabling any antivirus-like software (including windows defender) or firewall, maybe even reinstall *after* doing that.

Can you elaborate on what these strange errors are exactly?

**Comment by sambob220** [comment]
The main error was that I would load a ROM directory and it would only end up detecting 2 out of the 14 roms it said that it found, which was weird. Attempting to launch the ROM had errors until I realized switching the CORE fixed that. 

I'm able to use the program alongisde launch pad without a problem now after manually installing all of the cores from the URL. But it still has no update connectivity through the interface. I'm going to see if it's something with windows firewall later. That could be the problem. 

Thanks for the reply!

**Comment by hidwulf** [comment]
Dunno if it could help but the real issue there that the URI in the config file are good except they are in http instead of https! A fix is expected.
