### ISSUE TITLE
[Windows] Scanning files doesn't seem to be working

### ISSUE THREAD

**Issue by rcmero** [libretro/RetroArch#5437]
I had a previous version of RetroArch installed and it scanned the collection of files I had no problem. Now for some reason those same files aren't being detected by RetroArch.

Normally RetroArch would detect the files and the console they correspond to, and then group them together. Now RetroArch doesn't even detect them.

I have updated the database information of my installed cores multiple times, thinking that to be the issue, but that doesn't seem to be it.

The files still load on their corresponding core correctly, they're just not being displayed on the main menu of RetroArch.

Running Windows 10 v1704, on the most recent stable version of RetroArch.

**Comment by twinaphex** [comment]
Can anybody confirm this? @radius @bparker06

**Comment by ofry** [comment]
Could you try latest NIGHTLY version of Retroarch?

**Comment by bparker06** [comment]
Works fine here on latest commit under Linux.

**Comment by fr500** [comment]
Seems to work here too

**Comment by orbea** [comment]
Given that this issue was not reproducible, other users haven't complained about scanning being broken on windows and the lack of activity I am going to close this issue.

Here are a few common reasons scanning could fail:
* The core info file is missing
* The database file is missing.
* The rom is not part of the database file.

If the problems persist please make sure to be using an updated RetroArch version and confirm its not one of the above reasons.
