### ISSUE TITLE
Custom aspect ratio X and Y position options don't work in portrait.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#5525]
Using latest nightly on Android. These options work in landscape but in portrait all I get is a black screen when selecting custom aspect ratio. It is a problem if you want to use borders or gb overlay in portrait.

**Comment by hizzlekizzle** [comment]
Something must be going on other than the option just being flat-out broken because someone just submitted a gameboy overlay that requires a custom viewport in portrait (possibly the one you're referring to) and it couldn't have even worked for the creator if the feature was completely broken. So, perhaps it's related to your device/GPU/whatever...?

**Comment by blackman91** [comment]
If I enable integer scale the screen does not disappear in portrait with custom aspect ratio enabled but the x and y position options don't work with this enabled as intended, this issue happens with motog5plus, can anyone with an android reproduce this issue?

**Comment by blackman91** [comment]
Just tried the latest nightly and this issue seems to be fixed now, I can play with the gb overlay now with my device, you can close this now, great job guys.
