### ISSUE TITLE
Quick Menu icon rendering issue and empty launch menu after closing content

### ISSUE THREAD

**Issue by Brunnis** [libretro/RetroArch#5590]
## Description

When entering the Quick Menu, the "play" icon shown when launching content from a playlist is rendered behind the regular item icons. Also, when closing content and returning to the launch menu for the playlist item, instead of "Run", "Information", etc, the text "No items" is shown.

Note: the issue is not present when launching content by choosing "Load Content", only when launching from a playlist.

### Expected behavior

The play icon shall not be shown behind the regular icons in the Quick Menu. When returning to the playlist item launch menu, it shall not be empty.

### Actual behavior

See description.

### Steps to reproduce the bug

1. Launch game from playlist.
2. Go into Quick Menu. Notice the incorrect icon rendering.
3. Choose "Close Content". You now return to a view saying "No items".

### Bisect Results

The offending commit is https://github.com/libretro/RetroArch/commit/538d51553c77ed22963eb0533c29b38af466ad55

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 03803d1b

### Environment information

- OS: Not OS dependent (tested on W10 and Linux)

**Comment by Brunnis** [comment]
I just completed a bisect. The offending commit is: https://github.com/libretro/RetroArch/commit/538d51553c77ed22963eb0533c29b38af466ad55

**Comment by orbea** [comment]
Yea you are right, sorry about that I failed to test loading from a playlist. I can try to play with it more today to see if I can get it right, but any advice would be appreciated ofc...
We could revert it, but the other issues will come back then.

**Comment by orbea** [comment]
Also, I'm not sure what you mean the the incorrect icon?

**Comment by orbea** [comment]
@Brunnis I sent a PR that seems to fix the regressions. https://github.com/libretro/RetroArch/pull/5591

However there are still some issues that existed from before my changes.
1. When loading content from the cli or a contentless core (2048) it will still return the user to the quick menu with `No items` listed.
2. When loading a contentless core and then opening the menu, it will default to `Restart` instead of `Resume`.

I suggest leaving this issue open for now to track these problems.

**Comment by orbea** [comment]
@Brunnis I sent a PR that seems to fix the regressions. #5591

However there are still some issues that existed from before my changes.

1. When loading content from the cli or a contentless core (2048) and then closing the content it will still return the user to the quick menu with `No items` listed.
2. When loading a contentless core and then opening the quick menu, it will default to `Restart` instead of `Resume`.

I suggest leaving this issue open for now to track these problems.

**Comment by Brunnis** [comment]
Okay, good. I'll test the fix ASAP. As for keeping this issue open to track the two pre-existing issues, I'd prefer to have separate issue(s) tracking those. Maybe @twinaphex can chime in regarding any preference on how to handle that?

**Comment by Brunnis** [comment]
I can confirm that the pull request fixes the issues I was seeing. Thanks!

**Comment by orbea** [comment]
Cool, thanks for trying it. I'll leave it to you and @twinaphex on where to track the prexisting related issues.

**Comment by orbea** [comment]
While we are keeping track there is a third issue with `Close Content`.
3.  When closing content it defaults to `Remove` instead of `Run`. I think this in `menu/cbs/menu_cbs_ok.c` is related.
```
int action_ok_close_content(const char *path, const char *label, unsigned type, size_t idx, size_t entry_idx)
{                                                                                                            
   /* This line resets the navigation pointer so the active entry will be "Run" */
   menu_navigation_set_selection(0);
   return generic_action_ok_command(CMD_EVENT_UNLOAD_CORE);
}
```

**Comment by orbea** [comment]
@Brunnis I made issues for the three I mentioned here, please feel free to close your issue. :)
https://github.com/libretro/RetroArch/issues/5594 https://github.com/libretro/RetroArch/issues/5595 https://github.com/libretro/RetroArch/issues/5596

**Comment by Brunnis** [comment]
Great, thanks!
