### ISSUE TITLE
Make ppsspp core auto download needed files.

### ISSUE THREAD

**Issue by duramato** [libretro/RetroArch#5695]
To make ppsspp work, I had to download files mentioned here https://wiki.libretro.com/index.php?title=PPSSPP
I don't know if this is the expected behaviour but I was expecting it to work out of the box, to just need to download the core from within retroarch.

**Comment by bparker06** [comment]
Those files are actually very outdated (so is the wiki), the new ones are here:

https://github.com/libretro/ppsspp/tree/master/assets

You may experience issues with some games without the latest version of the assets.

**Comment by duramato** [comment]
Which further supports my complaint. I had a hard time finding that wiki explaining I had to also "install" some extra files. 
Why isn't it auto grabbed when the core is installed? Doesn't make sense to me not to as ppsspp doesn't work without them.

**Comment by RobLoach** [comment]
Rather than having the core do this, it might be best as a script in [libretro-database](https://github.com/libretro/libretro-database) . We could make a script that would automatically download free, publicly available, files. There is [BIOS.dat](https://github.com/libretro/libretro-database/blob/master/dat/BIOS.dat) that documents all BIOS files across all cores.

**Comment by fr500** [comment]
We're in dire need of a global solution for core assets / bios files, I'll open an issue about this

**Comment by orbea** [comment]
@fr500 Yes, this would help a lot with distros when the bios/system files are legal to distribute. See nestopia and ppsspp for example. Or Gearboy which uses an free bios.
