### ISSUE TITLE
Bug Retroarch core DOS in PSVITA

### ISSUE THREAD

**Issue by stefanobasile** [libretro/RetroArch#5774]
## Description bug

every time you try to start this game, the backward core crashes!
this happens when I backward on psvita core "dos"

games name:
Top tennis (dos,1997) 

game link:
https://mega.nz/#!MlVnBZJa!5tpykxvuNhmQwt6xnnYAt4P643_-19HwjdkiDdeKGa8

**Comment by meepingsnesroms** [comment]
What does that mean "when I backward", rewind is not supported on this core because it does not support savestates, it dosent support save states because you would have to backup entire floppys/harddrives on savestate or you would corrupt the filesystem.

You should refile this as "RetroArch crashes when attempting to rewind on cores that dont support savestates".

**Comment by stefanobasile** [comment]
when application load freezes!

**Comment by fr500** [comment]
please use the template to report bugs.
