### ISSUE TITLE
[IMPORTANT] Redream is no longer open-source

### ISSUE THREAD

**Issue by JackoboLeChocobo** [libretro/RetroArch#6066]
Hi developpers of RetroArch,

I see on your website an article about Redream and a core of it on RetroArch. I'm here to inform you that Redream is now closed source on Gitlab ( https://gitlab.com/inolen/redream ) and so we can't download any source code. He applied that since I reported an issue about users that must pay once the access to download any binaries.

Here is the answer of the developper, Anthony Pesch (inolen) after I say that now his works on Gitlab violates the GPL3 licence : 

_"No, the project is not in violation of the GPL.

This project does not use any GPL licensed dependencies, so there are no copyleft stipulations requiring the code to be licensed under the GPL, leaving myself (the author) to license the code as I see fit.

Previously, the code was public and provided under the GPL license. **Now however, the source is closed and not provided to you under any open source license**."_

If people want to contribute to Redream project, you can go here : 
- https://github.com/libretro/redream
- https://github.com/JackoboLeChocobo/redream-Reloaded
Or of course on any fork of Redream that i don't have seen ^^ . Open-source is a share of knowledge, not a business.

Do I need to report these issue on the documentation repository ? ( https://github.com/libretro/docs/issues )

**Comment by twinaphex** [comment]
Really shitty move. Yeah, I know all about inolen, and ever since the sega forever/retroarch story hit, he has been having dollar signs in his eyes and would like to make business deals with Redream. Except he goes about in the most stupid of ways, and honestly he will make no money.

Dreamcast emulation is almost completely sabotaged at this point on the opensource front by these guys. They put the cart before the horse, and before the emulator even amounts to anything, think they can make a ‘business’ around it. I think also since he works at nvidia that others have been whispering into his ear that this is the way he should go. the author of the other dreamcast emulator that is opensource is also an nvidia employee, and ever since he got hired reicast/nulldc has been left for dead. so honestly, opensource dreamcast emulation is at a standstill now. none of them care about opensource or preservation, its about what is good for them and them alone.

anyway, we will not remove the current redream repository. it was still GPL 3 back then, it is what it is.

**Comment by JackoboLeChocobo** [comment]
Indeed don't remove your repository ;3 Like I said, If people want to contribute to Redream project, they can go for instance in your repository. I created too a repository of Redream to conserve the project and to apply patches/codes of other people if they want to improve the Dreamcast emulation. I have saved a copy of the messages of the issue between me and inolen in case of I will need it.

I think we can have the help of people to improve the emulator. If someone reads all of this, we will really appreciate any help to improve the emulator.

I will put a link of your repository on my github project : https://github.com/JackoboLeChocobo/redream-Reloaded .

**Comment by twinaphex** [comment]
It's really beyond sad how sabotaged opensource Dreamcast emulation is, and all just for petty greed. I hope we can make a positive difference in that regard. It's clear none of the existing authors care at this point.

**Comment by JackoboLeChocobo** [comment]
That's why I do a copy of the code and put it in my repository called "redream-Reloaded". I applied the same method for DS emulation ( DeSmuME-Reloaded on my repository) . If people want to contribute, they can do it ^^

**Comment by twinaphex** [comment]
is desmume as a project dead then?

**Comment by JackoboLeChocobo** [comment]
Several years ago, DeSmuME team has created the Wifi support for connection on DWC servers, but they never applied the code. And the team on DeSmuME is the same mentality as inolen. So I use the last code (0.9.12) on their repository, and I include myself the code for Wifi connection on DWC servers. I tested this support on Windows and Linux.

**Comment by RinMaru** [comment]
Well im disappointed I really wanted Redream to succeed since it was on Windows and not Android focused like Reicast. Demul is good but I like playing my stuff in HD and the old DX11 plugin just doesn't work well enough for me.

**Comment by twinaphex** [comment]
I'm disappointed too. It is what it is. Anyway, we will keep the current GPLv3 version of it that was still available, and I hear from @fr500 that there will still be a libretro core version available, but potentially behind a paywall. So whatever, it is now outside of my hands and I don't really like how Dreamcast emulation is now going behind some kind of paywall. 

Maybe we would get somewhere with Dreamcast emulation if we would crowdfund it and then stipulate that all code has to be opensource, or maybe get involved ourselves, dunno. I just don't like the fact it's 2018 by now and Dreamcast emulation as far as opensource is concerned is still so poor. It should be way ahead of this current state. I wonder if there is anybody from MAMEdev we could collaborate with to drag DC emulation out of the doldrums, but not sure, diplomacy is not exactly what this scene is known for and greed and self-interests seems to be the only thing most devs care about instead of what is good for the scene.

**Comment by JackoboLeChocobo** [comment]
I can try to get a libretro working version. I see a libretro version of redream somewhere.

**Comment by orbea** [comment]
Can't say I didn't see this coming even if I hoped otherwise. :(

**Comment by ofry** [comment]
About desmume:

https://github.com/TASVideos/desmume/

It's official repo now. And it's active...

**Comment by JackoboLeChocobo** [comment]
For information, DesMuME-Reloaded uses this repository but with new features like the WiFi support to connect to DWC servers (https://github.com/polaris-/dwc_network_server_emulator) , feature that was created by _luigi / StapleButter several years ago. And with a Windows version that compiles and works without issue ^^" . DesMuME is maintained by a team who has the same mentality as inolen ( see some posts / answers of zeromus with people on the forums ...... ) . So I decided to create a working version of it and I have a libretro version of it that works for the moment on Linux with all my new features.

**Comment by willcast** [comment]
May I ask what happened to the redream reloaded source repository? Seems like the account that owned it was deleted and re-created somewhat recently.

**Comment by twinaphex** [comment]
Nothing was added to it. I think we can just use the existing redream repo on libretro if there's any need for that or if there is a sudden upswing/resurgence in developer interest.

By all practical accounts, though, Reicast Libretro is the one to watch, and it has surged ahead of closed-source Redream already in a lot of areas, so I think our efforts are best spent there.

**Comment by polocatfan** [comment]
really lame you guys removed this. you're allowed to continue using code that was once open source.
