### ISSUE TITLE
Load Core & Load Content Borked on Android

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6254]
## Description

Since recently load core & load content are completely messed up, it seems core information is no longer being populated correctly so there are never any core suggestions on load content, when going to load core the names are not the nice core names either.

### Expected behavior

The core names should be the friendly names in Load Core
There should be suggestions in Load Content

### Actual behavior

![image](https://user-images.githubusercontent.com/1721040/35980148-faa69408-0cb7-11e8-855e-f2b35d6ab3d7.png)

![image](https://user-images.githubusercontent.com/1721040/35980167-0792545e-0cb8-11e8-81dc-7f659079d9e7.png)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: f0227c7

### Environment information

- OS: Android 7
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
Maybe somethign to do with this is wrong now?

https://github.com/libretro/RetroArch/blob/master/core_info.c#L209

We really need to get rid of that crappy code to be honest. I think it tries to do some path manipulation stuff to then arrive at the right filename / path for the associated core info file.

The problem here is that dynamic libraries for Android are named differently from all the other platforms due to this _libretro_android prefix. Consoles do this too.

**Comment by fr500** [comment]
well when I suggested renaming the libraries you shut it down immediately,
Now it's too late to change that, it would break all installations

**Comment by meepingsnesroms** [comment]
Does this happen on iOS as well, it has *_ios.dylib?

**Comment by fr500** [comment]
@meepingsnesroms it's fixed now via rollbacks
