### ISSUE TITLE
(Video) D3D11 Shader preset cannot save

### ISSUE THREAD

**Issue by dora3k** [libretro/RetroArch#6351]
Using Video Driver d3d11
After Choosing a Video shader,

Save Core Preset or Save Game Preset. But no effect. It has not been saved.

Using Video Driver gl,
Save Core Preset or Save Game Preset Works Correctly.

Solly, I want to use d3d11.
Can you solve it?

- RetroArch-1.7.1-x86
- OS: Windows 7

**Comment by hizzlekizzle** [comment]
I suspect what's going on here is that if you save a core/game preset of one shader type and then save another core/game preset of another type for the same core/game, the first one is not overwritten (unsurprisingly, since they have different filenames) and RetroArch will continually try to load one or the other depending on shader priority and regardless of which video driver is active. This leads to no shader being loaded if the highest-priority shader is wrong for the video driver.

**Comment by LazyBumHorse** [comment]
That's exactly what has been happening and it's fixed by 579ff877e4a44be31b71a313b55dadeb0e7dd001 with the only exception being gl, which loads GLSL before Cg if there's both.

So dora3k, if you're still out there, use the next nightly build.

I think this issue can be closed.

**Comment by hizzlekizzle** [comment]
Awesome! I'll close it and if the problem persists, we can reopen it.
