### ISSUE TITLE
Keeping window maximized when resolution changes

### ISSUE THREAD

**Issue by Oggom** [libretro/RetroArch#638]
When RetroArch is running in a maximized window it will un-maximize itself when a core changes its resolution.
For example this happens when entering the 2P mode in Sonic the Hedgehog 2 on Genesis Plus GX.
Tested on Windows 7 x64 in case this may be platform-specific.

**Comment by Ferk** [comment]
I noticed this issue as well and I was looking if it had been reported in the past but found this which was closed. Was it closed because it was resolved in some way or because it's not gonna be?
It's annoying that the window keeps getting resized and has to be re-positioned manually, often getting out of the boundaries of the screen (unless you constantly keep the window in the upper left corner).

However, after playing a bit with the settings I discovered that if you set the "Window Scale" option to a very big number (bigger than your screen), it'll keep the window as big as possible even when different cores change resolution, so it's essentially equivalent to being maximized.
Note that this only works if you have "Window decorations" enabled. For some reason if the window decorations are disabled the Window will resize past your screen size.
