### ISSUE TITLE
Godot Core

### ISSUE THREAD

**Issue by moocow1452** [libretro/RetroArch#643]
Godot is a Game Making Application created within it's own engine, and I was wondering since Libretro is trying to push into it's own gaming architecture to run games everywhere, might it be worthwhile to form a Godot runtime so that games can be created and played entirely within the same application, or would just be outside of the scope of the project for now?

**Comment by silverkorn** [comment]
@twinaphex, @kivutar,
Sorry to bring back an old thread but do you think that it might be more considerable with the recent release of 3.0 and the more attention it's starting to get?

I'm not really familiar with Godot neither libretro integration and I might be totally wrong but might it be created as a driver?

Thanks!

https://godotengine.org/ - https://github.com/godotengine/godot

**Comment by mathpeseg** [comment]
With godot 3.1 it would be better to make it probably, they are getting back the opengl 2.0 for the engine. I would love to make games for mi raspberry with godot.

**Comment by Ferk** [comment]
Doesn't Godot allow for games to be coded in C++? Does that mean that the games are exported to each different platform and are not really portable once exported?

Does Godot allows to distribute the games in some crossplatform way that can be portable for a libretro core to load?

**Comment by walksanatora** [comment]
@Ferk replying a bit late (but I got nerd sniped when trying to play wii games on my quest 2), since we are now in Godot 4.3
the Godot editor it's self wont let you write c++. it does allow C# (via the mono editor) or it's own lang called GDScript.
but you *can* make and register custom nodes/objects/RefCounted's via Godot's GdExtension(in 3.x it is called GDNative) api which allows you to write and compile native code into libraries that Godot depends on (which can also be published to Godot's Community Repository)

**Comment by Ferk** [comment]
@walksanatora So that means they wouldn't be portable, correct?
That would make it not a good candidate for a libretro core, imho.

Ideally, Godot should have an option to export to a format that could run over a layer that is portable. But this does not seem possible if the game content itself could be containing native code.

**Comment by walksanatora** [comment]
It could be portable since you can compile natives for each target platform and only include natives for the target platform

**Comment by moocow1452** [comment]
Could we revisit this now that we would have something to build around?

https://github.com/migueldeicaza/libgodot
