### ISSUE TITLE
[Feature Request] - Allow RetroArch Android version to force screen orientation (ignore system value)

### ISSUE THREAD

**Issue by singularity098** [libretro/RetroArch#6535]
## Description

Would love for RetroArch to support a forced screen orientation on Android/iPhone version.  In other words the user could select something like "Force orientation = landscape or portrait" and then the Android system setting of forced portrait, forced landscape or auto select will be totally ignored by RetroArch.

### Expected behavior

This is expected as an option because most native games on Android do not support different screen orientations.... they will often just force to landscape mode, and this is desirable as most peoples phones are usually locked to portrait but in the case of gaming, landscape is generally preferred.  In my opinion portrait mode is nearly useless for RetroArch as it takes poor advantage of screen real estate in 99% of games, though that's just my opinion.  The option to force landscape orientation would be wonderful.

### Actual behavior

Forced orientation (of EVERYTHING, including menus, not the rotate option) does not appear to be an option in RetroArch.

### Steps to reproduce the bug

N/A

### Bisect Results

N/A

### Version/Commit
You can find this information under Information/System Information

- RetroArch v 1.7.1

### Environment information

- OS: Android
- Compiler: N/A

**Comment by PrimordialHelios** [comment]
Nobody's responded to this, but if you're still looking for a workaround, you can set the aspect ratio to .67 and the rotation to 270 degrees. The only issue is that the video is centered on the screen. it's still better than nothing though.

**Comment by Gnalvl** [comment]
I too would love to have this option. Many androids get flaky about rotating properly over time, either because the accelerator gets damaged or static buildup causes interference. Mine suffers from this problem and when it happens, Retroarch will not switch to landscape mode no matter how I tilt the phone. Meanwhile, portrait mode for typical 4:3 and 16:9 games is so tiny it's not even worth playing.

As a workaround, I recommend using an app like this to force landscape when necessary:
https://play.google.com/store/apps/details?id=nl.fameit.rotate

There's also some advice from Google here about restoring rotation when static buildup happens:
https://forums.androidcentral.com/google-nexus-7-tablet-2013/389593-auto-rotate-does-not-work.html

"Called Google while still under warranty and they said it was because static builds up on the accelerometer and requires a soft reset. Turn the tablet off. Wait a few minutes. Press and hold the power button for 30+ seconds (let it cycle through turning on and off) and let it finish it's cycle to off after holding it for 30 seconds (thus the +). Power it back on and it should be fixed."

**Comment by bmaupin** [comment]
Here's what I did to achieve this (using RetroArch v1.7.7):

1. *Settings* > *User Interface* > enable *Show Advanced Settings*
1. *Settings* > *Video* > *Screen Orientation* > *90 deg*

Now the RetroArch menu and any games are automatically rotated even though I have my screen rotation locked.

**Comment by singularity098** [comment]
@bmaupin - This suggestion totally works.... didn't realize that you can already do this.  Thank you sir!

I'll mark this as closed because the feature already exists, I just didn't realize it.

**Comment by alo224** [comment]
Just use an app for Android called Rotation Control. It works great!

**Comment by KINGLIFER** [comment]
NO they mean this. https://apps.apple.com/us/app/delta-game-emulator/id1048524688
