### ISSUE TITLE
[Import] Scanner cannot real dual-layer Wii discs

### ISSUE THREAD

**Issue by flibitijibibo** [libretro/RetroArch#6544]
## Description

When attempting to add dual layer Wii discs to the playlist via the Scan Directory/Scan File function, the process will fail to add them to the list due to an unknown bug in the file detection system.

### Expected behavior

The serial number would get read from the top of the ISO, recognized by the database, and added to the Wii playlist.

### Actual behavior

From what I can tell, we don't get as far as the serial detection. The serial is valid and exists in the database, but typically when you read in a Wii disc you get something like this in the log...

```
[INFO] Found disk label 'RM3E01'
```

... but for DL discs that never happens. So presumably this function never trips...

https://github.com/libretro/RetroArch/blob/0ee124582c8f2b60cb71ab2537811dd0aad2fcc3/tasks/task_database.c#L166-L172

... which means this doesn't happen...

https://github.com/libretro/RetroArch/blob/0ee124582c8f2b60cb71ab2537811dd0aad2fcc3/tasks/task_database.c#L603

... so for some reason these files in particular don't get iterated on by the database task. The only significant difference between SL and DL for ISO files is the size; SL discs are 4699979776 bytes while DL discs are 8511160320 bytes. Perhaps the file is just too big...? Unfortunately since I'm using the Flatpak version I can't step through and see exactly where things go wrong.

### Steps to reproduce the bug

1. Import > Scan File...
2. Select Wii DL ISO, should attempt to scan and say "done"
3. No new entry!

Tested files are Metroid Prime Trilogy, Super Smash Bros. Brawl, Metroid: Other M, and Xenoblade Chronicles.

### Version/Commit

- RetroArch: Flatpak 1.7.1

### Environment information

- OS: Fedora 27 x86_64

**Comment by RobLoach** [comment]
Could you provide the CRC of the four tests you provided?

**Comment by flibitijibibo** [comment]
```
8a4b439d Metroid Prime Trilogy
29da327a Metroid: Other M
854b2889 Super Smash Bros. Brawl
472ffed2 Xenoblade Chronicles
```

**Comment by i30817** [comment]
It's actually not only dual layer discs. It's not reading 

> game (
> 	name "Another Code: R - A Journey into Lost Memories (Europe)"
> 	serial "RNOP01"
> 	developer "Cing"
> 	publisher "Nintendo"
> 	releaseyear 2009
> 	releasemonth 6
> 	releaseday 26
> 	users 1
> 	rom (
> 		serial "RNOP01"
> 	)
> )

in spite of the data being on the Wii dat and redump dat. It finds the serial and bails out:

> [INFO] Comparing with known magic numbers...
> [INFO] Found disk label 'RNOP01'
> [INFO] Comparing with known magic numbers...
> [INFO] Found disk label 'SL2P01'
> [INFO] Written to playlist file: /media/i30817/Huggin/Documents/retroarch/playlists/Nintendo - Wii.lpl
> 

So i think there is something wrong with `int detect_serial_ascii_game(intfstream_t *fd, char *game_id)` at `task_database_cue.c`. Should be relatively easy to solve.

**Comment by i30817** [comment]
Well that function is more than a bit strange. It basically does:

```
for x in [0...9999]:
  if can read 15 chars
     for y in [0..15]
        count number of 'ascii chars'
     if number of ascii chars > 3 and < 9
         return because it 'could' be a serial
```

This is... very error prone if i understand it correctly. First, there is no handling of the case where the serial in in two multiples of 15, with a character right in the middle... second, who's to say that a sequence of chars that is between 4 and 8 characters won't appear first that isn't a serial?

**Comment by i30817** [comment]
Ok, i have a idea. In `task_database_cue.c` there is this table:

```
struct magic_entry
{
   int32_t offset;
   const char *system_name;
   const char *magic;
};

static struct magic_entry MAGIC_NUMBERS[] = {
   { 0,        "ps1",    "\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x02\x00\x02\x00"},
   { 0x838840, "pcecd",  "\x82\xb1\x82\xcc\x83\x76\x83\x8d\x83\x4f\x83\x89\x83\x80\x82\xcc\x92"},
   { 0,        "scd",    "\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x02\x00\x01\x53"},
   { 0x000400, "gc",     "\x00\x01\xC7\x04\x80\x28\x00\x60\x00\x00\x00\x00\x00\x00\x00\x00\x00"},
   { 0,        NULL,     NULL}
};

```
(scd and gc start with \00)

The function searching for the signatures uses this code:
`if (string_is_equal(MAGIC_NUMBERS[i].magic, magic))`

Now imagine that the offset of the disc (that was read into magic) started with \00

string \00 is equal to \00 right?

Basically, don't use string_is_equal to compare fixed size file offsets? Let's see the definition of it on `./libretro-common/include/string/stdstring.h`:

```
static INLINE bool string_is_equal(const char *a, const char *b)
{
   if (!a || !b)
      return false;
   while(*a && (*a == *b))
      a++, b++;
   return (*(const unsigned char*)a - *(const unsigned char*)b) == 0;
}
```

And a test:
```
      if(string_is_equal("\x00\x01", "\x00\xff")){
        printf("WRONG!\n");
      }
```
Prints because the 'string' ie: the characters until the first \00, are indeed equal. Equal to "" that is.

**Comment by i30817** [comment]
Replacing that if by `if (memcmp(MAGIC_NUMBERS[i].magic, magic, MAGIC_LEN) == 0)` is not enough apparently. Wii discs get no system (as they're supposed to) but several still don't parse. That some parse indicates there is a fallback somewhere above in the callers but i haven't figured it out yet.

**Comment by flibitijibibo** [comment]
Here's a question: How hard is it to isolate the database task into a separate program for the purposes of unit testing? Normally I'm not a TDD guy but if there's a way for me to just load up a filename and send it straight to the task without loading up all of RA I'd totally be up for stepping through this line-by-line. (Gotta do something while my **REDACTED** devkit is in limbo...)

(Also argh, that strcmp - if nothing else comes out of this, let's at least turn that into a memcmp!)

**Comment by flibitijibibo** [comment]
>This could actually be feasible since I think the task-based code is fairly well compartmentalized from the rest of the RetroArch code.

Definitely! I did notice that the whole task was isolated in its own world in the source, but I wasn't sure that it could build as a lazy `a.out` file right away. If anyone has tried this, I'd be open to trying a ghetto `Makefile` to test this thoroughly.

>Haha, yes... I miss std::string, and C#'s String Class a lot when working on legacy-C codebases.

Maybe it's all the FNA experience, but any time I can replace "string" classes with plain ol' C operations is welcome to me >_<

**Comment by twinaphex** [comment]
I will try to take some stabs at making the database scanning a standalone optional program. You will need to be running at least a shell in order to use it though, it will be a commandline program only.

**Comment by flibitijibibo** [comment]
That sounds great! If this works out just ping me when the commits are in and I'll tear through this ASAP.

**Comment by i30817** [comment]
BTW, import of wii dual layer discs fails at a filesize check when searching for serial here:

https://github.com/libretro/RetroArch/blob/master/tasks/task_database.c#L226

at a guess it would also fail in the exact same check here (for crc):

https://github.com/libretro/RetroArch/blob/master/tasks/task_database.c#L378

**Comment by twinaphex** [comment]
OK, I successfully converted this into a standalone program @flibitijibibo -

go to samples/tasks/database, and run make.

Basic usage -

$ ./database_task.exe
Usage: database_task.exe <database dir> <core dir> <core info dir> <input dir> <playlist dir>

database dir - path to the RDB database directory
core dir         - path to the libretro core directory
core info dir  - path to the libretro core info file directory
input dir        - the directory that you want to scan
playlist dir     - the playlist directory - this will be used to save the newly generated playlist file to upon program completion

Here is a test invocation of the program -

$ ./database_task.exe "C:/Games/RetroArch/database/rdb" "C:/Games/RetroArch/cores" "C:/Games/RetroArch/info" "C:/Users/libre/Downloads/Games/Saturn" "C:/Games/RetroArch/playlists"

I turned verbose logging on so that is why it might be slower than usual. 

I hope that it will compile and work out of the box on both Windows and Linux/OSX. So far I tested it on Windows and it worked.

**Comment by bparker06** [comment]
@i30817 Can you try this patch? http://p.0bl.net/182559

**Comment by i30817** [comment]
Well, good news and bad news.

Good news is that it made the Last Story (one of the two 'dual layer' discs i have) scan. Bad news is that it didn't work for Metroid Prime Trilogy or the 'Another Code R' (this one isn't dual layer).

Seems like there are other bugs interfering. I'll add the memcmp fix back and see if that's it.
edit: nope.

**Comment by bparker06** [comment]
I should have mentioned that I edited the post earlier with an updated patch, maybe just double check that you're using the same one that's currently in the post. Otherwise, not sure what else is wrong at the moment.

**Comment by i30817** [comment]
Think i know what's happening here. It's a database problem if i'm not wrong.

Correct me if i'm wrong @RobLoach , but the wii rdb stores the serial number as plain hexadecimal digits right? Because if i use 'libretrodb_tool' to extract the wii rdb, i find that for metroid prime trilogy (USA) (my disc) we have

`"serial": "474D384A3031"`
which converted to ascii gives:
`"serial": "GM8J01"`

GM8J01 is the serial of *another* game Metroid Prime (Japan), while the serial extracted was R3ME01. There are even two serials according to the Dolphin database: https://wiki.dolphin-emu.org/index.php?title=Metroid_Prime:_Trilogy (though i suppose one could be the europe or australia release so no problem).

As for another Code R, that title simply doesn't have a serial. Apparently the fallback to checksum is disabled or never existed for wii games.

**Comment by i30817** [comment]
Your patch should still be applied @bparker06, you should open a PR. Also could you please add a commit for the memcmp fix too?

**Comment by flibitijibibo** [comment]
Stepped through and can confirm @bparker06's patch resolves this issue, the file was indeed too large!

**Comment by twinaphex** [comment]
I'm going to close this now if the current nightly indeed resolves this.

**Comment by RobLoach** [comment]
Do you still happen to have the patch from http://p.0bl.net/182560 ? Unsure if it was pushed up in a PR.

**Comment by i30817** [comment]
Filesize is int64_t in my link above now so i'd expect so. In fact, git blame from github interface makes it easy to see the commit: https://github.com/libretro/RetroArch/commit/1751f4a0afbc1c2ab21977413aac983a83279221

**Comment by RobLoach** [comment]
Oh great! Glad it got pushed. Thanks a lot, Twin, i3 + flibitijibibo.
