### ISSUE TITLE
'Device' gets saved in two places - Core overrides, and core remaps, causes problems

### ISSUE THREAD

**Issue by prataczak** [libretro/RetroArch#6642]
## Description

If I decide I want to use the 4 player adapter for Barkley Shut Up and Jam! 2 for Genesis, I can make a core remap file, and the following code appears in the remap file: input_libretro_device_p1 = "513"

The problem is, if I happen to be playing this game, and decide to save a core override, that same code is automatically added to the override file, affecting all games.

### Expected behavior

In my opinion this code should only be appearing in one place, and checked in one place by RetroArch. Code in core overrides should not be accidentally saved to remap files, and vice versa.

### Version/Commit

- RetroArch: 1.7.2

### Environment information

- OS: Windows

**Comment by fr500** [comment]
Actually remaps (which is a bad name for controller configs) is the only place were it should save.
It saves in overrides because overrides saves everything on settings_t and I'm not going to start making special cases.

So it's either removed from the main settings or it will keep saving in both places.
