### ISSUE TITLE
Retroarch Freezes before playing 1 or 2 minutes with a video filter activated on PS Vita.

### ISSUE THREAD

**Issue by Nube79** [libretro/RetroArch#6659]
The option Works great, but freezes retroarch over time.

## Description

Retroarch Freezes before playing 1 or 2 minutes with a video filter activated on PS Vita.

### Expected behavior

No pay limit, without freezes.

### Actual behavior

The system Freezes before short time playing when enable video filter.

### Steps to reproduce the bug

1. Load any rom on any core
2. Go to video, and select video filter, select Scale2X filter or other.
3. Play the game some minutes.

### Bisect Results

Over time playing with the filter enabled.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: ALL Playstiation Vita Versions

### Environment information

- OS: Playstation Vita 3.60 and 3.65
- Compiler: All official releases and All nightly published on the site.

Thank you guys for the best emulator ever.

**Comment by twinaphex** [comment]
@frangarcj Do you know whether this is the case?

**Comment by frangarcj** [comment]
I can look at it

**Comment by Nube79** [comment]
thank you guys, we are waiting more than one year for shader support on vita, the video filters are the only solution for post processing now.

**Comment by Nube79** [comment]
:_(

**Comment by Nube79** [comment]
:_(

**Comment by Nube79** [comment]
😭

**Comment by bparker06** [comment]
Please stop bumping the thread

**Comment by Nube79** [comment]
any news about shader support or filters fix?

**Comment by Nube79** [comment]
@frangarcj alguna novedad sobre el tema?

**Comment by noradninja** [comment]
I am able to run with filters on 1.7.6 (stable) on my PS Vita, however, on my PSTV, the issue remains, any filter enabled will lock RA after the game plays for between 20 seconds and 1 minute.

**Comment by Nube79** [comment]
@noradninja, the current stable version is 1.7.5, and the problem continues on 1.7.5 stable and the current nightly "2018-10-26_RetroArch.vpk"

Tested with: 0:/ux0:/data/retroarch/filters/video/Scale2x.filt

**Comment by twinaphex** [comment]
Honestly, just don't use the filters for now and wait maybe until shaders get implemented. It's not ideal to use them on something as slow as the PS Vita anyway, you need all the CPU horsepower you can get already.

**Comment by Nube79** [comment]
ok @twinaphex , the shader revolution is a perfect version for the retroarch PSVita :-D

**Comment by noradninja** [comment]
@twinaphex Do you have any idea how long we are talking for shader support? Don't want to bug anyone about it as I know its in the pipe.

**Comment by Nube79** [comment]
I love retroarch, I love rewind, I love the project, shader support for PSVita is the utopia, the perfect version for all the Retroarch user in PSVita platform.

**Comment by nezumisama** [comment]
I'm sorry for bumping, I just installed a nightly version this Monday (ff410f5) on my VITA and the issue still exists. Retroarch freezes on vita after about a minute when scale2x is enabled, even if no content was loaded (but the Os works, you can exit with the PS button and close the app).

I'm interested in tackling this in spare time, if it's worthwhile. I'd first check if it happens with all filters and if not, which. If it happens with darken (a useless dummy filter made for demonstration), then it's probably a bug in retroarch itself and not in any of the filters. And I'd find the the exact first problematic version, by first bisecting with nightly builds, then I'll setup the right build system and build and try with the remaining few commits. Then I'd report here and see what to do next.

However, I'm not sure if it's worthwhile. The filters should be slow, since not only they aren't ran on GPU, they are just regular C code, no assembly/intrinsic, and I'm not sure if they use multiprocessing (I think they can and do). But I've ran that scale2x one with a gameboy color game (gambatte core), and there were no slowdowns I think, so the console has enough horsepower for at least some filters with some cores. So, whether it's worthwhile or not depends on how close are we to supporting GPU (Cg) shaders on VITA (or if we're already there and I just didn't notice).

So @twinaphex, may I humbly ask, how close are we to getting GPU shaders support on VITA? Or is there just no chance?

**Comment by whgang99** [comment]
I'm sorry if I'm making a noobish post, but maybe would it be possible implement sort of sharp-bilinear effect by making retroarch to render to sub-native framebuffer? Like, drawing 256x224 SNES game on 790x448 framebuffer and then scaling framebuffer to 960x544 display will provide essentialy the same as normal2x filter.

I would really love to play retro games on vita with sharp-bilinear, but with shader support on vita seeming to be difficult, it will be awesome to see something like that!

**Comment by nezumisama** [comment]
@whgang99 Do you mean to do it in two steps, nearest-neighbor scaling to some resolution and then bilinear scaling that to the final one?

I've made a quick test with tools I have at hand. I downloaded an original-res screenshot from an SNES game at 256x224 and did some scaling: https://imgur.com/a/YVqQ9aq As you can see, the two-step method doesn't quite look like scale2x (or any of the pixel art scaling algorithms).

**Comment by whgang99** [comment]
@nezumisama Yes. If I'm aware that's how sharp bilinear works, isn't it?

**Comment by Nube79** [comment]
I think it's easier to fix the filters bug ...

**Comment by twinaphex** [comment]
Hi there @nezumisama,

any participation on the Vita port is very much welcomed and needed, we are lacking in developers on that front.

Hope that answers your question, and if you want to discuss further, you could meet us on Discord (I'm known as Autechre on there).

**Comment by nezumisama** [comment]
@whgang99 Well, not exactly. Normal2x simply doubles the pixels (i.e. for each input pixel, it churns out 4 identical ones). If you combine that with the bilinear option, you'll get what you've described.
@Nube79 Yeah, that's probably right.
@twinaphex Well, I didn't get an answer to my question, but thanks for the reply anyway! I'll be sure to check out the Discord.

**Comment by Nube79** [comment]
ScummVM has all the Filter Shaders working on PS Vita.
Is it possible to use the code of the shaders for retroarch?
https://github.com/rsn8887/scummvm/tree/vita_1.14

**Comment by Nube79** [comment]
Closed, the bug has been fixed by Fran.
Thanks.
