### ISSUE TITLE
[UDEV]Wrong keys during keyboard remapping

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#6696]
First and foremost consider this:
Only RetroArch bugs should be filed here. Not core bugs or game bugs
This is not a forum or a help section, this is strictly developer oriented
Description
Wrong keys are mapped when remapping keyboard keys using udev driver.

Expected behavior
[What you expected to happen]

Actual behavior
The actual keys should be remapped as whats being pressed

Steps to reproduce the bug
use udev driver (im assuming that current user is already a member of input group)
run retroarch
goto "input", select any of the "binds" menu
try to remap new keys from the keyboard.... most of the keys should display wrong when remapped( for example, assigned a spacebar to some key will will set K: d instead of K:space)
Bisect Results
[Try to bisect and tell us when this started happening]

Version/Commit
You can find this information under Information/System Information

RetroArch: 1.7.3
Environment information
OS: linux (arch)
Compiler: 7.x.x+

**Comment by orbea** [comment]
I'd like to see this fixed too. Its especially problematic when trying to use the keyboard + mouse in fps games.

**Comment by retro-wertz** [comment]
and to add, interestingly, games that used full keyboard (e.g. PX68K) does display the correct keys when pressed, so I am assuming that that udev reading keyinputs are correct, and this issue is on the remapping function...

**Comment by Raven-Singularity** [comment]
Not sure if this has anything to do with udev.  I'm on Windows 10, key inputs are often messed up.  Not sure how to assign any hotkeys in 2022.  I press F11 repeatedly and nothing is input at all.  I press F and it shows Scroll Lock.  How is anyone supposed to use this emulator?

Why is this marked as "bug: minor", not being able to assign hotkeys is extremely major.  Or is it supposedly just the labels that are wrong, but the hotkeys will still work normally?

Because that's not how it is for me.  When I choose "F" for fullscreen (because "F11" can't be assigned), it says "Scroll Lock" instead of "F".  So I go to my game and hit "F" but it doesn't do anything.  I hit "Scroll Lock" and it goes into fullscreen.

This may be different than the udev bug, or the same.  But this is definitely a major bug, it prevents even basic use of RetroArch.

**Comment by zoltanvb** [comment]
Udev input driver should work correctly nowadays, as I checked with the keyboard tester (#16390), however if there is a problem with Windows+SDL combination, this better remain open.

**Comment by sonninnos** [comment]
Yes indeed those Windows drivers have been fixed ages ago, so closing time.
