### ISSUE TITLE
[Bounty] Update Dolphin core and port it to ARM64

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#6841]
The [current libretro core](https://github.com/libretro/dolphin) doesn't compile on ARM64 targets as it is missing some make rules. 

However, the core is heavily outdated compared to the standalone version (~4500 commits, one major version and two years of improvements behind). It has to be rewritten from scratch.

The idea would be to :
1. Update the core so that it's on par with the latest ~~(stable ?)~~ version of Dolphin - don't port from a release, just pick the master branch
    * How is the configuration handled ? The original emulator has `~/.config/dolphin-emu/Dolphin.ini` - this config file is required on some platforms
2. Adapt the makefile so that it builds and works on ARM64 targets (obviously with JIT)

Obviously, upstreaming is preferable if possible. See how the current core is made to see how both the standalone emulator and its libretro core can cohabitate within the same codebase.

Here are some guidelines from degasus, a Dolphin developer :

- Try to minimize the patchset for libretro support and keep it rebase-able. 
- Upstream dolphin internal changes. Most of them are likely cleanups and optional feature disabling.
- Don't mix libretro and dolphin-internal patches. Never.

Discussion about the port and this bounty on Dolphin forums : https://forums.dolphin-emu.org/Thread-bounty-for-libretro-dolphin

**Comment by i30817** [comment]
The support for WiiU (which i imagine is most of the motivation for this usecase?) is being worked in [collaboration with upstream here.](https://github.com/hrydgard/ppsspp/pull/11001)

**Comment by mstreurman** [comment]
As was posted on the Dolphin dev-forums, one has to keep in mind that the current JITARM64 will be tremendously slow on the Switch, since the current JIT is barely able to run any game at full speed on the much faster Shield TV... One probably has to rewrite the whole core for it to be even remotely viable.

**Comment by fr500** [comment]
Actually CPU is running at full clocks on switch linux.

**Comment by natinusala** [comment]
It reportedly runs at steady 30 FPS on Arch Linux with GNOME.

**Comment by mstreurman** [comment]
@fr500 yet in Linux only runs at around 60% speed without any game breaking hacks/tweaks/settings and even if it runs as fast as the Shield TV you will still have a lot of issues getting games to run fast enough without those hacks. Since the Shield TV doesn't even have enough power to run most games consistently fast enough. Even the reportedly faster XBONEX and PS4pro isn't fast enough and they would be able to run the "optimized" x86_64 version of Dolphin...

It but yeah, I would love it to see people work on the different JIT's for Dolphin, maybe there still is some breakthrough to be had that suddenly makes it a lot easier on the hardware. As soon as my wages come in next month I'll back.

**Comment by natinusala** [comment]
Even if the performance is mediocre on the Switch for now, porting the core still have some advantages :
* It will be ready for updating when the necessary optimizations come
* It will most certainly be used on desktop, either via Lakka or standalone RetroArch - the Switch is only one hardware among others
* It is beneficial for the libretro ecosystem to have another core for a "big" emulator, even more if the support is upstreamed

While _my_ motivation behind this bounty was to run it on the Switch eventually, I'm not alone and I'm sure a lot of people could benefit from this port too.

**Comment by iOS4all** [comment]
@natinusala you’re absolutely right.
We really hope to get dolphin core running on switch via Lakka.

**Comment by LeSaumonMasque** [comment]
Just added my money to the bounty. I'm happy to see I'm not alone to see dolphin become more and more functionnal. I don't own a Switch, I'm using it on PC.

**Comment by tiliarou** [comment]
Added a few bucks to the bounty as well ! Very excited to see this being worked on in the near future hopefully !

**Comment by ShadyGame** [comment]
so there is someone already working on this? 

"aliaspider has begun working on a solution to "[Bounty] Update Dolphin core and port it to ARM64".

aliaspider provided the following URL to track his or her progress: https://github.com/aliaspider/dolphin

The bounty can be claimed once the issue gets closed on the original issue tracker. When a bounty claim is submitted, all Backers will be notified.


Thanks,
The Bountysource Team"

**Comment by aliaspider** [comment]
the port has been completed and merged to https://github.com/libretro/dolphin. prebuilt binaries for linux/windows/osx/android can be downloaded from the buildbot directly or through the online updater.

check https://lakka-switch.github.io/documentation/ for instructions on how to run lakka on the switch. it might take some time until a precompiled core is added to the official package for lakka-switch so you would have to compile it yourself in the meantime.

**Comment by flibitijibibo** [comment]
Thanks for doing this! I'm running RetroArch via Flatpak and have a couple notes:

1. The Linux build depends on sndio, possibly because the [cubeb library enables it](https://github.com/kinetiknz/cubeb/blob/master/CMakeLists.txt#L209)
2. The Linux build also depends on ffmpeg, which I think is just used for AVI dumps.

If those two pieces are disabled I _think_ it should boot and run with the Flatpak version. I'd be interested in seeing the real Wiimote and Wii U GC adapter support as well, but this is still really REALLY nice to see and I hope it gets upstreamed soon.

**Comment by aliaspider** [comment]
both sndio an ffmpeg are only used in the build if they are actually found when running cmake the first time. if your cross-compile environment differs from your actual runtime environments then that might be an issue yeah.
both are unused in the core of course, they weren't disable because it would just add unnecessary differences to upstream code.

**Comment by fr500** [comment]
Well I guess the buildbot has ffmpeg and sndio in the path...
Linux portable cores are a bad idea for a number of reasons, this is one :)

**Comment by aliaspider** [comment]
@flibitijibibo I ended up disabling those two dependencies afterall :
https://github.com/libretro/dolphin/pull/30
hopefully that should increase the compatibility of the Linux portable build a bit.

**Comment by flibitijibibo** [comment]
Excellent, will try this again once it pops up in the nightlies.

**Comment by flibitijibibo** [comment]
Gave it another try and the good news is on normal human distributions this new core works fine, and fresh Linux installs should be able to run this with no problems. Thanks to @aliaspider for the quick fix!

One thing I forgot about is that Flatpak is, at the moment, deliberately not supporting libudev (?????) so the libudev/libusb dependencies still won't work in their sandbox. You can fuss with those two dependencies in the sandbox if you _really_ want to, but really they just need to fix this in Flatpak and probably the freedesktop runtime as well. (In SDL we can't even do joystick hotplugging right now because of this, it's a real fun time)

**Comment by aliaspider** [comment]
ping @tjg1 @bionik

**Comment by tjg1** [comment]
Done

**Comment by bionik** [comment]
Done too

**Comment by prataczak** [comment]
Is there any chance of getting multi disc support added? The standalone version has it. I'd be willing to contribute a little extra to see it implemented, and I know someone else who would too.

**Comment by LeSaumonMasque** [comment]
Tales of Symphonia :)

**Comment by prataczak** [comment]
Respectfully, if I'm going to go to all that trouble, I might as well be using the standalone all along. :)

**Comment by natinusala** [comment]
@aliaspider any insight on multi disks ?
