### ISSUE TITLE
[Bounty] Create a pcsx2 core

### ISSUE THREAD

**Issue by weirdbeardgame** [libretro/RetroArch#6867]
What would be required?
rewrite PCSX2's plugin system to fit into Retroarch's core system
adjust config files and pcsx2 settings to work with Retroarch 
adjust GUI config areas in pcsx2 to fit with Retroarch's quick menu

**Comment by i30817** [comment]
I think it's far more likely that dobiestation or some other emulator gets a port than pcsx2. It would be a incredible burden to port and redesign the plugin system to retroarch and you wouldn't have the benefit of getting upstream commits. It would be the hardest of hard forks.

Granted dobiestation is a toy emulator, being a one man show, but i still consider it more likely.

**Comment by kenshen112** [comment]
Actually dobiestation has several contributers at this point, and whilst yes it would be a chore and a half it would be our best bet for now to get a compatible working ps2 core in RetroArch aside from play! or in the future DobieStation

**Comment by anothername99** [comment]
Perhaps look into Orbum:
https://github.com/marco9999/orbum

It's a rewrite of PCSX2. It should be more portable than mainline PCSX2.

**Comment by orbea** [comment]
I think step 1 is to fix the 64-bit build upstream and make sure `-fPIC` is entirely supported.

**Comment by natehaxx** [comment]
> I think step 1 is to fix the 64-bit build upstream and make sure `-fPIC` is entirely supported.

its already fixed on the newest Play Forks ... Emulation runs now on the Nintendo Switch slow but it runs

**Comment by Zer0xFF** [comment]
I am considering looking into this bounty, however for `Play!`.

however, I want to confirm the validity of this as the paragraph for `Play!` isn't encouraging.

```
Note: Play! though not preferred would be an acceptable alt if someone wants to do that,
```

**Comment by twinaphex** [comment]
As for this bounty - let's deliver a couple of conditionalities:

* In order for the bounty to be obtained, full sourcecode must be provided, and the repo has to be delivered. It has to be publicly obtainable and its right cannot be CLA'ed to anybody in particular.
* It must be GPL just like the original project in PCSX2's case
* No other legally binding agreements beyond just adhering to the emulator's GPL license

Beyond that, everybody can fulfill the bounty, yes.

**Comment by Zer0xFF** [comment]
@twinaphex thanks for the reply, but it didn't really address my question, the issue was original opened for `PCSX2`, but then `Play!` was added as an acceptable alternative, though the wording for that is somewhat discouraging, so I want to confirm if a core for `Play!` will indeed be accepted?

as for your comments.

- the code will be pushed out
  - and no CLA is in place at the moment (while I don't foresee a CLA in the future, (1) its does not apply retroactive, (2) so my work regarding the core remains true, (3) should Jean (emu owner) does purse it, its his choice, but I don't see it having a bearing on this bounty as per point (1) and taking that into account, this could apply to ALL current cores, so not really my issue in the future) ()
-  in the case of `Play!` license is MIT, and since there is no CLA in place, relicensing isn't a choice I even have (nor will I be able to obtain since I'm not the project owner XD)

**Comment by twinaphex** [comment]
Hi @Zer0xFF, sorry for maybe confusing you. This was not related to Play!, more to somebody else who offered to fulfill this PCSX2 core bounty.

I'd also like to see a Play! core bounty, but ultimately the bounty backers decide. A vote could be done. Personally I'd still think it's best that Play! gets its own separate bounty, since I think we'd like to see both, but it's of course unreasonable to have that be part of the same bounty.

**Comment by Zer0xFF** [comment]
Thanks for the reply.

Well I presume, they only way backers can decide is after the bounty is fulfilled?
in such case, I'm afraid, I will not be taking this on, since my main reason for doing this is the financial compensation, if this can be done ahead of time that'd be great.

**Comment by twinaphex** [comment]
I believe it might be best if we built up a separate core bounty for Play! and we bring that to the level of $300 and then make that grow from there. To reiterate, I'd like to see both get a libretro core, but I understand that can't be done with one single bounty.

**Comment by Zer0xFF** [comment]
> I believe it might be best if we built up a separate core bounty for Play!

I agree, and I've foreseen the inevitable confusion in this case, which is why I decided to ask 1st.

**Comment by twinaphex** [comment]
Hi there @Zer0xFF,

please contact me at libretro@gmail.com. I might have a proposal if you're interested.

**Comment by twinaphex** [comment]
I reached an agreement with @Zer0xFF to do a Play libretro core. This will be done outside this bounty.

So this bounty can instead be strictly dedicated to PCSX2 now.

**Comment by Specced** [comment]
That´s good news! Happy coding!

**Comment by c4pt000** [comment]
you realize there is a dolphin pcsx2 wrapper for retroarch to load pcsx2 titles ?

**Comment by c4pt000** [comment]
@op https://github.com/coldscientist/libretro-pcsx2-launcher

**Comment by c4pt000** [comment]
I was just editing this about a week ago for better integration into retroarch

**Comment by c4pt000** [comment]
https://github.com/c4pt000/libretro-pcsx2-launcher


^ whats it worth to you? $650 ?

**Comment by twinaphex** [comment]
Umm, it needs to be a real libretro core. A launcher core really is not going to do and wont be accepted.

**Comment by ddg00101** [comment]
This issue seems to have gone stale. I would love to be able to play ps2 games on my switch, and pcsx2 seems like the best bet for this since it has dealt with more of the compatibility issues already. Play! is interesting, but needs a great deal more work still for most games. I'd be more than willing to kick in money personally. Not sure how to officially do this though? I'd be fine with $500-$1k depending on what the true complexity and time would be. I'm not sure how much is already 'in the pot' so to speak. Hell, keeping a monthly maintainer to merge code in from upstream if it can't be easily merged regularly would be fine with me on top of that.

**Comment by DukeSkinny** [comment]
> 
> 
> I'd be more than willing to kick in money personally. Not sure how to officially do this though?

[Here's](https://www.bountysource.com/issues/59336467-bounty-create-a-pcsx2-core) the issue on BountySource, where you can contribute if you so wish. A bit late, but hopefully you'll see this and are still interested.

**Comment by GovanifY** [comment]
I figured I might as well update this issue, even though there's a long road ahead.
I began merging pcsx2 plugins into its core, with the goal of merging all of them ASAP.
The idea is after that to eventually have a clean core/gui separation, which would allow "easily" a retroarch port by this point; the scope out of retroarch is to eventually drop the WxWidgets GUI and get a new, cleaner one, probably Qt based.

With that said there is a high probability that only x86_64 builds will get a JIT on retroarch, since the 32 bit JIT basically makes PIE impossible, which I assume is a requirement for retroarch libraries. Of course pcsx2 new 64bit JIT isn't even finished yet.

No ETA for this as it requires rewriting most of pcsx2 codebase in major ways but I've already merged the CDVD and FW plugins, so 2/7.

**Comment by hizzlekizzle** [comment]
@GovanifY that's really exciting news! Thanks for the update :)

**Comment by twinaphex** [comment]
Great to hear there's an interest in this. For now if it helps you get to a POC stage faster, you can focus on x86_64 for now. Hopefully the 64bit JIT is not too bad at this point.

**Comment by capsbold** [comment]
Haha, it's hilarious!

Half a year ago I've spent a week working on a clean-slate rewrite of the jit, targeting amd64 and aarch64, and have had to scrap the work due to _some nutcase_ embarking on a months-long crusade of hacking the existing jit to do amd64. It's not that I hated being one-upped, it's just that for the entire summer the codebase was as volatile as Nitroglycerin, precluding any meaningful work on my part. Now pcsx2 has 64-bit EE and IOP recs that are roughly twice slower than that they have any right to be.

Now it's more of the same: the same week I revisited the issue _some other nutcase_ has just decided that it'd be nice to open the road for _even more nutcases_ to break the plugins encapsulation and smear them all over the core, as if it isn't a fucking nightmare already.

Well, I've lost any shred of hope for those guys, so I'm starting my own fork. Because that's how and why forks are made - to have a comfortable codebase that doesn't turn to a fucking warzone overnight.

**Comment by tellowkrinkle** [comment]
> Half a year ago I've spent a week working on a clean-slate rewrite of the jit, targeting amd64 and aarch64, and have had to scrap the work due to some nutcase embarking on a months-long crusade of hacking the existing jit to do amd64. It's not that I hated being one-upped, it's just that for the entire summer the codebase was as volatile as Nitroglycerin, precluding any meaningful work on my part. Now pcsx2 has 64-bit EE and IOP recs that are roughly twice slower than that they have any right to be.

If it's a clean slate rewrite, why would it be affected by changes to the current one?  And while there was all sorts of changes happening on the x64 work branch, the final merge was fairly clean and changed little.  That was the plan from the beginning, so if you were worried about it, you could have asked on the PR thread and we would have said so.  Same goes for the plugin to core merge, if you're working on a JIT you shouldn't have to touch any of the things touched by those merges, and can just ignore them.

In general, I would recommend that if you plan to make big changes to anything, that you make a fork from the start.  Don't bother trying to stay up to date with master until you're ready to PR.

**Comment by GovanifY** [comment]
> Now it's more of the same: the same week I revisited the issue, spending some 16 hours to untangle the core's dependency graph, _some other nutcase_ has just decided that it'd be nice to open the road for _even more nutcases_ to break the plugins encapsulation and smear them all over the core, as if it isn't a fucking nightmare already.

Thank you for the kind words dear stranger, now if you may allow me to speak this whole "plugins smeared all over the core" is done for a reason: splitting core, old gui, new gui etc and make the application much easier to port and straightforward overall. Unless you're blind the dependency graph is basically lessened as plugins callbacks existed in the main codebase, and you can follow them into their respective folders.
As tellow so kindly pointed out, if you want to work on something just ping us, exchange ideas, possibly open an issue or a draft PR to show people this is a thing. That's a concept that might be unknown to you but is actually crucial to FOSS development. It is called "collaboration". That is if any of what you said is true, which I am going to highly doubt seeing the contents of your GitHub account and how recently it was created.

Excuse me for the condescending tone, but I've had enough about people smearing over other's work by principle. ANd I'm not talking about just mine.

**Comment by twinaphex** [comment]
Hi there @GovanifY ,

no problem with it being a hard fork. As long as it is a PCSX2 derivative running as a libretro core and working well I don't see an issue. You are in the driver's seat here as far as we're concerned.

**Comment by twinaphex** [comment]
My bad, I read that previous exchange between you two guys wrong.

**Comment by GovanifY** [comment]
> @GovanifY for this libretro core you're preparing, is both Linux and Windows support planned?

Definitely. I am reiterating that this will take some time to go there and I'm prioritizing work on the core of pcsx2 over retroarch for now. I don't want to promise anything, so we'll see once we get there, but there's no reason for me not to support at least Linux and Windows

**Comment by aliaspider** [comment]
https://github.com/aliaspider/pcsx2
this is still a very early WIP, but since it kinda runs on linux already, I thought I would share it. windows isn't supported yet.
to try it out you need to first build the standalone version
```mkdir build
cd build
cmake ..
make install```
after that copy the `bin` directory in the root folder to your retroarch system dir `path/to/systemdir/pcsx2/`.
next build the core itself
```mkdir build-libretro
cd build-libretro
cmake .. -DLIBRETRO=ON
make```

as I said, this is still a very early work in progress, so expect a lot of bugs/crashes etc.
the code itself contains a bunch of hacks at the moment to get things going and requires a lot of cleanup until it is ready.

@GovanifY sorry I didn't realize that you were also working on this until I was done xD

**Comment by GovanifY** [comment]
@aliaspider not a big deal, although pcsx2 codebase is currently undergoing huge changes, I'd wager it'd be safe to wait until we finish at least merging the plugins and splitting the core/gui base fully until you continue to work on it, if you so wish, unless you want another hard fork with development efforts split, which I'd rather avoid as a PCSX2 contributor.

**Comment by aliaspider** [comment]
most of the libretro specific code can be easily rebased on top of any refactors that are made upstream so that shouldn't be an issue at all, and besides the hard part is already done anyway.

it is cool to hear though that you are planning to split the core/gui, since that would make a shallow fork finally a possibility. I don't like messing with the core code much so my plan right now is to minimize that as much as possible, most of it can't be avoided though due to tightly it interacts with wxwidgets.

hopefully at some point I can get something that integrates nicely with the main codebase.

**Comment by GovanifY** [comment]
Well that was the plan before you came in with your fork to be fair, it would have simply taken more time since, surprisingly, it wasn't on our immediate priority list :p

My idea was to integrate it into the master branch directly to avoid a fork, which is still going to happen probably, hence why I told you to probably wait. I can definitely tell you most of your work, notably on the FakeThread, won't be rebased easily at all. A mostly whole project code refactor will happen during the core/gui split, and would probably require you reprogramming from scratch entire parts of your fork.

I'm not after the bounty myself so I do not care about who gets to do what, I'd just rather wait if possible for that single reason tbh, but I'm not going to actively try to oppose your fork in any way, it's just bad timing to be fair.

**Comment by aliaspider** [comment]
the code is in no way final. and I still don't see why it is a bad timing or hard to rebase but ok. 
besides I'm the one who will do the rebase anyway so :)

**Comment by twinaphex** [comment]
Just to be clear, I am sorry if my previous comments were taken the wrong way and if it sowed confusion.

But I absolutely did contact aliaspider before and asked if he could do the PCSX2 core since it's been such a much-requested core and it's been years of people requesting for something to finally run in RetroArch.

I intend to fully meet all of the obligations and commitments I promised to @aliaspider as part of this, and I thank him for getting such a WIP up and running in such short notice.

I'm sorry if this means that others feel like it's getting ahead of their own rebasing efforts but ultimately what we care about is having a working libretro core here, and we kinda already accepted that this was going to be a hard fork at this point anyway. I've known @aliaspider since 2015 and I have 100% trust in his abilities to see this core successfully through.

**Comment by aliaspider** [comment]
some updates:
added windows support and implemented most important features. there are still a few issues left to deal with and but the core should be relatively useable by now.

compilation should also be a bit simpler now. (no need to compile standalone first)
```
mkdir build-libretro
cd build-libretro
cmake .. -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Release
make
```
for windows you need to run `--build . -- -p:Configuration=Release` instead of `make` for the last step.

you can get a precompiled windows binary from here:
https://github.com/aliaspider/pcsx2/releases/download/v0.1-libretro/pcsx2_libretro.7z
just copy the `system` folder and core to the correct locations, and copy your ps2 bios to `system/pcsx2/bios`

**Comment by twinaphex** [comment]
Thanks for the update and thanks for continuing to work on it. The additional bonus promised on top of the bounty will be upheld on my end.

**Comment by twinaphex** [comment]
Thanks for the update.

**Comment by Ether009** [comment]
@aliaspider I cannot get those precompiled bins to work. Stable does not even identify that this is a core. Nightly does, but x86 version when trying to load the core outputs
`[ERROR] Failed to open libretro core: "D:\Userdir\Downloads\RetroArch (1)\cores\pcsx2_libretro.dll"
[ERROR] Error(s): %1 is not a valid Win32 application.`
while if I use the x86_64 nightly, I instead get
`[ERROR] Failed to open libretro core: "D:\Userdir\Downloads\RetroArch (2)\cores\pcsx2_libretro.dll"
[ERROR] Error(s): The specified module could not be found.`

So it seems that x86_64 nightly would be the required retroarch version, but it does seem to still be missing some dependency although it makes no mention of what that would be. It could be the bios, but you make no mention of which bioses would work, or what to name it. Could that be the module it's missing? Which should I put there, and named what? Or is it some mingw or cygwin library it needs or something?

Awesome work btw. Cant wait to get this working right. Last stand alone emu I use to finally be scrapped :)

**Comment by Joshndroid** [comment]
> 
> 
> some updates:
> added windows support and implemented the most important features. there are still a few issues left to deal with and but the core should be relatively useable by now.
> 
> compilation should also be a bit simpler. (no need to compile standalone first)
> 
> ```
> mkdir build-libretro
> cd build-libretro
> cmake .. -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Release
> make
> ```
> 
> for windows you need to run `cmake --build . -- -p:Configuration=Release` instead of `make` for the last step.
> 
> you can get a precompiled windows binary from here:
> https://github.com/aliaspider/pcsx2/releases/download/v0.1-libretro/pcsx2_libretro.7z
> just copy the `system` folder and core to the correct locations, and copy your ps2 bios to `system/pcsx2/bios`

thank you for your  awesome work.
I tried this in retroarch playtest (steam) and just get a black screen. The sound works so i know it loads.
used a bios listed in here - same issue https://docs.libretro.com/library/pcsx2/
made sure i had visual c++ 2019 as within here - sa,e issue https://github.com/libretro/pcsx2

Am i doing something wrong?

**Comment by countfistula** [comment]
I did some searching around forums and this thread but didn't find anything, so I apologize if this has been asked already.  I'm brand new to Github and the whole concept of "binaries", "source code" etc. are an alien language to me.  I intend to learn a lot and I'm currently in school going for a degree in IT (I just started).  

With all that said, can anyone tell me what files from this project I need to download in order to attempt using it with RetroArch on my Raspberry Pi 4?  I've been tinkering with it and having a lot of fun learning Linux command line stuff, but the second I look at this big list of folders and files I feel completely overwhelmed.

**Comment by tellowkrinkle** [comment]
> With all that said, can anyone tell me what files from this project I need to download in order to attempt using it with RetroArch on my Raspberry Pi 4?

PCSX2 currently requires an x86 (Intel or AMD) processor, which the RPi4 doesn't have.  Don't expect this to change anytime soon.

**Comment by Jessomadic** [comment]
@tellowkrinkle How about a UWP file. Seeing as the Xbox One line of consoles use a CPU based off of AMD Athlon

**Comment by colejd** [comment]
@GovanifY do you have a link to a PR or something to track the rewrite / work separating the GUI from the core? How close would you say you are to clearing @aliaspider to continue without needing to do a huge rebase?

**Comment by GovanifY** [comment]
@colejd The work will begin once the last plugin (GSdx) has been merged, you can track the progress of this one here: https://github.com/PCSX2/pcsx2/discussions/4100

I never forbid aliaspider to continue, he can do so if he so wish, but there's already a non trivial effort required to rebase the core on the master branch because of how much changes have happened.

**Comment by RyanBram** [comment]
Finally PCSX2 is pluginless 🎉
https://github.com/PCSX2/pcsx2/pull/4436

Thank you very much for PCSX2 Dev Team.

**Comment by aliaspider** [comment]
so, finally got around to finishing this up. resolved most issues with the previous version and rebased on latest upstream.
https://github.com/aliaspider/pcsx2

this is a precompiled windows binary if someone wants to test it:
https://github.com/aliaspider/pcsx2/releases/download/v0.2-libretro/pcsx2.7z

make sure to copy the `resources` directory from the source `bin` folder to `<retroarch system folder>/pcsx2`

**Comment by gouchi** [comment]
I tested it quickly on Linux and it is working.

Thank you !

**Comment by aliaspider** [comment]
solved the above mentioned `.dll` problem and some minor issues :

**Comment by i30817** [comment]
It can't seem to find tls here (ubuntu 22.04) which then crashes when starting any game. I do have tls libraries installed 

```
CMake Warning at 3rdparty/libzip/libzip/CMakeLists.txt:226 (message):
  -- neither Common Crypto, GnuTLS, mbed TLS, OpenSSL, nor Windows
  Cryptography found; AES support disabled
```

Specifically, i tried to install `sudo apt install libssl-dev` and `sudo apt install libmbedtls-dev` and `sudo apt install libgnutls28-dev`

The crash is:
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
__tls_get_addr () at ../sysdeps/x86_64/tls_get_addr.S:33
33	../sysdeps/x86_64/tls_get_addr.S: No such file or directory.
```

**Comment by i30817** [comment]
On it builds with those options here all right. It just crashes when run with a game. Might be ASRL (address space randomization) causing problems. All i know is that the thread local storage freaks out.

**Comment by i30817** [comment]
nah i did all of that ... except the explicit -j multiprocessor building.

Anyway debug says a very different story:

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffec24dbe0 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
(gdb) bt
#0  0x00007fffec24dbe0 in  () at /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#1  0x00007ffff78aa831 in eglBindAPI () at /lib/x86_64-linux-gnu/libEGL.so.1
#2  0x0000555555876d4d in egl_bind_api ()
#3  0x00005555556976a0 in video_context_driver_init_first ()
#4  0x000055555589cc9d in gl3_init ()
#5  0x00005555556983fe in video_driver_init_internal ()
#6  0x00005555555ecaac in drivers_init ()
```
So i tried to change the main (ozone) driver from vulkan to gl. And it changed again.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
get_cached_stack (memp=<synthetic pointer>, sizep=<synthetic pointer>) at ./nptl-stack.h:34
34	./nptl-stack.h: No such file or directory.
(gdb) bt
#0  get_cached_stack (memp=<synthetic pointer>, sizep=<synthetic pointer>) at ./nptl-stack.h:34
#1  allocate_stack (stacksize=<synthetic pointer>, stack=<synthetic pointer>, pdp=<synthetic pointer>, attr=0x7ffffffee860) at ./nptl/allocatestack.c:364
#2  __pthread_create_2_1 (newthread=0x7ffffffee9a8, attr=0x0, start_routine=0x7fff8ff63054 <Threading::Thread::ThreadProc(void*)>, arg=0x555558079480) at ./nptl/pthread_create.c:647
#3  0x00007fff8ff63281 in Threading::Thread::Start(std::function<void ()>) (this=0x7fff91d67158 <vu1Thread+16777432>, func=...) at /home/i3/Downloads/pcsx2-git/common/Linux/LnxThreads.cpp:275
#4  0x00007fff8f9a2477 in VU_Thread::Open() (this=0x7fff90d67080 <vu1Thread>) at /home/i3/Downloads/pcsx2-git/pcsx2/MTVU.cpp:111
#5  0x00007fff8fafb6c5 in recMicroVU1::Reserve() (this=0x7fff921a2010 <CpuMicroVU1>) at /home/i3/Downloads/pcsx2-git/pcsx2/x86/microVU.cpp:377
#6  0x00007fff8f9e2594 in SysCpuProviderPack::SysCpuProviderPack() (this=0x555559a46740) at /home/i3/Downloads/pcsx2-git/pcsx2/System.cpp:277
#7  0x00007fff8fd6dd84 in std::make_unique<SysCpuProviderPack>() () at /usr/include/c++/11/bits/unique_ptr.h:962
#8  0x00007fff8fd60add in VMManager::Internal::InitializeMemory() () at /home/i3/Downloads/pcsx2-git/pcsx2/VMManager.cpp:308
#9  0x00007fff8f977465 in retro_load_game(retro_game_info const*) (game=0x5555564c4e30) at /home/i3/Downloads/pcsx2-git/libretro/main.cpp:588
[more pointless stuff....]
```
wew

**Comment by i30817** [comment]
Yours will not open, your required libraries are probably named differently from ubuntu, 'libSoundTouch.so.2' while mine list of those in the system is 'libSoundTouch.so        libSoundTouch.so.1      libSoundTouch.so.1.0.0'. I tried to hack around it with ln -s but it just progressed to the next. I'm not willing to hack it up.

For the same reason, me posting mine won't help you probably.

**Comment by aliaspider** [comment]
try posting the whole log from retroarch, it might help figuring out the problem.
and yeah you should use glcore for linux.

**Comment by i30817** [comment]
64 bits. I guess it's not _all_ static yet.

Anyway.... PLOT TWIST. Turns out that loading from the command line actually loads the game.

But the emulator doesn't support cue, so i had to load the bin ugh.

**Comment by i30817** [comment]
BTW, i noticed this when loading growlanser II, when you load a patch you're missing a \n (or when you read the information it's not reading the \n or it's \r instead or another problem). It shows this:
`[libretro INFO] Author: kozarovv[libretro INFO] comment: IPU freeze fix[libretro INFO] (GameDB) Patches Loaded: 2[GameDB] Searching for 'slus-20758' in GameDB`

A single line instead of the two it obviously should be.

**Comment by i30817** [comment]
From context and the various crashes what i 'think' (as a total amateur) is happening is that pcsx2 wants to be on a specific memory location at the start, or alignment, and retroarch being already using it prevents that somehow.

**Comment by aliaspider** [comment]
pushed an update that will hopefully fix the crash when loading content from the menu on linux.

**Comment by aliaspider** [comment]
are you bypassing segfaults in gdb with this command ?
`handle  SIGSEGV pass nostop noprint`
you need to do that when debugging code that uses a dynamic recompiler.

**Comment by LibretroAdmin** [comment]
Was asked to close this issue so @aliaspider can claim the bounty, so I did. Vulkan and D3D12 renderer being hooked up can come later.

**Comment by i30817** [comment]
It's working. Except as i mentioned, upstream not allowing a cue/bin (MODE2/2352) although i suppose it could be MODE2/2048 (cd in a cue) or MODE1/2048 (dvd in a cue)).

This is just because redump has those files as cue/bin instead of iso.

**Comment by i30817** [comment]
This is just for games that were originally released as cds not dvds. The ps2 driver apparently could read both.

**Comment by i30817** [comment]
http://redump.org/disc/55127/

This is one of the games redump has for the playstation that uses cue because it originally used the cd format. There are other examples, like the remakes of phantasy star in the SEGA Ages (or whatever it's called) remake series of megadrive games.

**Comment by i30817** [comment]
Another detail, the ps2 memory cards are being created in the core directory, not the saves directory. (Mcd001.ps2 and Mcd002.ps2)

**Comment by i30817** [comment]
For some reason games like `Primal (USA)` or `Blood Will Tell - Tezuma's Osamu's Dororo (USA)` crash when going in game here, but they kind of already did in the previous version so i'm unsure if this isn't just me doing something wrong or trying games that never worked.

**Comment by i30817** [comment]
Yup... i expected too much, the libretro/pcsx2 repository doesn't have this port yet, it's still using the broken old one.

BTW, found another thing missing here, m3u support.

**Comment by i30817** [comment]
Woah. This core has savestates. I thought it didn't. In fact, the copy past core info file i have for the core says it doesn't have savestate support but it still works. Weird but good, because otherwise i wouldn't have noticed.
