### ISSUE TITLE
(Menu) Failed to open assets/xmb/monochrome/font.tff

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#7229]
When you don't have retroarch-assets installed, RetroArch will still attempt to load `assets/xmb/monochrome/font.ttf`. When it fails to load it, it gives this warning....

```
➜  ~ retroarch
Failed to open /home/rob/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Failed to open /home/rob/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
```

This is likely my fault, but it would be good to check if the file exists before loading it.

## To Test

```
sudo apt-get remove retroarch-assets -y
mv ~/.config/retroarch ~/.config/retroarch-backup
retroarch
```

**Comment by bparker06** [comment]
Wouldn't it be better to have an error message than none at all?

**Comment by RobLoach** [comment]
Agreed. Rather than an error, perhaps a warning saying that it'll fallback to the system font.

**Comment by Efimero** [comment]
I have the same issue, but I get a crash when the menu shows up
however, I do have the files in the place it's supposed to look for them
since retroarch broke after some updates and clamed (rightfully) that a file under /app didn't exist, I tried using symlinks to fix the paths, but now it still crashes saying the file doesn't exist, while the path it gives does, indeed, exist and is readable

**Comment by orbea** [comment]
I am not sure this is a bug, but its related to https://github.com/libretro/retroarch-assets/issues/266.
