### ISSUE TITLE
(RGUI) Add option to select audio device

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#724]
Retroarch already has an option to select what device you want to output audio to ("audio_device"), but you can't change it with RGUI, only by file editing. This option would be useful for people that use a TV as a second monitor.

**Comment by qvazzler** [comment]
Sorry but I want to pitch in here.. As a person who needs to constantly switch between speakers and headphones because there's more than 1 person in the household with varied needs, I'm finding the lack of audio output selection really.. weird. Looking at Kodi as an example, audio output is pretty standard. You'd simply expect it to be there. @Themaister
