### ISSUE TITLE
[Feature]Mobile rumble

### ISSUE THREAD

**Issue by DieKatzchen** [libretro/RetroArch#7272]
It's been mentioned in other feature requests, but I wasn't able to find one for this specifically. All mobile phones can vibrate, so some way to use that to simulate the rumble feature when using onscreen controls or controllers without rumble would be cool.

**Comment by DieKatzchen** [comment]
Because I believe in doing the legwork, https://developer.android.com/reference/android/os/Vibrator

Probably want to use the createOneShot method of https://developer.android.com/reference/android/os/VibrationEffect just chaining it.

**Comment by bparker06** [comment]
Thanks for that, however, VibrationEffect only exists since API Level 26 (Android 8.0), and the normal RA build only even targets level 24... so an older method would need to be used.

The trouble with that is that the old methods become deprecated at level 26, so when RA fully targets that level, it will need to be changed to be able to support both newer and older devices appropriately (you can't just target 26 and then use functions that require 26, or older versions of Android will just crash).

Also, the oneshot approach isn't an option here because the libretro rumble interface only supports a never-ending "on" and "off" state for the motors.

**Comment by DieKatzchen** [comment]
So there's no amplitude data at all? Why not?

**Comment by DieKatzchen** [comment]
Wait, I understand now. The core sends on and off representing the duty cycles of the original hardware. That complicates things. I guess you could check every cycle whether it should be on or off and send a vibrate command (or not) for the length of one cycle. Or you could set a longer vibrate command and use cancel() when the state changes. Can't think of any non-hacky solutions.

**Comment by DieKatzchen** [comment]
Tried it on epsxe for android, which has this feature. Sort of. It's a juddery buzz that bears no resemblance to the rumble pattern on a real ps1. Might not be possible.
