### ISSUE TITLE
Issue with how retro_serialize/retro_unserialize work

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#7299]
`retro_serialize/retro_unserialize` is needed for a lot of libretro features, to the point it breaks standard savestates saving/loading in some cases.

I'll talk about 2 issues i have with this in fbalpha : 
- savestates are not compatible with standalone fbalpha, standalone compress its savestates with deflate, but if we do that in `retro_serialize/retro_unserialize` we could end up having performance issues with netplay, rewind, read ahead, ...
- sometimes the libretro port needs to remove a part of the savestate to save bandwidth because it's not necessary and harmful for netplay. However it prevents proper sprite loading when loading a savestate. One good example is CPS3 games : try saving, leaving, then reloading your savestate.

If we can't determine the purpose of a call to `retro_serialize/retro_unserialize` through a third argument, an api call, or whatever; then the only option i see is having a set of 2 new separate functions to handle normal savestate saving/loading.

**Comment by twinaphex** [comment]
But you point out yourself why compression is not really desired from a libretro core perspective, since that would cause performance issues for netplay, rewind, readahead.

It's too bad if certain standalone emulators do stuff a certain way that is not 1:1 applicable to how libretro does things. Libretro requires things to be done differently, and most of the time, there are very valid reasons for this. You would not want states to be compressed.

I really do not want to start introducing separate paths for savestate saving/loading - there is no reason to spin this off from the retro_serialize calls. What is the motivation here? So the libretro core can use the same savestates that standalone would? But why would we do that or want that when there is nothing but drawbacks to this method when they start compressing a state?

Emulator developers will just need to accept that this is the way libretro does things, and we are not going to change how the entire API works, introduce an API break, just because of certain (bad IMHO) habits that die hard. Libretro will require different codepaths vs. a standalone emulator, and that is just the way it has to be.

**Comment by twinaphex** [comment]
> sometimes the libretro port needs to remove a part of the savestate to save bandwidth because it's not necessary and harmful for netplay. However it prevents proper sprite loading when loading a savestate. One good example is CPS3 games : try saving, leaving, then reloading your savestate.

We made the conscious decision to change this in FBAlpha 2012 because it meant much faster netplay. If it is not wanted, simply don't implement it in your core.

Honestly, I see no point to changing the entire way libretro works (and this would not be possible since it would break the API anyway) just for these niche usecases.

**Comment by twinaphex** [comment]
BTW @barbudreadmon, none of this is meant negatively.

I am just trying to prevent a hard break in the libretro API 8+ years into its lifespan. I just want to avoid that at all costs, hence my trepidation with issues raised like this.

**Comment by twinaphex** [comment]
@barbudreadmon Would leveraging the environment callback FAST_SAVESTATES perhaps be a solution as @fr500 proposed? For instance, the CPS3 speedhack for serialization could be applied only when that environment callback returns true for instance.

Just trying to think of possible solutions here while staying within the framework of libretro.

**Comment by barbudreadmon** [comment]
@twinaphex fair enough, i wouldn't want to break anything, still if there is a way to do this without breaking the api : 
- about savestates compatibility, i've seen a lot of topics about how to convert saves from emulator X to emulator Y over the years, so it seems it is kinda a hot topic for users. I would use this compatibility myself for debugging.
- about the missing sprites, they are not missing for "only a few seconds", in the case of a mid-battle sfiii save, background will be missing until the end of the fight after you reload. Rewind is also barely usable on sfiii with sprites becoming artifacts.

So i think they are real issues and they should be taken in consideration. I don't think controlling the content of savestates through a core option would be "sane".
Also, i don't know anything about fbalpha2012 (i don't even know if the work done over the last year for full cross-platform netplay compatibility was backported). 
I'm talking about mainline fbalpha here, and when i removed the cps3 "hack" in the past (i didn't understand why it was there at first), i'm pretty sure you were the one who told me to put it back.

**Comment by Dwedit** [comment]
Savestates being forced to a fixed size has always been problematic.  I'd redesign the whole thing to use a COM-style memory stream object instead of a plain pointer, then you wouldn't need to worry about malloc/free functions not matching between modules.

**Comment by barbudreadmon** [comment]
@twinaphex @fr500 Any news about the leveraging of the environment callback FAST_SAVESTATES ?

**Comment by fr500** [comment]
```C
+++ b/dynamic.c
@@ -1837,6 +1837,8 @@ bool rarch_environment_cb(unsigned cmd, void *data)
 #ifdef HAVE_NETWORKING
          if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_REPLAYING, NULL))
             result &= ~(1|2);
+         if (netplay_driver_ctl(RARCH_NETPLAY_CTL_IS_ENABLED, NULL))
+            result |= 8;
 #endif
          if (data != NULL)
          {
```

This should do it.
Of course you need to add something like this to the core:
https://github.com/snes9xgit/snes9x/blob/master/libretro/libretro.cpp#L1529

**Comment by fr500** [comment]
Are you on discord or IRC? (it's far easier to work these things out in real time

**Comment by barbudreadmon** [comment]
If you don't mind the text mode (i'm not fluent enough in english), i can connect to discord, IRC is a pain in the ass to configure...

**Comment by fr500** [comment]
Yeah we prefer discord nowadays too, and don't worry I don't voicechat either :)
https://discord.gg/6xdkfr
