### ISSUE TITLE
(Switch) Add thumbnails to match ROM file name options

### ISSUE THREAD

**Issue by loverlf** [libretro/RetroArch#7389]
## Description

Switch official system does not support Chinese language，so RA cannot read the ROM of the Chinese file name.  
Rename ROM's file name in English and user a playlist to put the Chinese name in there as the label.  
This operation can display the Chinese name in playlist, but thumbnails can not be displayed because thumbnails match the label in playlist.
Can we set a toggle option let thumbnails matches the ROM file name, so that the thumbnail can be displayed and Chinese lable in playlist can be displayed at the same time.

**Comment by RobLoach** [comment]
I think the thumbnails match whatever is listed in the playlist. Haven't tested with Chinese characters though.

**Comment by goooooouwa** [comment]
@RobLoach what do you mean? Does retroarch match anything other than label for thumbnails as well?

> I think the thumbnails match whatever is listed in the playlist.

**Comment by goooooouwa** [comment]
Switch official system does support Chinese language since version 7.0. But the issue that RA cannot read the ROM of the Chinese file name still exists with the latest stable version 1.9.14.

Related issues:
https://github.com/libretro/RetroArch/issues/10440
https://github.com/libretro/RetroArch/issues/10374

Might be an issue with FAT32 partition with Unicode characters.

**Comment by gouchi** [comment]
@loverlf 

This issue has been [fixed](https://github.com/libretro/RetroArch/commit/32ed9b604154bb09ef96fa1af63fb3637c212348) thanks to @bulzipke.

The fix is available in nightly build or future RA version 1.17.0.

So please close this issue.

Thank you.
