### ISSUE TITLE
configure script usage output is horrible

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#7474]
## Description

configure script usage output is horrible

### Expected behavior

configure script that has a sane usage (output).

### Actual behavior

configure usage spam

Listing the --enable-* beside the --disable-* options for each feature and in no order is just terrible and redundant. In 2018 you don't have to use autoconf if you hate it so much.

Just look (below) what was necessary to get it under reasonable control.

### Steps to reproduce the bug

    ./configure $(./configure --help|grep -i -- '--disable'|awk '{ print $1 }'|sort|xargs|sed "s/ ---- /\n---- /g") --enable-sdl --enable-alsa --enable-zlib --enable-dylib --enable-dynamic

### Result

retroarch with few dependencies

### Version

current git

### Environment information

- OS: Linux
- Compiler: CC

**Comment by orbea** [comment]
I don't even understand what you are trying to do or what part of the output you find bad.... Bluntly that is one of the worst ways to use `configure`, does it even work with autotools? I'm having a hard time seeing where the bug is, can you explain what you are talking about better?

For what its worth, the current `./configure --help` will show `--enable-foo` and `--disable-foo` when it automatically determines to use the dependency with tools like `pkg-config`, it will show only `--enable-foo` when its the feature is disabled by default and likewise will show only `--disable-foo` when the feature is enabled by default. This seems pretty clear and is easy to read by humans which is what `./configure --help` is meant for.

**Comment by orbea** [comment]
Okay, I see your point now, thanks for explaining, but this is trading vertical bloat for horizontal bloat. I'm personally not sure which would be better and it might not be a trivial change. Its worth considering though.
