### ISSUE TITLE
PATCH: Remove HAVE_NO_* defines

### ISSUE THREAD

**Issue by noisybe** [libretro/RetroArch#7479]
Please don't do this.

```
diff --git a/qb/qb.params.sh b/qb/qb.params.sh
index 2a68f0605e..054acea176 100644
--- a/qb/qb.params.sh
+++ b/qb/qb.params.sh
@@ -102,7 +102,6 @@ parse_input() # Parse stuff :V
                        --disable-*)
                                opt_exists "${1##--disable-}" "$1"
                                eval "HAVE_$opt=no"
-                               eval "HAVE_NO_$opt=yes"
                        ;;
                        --with-*)
                                arg="${1##--with-}"

```

**Comment by orbea** [comment]
Can you explain why not?

**Comment by orbea** [comment]
its been a while since I looked at this code, so I could be forgetting something, but I think that adds lines like `HAVE_NO_DISCORD = 1` to `config.mk` and similar files when using configure arguments such as `--disable-discord` for example.

That said I am not sure anything in the code base is using these or at least I have not been able to grep for it, so maybe it is safe to remove. That said I am still not sure what the benefit would be?

**Comment by fr500** [comment]
HAVE_NOUNUSED_VARIABLE is the only used thing but it seems like such a pointless thing to change

**Comment by orbea** [comment]
I think the `HAVE_NOUNUSED_VARIABLE` is set elsewhere too.

**Comment by noisybe** [comment]
Okay.

You have in config.h:

```
/* #define HAVE_A  1 */
#define HAVE_NO_A
```
That is amateurish.

Because now you have people check either

`#ifndef HAVE_A`

OR

`#ifdef  HAVE_NO_A`

in their code. Which will result in cancer.

Defining HAVE_NO_A is redundant because of #ifdef OR #ifndef.

I am not going to debate this further.

**Comment by orbea** [comment]
Thanks for the explanation and it seems like a good point. I'll give it some thought and testing. (Hopefully soon...)

**Comment by bparker06** [comment]
>You give people two different ways to check for the same thing in their code.

It's not the same.

HAVE_NO_* is only defined when the user explicitly disables a feature, regardless of whether or not it was detected by the system. It could potentially be useful for something in the future, I see no reason to get rid of it just because you don't like it.

It doesn't complicate things, you still only need to check for HAVE_* to see if the feature is supported, checking for HAVE_NO_* would only be useful to know that the user disabled the feature themselves.

For example one potential use might be in the System Information menu, instead of just saying "No" for an unsupported feature, it might say "Disabled by user" or something instead.

**Comment by noisybe** [comment]
> It's not the same.

You think it isn't. But it is.

> "No" for an unsupported feature, it might say "Disabled by user" or something instead.

You advertise non-present features at _runtime_ that were disabled during _compilation_. What is the point of this?

Rather put the "Disabled by user" information at the end of the configure script (at compile time).

Or use HAVE_* and USE_* definition which is more intuitive.

HAVE_NO_* suggests that the feature doesn't exist, and not, as you say, that is was disabled.

HAVE_* for all functionalities that exist.
USE_* for all functions that are enabled.

**Comment by bparker06** [comment]
>What is the point of this?

Let's say a user tries to use a Cg shader and it doesn't work. They might have gotten RA from a package manager where it was built by someone else. They check System Information to see that Cg was disabled at compile time, now they know to tell the package maintainer about it. Or, they might have built RA themselves and simply don't remember what features they might have disabled or not, it can be useful when debugging, especially juggling multiple versions of builds.

Anyway, I see no reason to discuss this further, so to prevent any drama I'm locking this thread.

**Comment by orbea** [comment]
For the record I tested this quickly and found this is the change in `config.h` and `config.mk` with a few arbitrary configure arguments, `--disable-networking`, `--disable-qt`, `--disable-systemd`, `--disable-discord`, `--disable-vulkan`.

config.h
```
--- config.h.old	2018-10-24 06:04:45.952952807 -0700
+++ config.h	2018-10-24 06:05:21.877239214 -0700
@@ -72,11 +72,6 @@
 /* #undef HAVE_NETWORK_CMD */
 #define HAVE_NOUNUSED 1
 #define HAVE_NOUNUSED_VARIABLE 1
-#define HAVE_NO_DISCORD 1
-#define HAVE_NO_NETWORKING 1
-#define HAVE_NO_QT 1
-#define HAVE_NO_SYSTEMD 1
-#define HAVE_NO_VULKAN 1
 /* #undef HAVE_NUKLEAR */
 /* #undef HAVE_OMAP */
 /* #undef HAVE_OPENDINGUX_FBDEV */
```
config.mk
```
--- config.mk.old	2018-10-24 06:04:45.733951061 -0700
+++ config.mk	2018-10-24 06:05:21.697237780 -0700
@@ -104,11 +104,6 @@
 HAVE_NETWORK_CMD = 0
 HAVE_NOUNUSED = 1
 HAVE_NOUNUSED_VARIABLE = 1
-HAVE_NO_DISCORD = 1
-HAVE_NO_NETWORKING = 1
-HAVE_NO_QT = 1
-HAVE_NO_SYSTEMD = 1
-HAVE_NO_VULKAN = 1
 HAVE_NUKLEAR = 0
 HAVE_OMAP = 0
 HAVE_OPENDINGUX_FBDEV = 0
```
