### ISSUE TITLE
[Feature request] (Switch) exFAT support

### ISSUE THREAD

**Issue by mputilin** [libretro/RetroArch#7480]
## Description

Please, add exFAT SD cards support, because FAT32 is outdated and doesn't support large files.

### Expected behavior

RetroArch running from exFAT formatted microSD card. 

### Actual behavior

No RetroArch in Homebrew section of SX OS

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5

### Environment information

- OS: SX OS 2.0

**Comment by Ferk** [comment]
I'm using exFAT and it does work for me. I don't think Retroarch has anything to do with what filesystem is being used.
Maybe your Switch is in an old firmware that doesn't support exFAT.

**Comment by mputilin** [comment]
@Ferk no. I'm able to play games just fine, but no RetroArch in Homebrew section. It's my first and only one homebrew. I should check if other homebrew works

**Comment by natinusala** [comment]
The issue with exFAT is that the current implementation **Nintendo** uses is bugged and "randomly" deletes files. We **cannot** fix this. Nintendo can, and since it's not an issue on their end they will probably never do it.

> No RetroArch in Homebrew section of SX OS

This doesn't seem exFAT related, unless RetroArch was deleted before you even got the chance to run it once. 

This also doesn't concern RetroArch at all, that would be an issue with whatever homebrew menu SX OS uses. Here, we assume that you can at least run the homebrew, which is not the case here.

And last, SX OS is not a supported OS, please come back if you have the same issue on Atmosphère and hbloader / hbmenu.

**Comment by twinaphex** [comment]
m4xw wants me to close this issue.  He does not want to provide support to SX OS either officially.

**Comment by twinaphex** [comment]
> Please, add exFAT SD cards support, because FAT32 is outdated and doesn't support large files.

As far as I understand it and have been told by RetroNX devs, this is actually an OS issue. Nintendo has spotty/bad exFAT drivers. Formatting your SD card as exFAT and doing many writes to it with Switch is begging for corruption.

**Comment by fr500** [comment]
There isn't a single game that a retroarch switch core supports that exceeds 2GB.

**Comment by natinusala** [comment]
Well there is one : Dolphin but it's not available on the Switch anyway

**Comment by m4xw** [comment]
Why is this still open?
Please close this.
#DOESNOTFIX

**Comment by caHarkness** [comment]
Is there any hard evidence that this is a real thing? If Nintendo's implementation of exFAT is bad, wouldn't the problem be well known by now? That screen capture button has ought to have destroyed thousands of SD cards by now if this were true.

**Comment by CTCaer** [comment]
The FAT drivers in general and how the FS sysmodule works are bad.
PrFILE2 which is the fat driver that HOS uses have certain bugs in its cache system also.

Both FAT32 and exFAT drivers are bad:
It's just that FAT32 is able to recover because it caries 2 FAT instead of 1 that exFAT has.

The FS sysmodule, when you open a file, it also opens the directories as writable handles. And when a homebrew crashes or is exited forcefully or sometimes just reading stuff, these records get deleted from the file allocation table.
Don't get the wrong assumption that nintendo does not have that problem. They have it but they emulate a journaling system.

Screenshots are handled on system level. If a commercial game for example, does the mistake to touch the sd card, it will corrupt things. That's why no game uses the sd card to save stuff.
Everything you see in the Nintendo folder is protected by that said journaling system. But sometimes it fails (corrupt screenshots/videos).

**This is basically not an issue and can't be fixed! Only mitigated.**

Only ninty can change that behavior or a complete rewrite of the FS sysmodule.
Ninty uses the journal system. So forget about having an official fix for homebrew.

**Comment by Jj0YzL5nvJ** [comment]
Thanks @CTCaer, you saved me a lot to say (translate).
It's no surprise, exFAT isn't a secure file system even in Windows and other **Microsoft** products.
It gets corrupted VERY easily, not even its **creators** trust it. **They** added an additional "pseudo journaling system" relatively recently within the "System Volume Information" folder of the unit itself. That was not part of the original specification.

 If you do not need support for files above 4GB, avoid exFAT as if it were AIDS. If you do not have a better option, make backups frequently and **use checksums**. And do not cry when you lose the files, because it's going to happen, it's just a matter of time.
 Alternatively you can use an **NTFS without the USN Journal** (`fsutil usn deletejournal /d x:`). The USN Journal is the reason why it is not advisable to use NTFS in flash drives.
 The lifetime of flash memory will not be so affected if you turn off the USN. But again, **avoid using it** if you don't need support for files larger than 4GB.

**Comment by natinusala** [comment]
NTFS on the Switch?

**Comment by Jj0YzL5nvJ** [comment]
exFAT on the Switch and not NTFS?
If NTFS on Switch not option then you all are f***ed.

**Comment by natinusala** [comment]
The only options are fat32 and exfat

**Comment by natinusala** [comment]
Use just use fat32 as there is no point in using exfat

**Comment by bparker06** [comment]
@fr500 I believe there are psp games over 2GB as well
