### ISSUE TITLE
Error saving shader preset

### ISSUE THREAD

**Issue by billywade** [libretro/RetroArch#7551]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to save a shader core preset, Retroarch attempts to save the preset in the shader's directory rather than the Retroarch config directory, causing a permissions error and no preset to be saved.

### Expected behavior

The core preset to be saved in a directory somewhere within /~.

### Actual behavior

```
[INFO] Resetting shader to defaults ... 
mkdir(/usr/share/libretro/shaders/presets/Mupen64Plus OpenGL) error: Permission denied.
Failed to create directory: "/usr/share/libretro/shaders/presets/Mupen64Plus OpenGL".
```

### Steps to reproduce the bug

1. Start Retroarch 1.7.5 on Linux.
2. Run any core and content.
3. Modify the existing shader configuration.
4. Attempt to save the shader config as a core, game, or other preset config.

### Bisect Results

This started happening pretty suddenly, with the only change having been turning off shaders temporarily for one game. If it means anything, at the same time xbr-lv2-3d.glsl stopped working on  Snes9x

### Version/Commit
Retroarch 1.7.5 release for Linux

- RetroArch: [version/commit]

### Environment information

- OS: Manjaro Linux x64, up to date
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
It has always saved shaders in the preset directory.
This is a packaging problem more than a real issue in my opinion.

**Comment by billywade** [comment]
Has it always saved them outside of the user's home directory, though? I would have assumed that they would be saved in ```~/.local/share/libretro/shaders/presets/```. This is what happens when I build from the AUR retroarch-git package, too.
Is there a way to at least allow changing of the presets directory? It's usually considered a vulnerability when something like this needs administrative privilege.

**Comment by hizzlekizzle** [comment]
It's always going to follow the shader directory, so if the packager sets that somewhere not user-writeable, then yeah, it's going to require elevated privs. So, yeah, I agree with @fr500 that it's a packaging issue, though not one that is easily solved.

**Comment by billywade** [comment]
Alright, thanks @hizzlekizzle and @fr500, I'll go ahead and set this up in root. 

Incidentally, any idea why a shader would suddenly stop working?

**Comment by hizzlekizzle** [comment]
Rather than using elevated privs, you could just make a user-writeable directory and point your shader directory to that instead. Re-download them from the online updater and you're good to go.

Dunno why one would stop working, but a log of it failing should give us an idea.

**Comment by billywade** [comment]
> Rather than using elevated privs, you could just make a user-writeable directory and point your shader directory to that instead. Re-download them from the online updater and you're good to go.

That... Is a vastly better idea, thanks. 

> Dunno why one would stop working, but a log of it failing should give us an idea.

I can get that to you, assuming it's just part of the terminal logging, but should I open that as a new issue and close this one or is it fine to have them both here?

**Comment by hizzlekizzle** [comment]
Some of the package maintainers patch out the online updater altogether, but there are also options in settings > user interface > views to show/hide various elements, including the core updater, etc. (you may need to make sure 'show advanced options' is enabled, as well). If those settings were already set to 'off' due to the packaged version, you'll have to re-enable them, or else just delete your ~/.config/retroarch/retroarch.cfg to get back to default settings.

I would normally say to create a new issue for the broken shader thing, but you may as well do it here. However, it'd probably be even better if you could come to the forum or discord, which are better suited to general support than github.

**Comment by berarma** [comment]
I think that it would be an improvement that user generated content/settings would be saved to a different directory than downloaded content. The downside being that there would be two directories to browse when loading a preset.

This way users wouldn't accidentally overwrite downloaded shader presets, or downloaded presets would overwrite the ones by the user.

By the way, who builds the flatpak package? This problem should be fixed there in case nothing changes in Retroarch.

**Comment by berarma** [comment]
I've noticed that pressing the space bar in the shaders directory setting has changed it to a directory in my home. Why isn't this the default directory setting when installing the flatpak package?

**Comment by fr500** [comment]
@berarma it doesn't overwrite the downloaded shaders.
It always creates a configname.ext shader preset in the top level shader dir whenever you load one of the bundled presets.

When you save core/game presets those are saves in presets/corename/

**Comment by billywade** [comment]
I should probably update my experience here. Since setting all of my directories to ones inside my home directory, all of which have rwx permissions, I still can't save shader presets. I haven't looked into the new issue all that much lately, but I know it exists.

**Comment by x6fan** [comment]
As an Arch Linux user this also affects me. I do not believe it is a packaging error. It makes sense to install shaders to `/usr/share/libretro/shaders/` since they can be shared by many RetroArch installations. For example, I have the official [`retroarch`][retroarch] package installed globally and also use [`retroarch-git`][retroarch-git] to obtain, build and use development versions. Both packages are mentioned in [RetroArch's Linux install instructions].

It would be nice if RetroArch had separate directory configuration variables for system and user shaders. That way it is possible to have a read-only shaders directory that matches the contents of upstream shader repositories as well as a user specific shader directory where core/content directory/content specific shader presets can be stored.

The [XDG Base Directory Specification] is useful in situations like this. `XDG_DATA_HOME` represents a user specific `share` directory and is perfect for this use case. I have pointed RetroArch's shader directory to `"$XDG_DATA_HOME"/libretro/shaders/` in order to work around this issue but now RetroArch won't make use of the globally installed shaders. I had to use RetroArch's autoupdater to redownload all shaders unnecessarily.

According to issue #8901 this affects Android systems as well.

[retroarch]: https://www.archlinux.org/packages/community/x86_64/retroarch/
[retroarch-git]: https://aur.archlinux.org/packages/retroarch-git/
[RetroArch's Linux install instructions]: https://www.retroarch.com/index.php?page=linux-instructions
[XDG Base Directory Specification]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by stevenxxiu** [comment]
:+1:, I'm impacted this by now, after just installing `retroarch` and finally getting shaders to work.

For those interested, I failed to google this. But switching the `video_driver` from `gl` to `vulkan` made this work on Linux. It is very confusing that RetroArch says nothing about why shaders can't be loaded, and simply hides them.

**Comment by stevenxxiu** [comment]
@x6fan There's still a good way to solve this currently so we can use Arch Linux's packages.

Just make a symlink:

    $ ln -s /usr/share/libretro/shaders/shaders_slang/ ~/.local/share/libretro/shaders

Then we won't have permission issues, since RetroArch stores the shader configurations for each core at `~/.local/share/libretro/shaders/presets/`, which has our permissions and not root permissions.

It's sort of a hack, so an official solution would still be better.
