### ISSUE TITLE
Setting controls is confusing and broken

### ISSUE THREAD

**Issue by qmr** [libretro/RetroArch#7712]
When using NES core, why do I have settings for anything other than the 8 NES buttons in menu?

The default mappings for NES buttons are difficult and awkward, if I change the settings in this "universal" or whatever menu, that's going to change settings for SNES and PSX, which I do not want.

It should not be this difficult to use an emulator.

**Comment by fr500** [comment]
It may be confusing.definitely not broken.

**Comment by hizzlekizzle** [comment]
Map your physical inputs in settings > input, move the core's functions around on your pad (or the retropad abstraction) in quick menu > controls.

The controls menu only shows the core's inputs (rather than the generic retropad's inputs) and the changes only affect the current core instead of bleeding into other cores' inputs.

If your physical gamepad is recognized and autoconfigured, you don't need to (and probably shouldn't) go to settings > input at all.

**Comment by orbea** [comment]
This doesn't look like an issue and as explained in the previous comment once a gamepad is autoconfigured there is rarely a need to touch `settings > input`. If you need any help configuring your gamepad please checkout the forum, discord or irc where other users can hopefully help.

If there are any specific issues with settings controls please submit a new issue and follow the issue template, thanks.
