### ISSUE TITLE
provide default mouse button mapping to lightgun API triggers

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#7904]
RA support for the lightgun API is a useful addition to the input system.

At the present, when the user has a mouse connected and has selected lightgun as their input device, they do have an automatic mapping of the mouse movement to crosshair movement.

There is not at present a default mapping between mouse buttons and the lightgun API triggers. This is a request to add a default mapping.

![screenshot 2019-01-05 20 19 57](https://user-images.githubusercontent.com/19554678/50730974-5e008580-1127-11e9-9560-bbd3fc5ed62f.png)

**Comment by OctopusButtons** [comment]
I may be mis-reading your description, but I think the problem is  larger than described:  as of RetroArch 1.9.0 there is **no support at all for custom binding lightgun buttons** to anything other than default Mouse1 if you're using mouse to control crosshair.  If you try to change the binding in a config like any other binding, it won't work.

In other words, it's impossible to bind Lightgun Trigger/Fire to a controller button or keyboard button.  I mean specifically if (I think?) you're using a Mouse to control lightgun crosshair.  It's like it's hard-wired into the RetroArch code somewhere, and it automatically over-rides any attempt to config or bind it to something else.  Basically, Lightgun Mouse doesn't function like any other control

**Comment by markwkidd** [comment]
@OctopusButtons in the current version of RA, there is no default binding for the lightgun trigger (or other lightgun controls). What you are describing sounds like a separate, although equally frustrating, issue. In fact, I think someone else has just logged it in detail here: https://github.com/libretro/RetroArch/issues/12417

Does that issue sound the same as yours?

**Comment by markwkidd** [comment]
Closed via https://github.com/libretro/RetroArch/pull/12423

**Comment by OctopusButtons** [comment]
Sorry, I’ve been busy and never replied.  I’ll reply in the other thread.  It does seem similar, in that in that case and my case the accepted binds in the RA menu (or also using manual config entries) have no effect in game.  It’s like the Mouse button 1 is hard coded to lightgun trigger, I can disable that by binding it stop something else, but the something else doesn’t work, the only thing that works when bound to lightgun trigger is Mouse button 1.
