### ISSUE TITLE
 [Feature Request] SMB and FTP to serve ROMs from NAS to Apple TV

### ISSUE THREAD

**Issue by ScarAce1989** [libretro/RetroArch#8173]
I would like to use my NAS to serve ROMs for TvOS as the Apple TV doesn’t have much storage.

**Comment by fr500** [comment]
It's unfair to expect RA to implement complete networking protocols because a platform doesn't give users freedom.

**Comment by RobLoach** [comment]
Get hardware or a platform that lets you mount a network drive. A Raspberry Pi with Lakka will let you do that, and likely play the same games as an AppleTV. Other than that, root it?

Either way, seems like an issue beyond RetroArch, and more of an issue with Apple TV.

**Comment by ScarAce1989** [comment]
I’m not a developer, so I don’t know if it’s hard to add network protocols. There are some other apps with network protocols for the Apple TV, like Infuse or VLC.

**Comment by tonycoco** [comment]
Dated issue here, but it seems relevant now with the App Store releases.

**Comment by bgwallace** [comment]
Any chance this issue can be re-opened? Understand it would be great if Apple TV supported SMB file sharing at a tvOS system level but as this is unlikely to happen and because this feature would likely be a highly popular one due to Apple TV space limitations it would be awesome if RA devs could implement something for us. Thank you in advance for all you guys do!

**Comment by QuantumInferno** [comment]
I'd like to see this too. I previously had a RetroPi that had a SD card fail on (cheap, crappy, old), so when I rebuilt it I started mounting a share from my NAS. I've got a couple Apple TVs in other rooms that me and my kids would love to have the same library on them like we do Plex.

**Comment by patriknyblad** [comment]
Adding my +1 here as well, this is what's stopping me from using RetroArch on TV currently. Maintaining a copy/small subset of the emulation library on iOS platforms meant that I only really tested RetroArch a couple of times on the otherwise perfect device to run emulators on (as it's the main interface for our TV experiences in the house, no matter which TV).

**Comment by sdenike** [comment]
Being able to store ROMS on a NAS and access it would be fantastic if this made its way into RetroArch

**Comment by brycekw** [comment]
Non developer here. But I’m pretty sure this would be possible, as other apps like Plex use NAS to stream content to the Apple TV. And I’d like to chime in with another vote to have this implemented into RetroArch.

**Comment by sdenike** [comment]
> Non developer here. But I’m pretty sure this would be possible, as other apps like Plex use NAS to stream content to the Apple TV. And I’d like to chime in with another vote to have this implemented into RetroArch.

So while I see where you are going with this, and I agree.  I dont think its exactly the same since Plex has a Server and Client which they have created to speak to one another, I assume over their own protocol.  I did a little research about this yesterday, and the TVOS does not have Samba built in as a library, but apps like VLC bundle their own SMB library and make use of that. I think RetroArch developers would have to include the library in their code and make use of it to mount remote shares.

This is out of my league so I am no help outside of my Google skills 😀 but perhaps this is something one of the developers would find fun and want to invest some time into as it really would bring it to the next level being able to mount a share on a NAS where you can store/sort ROMS and play over the network.

**Comment by timemaster5** [comment]
I would like to reopen this request as I see some progress being made, and it seems a smb client is really a thing!

I am waiting for this, and hope it is going to be soon on the apple tv :)
