### ISSUE TITLE
Crash on Windows 98 SE

### ISSUE THREAD

**Issue by camthesaxman** [libretro/RetroArch#8376]
## Description

Retroarch crashes immediately upon startup on Windows 98 SE.

![retroarch_crash](https://user-images.githubusercontent.com/17279765/53466843-32a86180-3a19-11e9-8bb4-c9b8d31aac11.png)

### Version/Commit

- RetroArch: 1.7.6 for Windows 2000 / ME / 98SE

### Environment information

- OS: Windows 98 Second Edition
- Compiler: Visual Studio 2005

### Hardware/System Information

- CPU: Pentium 4 Willamette 1.5 GHz
- RAM: 512 MB
- GPU: ATI Radeon 9550xl AGP
- DirectX: 9.0c
- OpenGL: 2.0

**Comment by camthesaxman** [comment]
I've tried 1.6.7 (the first VS2005 version), and same result.

**Comment by twinaphex** [comment]
Hi @bparker06 , this might be of interest to you.

**Comment by gouchi** [comment]
@camthesaxman  you can use this [link](https://docs.libretro.com/compilation/windows98/) for the documentation.

**Comment by bparker06** [comment]
Hi @camthesaxman,

Please try downloading the latest nightly build here:

http://raw.libretro.com/nightly/windows-msvc2005/x86/

If you still experience the crash it is probably due to an incompatibility with your GPU and our GL2 driver. 

You can try the brand new GL1 driver from the nightlies (which should give you the best performance on Win98) by editing `retroarch.cfg` and adding this line:
```
video_driver = "gl1"
```
Make sure to delete any existing lines that start with "video_driver".

If that still does not work, try the software renderer with:
```
video_driver = "gdi"
menu_driver = "rgui"
```

Please let me know if you need anything else. I have a Win98 system here that I regularly test with as well and it is working for me.

**Comment by camthesaxman** [comment]
The gl1 driver works in the latest nightly. The regular "gl" driver and the "d3d" driver still crash, though. I'm also having a problem when downloading databases-rdb.zip. It always gets to 68%, then quits saying task failed.

**Comment by bparker06** [comment]
The only thing I can think of regarding the database download is running out of memory. Other than that I'm not sure.

**Comment by bparker06** [comment]
Should this issue be closed now?

**Comment by camthesaxman** [comment]
Yes, you can close it. I just copied the files from another machine.
