### ISSUE TITLE
Add automatic individual thumbnails download

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#8404]
The idea would be to download only needed thumbnails, only when necessary (of course users can still download the whole thumbnails packages if they want to). It should be asynchronous, and the menu driver should be refreshed when a new thumbnail is available (if needed). A placeholder loading icon can be displayed instead of the thumbnail while it is downloaded.

Here are some implementations ideas:
- When scanning content, download the thumbnails as part of the scanning process
- When loading a playlist, download the thumbnails as part of the loading process
- When going through a playlist, if the thumbnail is missing download it
    - A flag can be added to the playlist entry if no thumbnail is available to prevent fetching the thumbnail and failing each time we go through the playlist (JSON playlists may be required for that)

This would be a big quality of life improvements, at least for platforms where disk space is limited (like the Switch or Android for instance), or platforms with unstable network I/O where downloading the whole thumbnails package can be troublesome.

It could be a good idea to abstract the thumbnail code out of the menu driver before doing that (right now, thumbnails code if copy pasted from xmb to ozone).

**Comment by jdgleaver** [comment]
I think downloading thumbnails in real-time while loading or browsing a playlist would make for a pretty miserable (i.e. slow/laggy) user experience.

The ability to select an existing playlist and have a (blocking) menu option 'download thumbnails for all entries' could be rather nice, however.

**Comment by natinusala** [comment]
Well, this is a valid concern, however we already have background downloading as part of the online updater, I don't think the impact will be too much

**Comment by jdgleaver** [comment]
Sure, but I think most people select an item to download, and then wait for it (or just go through and update all their cores, which is ~10-20 items). You're talking about queuing up maybe 1,000-2,000 individual thumbnail fetch operations at a time, which makes me uncomfortable.

But hey, I have no strong feelings here. As long as the option can be turned off, I don't mind :slightly_smiling_face:

**Comment by natinusala** [comment]
Well, they can be queued in a task of its own to show users `Downloading thumbnail 144 of 1475...`.

_menu widgets wen_

**Comment by retro-wertz** [comment]
i'd say no auto-download. qt-ui already has download from playlist (by title or system) or individually if needed (not sure if this is available in other other). how would it work though? would it be downloading when you pass by the title name (like just when scrolling through the list???)

**Comment by markwkidd** [comment]
My understanding is that previous attempts to do this have found it to be slower than downloading the full packs for reasonably large collections because of the overhead of negotiating many small downloads is greater than one large sequential file download.

Personally it does seem wasteful!

@natinusala you might want to put your head together with @RobLoach who was recently writing about  https://datproject.org/ as a possible means to distribute thumbnails

https://github.com/libretro-thumbnails/libretro-thumbnails/issues/21#issuecomment-460007406

**Comment by natinusala** [comment]
Some platforms cannot download the whole thumbnails package properly, or don't have enough storage to store it in its entirety. 

The point would not be to have faster downloads but to have a more flexible approach for those platforms where downloading the whole file is not possible. 

However I understand that to be remotely usable, it would need some "smart" server to support that system and serve only the required thumbnails in an efficient manner. This is a challenging issue.

**Comment by bparker06** [comment]
To properly download thumbnails from github outside of Qt land, we'd also need (multiple) redirect support added to the net_http code... and HAVE_SSL would be mandatory for any platform with this download feature as well (github no longer supports plain HTTP downloads).

So not only that, but it takes 3 separate requests to fetch a thumbnail, and that's without knowing if it even exists on the remote end; just because a thumbnail is missing on the client doesn't mean the server has it either. Not to mention these are all full size png images.

**Comment by RobLoach** [comment]
Could also use http://thumbnails.libretro.com for individual requests. Download only thumbnails that don't exist yet. There are clear technical hurdles we'd have to handle to not make it a poor user experience.

**Comment by bparker06** [comment]
Not sure if this matters but I did read about an emulator on the play store (which I won't name because they rip off non-commercial code for profit) that alleged that they had previously been banned from the play store for having a cover art downloader.

**Comment by sonninnos** [comment]
Isn't the on-demand thumbnail download feature covering this enough?

**Comment by RobLoach** [comment]
Yeah this is done
