### ISSUE TITLE
[Ozone] Image playlist showing core association, playtime log and last played

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#8521]
As the title says, current build is displaying additional information for each playlist entry in the Image playlist (and possibly also the Music and Video playlists, but I have those disabled at the moment), including core association, last played date and playtime log. 

Especially the latter two display no relevant data for that kind of playlist as per @jdgleaver's code, so they should probably not appear at all.

See this screenshot as a reference: https://imgur.com/a/pXaBl8q

**Comment by orbea** [comment]
Is this only with ozone?

**Comment by Ryunam** [comment]
I can confirm that on XMB at least 'last played' and 'playtime log' do not appear in the corresponding sublabels for this type of playlist. Only core association shows up.

**Comment by orbea** [comment]
> but I have those disabled at the moment), including core association, last played date and playtime log.

How? I can't find any way to disable these, figuring out how to enable them was hard too... We have a issue template for a reason...

**Comment by Ryunam** [comment]
What I meant was that I have hidden the Music and Video playlists, by going to Settings -> User Interface -> Views, then setting both "Show Music tab" and "Show Video tab" to OFF.

**Comment by orbea** [comment]
Sorry, but that just confused me more...

I see that those `Show Music tab`, `Show Video tab` and etc. require restarting RetroArch to take effect, but I don't understand what that has to do with core association, playtime log or last played?

**Comment by Ryunam** [comment]
The reason why I had mentioned the Music and Video tabs is that I don't know if core association, playtime log and last played date information is being displayed for those tabs as well, since I have them hidden at the moment. 
I can only speak with regards to the Image tab, the one that I have enabled and that I typically use to check the screenshots taken with RA.

**Comment by orbea** [comment]
Oh, I see what you mean now, I'm not sure its very useful to have that information in the images, videos and music playlists, but it might be more useful in the future if there are alternative cores that can load the same content are available. There are already two video player cores, ffmpeg and libmpv (Which uses ffmpeg).

@jdgleaver Do you think its worthwhile to show core association, playtime log and last played information for the images playlist? How about music and video playlist?

**Comment by jdgleaver** [comment]
@orbea When I implemented playlist sublabels, I included core name on everything, but only added runtime/last played to history, favourites and 'normal' collection playlists (i.e. not on images, music or video)

I still think that's a pretty good way to handle things.

I imagine the issue reported here was just a tiny oversight in ozone (which doesn't use sublabels at all now) - in fact, I think it can be fixed by editing this:

https://github.com/libretro/RetroArch/blob/cec06a08592c7987be275e18ffb19756f889af19/menu/drivers/ozone/ozone_entries.c#L730-L786

so the `else if (!string_is_equal(ozone->selection_core_name, "imageviewer"))` check comes first (and maybe add checks for music/video, as well...?)

**Comment by orbea** [comment]
Thanks for helping explain, I think that is a reasonable approach and I see that this only a problem in ozone. Unfortunately the fix doesn't seem to be as trivial as you suggest.

With some printf debugging I see that `ozone->selection_core_name` is actually `Core: imageviewer` which is why it doesn't match, but if that is changed it doesn't show even the core name like in xmb/glui (How do you see sublabels in rgui again?). @natinusala Maybe you would like to look at this?

**Comment by natinusala** [comment]
It looks like I forgot to change that when I changed the layout from two columns to one column. `ozone->selection_core_name` went from `imageviewer` to `Core: imageviewer`.

I know how to fix it, I'll submit a PR tomorrow probably

**Comment by orbea** [comment]
Thanks, I appreciate it!

**Comment by natinusala** [comment]
Sorry for the delay, I had some spicy Switch stuff to do first - the fix is here: https://github.com/libretro/RetroArch/pull/8532
