### ISSUE TITLE
3ds cores randomly crash if they have and when using dynarec 

### ISSUE THREAD

**Issue by TriforceOfPwnage** [libretro/RetroArch#8750]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Cores that use dynarec crash at random when it is enabled on "new"3ds

### Expected behavior

Dynarec speeds up game 

### Actual behavior

Dynarec causes game to crash and makes cores unusable 

### Steps to reproduce the bug

1. Load up core that uses dynarec example gpsp 3ds
2. Play game as normal 
3. Game will crash system at seemingly random points of gameplay. 

### Bisect Results

Retroarch 1 3.2 onward

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.3.2-current/commit]

### Environment information

- OS: new3ds xl
- Compiler: N/A
![JPEG_20190510_174703](https://user-images.githubusercontent.com/15988336/57558856-6e32a680-734d-11e9-880f-ec0bd5c707bc.jpg)

**Comment by orbea** [comment]
@jdgleaver Are you capable of confirming this or not? I recall you have a 3ds setup with RetroArch.

**Comment by jdgleaver** [comment]
This is specifically a gpsp (core) issue - it is not related to RetroArch...

But yes, gpsp has been broken for years. This is not just a 3DS issue - it's unstable on all ARM platforms AFAIK. It runs somewhat better when using a real bios file, but I wouldn't really trust it.

Unfortunately, I don't know if this will ever get fixed...

- Writing a dynarec is very difficult and requires specialist knowledge. gpsp is a niche core, and finding a 'specialist' willing to work on it is not a trivial thing.

- On top of this, we would need someone who is also an expert at debugging software on 3DS. I can do the basics, but this is on a different level. There are not really that many people in the world with the right skill set (i.e. not many people even know how to read a 3DS exception dump), and attracting one of them to do some free work is again not trivial.

- The demand for GBA emulation on 3DS just isn't there. I know it's important for a small number of users, but the 3DS contains actual GBA hardware - GBA VC injects run natively, and are the best possible way to play GBA games (perfect performance, perfect sound, zero lag - markedly better than mGBA, in fact). So basically, this is a bug with very limited relevance - and while it would be wonderful to get it fixed, hardly anyone is going to have the ability or motivation to look at this.

@TriforceOfPwnage I guess the best you could do here is start a bounty, if you feel like it, and hope that someone bites...

On the other hand, I do want to see if we can get the mGBA core building again on 3DS, so maybe that would be an alternative (although whether I'll succeed is another thing, and I have some other big projects to do first...)

**Comment by ShadowOne333** [comment]
@jdgleaver mGBA has a native port for 3DS officially released by endrift, so if there's any issue with its compilation, I would suggest contacting endrift to get the mGBA running/compiling properly for 3DS.

**Comment by TriforceOfPwnage** [comment]
I remember gpsp running fine first hand with no crashes at one point though. I think it was before 1.3.0 stable. Right around the time the dynarec was overhauled i believe. Would it be possible to revert that change for arm builds for a possible fix? Just a suggestion don't really have enough experience hence this question?

**Comment by TriforceOfPwnage** [comment]
@jdgleaver f1d14fbe7ce749b613ee2f7071cdfff1de013152 this is the only commit related to dynarec around the time the issue started. Idk if looking at that would help

**Comment by vaguerant** [comment]
This might not be relevant here, but I don't know if it's really worth having a separate issue. Another issue with dynarecs in RetroArch on 3DS is that they only work when apps are installed as CIA. As far as I know, there's no technical reason for this on modern (Luma3DS/Rosalina) CFW, which should open up access to all services, including `svcControlProcessMemory`.

I think the reason for this missing feature is probably just that there was a time in 3DS homebrew history when 3dsx homebrews were usually being launched in user-mode, whereas CIA installation always required a fully exploited 3DS, so homebrews started disabling their more advanced features when compiled as 3dsx. That shouldn't be the case any more though, so cores like gpSP, pcsx-rearmed and Picodrive *should* be just as capable when run from Rosalina.

**Comment by jdgleaver** [comment]
@ShadowOne333 Thanks - yes, I know about the standalone version of mGBA. It looks like the build is failing because it's linking in some 3DS-specific source files from standalone which conflict with our custom versions. I think this should be fixable - just haven't had time to look at it properly...

@TriforceOfPwnage Ugh... I tried reverting that commit, but it's entangled with a heap of frontend changes. I can't even build just an old version of the core, because too much has changed elsewhere. This is too much of a mess to fix...

But it might also be worth mentioning that some games just aren't compatible with gpsp (and are known to crash on all platforms). I know that some users have success with gpsp for certain games - it could be that you're running into content that's broken upstream...?

As I said in my first comment, I don't think this is something any of our existing devs will be able to sort out... :(

@vaguerant That may well be true, but just because something *should* be possible doesn't mean we can do it  :)

I don't know of any other homebrew that has managed to do what you say. This is another case of trying to attract an expert 3DS developer to help us - and again, a bounty might be the best (only?) incentive...

**Comment by vaguerant** [comment]
@jdgleaver I don't have a build environment for 3DS set up (I promised I'd do it Friday ...) currently, so I can't test it myself, but looking at libretro/picodrive, it seems like `svcControlProcessMemory` is just buried behind `if` statements checking the value of `ctr_svchack_successful` (`0` or `1`) in `libretro.c`.

Maybe I'm supposing this to be more simple than it is, but have you ever tested just ... forcing `ctr_svchack_successful` to `1` (quick/ugly hack solution for testing) or removing the `if` statements entirely (more permanent solution assuming it's really that simple)?

From the sounds of things, `svcControlProcessMemory` *should* "just work" in Rosalina environments. That's not to say that it *does* and I'm far away from being qualified to say that, but if I can get a build environment working next week I'll certainly give it a shot. Thanks for the response!

**Comment by jdgleaver** [comment]
@vaguerant That's... not how it works. You can't make a rock fly by commenting out the `if (has_wings)` check. It's going to require some deeper code changes than that!

(Also, we can't have hacks like that in production code even if they did work, since it would break things for other users)

TBH, if you want to pursue this, I think you'll need to contact AuroraWright (since it's OS-related), and maybe smealum as well (author of ctrulib). I would also suggest posting it as a question on the gbatemp forums and the 3dshacks subreddit (although I'd phrase it as a 'general' development question rather than specifically mentioning RetroArch, otherwise trolls may swarm and attack).

As for building RetroArch 3DS, you need a specific version of the toolchain, which you can find here: https://github.com/libretro/libretro-toolchains

**Comment by vaguerant** [comment]
Thanks for the help, @jdgleaver. I will try again tomorrow with the libretro toolchains and see if I can get things compiling.

As for just cutting out `if` statements, I'm sure it's different in RetroArch, but in bubble2k16's native 3DS Picodrive port (which I believe is partly based on RetroArch's), there are literally if statements that disable the dynarec if the emulator was launched from the Homebrew Launcher, so the rather than `if(has_wings)`, in that case we're looking at something more like `if(has_feathers)`--and we don't need feathers to fly. :)

Obviously, if something like that even had a hope in hell of working, an ugly hack like that would have to stay out of production code, but I'm not convinced it would break anything for anybody who meets the minimum "system requirements" for RetroArch on 3DS. Since Luma3DS is expected to be running for anyone who wants to use RetroArch, there are in theory 0 people using RetroArch in user mode--all of the users whose homebrew setups are officially supported by RetroArch are running a full-service CFW.

**Comment by jdgleaver** [comment]
Fair enough! Let me know how you get on :)

**Comment by vaguerant** [comment]
@jdgleaver Success! At least in Picodrive, I haven't tried the others. Now, like I said, I went with a super ugly hack approach. Here's a diff of the official `libretro.c` and mine.
```
56c56
< static int ctr_svchack_successful = 0;
---
> static int ctr_svchack_successful = 1;
289c289
<    if (ctr_svchack_successful)
---
>    if (1)
328c328
<    if (ctr_svchack_successful)
---
>    if (1)
369c369
<    if (ctr_svchack_successful)
---
>    if (1)
487c487
<    if (ctr_svchack_successful)
---
>    if (1)
1555c1555
<    ctr_svchack_successful = ctr_svchack_init();
---
>    ctr_svchack_successful = 1;
1566c1566
<    if (ctr_svchack_successful)
---
>    if (1)
```
I am garbage.

As you can see, I let `ctr_svchack_successful` default to `1`, turned all checks for `if (ctr_svchack_successful)` to `if (1)`, and turned `ctr_svchack_successful = ctr_svchack_init();` into `ctr_svchack_successful = 1;`. I have literally no idea how many of those were important and how many were not. However, I'm now playing full speed Knuckles Chaotix (a 32X game) using the Picodrive dynarec, in a 3dsx build on a New 3DS. I can confirm the dynarec is working by switching it off to see the framerate plummet to about 17FPS.

I don't have the core competency to implement this fix properly, but there's clearly not much work to be done here. Luma3DS provides the `svc` access, RetroArch is just getting in its own way by making the software jump through hoops to prove it has the access. None of it is needed any more in a modern, Luma3DS setup where *everybody* has `svc` access.

**Comment by jdgleaver** [comment]
Ah, that's really cool - well done.

So I believe the correct place to fix this 'properly' is right here:

https://github.com/libretro/picodrive/blob/82f7735d8ec942fb954917dec61f42ff9da809cb/platform/libretro/3ds/3ds_utils.c#L48-L58
``` c
int ctr_svchack_init(void)
{
   extern unsigned int __service_ptr;


   if(__service_ptr)
      return 0;


   /* CFW */
   ctr_enable_all_svc();
   return 1;
}
```

I believe that `__service_ptr` is a simple flag that indicates whether or not the application was started via the homebrew launcher.

So what we need is another check - if started via the homebrew launcher, try to see if we have `svc` access anyway.

Check this out, from Luma Updater:

https://github.com/KunoichiZ/lumaupdate/blob/master/source/version.cpp

This contains functions for getting the currently installed Luma version. Now it will require some work/testing to integrate any of this, but what we ultimately want is something like:

``` c
int ctr_svchack_init(void)
{
   extern unsigned int __service_ptr;


   if(__service_ptr)
      if (luma_version() < 8.0f)
          return 0;


   /* CFW */
   ctr_enable_all_svc();
   return 1;
}
```

Do you want to look at implementing this? I'm happy to have a go if you like, but it's gonna have to wait a while... I've already made promises to implement two significant frontend-related things, and that's going to keep me busy for a couple of weeks...

(As for the other dynarec-enabled cores - I imagine these will need to be looked at on a case-by-case basis - but I think there's only pcsxrearmed and gpsp? And TBH, neither of these are really fit for use. Maybe picodrive is the only one worth bothering with?)

**Comment by vaguerant** [comment]
I doubt it'd ever get done if I was implementing it, I don't think I know enough to do anything other than copy-pasting your code. 3dsx users have lived without dynarecs for this long, we can wait a little longer. I agree that gpSP is a lower priority since the dynarec is so crashy anyway, but people do seem to use pcsx-rearmed quite a bit; there's a compatibility list over on GBATemp and more games than I expected are full speed.

**Comment by jdgleaver** [comment]
Okay - no problem. I'll add it to the TODO list, and ping you when it's done  :)

**Comment by ShadowOne333** [comment]
I'd agree that PCSX Rearmed is fairly used on the 3DS still, Picodrive too.
gPSP is an oddball, as while it does indeed have a dynarec for the system, the dynarec itself is really unstable.
Perhaps fixes for PCSX and Picodrive should be good, gPSP is there's time and motivation, but I would suggest adding mGBA instead of focusing into gPSP fixing if it becomes too unbearable.

**Comment by vaguerant** [comment]
Another ugly hack, but I have the dynarec working in pcsx_rearmed as 3dsx on my end now too.

This time, I actually made no changes to libretro/pcsx_rearmed, as it was using `libretro/RetroArch/ctr/ctr_svchax.c` for its (unnecessary) privilege escalation stuff. Here's my diff:
```
18,19c18,19
< u32 __ctr_svchax = 0;
< u32 __ctr_svchax_srv = 0;
---
> u32 __ctr_svchax = 1;
> u32 __ctr_svchax_srv = 1;
```
As always, I don't know which of those two tweaks did the trick and it's not a proper fix, it just shows everything is all ready and hooked up, able to work on 3dsx builds.

**Comment by jdgleaver** [comment]
Good detective work. I'll add all this to the TODO list, and make it system-wide as you suggest. (Also need to check whether that `enable_all_svc()` stuff from picodrive is required for the other dynarec-enabled cores).

Currently neck deep in the new thumbnail downloader, so I'll come back to this in a week or so  :)

**Comment by justinweiss** [comment]
I believe this one is fixed now and can be closed.
