### ISSUE TITLE
feature request: see filepath in the info for a playlist entry

### ISSUE THREAD

**Issue by kcin2001** [libretro/RetroArch#8865]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

sometimes i get duplicate entries and i cant tell which playlist entry i want to delete without using desktop menu or opening the playlist file

### Expected behavior

the info section in the playlist entry to show the filepath for the rom

### Actual behavior

there is no such thing

### Steps to reproduce the bug

not really a bug

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: win8.1
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
@jdgleaver This could be useful, what do you think?

**Comment by jdgleaver** [comment]
@orbea Hmm... I can't think of a good reason not to show *all* available info on the information screen (file path, current core,  content runtime if available). This would also be nice on platforms without database support (gives the user something to look at rather than 'no entries found').

I've got a few things lined up already for this week (and I have some non-retroarch jobs as well!), but sure - I can look at implementing this (probably Thursday/Friday, or next week at the latest)

**Comment by orbea** [comment]
Ofc, whenever time and motivation permits, its always great to see your work. :)
