### ISSUE TITLE
Minor feature request - Scaling of thumbnails

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8915]
so i could be incorrect, but as best I can tell - no setting exists to resize the thumbnails as theyre displayed in the xmb.

I assumed this was based on the resolution of the image, but that doesnt seem to be the case.

Im in the process of trying to standardize the size of my thumbnails to some degree - and im worried about some of the smaller thumbnails looking lower quality because theyre displayed ginormously.   Exasperated by the fact I stream to a 65" tv ;p

Ultimately a scaler similar to whats in place for the overlays would be a welcome addition.  In the UI/appearance tab i reckon.

If something like this is present or the size is determined by some other means, please lmk.

**Comment by twinaphex** [comment]
Well, I do think we should probably go for some quality control on the https://github.com/libretro-thumbnails organization. Thumbnails of boxart should be 512x in width at least so that they are of adequate quality on higher resolutions (anything 1080p and above basically). Some of the boxart thumbnails might still be 256x which would result in low quality.

As for the scaling, maybe @jdgleaver could comment on that.

**Comment by jdgleaver** [comment]
Hmm... I don't think that changing the thumbnail display size is right option here. You either end up making everything too small (i.e. shrink all images to match the lowest resolution ones), or you display them at the original resolution (or some multiple thereof) which would make the small thumbnails show up as postage stamps, and lead to a huge inconsistency when switching between items.

The real issue here is that thumbnails in XMB/Ozone are always scaled with plain bilinear filtering. This is fine when images are downscaled, but it makes all upscaled images look like garbage. This doesn't just affect boxarts - most screenshots are low resolution (e.g. 160x144 for GB/GBC, and barely anything exceeds 320x240), which makes them pretty awful when blown up at 1080p. (As an aside, this is not an issue with RGUI, which is what I use, so I've never really paid any attention to this before!)

Now I've just experimented a little, and these are my findings:

- Upscaling thumbnails using nearest neighbour filtering is no good at all - it's fine for e.g. GB/GBC screenshots, but everything else is jaggy/uneven, and the quality is dependent upon display resolution.

- Upscaling thumbnails using lanczos3 filtering in fact looks *worse* than nearest neighbour - you get half the fuzziness of bilinear, but with added ringing effects. Absolutely horrible.

I think the best we could do is check each thumbnail as it is loaded, and if it is smaller than say 512x512:

1) Upscale it (nearest neighbour) to the next nearest multiple greater than 512x512.

2) Let the GPU scale it back down using (hardware) bilinear filtering.

We already have an algorithm for performing nearest neighbour scaling using the fastest possible method, so performance shouldn't really be an issue (at least, not on the desktop).

I'm going to knock up a proof of concept, and see how it turns out...

**Comment by klepp0906** [comment]
I'm sure anything would be an improvement :)

Of course thats been my MO at this point.  Is to shrink all my images to match the lowest one I have.  For PSP for example, theyre all 290x500 now.   Problem is like you said when theyre upscaled they look rotten.

The issue I was trying to resolve with scaling, was partially the images looking bad, and partially how huge some of them simply are related to the text to begin with.

On my tv, the gameboy color box art litereally eats up 35% of the screen when going down the playlist lol.  

I have no idea if a per playlist scaling setting from 0/100 as far as thumbnail display size would be possible to resolve that (irrespective of affect on image quality) or if you dont deem the work required worth it.

Of course its purely aesthetic, but options to users to customize is always a win, and is RA's thing :)

Still, wholly up to you.  Any improvement in the area is a win.

thanks for taking a peek nonetheless gentlemen.

**Comment by jdgleaver** [comment]
@klepp0906 Okay, PR #8920 should fix the image quality.

As for the size... I can't do per-playlist scaling, but I could do a global 'max width' scale modifier. It would look something like this:

- Normal scale - 1.0:

![Screenshot_2019-06-07_13-13-45](https://user-images.githubusercontent.com/38211560/59103273-520f2e80-8926-11e9-8fd1-c83f97175f9a.png)

- 0.7 scale:

![Screenshot_2019-06-07_13-14-14](https://user-images.githubusercontent.com/38211560/59103302-62270e00-8926-11e9-8f70-7050732b8bea.png)



Would that be good enough?

**Comment by klepp0906** [comment]
oh, dont say it that way! "would that be good enough" lol.   

This is far beyond my capability, whatever you choose to do is good enough!   But yes, making it smaller by any means is helpful (or larger but i cant imagine that being needed by anyone, ever :P)

excited to check out both changes :)  assume the setting for scaling will be under user interface > appearance? or will it be under playlist?

thank you!

**Comment by jdgleaver** [comment]
Heh, glad you approve!

The settings will indeed be under `User Interface > Appearance`. I'll try to get the scaling PR done today.

**Comment by jdgleaver** [comment]
...and here's the scaling PR: #8935

**Comment by klepp0906** [comment]
Your the best!  Sincere gratitude my friend :)

I love RA and it’s pretty exciting to watch it improve bit by bit

**Comment by realnc** [comment]
This issue should be closed as fixed.
