### ISSUE TITLE
Can anyone make available Retroarch for Apple TV ipa file?

### ISSUE THREAD

**Issue by s-areal** [libretro/RetroArch#8919]
I was wondering why isn't the IPA file of Retroarch for Apple TV available?
I know there's a tutorial for this, but for people like me, that don't have a provisioning file, we are out of the game.
I guess this could be helpful for a lot a people without the skill to make the build. 

So, can anyone make available Retroarch for Apple TV ipa file?

**Comment by orbea** [comment]
Just so you know we have an issue template for a reason, it would be really appreciated if it was filled out. It makes it much easier to understand the issue for someone who may not be familiar with the problem.

**Comment by s-areal** [comment]
Sorry, i didn’t know that. I’m newbie arround here. Sorry again

**Comment by yoshisuga** [comment]
Part of the reason why an IPA isn't available is because we need to bundle all the cores in the iOS app. Cores can't be downloaded in iOS because of the security restrictions put in iOS 10 and above. Ideally the buildbot would create an IPA file after compiling all the cores, so work would need to be done there. Also, bundling the cores might have something against the licenses around redistributing the cores. We've had discussions about that on discord, but not sure if we definitively decided what to do about that.

I'd try asking on the apple forum in the libretro forums about an IPA file.

**Comment by s-areal** [comment]
> Part of the reason why an IPA isn't available is because we need to bundle all the cores in the iOS app. Cores can't be downloaded in iOS because of the security restrictions put in iOS 10 and above. Ideally the buildbot would create an IPA file after compiling all the cores, so work would need to be done there. Also, bundling the cores might have something against the licenses around redistributing the cores. We've had discussions about that on discord, but not sure if we definitively decided what to do about that.
> 
> I'd try asking on the apple forum in the libretro forums about an IPA file.

Thanks yoshisuga. It would be great, to have the IPA available. hope the ear from you again.

**Comment by s-areal** [comment]
White this discussion isn’t finished can anyone send me a temporary link to download the Ipa with alô the core built in? Please....
