### ISSUE TITLE
[Switch] Thumbnails not showing up on patched games?

### ISSUE THREAD

**Issue by iGom** [libretro/RetroArch#9084]
## Description

Thumbnails are not showing up on patched N64 games. 
I have got patched roms for "Banjo-Kazooie (USA) (Rev A)" and "Legend of Zelda, The - Ocarina of Time (USA) (Rev B)" from No-Intro set. RetroArch didn't download thumbnails for both of them, so I did it manually by downloaded them from http://thumbnailpacks.libretro.com and thumbnails still do not show in the program. Names of both files are matched.

[What you expected to happen]

thumbnails will show up

[What is actually happening]

nothing

### Bisect Results

Unrelated

### Version/Commit

- RetroArch: [1.7.7/9e4ce6c]

### Environment information

- OS: Nintendo Switch

**Comment by iGom** [comment]
I gound a problem, filenames of thumbnails need to match the name of the game from DATABASE, not the actual name of romfile, in database patched roms have (Rev 1,2 etc.) at the end of the name, while thumbnails have (Rev A, B etc.)

**Comment by RobLoach** [comment]
Correct. Thumbnails need to match the entry's playlist name, this is so that you can name the file whatever you want, and the thumbnail will be :+1:

Hope to update the No-Intro DB sources within the next couple weeks.

Going to close this one for now. Thanks! Also, there are a few good issues over in https://github.com/libretro/libretro-database you may have interest in. Would love your help keeping the databases and thumbnails up to date!
