### ISSUE TITLE
[Bounty] Feature request for per playlist label name sanitization

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9107]
Hoping to get a feature added to to clean up label names.  How the innards work is beyond my understanding so a compromise if necessary is ok.

Ideally this  would be a toggle per playlist to remove anything within () a toggle to remove anything within [] one to leave (region) and one to leave (disc x)

Id go so far as being okay with a global remove anything in () and [] however which can be expanded upon later. 

This is one of the few items left preventing me from forgetting about other frontends entirely :P

**Comment by RobLoach** [comment]
Something like....

```
Settings > Playlist > Hide Label Flags
```

...Or something would be neat. Few things to consider:

- Thumbnail path is grabbed from the Playlist, so we'd have to find the canonical name.
- This shouldn't save the changes to the playlist file, should just be ascetic change
- Default to disabled

**Comment by klepp0906** [comment]
whatever is decided upon, i assume/hope it wont affect this implementation here https://github.com/libretro/RetroArch/issues/8635?

I spoke with jdgleaver earlier and he said he doesnt expect the the way it would be implemented would, but i just want to put that out there.  Dont want to be stuck with a choice.

Agree with the playlist portion however, which will likely circumvent the aforementioned if i had to guess.  (talking from my ass of course). 

I know mame roms are super picky about that stuff so making it purely aesthetic is a win on all fronts. 

heres to hoping.

**Comment by Justme488** [comment]
It would have to show on only the menu. If the playlists were changed, it would affect thumbnails and metadata.

**Comment by jdgleaver** [comment]
This is actually a pretty nice feature, and I know how to make it work without affecting any existing functionality.

I won't have time next week, but I can certainly tackle this the week after.

**Comment by tmtvl** [comment]
This seems like a fairly good issue for a first-timer like me. For the formatting itself I think I should look at `menu_displaylist_parse_playlist` in menu_displaylist.c?

**Comment by jdgleaver** [comment]
@tmtvl If you want to tackle this, I'd recommend the following approach:

- Define a new 'playlists label display mode' enum somewhere. This should have values corresponding to at least the following settings: 'default', 'remove ()', 'remove []', 'remove () + []', 'keep region', 'keep disk index', 'keep region + disk index'

- Add this 'playlists label display mode' setting to the playlist metadata (`playlist.h`/`playlist.c`). You'll need to support both old and new style playlist files.

- Add a menu option for changing the display mode for each playlist under `Settings > Playlists > Playlist Management > <playlist_name>`

- The name sanitisation functions could be useful in various places, so you'll probably want to put them in a new library (`.h`/`.c` file). I guess this should be generic enough to go in `libretro-common`. You'll need routines for each of the 'playlists label display mode' settings, of course, and they should be carefully optimised, since they'll have a direct effect on playlists loading (and hence menu navigation) performance.

- The actual place where the label will be modified is indeed in `menu_displaylist_parse_playlist()` - in particular, right after `menu_entry_label` is set for the first time. You'll want to be careful not to impact performance if 'playlists label display mode' is 'default'.

**Comment by tmtvl** [comment]
Thanks for the suggestion, I'll give it a go.

**Comment by tmtvl** [comment]
I think we can close this, unless we want #9235 fixed first?

**Comment by jdgleaver** [comment]
I would consider #9235 to be a completely separate issue.

I agree that this should be closed now :)
