### ISSUE TITLE
[Android] Shader settings not saving and being applied after restart

### ISSUE THREAD

**Issue by ZandigSlaytanic** [libretro/RetroArch#9116]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Shader settings are not saving and being applied after restart,

### Expected behavior

Saving the shader options should reapply them for future use.

### Actual behavior

Shader settings are not applied after you close the content or Retroarch itself. Next time you go to play the game no shader settings are not applied. The shader is listed in the "Shaders" option but if you open "Shader Parameters" it will be empty. It will also sometimes crash when you attempt to view the "Shader Parameters" here.

### Steps to reproduce the bug

1. Load a shader
2. Save Core Preset
3. Overrides/Save Core Overrides (or any other the other 2 options listed there)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
2019-07-15-RetroArch_aarch64.apk (also the last week or so of nightlies I've tried)
...also tried the 32bit version and have the same problem.

### Environment information

- OS: Android / Nvidia Shield TV

**Comment by LazyBumHorse** [comment]
Can reproduce, the shader presets are written but loading will fail, I fear #8933 broke the paths somehow.

Now, how to access the shader presets on Android...

**Comment by LazyBumHorse** [comment]
Yeah, the preset looks fine except for the paths:
`shader0 = "../../../../../../data/com.retroarch.aarch64/shaders/shaders_glsl/blurs/kawase/linearize.glsl"`

This will be concatenated with an absolute path to something like
`/data/user/0/com.retroarch.aarch64` + `../../../../../../data/com.retroarch.aarch64/shaders/shaders_glsl/blurs/kawase/linearize.glsl`
and I'm thinking Android doesn't like opening paths with "..", so we probably need to implement `path_resolve_realpath` in file_path.c for Android.

**Comment by ZandigSlaytanic** [comment]
Thanks for the confirmation and update on the issue.

**Comment by LazyBumHorse** [comment]
Hm... actually, `border/bigblur.glslp` loads just fine and that uses ".." in its path, so it shouldn't be that.

I'm still wondering how exactly it got `../../../../../../data/com.retroarch.aarch64`, that's 6 "..".

I'm guessing that `path_relative_to` got the path
`/data/data/com.retroarch.aarch64/shaders/shaders_glsl/blurs/kawase/linearize.glsl`
and the base
`/data/user/0/com.retroarch.aarch64/shaders/presets/Snes9x/`
so it had to step all the way down to `/data/` and up again.
Not sure how access permissions work in Android, maybe this counts as a direct access to `/data/` which fails because we're not rooted.

The real question is why path and base are so different. `/data/user/0/` is probably a symlink to `/data/data/` and one part of the code gets the symlink while the other part gets the real path.

**Comment by LazyBumHorse** [comment]
Alright, this took _way_ too much time to pin down exactly, take a drink every time I say "path".

So, first of all, `path_resolve_realpath()` _is_ implemented for Android since it's basically Linux.
It's using `realpath()` and `realpath()` does not only resolve `.`, `..`, multiple slashes etc, but it also resolves symlinks.

The strange relative shader path above really is the result of the exact paths I guessed.
The shader paths get a special treatment in `video_shader_resolve_relative()` where `fill_pathname_resolve_relative()` is called on them, which internally calls `path_resolve_realpath()` (so `realpath()`) at the end - mainly to resolve the `..`.
The path to the shader preset, however, does not get the `path_resolve_realpath()` treatment, so only one path gets its symlink resolved, which makes for a bad relative path.

But that still didn't explain why it can't open the relative path.
I thought it's some access problem or whatnot, but actually, both the `/data/user/0/com.retroarch.aarch64/...` `/data/data/com.retroarch.aarch64/...` paths can be accessed without any problem.

The _actual_ problem is that `realpath()` for _some_ reason will not resolve the path
`/data/user/0/com.retroarch.aarch64/shaders/presets/Snes9x/../../../../../../data/com.retroarch.aarch64/shaders/shaders_glsl/blurs/kawase/linearize.glsl`
If it would try, it'd get
`/data/data/com.retroarch.aarch64/shaders/shaders_glsl/blurs/kawase/linearize.glsl`
which is perfectly valid and can be opened and read.

There are two possible solutions to this problem.
1. Resolve symlinks at both places, i.e. give the shader preset path the `path_resolve_realpath()` treatment as well
1. Don't resolve symlinks, i.e. throw away and replace `realpath()`

Option 1 is easy to implement and _probably_ won't hurt doing in any case, this will also fix this same issue for other platforms when using a symlink in the RA shader path.
Option 2 might solve other issues that haven't yet surfaced but it might also cause some, though I don't know what that might be.

I'll probably try both options since I already implemented my own `path_resolve_realpath()` for UNIX.

**Comment by LazyBumHorse** [comment]
Can confirm both options solve the issue.

I think I understand now why `realpath()` behaves weirdly with symlinks and `..`.
It will resolve symlinks _first_, `..` second, so if `/foo/bar/` is a symlink to `/baz/`,
`/foo/bar/../`
doesn't become
`/foo/`
but it first becomes
`/baz/../`
and finally
`/`

This is not how RA intends those `..`, so it really has to be replaced.

**Comment by LazyBumHorse** [comment]
There we go, now we wait.

**Comment by ZandigSlaytanic** [comment]
Just tested out nightly:
2019-07-21-RetroArch_aarch64.apk  -  2019-07-21 06:40 92.3 MB
and it's now fixed.

Thank you.

**Comment by LazyBumHorse** [comment]
You're welcome!
Thanks for the report, a lot came out of it.

**Comment by LazyBumHorse** [comment]
@twinaphex Both parts of this have been implemented, so this can be fully closed.
