### ISSUE TITLE
Ozone doesn't properly display 3-d box art

### ISSUE THREAD

**Issue by Justme488** [libretro/RetroArch#9243]
Ozone doesn't properly display 3-d box art.

![ozone](https://user-images.githubusercontent.com/5625616/62412532-e2d65380-b5d1-11e9-89bf-8504d4425b8f.png)

@jdgleaver Do you have time to fix this?

**Comment by jdgleaver** [comment]
That's odd - it looks like it's not handling the transparency correctly.

Could you post an example box art image (i.e. the source file) for testing?

**Comment by Justme488** [comment]
It does this with all of them from the set I got. Here is the one from the pic above.

![ATV Racers (USA)](https://user-images.githubusercontent.com/5625616/62415756-efbc6c80-b5fc-11e9-8b6f-5ed70bc67914.png)

**Comment by RobLoach** [comment]
I don't think RetroArch has support for transparent images for the thumbnails.

**Comment by Justme488** [comment]
https://cdn.discordapp.com/attachments/607019903806865430/607176382870454272/unknown.png

**Comment by twinaphex** [comment]
@RobLoach RPNG definitely supports transparency.

**Comment by RobLoach** [comment]
Ooo, super fancy!

**Comment by jdgleaver** [comment]
Ah yes, Ozone was just missing a 'blend'.

This fixes it: https://github.com/libretro/RetroArch/pull/9247

(Note - both XMB and Ozone now have transparent thumbnail support, but RGUI can't and won't - because it's rendered in software I'd have to check every pixel for transparency and deal with it 'by hand' - that's too much of a performance overhead, even if I made it optional...)
