### ISSUE TITLE
[feature request] assign type of artwork to display on per playlist basis

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9262]
This is probably a big ask, especially taking into consideration the amount of work that has probably already gone into making playlist artwork function as it does at current.

It never even crossed my mind until I started working on some arcade stuff today.

Since we seem to be expanding on the playlist management section a bit lately, I figure it might be something suited for that area.  An override of sorts that ignores the global thumbnail setting or something.

In my particular case, I want to display Title screens for my arcade roms, but I use covers for several consoles.   My only option at this point is to put titles in the Boxarts folder for the particular playlist.

**Comment by illando** [comment]
I guess are just the thumbnails of the arcade playlists that needs a swap in the order they are visualised. Just because they don't have boxarts like consolle games.
Actually retroarch is using the poster thumbnails as main image for arcade games but it doesn't feel right. Maybe should be better to have title thumbnails as main and posters as third choice.

**Comment by klepp0906** [comment]
Yes, that is a stopgap sort of work around that would certainly apply to arcade in particular.

being able to choose across all playlists independently empowers the user to customize and improves RA but as a quick fix, that would certainly do  (at least for me).

Unfortunately its tricky because some people probably wouldnt see it that way.   The posters as you mentioned are incomplete and hard to source like conventional game boxes/cover art so with arcade it does make this particular situation troublesome.

I'm really trying to have RA be my sole frontend.  Ive put an extraordinary amount of time into setting it up (many many months, several hours a day) and its nearing the point that the only big thing missing opposed to other frontends is the display of metadata.  Thats another topic for another day though.

What im getting at is, for those of us who like a complete polished frontend, missing artwork isnt an option - and as such posters are not only going to be missing, some hard to source, some probably non existent.   Some plain wrong (look like brochures lol). 

Anyhow, heres to hoping someone with a bigger brain than I can think of a feasible solution and be willing to implement it - whether constrained as an option to arcade roms only, or globally.

Would be really sweet if the playlist manager had the option to choose which artwork to use in which position on a per playlist level though..

could be added as a 0=default 1=boxarts in 1st position (then cycle them) 2=snaps in 1st position/move boxarts to 2nd, 3=titles.

**Comment by hizzlekizzle** [comment]
This is something that could be added to the JSON playlists, hypothetically.

**Comment by jdgleaver** [comment]
Probably getting myself in trouble here, but this would actually be fairly straightforward to implement - and it would be useful for non-arcade content, too (e.g. NDS games typically have no screenshots available). Although it wouldn't be possible to have the specific per-playlist thumbnail settings carry over to history/favourites (because per-entry associations would be ridiculous)

I can maybe have a look at this next week...
