### ISSUE TITLE
Vice64x fails to autoload zipped .d64 images

### ISSUE THREAD

**Issue by RoofTop1** [libretro/RetroArch#9500]
# First and foremost consider this:
Sorrry if this is the wrong forum but I got no idea if this is a core bug. I am just a c64 user
that enjoys to put c64 games and emulators up on various systems and consoles.

## Description
Fails to autload file from a zipped d64 image.

### Expected behavior
To load directory track 18 and search file name,  then go to actual track for file and load it.

### Actual behavior
Tries to load directory track 18 to search for file, then bumps to track 1 and retries
track 18. Then ends with a file not found.  As if no disk was inserted.

### Steps to reproduce the bug
1. Autoload a zipped d64 image.

### Version/Commit
Latest update 1.7.8

### Environment information
Retroarch for Playstation Classic.

Last minute notes:  Loading zipped .T64, .CRT and .PRG files works fine.

**Comment by rsn8887** [comment]
Wrong place. This issue should be made in libretro/vice-libretro.

Also, I cannot reproduce this on my system (OSX). I need detailed instructions how to reproduce.

Here's what works for me on my system (OSX):
- Start Retroarch, using default options and default core options, and latest version of C64 core, should display "1.7.8 - Vice x64 3.3 f3e7249" in bottom left corner. Use `Online Updater` -> `Core Updater` -> `Commodore 64 (Vice x64, fast) (to update core to latest version, should be version )
- Load Content -> select "1942 (1986)(Elite)[cr Jabba].zip"
- Select Load Archive
- Select Commodore - C64 (Vice x64, fast)
- C64 Boot screen displays, shows Load"*",8,1 etc.
- Game boots fine.

**Comment by RoofTop1** [comment]
I will bring it over to the correct forum.  
BUT I forgot to say that this happens only when True Drive Emulation is turned on.
Most games can have TDE turned off.  But there are many games that needs TDE to be on.

The bug i described will happen here on my setup, if I take your 1942 (1986)(Elite)[cr Jabba].zip and set TDE to be on in the option file prior to launching the game.

**Comment by sonninnos** [comment]
I believe this issue no longer applies, since the core has been bypassing frontend extraction for a while now, which means the archive can not be passed as-is to the emulator if the frontend (PS Classic in this case) skips the extraction "illegally".

The core unzips archives temporarily to `saves` (writing there should always be possible), which means the emulator always receives the unzipped file.

I haven't been able to reproduce the problem at all with Windows even before the above mentioned change, no matter the TDE core option.
