### ISSUE TITLE
[Enhancement] Disk Control

### ISSUE THREAD

**Issue by ichee** [libretro/RetroArch#9652]
Cores that support multi-disk games, such as both Beetle PSX and Saturn cores, always default to the first disk in a .m3u file.

An option for Retroarch to remember the last Disk Index accessed for the given game would improve user experience when starting a game after having progressed past the first disk.
Possible ways to implement would be:

1.) A per-game option for disk index last used, either Retroarch or user configured,

or

2.) When selecting a game from the playlist, after selecting run, if a game is pointing to a .m3u file, expand the context menu again with options to select which disk to start from.

Option 1 would probably be the easiest to implement, but option 2 would be the most user friendly.

**Comment by i30817** [comment]
IMO even better would be making savegames for retroarch also save the 'current disk configuration'. As a separate file or not, depending if savestate upstream compatibility is desired or not and (if you can't just support both versions).

**Comment by ichee** [comment]
Going the savestate route would not be desired given the potential compatibility issues between versions, and also the save corruption risk inherent to savestates. 

At the very least, since Retroarch already has a disk change option, a configuration file entry that can be user adjusted on an as needed basis, same as various other options already present and user configurable.

I'm still partial to option 2 above if someone is willing and able to do so, without too much difficulty, in the hopefully not too distant future.

**Comment by bslenul** [comment]
Not sure if it's a common thing but Beetle PSX switches index automatically when you load a state, that's really useful!

But yeah I'd love to see a feature like that without the need of states, maybe an option in the "Disk Control" menu like "Start this game at disk index" and you chose disc 1/2/3/4/etc.

**Comment by i30817** [comment]
It'd only work with a associated m3u though (without that other request i posted).

RA can't really decide if what is a 'game set of cds' without it.

Also this strategy (both) will probably never work with cores that take multiple floppies/cds/roms at once, without a way for the user to configure what the game may expect as a combination (and it's not possible to tell in advance if no one shares that information). 

The reason is that not all combinations are valid!

Also floppy games often required a user provided empty disk to save stuff.

**Comment by i30817** [comment]
It's also problematic to for m3us because if i understand correctly (i might not, i don't use them), m3us aren't actually 'scanned' thus don't appear as a entry point in a playlist.

This is for several reasons, but mostly because the scanner is not prepared to be that flexible. Enhancing my other issue https://github.com/libretro/RetroArch/issues/6410 to permit that might make it possible.

I think i'm going to close that issue and open a new one that organizes the special cases there better and deals with this issue.

**Comment by dukeblooders** [comment]
> 2.) When selecting a game from the playlist, after selecting run, if a game is pointing to a .m3u file, expand the context menu again with options to select which disk to start from.

I saw the disk control update on the website today, but did't see anything about this. 
I think it's a good idea, especially for CLI users. Letting the choice of disk at startup is a huge gain of time. There could be an option to enable/disable this functionality.

(+ and if possible with #9282, for people who want to manage this in a different frontend )

**Comment by ichee** [comment]
This issue has long been resolved, I just didn’t realize it was still open.
