### ISSUE TITLE
Retroarch 1.8.1 Android - Thumbnails not visible in Favorites list

### ISSUE THREAD

**Issue by omgwtfbbqpls** [libretro/RetroArch#9751]
### Description

RetroArch has downloaded thumbnails for my games, but they are not visible in the Favorites list:
https://i.imgur.com/zrHr6Fc.png

However, if I open the playlist for a console/system (e.g. NDS) the thumbnails are visible:
https://i.imgur.com/yCUXIU4.png

This has been the case ever since thumbnails were added to the UI.
Downloading thumbnails (manually or not) is not the issue, as they are clearly already downloaded.

### Version/Commit

- RetroArch 1.8.1
- Build date: Nov 19 2019 (recently updated from F-Droid repo)
- Git version: 79c336b

### Environment information

- OS: LineageOS 16 for MicroG
- Compiler: Clang/LLVM 8.0.7
- Phone: Moto X4

**Comment by jdgleaver** [comment]
In order for thumbnails to work in the history/favourites playlists one (or both) of the following must be true:

- The playlist entry was added via an existing 'collection' playlist with valid `db_name` fields

- The ROM directory has the same name as the thumbnail directory

You can read more about this here, in the `Thumbnail Additions` section: https://www.libretro.com/index.php/retroarch-1-7-7-ui-updates/

In your case, I guess there are two likely possibilities:

- Your collection playlists were made with an external playlist manager that breaks spec by not including `db_name` fields (if you used RetroArch's internal scanner, then ignore this!)

- Your favourites playlist was generated before RetroArch 1.7.7 was released (that's when we added support for history/favourites thumbnails - before that, the required metadata wasn't copied over)

If you upload your favourites playlist I can tell you if it's missing the necessary info.

If it is, then unfortunately you'll need to re-add them from a collection playlist with working thumbnails (or you could edit the playlist file by hand to fill in the missing `db_name` fields...)

**Comment by omgwtfbbqpls** [comment]
@jdgleaver
Thank you for the reply. I added the entries to my Favorites playlist manually, by opening them with "Load Content" and then adding them to Favorites from the Quick Menu. I didn't use "Scan Directory" or the playlists RetroArch itself generated.

I did all of this after 1.7.7 (May 9, 2019). As I undestand, that is when thumbnails were added for the desktop version. However, thumbnails were only added to Android recently, and I added my entries before Android had thumbnail support.

It seems the playlists RetroArch makes after scanning aren't perfect either, as some games/thumbnails are missing from them, although the majority are there. 

There is a "playlists" folder, but my Favorites entries are not there. As far as I can tell, the .lpl files in the folder are for the system-generated playlists. This is what is inside the system-generated DOOM.lpl file, for example:

```
{
  "version": "1.2",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "items": [
    {
      "path": "/storage/emulated/0/RetroArch/downloads/Doom/doom1.wad",
      "label": "Doom (v1.9) (Demo)",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "162B696A|crc",
      "db_name": "DOOM.lpl"
    }
  ]
}
```
Although this one has a "db_name", this is one of the few games where the thumbnail is still missing. In addition, I was unable to add "prboom.wad" (the one I'm actually playing) to this playlist by any means. This is inconvenient, as doom1.wad is only a demo. I might try and edit the DOOM.lpl file to add "prboom.wad", but I assume the thumbnail would still be missing.

So my questions now would be:

- Where can I find my Favorites playlist file, as it is not in the playlists folder?

- If having "db_name" in the .lpl file isn't enough to add a thumbnail, what can be done?

**Comment by jdgleaver** [comment]
> I added the entries to my Favorites playlist manually, by opening them with "Load Content" and then adding them to Favorites from the Quick Menu. I didn't use "Scan Directory" or the playlists RetroArch itself generated.

Ah - that's the root of the problem! When you run a game via `Load Content`, RetroArch knows almost nothing about the file you're selecting - just the path and the core you ran it with. There's no way of determining a `db_name` value, so thumbnails will only work for such an entry if the content directory name matches the thumbnail directory name.

So in future, if you want thumbnails in your favourites playlist, you need to select `Add to Favorites` via an existing playlist entry that already has working thumbnails.

> I guess my final question again would be - where to find the Favorites playlist file? I could re-add everything manually from the app, but just typing the "db_name" seems like it would be easier (if I can find the file, that is).

Ah, that's actually a bit of a problem...

I always forget about this because I set my history/favourites playlists paths manually (by editing the main RetroArch config file located in `/sdcard/Android/data/com.retroarch*/`), so they're always somewhere that I can access...

But by default, the favourites playlist is located inside `/data/data/com.retroarch*/` - so without root access, you won't be able to edit the file by hand...  :(

If you don't have root access, then I guess you will have to delete your existing favourites and start over (you can delete the whole file in one go by selecting `Settings > Playlists > Playlist Management > Favorites > Delete Playlist`).

If you want your new favourites playlist to be somewhere more sensible, edit `/sdcard/Android/data/com.retroarch*/retroarch.cfg` and set the `content_favorites_path` value to something like `/sdcard/RetroArch/content_favorites.lpl` (the actual 'sdcard' part of the path will depend on how the filesystem is mounted on your device).

> It seems the playlists RetroArch makes after scanning aren't perfect either, as some games/thumbnails are missing from them, although the majority are there.

Yeah, this is normal... RetroArch can only automatically scan files that match a database - so if your ROM file doesn't have the exact right checksum then it won't get added. For files like this, you need to either add them by hand, or use an external playlist generator (although a 'dumb' manual file-name-based scanner is on the TODO list - no ETA yet...)

For the thumbnails to show, the thumbnail file name must exactly match the `label` field in the playlist - so again, thumbnails can be missing if the name is slightly wrong (as in your Doom example). Also, sometimes there just isn't a thumbnail available! The thumbnail archive is a community project, and it only contains images that people have manually uploaded - it stands to reason that not every single possible game will be included!

On the subject of Doom, this is the contents of my Doom playlist, with the correct `label` names for thumbnail support:

```
{
  "version": "1.1",
  "default_core_path": "/data/data/com.retroarch.aarch64/cores/prboom_libretro_android.so",
  "default_core_name": "Doom (PrBoom)",
  "items": [
    {
      "path": "/storage/294C-0BB2/ROMs/DOOM/doom2.wad",
      "label": "Doom II - Hell on Earth (v1.9)",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "EC8725DB|crc",
      "db_name": "DOOM.lpl"
    },
    {
      "path": "/storage/294C-0BB2/ROMs/DOOM/plutonia.wad",
      "label": "Final Doom - The Plutonia Experiment",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "48D1453C|crc",
      "db_name": "DOOM.lpl"
    },
    {
      "path": "/storage/294C-0BB2/ROMs/DOOM/tnt.wad",
      "label": "Final Doom - TNT: Evilution",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "903DCC27|crc",
      "db_name": "DOOM.lpl"
    },
    {
      "path": "/storage/294C-0BB2/ROMs/DOOM/doomu.wad",
      "label": "Ultimate Doom, The",
      "core_path": "/data/data/com.retroarch.aarch64/cores/prboom_libretro_android.so",
      "core_name": "Doom (PrBoom)",
      "crc32": "BF0EAAC0|crc",
      "db_name": "DOOM.lpl"
    }
  ]
}
```

**Comment by omgwtfbbqpls** [comment]
@jdgleaver 
Thank you again for the help. Thankfully, I have root access - but I decided to change my Favorites playlist location for convenience anyway. I copied my old playlist from the root, pasted it into the new, convenient directory and it worked! 

I re-labeled the entries with missing thumbnails (ROMhacks and such), added "db_name" and now they all have thumbnails! 

Well, except for Raiden 2. Hopefully there will be option for us to upload custom thumbnails so we won't need to rely on volunteers for less-popular games. 

You mentioned scanning for files that match a "database" - can users know what this database contains? For example, it might turn out that a thumbnail for Raiden 2 _does_ exist, but I've labeled it wrong because I don't know how it's labeled in the database.

**Comment by jdgleaver** [comment]
Ah, great - I'm glad it's working now.

You can browse the databases online: https://db.libretro.com/

..but for your purposes, I guess the available thumbnails are more important. The full archive of them can be found here: http://thumbnails.libretro.com/ (this is where the files come from when you use the in-built thumbnail downloader)

And you can already use custom thumbnails! You just have to name your .png files after the playlist `label` field, and place them in your existing thumbnail directory with the following structure:

```
<db_name>
|-- Named_Boxarts
|   `- <label>.png
|-- Named_Snaps  
|   `- <label>.png
`-- Named_Titles
    `- <label>.png
```

(I recently did this for a bunch of Atomiswave and NAOMI titles, which don't have any thumbnails in the online archive - just took screenshots of the title screens + in-game)
