### ISSUE TITLE
XBox DevMode wont Launch after reboot

### ISSUE THREAD

**Issue by rfrayer420** [libretro/RetroArch#9861]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen] To install retroarch and have it work beyond a reboot

### Actual behavior

[What is actually happening] Retroarch works fine until the console is restarted and wont launch beyond space invader spash ever again.

### Steps to reproduce the bug

1. [First step] Install both RetroArch and Dependancys on Xbox one Dev Mode / Update Assets
2. [Second step] Reboot
3. [and so on...] Crashes on start without adding any error to dump

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: RetroArch 1.7.7 (Xbox One UWP)

### Environment information

- OS: Xbox One DevMode
- Compiler: [In case you are running local builds]

**Comment by m4xw** [comment]
Afaik this is related to the used cert and we likely just need to rebuild it, if i get Dominater01's observations right.

**Comment by EleazarRobaina** [comment]
When you are going to restart or exit developer mode, it asks you if you want to delete all installed applications. You should always deselect this option or it will delete RetroArch every time you exit developer mode.

**Comment by rfrayer420** [comment]
> When you are going to restart or exit developer mode, it asks you if you want to delete all installed applications. You should always deselect this option or it will delete RetroArch every time you exit developer mode.

If I were removing it when rebooting there wouldnt be an app to report an issue about...

**Comment by cnktknX** [comment]
I've same issue on my xbox one s console. Whenever I reboot console, retroarch or retrix applications are not launch again (shows app logo and go back to the dev home)

**Comment by retrojohnny** [comment]
Same problem on my system

**Comment by retrojohnny** [comment]
> Afaik this is related to the used cert and we likely just need to rebuild it, if i get Dominater01's observations right.

Was the problem resolved?

**Comment by webodan** [comment]
Same problem in my fat Xbox One. I tried installing version 1.8.4, configuring it, running some games, everything is fine until the console is rebooted. Then, just to make sure it wasn't a flaw with the latest version of RA or that I had a corrupted download I tried deleting it and reinstalling 1.8.0 and doing the same configuring, testing and then rebooting steps. Same result. RA is pretty much broken on Xbox One until this is fixed, since it can't be used like this.

**Comment by jwrmo** [comment]
I too have the same problem upon a reboot the app will not start again. I am not deleting the app.

**Comment by hizzlekizzle** [comment]
I forget who told me this, but apparently this affects a lot of (all?) homebrew, not just RetroArch.

**Comment by retrojohnny** [comment]
Really hope it can be fixed I dont anythin about coding but if did would
try and figure it out.. was maybe to good to be true

**Comment by webodan** [comment]
> 
> 
> I forget who told me this, but apparently this affects a lot of (all?) homebrew, not just RetroArch.

In order to test that claim, I did the following:

1- Downloaded some random app for Xbox One (I tried AwesomeTube_5.1.35.0.appxbundle that I got from [here](https://www.mediafire.com/folder/f2wf0t8eqm7j3/All_Xbox_One_Homebrew#62cfxb30obbh2)) and the prerequisite Microsoft.Advertising.XAML from [here](https://www.nuget.org/packages/Microsoft.Advertising.XAML/10.1811.22001) so it would install properly.
2- Ran it twice without rebooting, so it would configure itself or whatever.
3- Clicked on Leave Dev Mode so the console would reboot the same way that makes RetroArch fail. Have the console reboot...
4- ... Then rebooted once again into Dev Mode...
5- ...And ran the app again. It booted fine.

I'm not sure if that proves anything, but at least some other third party apps non related to RetroArch seem to work.

**Comment by rfrayer420** [comment]
It turns out this is an issue with Microsoft, I finally got to talk to a rep regarding this. It was intentional. They didnt get into specifics but they intentionally crippled anything that relys on file manager and have no plans on correcting it. This crippled the majority of dev apps yets for some reason they are still selling developer mode. So basicly they crippled all these apps and expect the developer to make changes. Ive been using retroarch for many years on both linux and windows and to be honest I doubt this can be done without completely rewriting retroarch fro the ground up and making it only work from its own directory forcing people to add roms via the dev mode browser interface.

**Comment by webodan** [comment]
Wow thank you @rfrayer420 that's sad. And we cant refund dev mode? This is a f*ckn scam

**Comment by rfrayer420** [comment]
Its turned into one, its about enough to make me sell my xbox and just stick to my raspberry pi or odroid xu4

**Comment by retrojohnny** [comment]
Ya they fleeced people for sure bunch of corperate pirates....Thankfully
only 20 bucks but still thats like days of my life gone for good and the
hope of being able to play my retro games on system with dreams crushed.
Whoever comes up with these ideas in the company gets paid way to much to
be a jerk. They cant just focus on their a new console and stop messing
around with shit lol

**Comment by webodan** [comment]
I managed to temporarily fix this bug by reassigning the file access permissions to the retroarch folders as demonstrated in this video:

https://www.youtube.com/watch?v=QcYqsr9zYeg

This is clearly a bug introduced by Microsoft since it resets file access permissions after every reboot and they have to be properly set manually with a PC.
