### ISSUE TITLE
Zipped DOS Games can't be load

### ISSUE THREAD

**Issue by xmha97** [libretro/RetroArch#9880]
Hello, I download a DOS game as ZIP format.

![image](https://user-images.githubusercontent.com/23485114/71226926-cc1b6980-22f2-11ea-9f2c-58f54aaed0a3.png)

It's can't be loaded because RetroArch can't extract the whole archive.

![image](https://user-images.githubusercontent.com/23485114/71226868-a68e6000-22f2-11ea-9a9f-fe6cc9012db1.png)

Is there an option to extract the whole archive?

**Comment by i30817** [comment]
Upstream Dosbox doesn't mount zips.

**Comment by amirrammari** [comment]
Thanks for your comment.
I don't need to mount or write access for the archive file.
RetroArch extract the executable file to catch the folder before emulating the game, then run executable file using Dosbox.
I looking for an option to extracting the whole archive.

**Comment by i30817** [comment]
That would mean that the game would be 'reset' every time you ran it, ie: savegames, highscores etc would all be gone.

DOS is different from a consoles, so the core can't segregate the writes to the 'save dir' on the retroarch dir, because DOS never had that separation, unlike (most) consoles.

Anyway, the problem you mention also exists with zipped-up console games, and even there retroarch refuses to extract everything (cue+tracks).

I think it's because very dumb people might try to 'play' multiple cds zips and RA then try to extract dozens of gb zips.

**Comment by RobLoach** [comment]
Extract whole archives in some cases: https://github.com/libretro/RetroArch/issues/4331

**Comment by RobLoach** [comment]
Dup https://github.com/libretro/RetroArch/issues/4331
