### ISSUE TITLE
[Feature Request] Multi-softpatching support

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#9947]
Currently in Retroarch multi-patching requires hardpatching multiple times, then generating a new patch for softpatching via comparison between the two copies. This isn't optimal, especially in situations where only one patch frequently needs updates.

It seems a standard already exists in snes9x standalone for file naming for multiple ips patches (https://github.com/snes9xgit/snes9x/issues/217#issuecomment-325655551). I'd simply request the same functionality as is listed in steps 8-10 of that comment be added to Retroarch. Having glanced through the source, it doesn't seem this functionality exists in any manner currently.

**Comment by Deide** [comment]
Step 11 would be useful too, especially if it meant you could actually keep useful names for the separate patches

**Comment by Sanaki** [comment]
Archive loading of softpatches would be nice, but I don't believe it's viable at this time. That said, since multiple games can inhabit the same archive, it'd likely require the same filename as well.

Still, that's undoubtedly a topic for another issue.

**Comment by eadmaster** [comment]
sorry for all the noise here, it was me and git fighting... btw a basic implementation of this was merged and it is now available in RA v1.

In the [initial PR](https://github.com/libretro/RetroArch/issues/9947) we also discussed some enhancements, but I won't be working on this anytime soon, since i've switched to static patching for various reasons.

**Comment by Sanaki** [comment]
Oh bugger, I thought this was auto-closed with the PR. Welp, fixing that....
