### ISSUE TITLE
PSX BIOS not recognized when using HLE option

### ISSUE THREAD

**Issue by coldspark29** [libretro/RetroArch#9986]
## Description

The right PSX BIOSes are in the folder, namely 

scph5500.bin | 8dd7d5296a650fac7319bce665a6a53c | Japan
scph5501.bin | 490f666e1afb15b7362b406ed1cea246 | USA 
scph5502.bin | 32736f17079d0b2b7024407c39bd3050 | Europe

but Retroarch still complains, that the BIOS is not found. I have checked multiple times, if it is the right folder and the right files. Also checked the MD5s

### Expected behavior

Playstation Logo to show up

### Actual behavior

Notification aboput missing BIOSes is shown

### Steps to reproduce the bug

I have no idea. It used to work before. 

### Bisect Results

After I reinstalled Retroarch or LAKKA on my RPi4. If it was on the PC it would not be such a big deal. I could easily reinstall everything.

### Version/Commit

- RetroArch: ea7e682253

### Environment information

- OS: LAKKA

**Comment by bslenul** [comment]
HLE is like an internal bios, if you want to use these scph files, you have to set "Use BIOS" to "auto" in PCSX core options, unless you have a good reason to use HLE?

But yeah, the error doesn't really matter since it will not use these files when "hle" is selected, but I guess that error should be hidden in that case.

**Comment by coldspark29** [comment]
I see. So what is the difference between original BIOSes and High Level Emulation? Latter sounds like it was more powerful.

**Comment by bslenul** [comment]
Original bioses are way more compatible, a quick example is Metal Gear Solid, it doesn't even boot with HLE, you just get a black screen :p I remember someone having saving issues also on a RPG with HLE, etc.

So if you have the files, I highly recommend switching to "auto" for bios in core options ;)

**Comment by coldspark29** [comment]
Okay thank you for making that clear! I think it would be good to also mention this in the config. "Use Auto if you have the original files (recommended) and HLE for using the emulators internal BIOS (may not work for some games)."

**Comment by bslenul** [comment]
There's already this description in Quick Menu > Options:

![image](https://user-images.githubusercontent.com/33353403/72205686-68fe9c00-3486-11ea-8472-e45be98dbfa8.png)

Seems pretty clear to me :p However when using HLE bios, the message should probably say something like "Using HLE bios, compatibility may not be optimal." or something like that instead of "No PlayStation BIOS file found".

**Comment by coldspark29** [comment]
Okay sorry for bothering you then :)
