### ISSUE TITLE
Vulkan running at half framerate with vsync off + sync to exact framerate in video options

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/RetroArch#9992]
Reproducible in all cores, AMD and Nvidia hardware with FreeSync and Gsync respectively.  Plays at full framerate with Vsync enabled in the video options but Vsync (or even audio sync) isn't necessary for Exact Framerate to work as OpenGL works without them perfectly.  Peculiarly, RA will show that it's running at 60fps (or the content framerate) but RivaTunerStatisticsServer will show half and half is what's actually being rendered.  This behavior is transferred to PAL games where RTSS will show 25fps and RA will show 50.  Stranger still when I toggle vsync 'on' in RA, and 'off' in the drivers (forcing vsync off in execution) this issue is cleared up.  So disabling in drivers and enabling in RA is a bit of a workaround... but still thought I'd call attention to this.

I'm opening this to discuss Sync to Exact Framerate for a bit as well.  It's officially documented that you need vsync for Sync to Exact Framerate to work, but I've found that vsync off is the ideal way to do this for least lag on a variable refresh display, and DEFINITELY with audio sync off as this will break the feature.  With OGL + audio sync off + video sync off it will pace frames perfectly (seen in Gundam Wing: Endless Duel), but audio sync will break the pacing.  Thanks for looking into it.

**Comment by n1ghttrap** [comment]
Of note, also running a 120hz display mode. (as this will allow for exact framerate to work on systems with a bit over 60fps

**Comment by Awakened0** [comment]
Having Vsync enabled in RetroArch shouldn't cause any extra lag for most content since FPS will be limited to something under 120fps. That keeps you in Gsync/Freesync range on a 120hz display. You should only experience Vsync lag if you actually hit 120fps, which would only happen in cores that support high framerate, like Cannonball. An external frame limiter like RTSS or the new one built into the Nvidia driver might work for that core if you set it to a 117 cap or so.

And you don't want to turn off audio sync either. The person who programmed the exact sync feature made it work best with default settings; all you need to do is turn it on and leave Vsync and audio sync on.

**Comment by n1ghttrap** [comment]
I can verify this isn't the case from testing both AMD and Nvidia hardware.  Using Gundam Wing + SNES9x as the test case as it's extremely obvious in the titles screen.  With audio sync + exact framerate, it will judder and miss the 30hz flicker effect every few seconds.  With audio sync off it doesn't miss a beat.

**Comment by n1ghttrap** [comment]
I just enabled driver level vsync, audio sync in RA, with exact framerate and got similar latency scores and no judder issues in GW:ED, so I'm gonna just say this is closed.  Maybe I can get more frames and the same result from audio/video sync off, but using it as directed it seems to work.
